### ISSUE TITLE
make_function_view return type ?

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1008]
Hi, I'm trying to use make_functional_view, the return type of my message isn't handled.

I assume there is a way of doing this, but I couldn't work out what it was.

cheers!

```
error: conversion from ‘caf::expected<caf::message>’ to non-scalar type ‘const playa::utility::Uuid’ requested
     const Uuid u = c(get_uuid_atom::value);
```

I can see this in the header files, but I couldn't work out how to use it.
```
template <class T>
using function_view_flattened_result_t =
  typename function_view_flattened_result<T>::type;
 
```

**Comment by Neverlord** [comment]
It seems like you're using dynamically typed actors in your code. The compiler already tells you what's wrong: the function returns a `caf::expected<caf::message>`. Essentially, this is either an error or a type-erased value.

Assuming `f` is your function view:

```c++
if (auto x = f(...)) {
  if (x.match_elements<playa::utility::Uuid>()) {
    // We've got our UUID.
    const auto& uuid = x.get_as<playa::utility::Uuid>(0);
  } else {
    // Got something else. Error?
  }
} else {
  // Timeout or error (e.g. receiver down).
  auto& err = x.error();
  // ...
}
```

**Comment by alatdneg** [comment]
Thanks, I wasn't sure if there was a more compact way of handling the result returned. i.e. with less boilerplate.

**Comment by Neverlord** [comment]
> less boilerplate.

Statically typed actors do reduce the boilerplate by removing the need for `match_element` and `get_as`. With typed actors, the compiler can figure out the return type based on the input. You still have to unbox the `expected`, though.

**Comment by alatdneg** [comment]
Ah, I wondered about that :)
