### ISSUE TITLE
Visual Studio 2019 warning level 4

### ISSUE THREAD

**Issue by ke9** [actor-framework/actor-framework#1010]
Having an issue with warning C4244 when building in level 4.

Build output, removed paths with [...] to clarify. :

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.24.28314\include\utility(149,16): **warning C4244**: 'initializing': conversion from '_Ty' to '_Ty1', possible loss of data
1>        with
1>        [
1>            _Ty=int
1>        ]
1>        and
1>        [
1>            _Ty1=uint16_t
1>        ]
[...]\include\caf\detail\tuple_vals.hpp(78): message : see reference to function template instantiation 'std::pair<uint16_t,const type_info *>::pair<int,const type_info*,0>(_Other1 &&,_Other2 &&) noexcept' being compiled
1>        with
1>        [
1>            _Other1=int,
1>            _Other2=const type_info *
1>        ]
[...]\include\caf\detail\tuple_vals.hpp(78): message : see reference to function template instantiation 'std::pair<uint16_t,const type_info *>::pair<int,const type_info*,0>(_Other1 &&,_Other2 &&) noexcept' being compiled
1>        with
1>        [
1>            _Other1=int,
1>            _Other2=const type_info *
1>        ]
[...]\include\caf\detail\tuple_vals.hpp(77): message : while compiling class template member function 'caf::type_erased_tuple::rtti_pair caf::detail::tuple_vals_type_helper<mipactors::ClientPhysicalId,0>::get(void) noexcept'
[...]\include\caf\detail\tuple_vals.hpp(110): message : see reference to function template instantiation 'caf::type_erased_tuple::rtti_pair caf::detail::tuple_vals_type_helper<mipactors::ClientPhysicalId,0>::get(void) noexcept' being compiled
[...]\include\caf\detail\tuple_vals.hpp(110): message : see reference to class template instantiation 'caf::detail::tuple_vals_type_helper<mipactors::ClientPhysicalId,0>' being compiled
[...]\include\caf\mailbox_element.hpp(120): message : see reference to function template instantiation 'caf::detail::tuple_vals_impl<caf::type_erased_tuple,mipactors::ClientPhysicalId>::tuple_vals_impl<const mipactors::ClientPhysicalId&>(const mipactors::ClientPhysicalId &)' being compiled
[...]\include\caf\mailbox_element.hpp(119): message : see reference to function template instantiation 'caf::detail::tuple_vals_impl<caf::type_erased_tuple,mipactors::ClientPhysicalId>::tuple_vals_impl<const mipactors::ClientPhysicalId&>(const mipactors::ClientPhysicalId &)' being compiled
[...]\include\caf\mailbox_element.hpp(213): message : see reference to function template instantiation 'caf::mailbox_element_vals<mipactors::ClientPhysicalId>::mailbox_element_vals<const mipactors::ClientPhysicalId&>(caf::strong_actor_ptr &&,caf::message_id,caf::mailbox_element::forwarding_stack &&,const mipactors::ClientPhysicalId &)' being compiled
[...]\include\caf\mailbox_element.hpp(212): message : see reference to function template instantiation 'caf::mailbox_element_vals<mipactors::ClientPhysicalId>::mailbox_element_vals<const mipactors::ClientPhysicalId&>(caf::strong_actor_ptr &&,caf::message_id,caf::mailbox_element::forwarding_stack &&,const mipactors::ClientPhysicalId &)' being compiled
[...]\include\caf\abstract_actor.hpp(120): message : see reference to function template instantiation 'std::unique_ptr<caf::mailbox_element,caf::detail::disposer> caf::make_mailbox_element<const mipactors::ClientPhysicalId&,>(caf::strong_actor_ptr,caf::message_id,caf::mailbox_element::forwarding_stack,T)' being compiled
1>        with
1>        [
1>            T=const mipactors::ClientPhysicalId &
1>        ]
[...]\include\caf\mixin\sender.hpp(84): message : see reference to function template instantiation 'void caf::abstract_actor::eq_impl<const mipactors::ClientPhysicalId&>(caf::message_id,caf::strong_actor_ptr,caf::execution_unit *,const mipactors::ClientPhysicalId &)' being compiled
[...]): message : see reference to function template instantiation 'void caf::mixin::sender<B,D>::send<caf::message_priority::high,caf::actor,const mipactors::ClientPhysicalId&>(const Dest &,const mipactors::ClientPhysicalId &)' being compiled
1>        with
1>        [
1>            B=caf::mixin::requester<caf::local_actor,caf::blocking_actor>,
1>            D=caf::blocking_actor,
1>            Dest=caf::actor
1>        ]
[...] message : see reference to function template instantiation 'void caf::mixin::sender<B,D>::send<caf::message_priority::high,caf::actor,const mipactors::ClientPhysicalId&>(const Dest &,const mipactors::ClientPhysicalId &)' being compiled
1>        with
1>        [
1>            B=caf::mixin::requester<caf::local_actor,caf::blocking_actor>,
1>            D=caf::blocking_actor,
1>            Dest=caf::actor
1>        ]

The issue seems caused by returning an int instead of a uint16_t in **tuple_vals.hpp**:

template <class T>
struct tuple_vals_type_helper<T, 0> {
  static typename message_data::rtti_pair get() noexcept {
    return {0, &typeid(T)};
  }
};

and **type_erased_value_impl.hpp**:

  static rtti_pair type(std::integral_constant<uint16_t, 0>) {
    return { 0, &typeid(value_type)};
  }

**Comment by Neverlord** [comment]
Closing here, because `type_erased_value` no longer exists. 🙂
