### ISSUE TITLE
Unexpected message after anon_send

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1046]
Getting some odd behaviour, I'm using anon_send(this, get_buff_atom_v)  from my actor to it's self, the handler will respond with a caf::result<mybuffer>, which if fulfilled via a response promise.

I'm expecting this to basically trigger the message handler and throw away the reply as I'm not using request.

What appears to be happening is that the reply is sent back to my message queue, as if I'd done send(this, mybuffer) 

This then kills the actor with unexpected message.

*** unexpected message [id: 20, name: PlayheadActor]: (<unprintable>)

Am I doing something wrong, or have I found a nasty bug ?

**Comment by Neverlord** [comment]
This one is actually intentionally. The return type of message handlers always sends a message back to the sender*. The only difference between asynchronous messages and requests is that the latter gives users a way to correlate two messages without ambiguity.

If you don't care about any response message, you can use `anon_send` instead.

* or to the next stage when using pipelining.

**Comment by alatdneg** [comment]
anon_send has the same problem. Which does sound like a bug.

**Comment by Neverlord** [comment]
Oh, sorry! I somehow missed the part that you're already using `anon_send`. Do have a minimal snippet at hand that reproduces this?

**Comment by alatdneg** [comment]
I tried both.

Just for context I'm a senior dev (team of three, likely to grow) in a a large post production facility (DNeg). 

We're writing a (hopefully  opensource) playback tool, like RV/FrameCycler etc., but better with a heavy VFX leaning.

I was the guilty party that forced the use of CAF, as was the cleanest implementation of MPI, and there was no way I wanted to go the semaphore/signal/mutex route.

All actors are event_based_actor actor classes.
After sending the anon_send i get

*** unexpected message [id: 20, name: PlayheadActor]: (<unprintable>)

```
	request(source_, infinite, media::get_media_uri_atom_v, t).then(
		[=](const std::pair<caf::uri, int> &result) mutable {
			const auto &[ uri, frame ] = result;
			anon_send(pre_reader_, media_reader::precache_image_atom_v, uri, frame, when, base_.uuid());
		},
	    [=](const error&err) mutable {
      	}
	);
```

**Comment by Neverlord** [comment]
> We're writing a (hopefully opensource) playback tool, like RV/FrameCycler etc., but better with a heavy VFX leaning.

Cool! I hope you're making good progress on the project!

> I was the guilty party that forced the use of CAF

Despite this bug, I hope you had a good experience so far with CAF. 🙂

If you have any suggestions how we can smooth out the learning curve for adopting CAF, please feel free to stop by in chat or drop me a mail.

> there was no way I wanted to go the semaphore/signal/mutex route.

You're really preaching to the choir here. 😉

**Comment by alatdneg** [comment]
> Despite this bug, I hope you had a good experience so far with CAF. 
> 
> If you have any suggestions how we can smooth out the learning curve for adopting CAF, please feel free to stop by in chat or drop me a mail.
> 

Yeah it's been very good so far, initial learning curve was a bit tough though, mostly simple things like how do I send/recieve a message from a event_based_actor.

I suspect a the problem is a lot of the examples are fairly simple, it'd handy to have examples of more complex behaviour.

I soon found things like response promises (which seemed fairly specialised) are used all over the place in my code.

Some general guide lines along the lines of "if you want to do this, you do this and this".
 
> You're really preaching to the choir here.

Yeah, life's so easy when everything is single threaded (locally), async behaviour is far easier to deal with.

**Comment by alatdneg** [comment]
Were you able to reproduce this problem ? I'm see it again, and I can't side step it this time.

Same problem, I'm using anon_send but still getting a response send back with triggers the unexpected message warning. 

The remote code is responding with a caf::result<bool>. And I get *** unexpected message [id: 40, name: PlaylistActor]: (true)

In the caller.

**Comment by alatdneg** [comment]
The unexpected msg also seems to stop the actor responding (dies ?), if I change the default_handler to skip, it seems okay.

**Comment by Neverlord** [comment]
> Were you able to reproduce this problem ?

Not yet, but it's on my todo list.
