### ISSUE TITLE
Please clarify API/ABI stability guarantees

### ISSUE THREAD

**Issue by hillu** [actor-framework/actor-framework#1049]
I am trying to figure out what meaning is attached to version numbers. [This blog post](http://blog.actor-framework.org/2019-11/breaking-changes/) tells me that there will be breaking changes with the next bump in ´CAF_VERSION_MINOR`, but I am not clear whether ABI breakage should be expected when only `CAF_VERSION_PATCH` changes.

Should I expect semantic versioning guarantees, i.e. will a program built and dynamically linked with libraries from 0.17.0 still work with libraries from any 0.17.x release?

**Comment by Neverlord** [comment]
Hi @hillu!

Excellent question. We've never openly discussed or documented our versioning policy or future plans.

> Should I expect semantic versioning guarantees

We currently have no such policies in place. We generally only put bugfixes or additions to patch-level changes, but there's no auditing or automatic testing for ABI compatibility.

That being said, we are going to adapt semantic versioning once we reach CAF 1.0.

We don't have a definite roadmap at the moment. However, with CAF 0.18 we'll finally have full .dll support on Windows and with it a way to define the ABI interface (via visibility `hidden` on UNIX). Also, the new type ID API is a big improvement to the current `add_message_type` API by removing one of the main pitfalls we've seen in practice (it's just too easy to forget adding a type to your config, especially when refactoring). My hope is that we there won't be a CAF 0.20.

**Comment by hillu** [comment]
I think that
> We generally only put bugfixes or additions to patch-level changes
is good enough a clarification for my purposes right now. Thank you!
