### ISSUE TITLE
Calling delayed_send in a test environment leads to an endless loop

### ISSUE THREAD

**Issue by Serbis** [actor-framework/actor-framework#1054]
Suppose the following situation. There is some periodic operation implemented through delayed_send. The actor sends a message to himself through a certain time interval and the handler makes a new call delayed_send to send the same message to himself and so on.
```c++
[&](internals::keep_alive_tick &msg) {
  // Send keep-alive message to shctl
  i_shell.keep_alive();

  // Reset timer
  delayed_send(this, keep_alive_interval, internals::keep_alive_tick {});
}
```
This code works correctly, but if you test the handler for this message, an unexpected behavior of the actor occurs.
```c++
CAF_TEST("for 'keep_alive' command must send keep-alive to the shell pool") {
  scoped_actor  probe {sys};
  scoped_actor probe_gate_out {sys};
  scoped_actor probe_io_actor {sys};
  sys.registry().put(GATE_OUT_ACTOR_KEY, probe_gate_out);
  auto app_ctl_actor = sys.spawn<app_ctl>(0, 1, 2, 4, probe_io_actor);

  probe_io_actor->send(app_ctl_actor, app_ctl::internals::keep_alive_tick {});
  sched.run_once();

  expect((long, long, shell_pool::commands::keep_alive), from(app_ctl_actor).to(probe_gate_out));
}
```
When delayed_send is called, the message handler is immedeatly called up again, it again calls delayed_send, and again, the handler is called again and so on until the test fixture timeout is called.

**Comment by Serbis** [comment]
Addition - it seems that any call to delayed_send in a test environment leads to an immediate call to the handler of the sent message. In the case of regular tasks, this in fact leads to deadlock on the handler of the scheduled message. This is an extraordinarily significant problem, since a single call to at least one such message handler leads to half the execution of the entire bunch of hundreds of tests.

**Comment by Neverlord** [comment]
Just to be sure: are you using the `test_coordinator_fixture`? Are you maybe calling `inline_all_enqueues`?

**Comment by Serbis** [comment]
Yes, fixture from the broken test:
```c++
struct app_ctl_fixture : test_coordinator_fixture<> {
  app_ctl_fixture() {
    application_config::instance().initialize(test_config { .shctl_pool_entry_lifetime = 1000000 });
    run();
  }
};
```

**Comment by josephnoir** [comment]
Hi, I'm looking into this. What I was able to reproduce is the endless loop. Here is my test case:

```cpp
CAF_TEST(delayed send loop) {                                                                                                                                                                         
  auto looper = sys.spawn(looper_testee_impl, 1);                                                                                                                                                        
  while(sched.try_run_once())                                                                                                                                                               
    ;                                                                                                                            
  CAF_MESSAGE("before delayed send");                                                                                                                          
  // self->delayed_send(looper, seconds(1), 1);                                                                                                                                      
  self->send(looper, 1);                                                                                                                            
  CAF_MESSAGE("after delayed send");                                                                                                                                                        
  //sched.trigger_timeout();                                                                                                                      
  sched.run_once();                                                                                                              
  CAF_MESSAGE("done");                                                                                                                                                          
}
```

The `looper_testee_impl` uses `delayed_send` with a one second timeout to send itself an incremented int and it receives an bigger-than-expected int, it will fail the test. What this prints for me is the following. Hence my suspicion with the stop function.

```
  -> before delayed send [line 98]
  -> after delayed send [line 101]
  -> loop with 1 [line 44]
  -> done [line 104]
  -> loop with 2 [line 44]
  -> hit unexpected loop counter 2 [line 46]  // CAF_FAIL message
     REQUIRED: test failure
```

The second loop is triggered (or at least printed) *after* "done".  That lead me to believe that this was a result of `test_coordinator::stop()`, which will call `trigger_timeouts()` as along as it can run something. Turns out, the `test_coordinator_fixture` itself calls run as well in its destructor.

*How to solve this:* We could make triggering timeouts in `run` optional. There might be cases where this is the desired behavior after all.

> Addition - it seems that any call to delayed_send in a test environment leads to an immediate call to the handler of the sent message.

That part I can't reproduce. How long is your timeout?

**Comment by Neverlord** [comment]
Closing due to lack of feedback.
