### ISSUE TITLE
OpenSSL module spins if write_some returns SSL_ERROR_WANT_READ

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1060]
While looking into https://github.com/zeek/zeek/issues/837, I found that CAF spins indefinitely in the poll loop if the SSL wants to *read* data before it can send something. This is especially the case during handshake, because SSL returns ` SSL_ERROR_WANT_READ` when trying to send before the host received the `ClientHello`.

**Comment by xiewei20082008** [comment]
Hi Neverlord, we reproduced this on a VM with a slow network io, i.e., a VM with an emulated NIC and low CPU freq. This issue can cause high CPU usage and the VM was completely hanging up.

I created a PR to fix it, could you help review it?

https://github.com/actor-framework/actor-framework/pull/1276

**Comment by Neverlord** [comment]
> I created a PR to fix it, could you help review it?

Sure thing! Thank you for the PR! 🙂
