### ISSUE TITLE
Inconsistent naming: component-blacklist / component-filter

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1064]
The actually usable configuration option seems to be `logger.component-blacklist`, and the docs and defaults have a `logger.component-filter` option.

The defaults even say this is a string, when is should be a vector of strings.

Is there a central way to get _all_ CAF command line options? I've found it really quite confusing to go through defaults.hpp and then having to grep the source code for the variable names with the underscores replaced with dashes.

```
❯ git grep "component[_-]\(filter\|blacklist\)"
doc/tex/ConfiguringActorApplications.tex:The two configuration options \lstinline^logger-component-filter^ and
examples/caf-application.ini:component-blacklist=[]
libcaf_core/caf/defaults.hpp:extern string_view component_filter;
libcaf_core/caf/logger.hpp:  std::vector<atom_value> component_blacklist;
libcaf_core/src/actor_system_config.cpp:    .add<std::vector<atom_value>>("component-blacklist",
libcaf_core/src/actor_system_config.cpp:  put_missing(logger_group, "component-blacklist", std::vector<atom_value>{});
libcaf_core/src/defaults.cpp:string_view component_filter = "";
libcaf_core/src/logger.cpp:  return !std::any_of(component_blacklist.begin(), component_blacklist.end(),
libcaf_core/src/logger.cpp:  auto blacklist = get_if<atom_list>(&cfg, "logger.component-blacklist");
libcaf_core/src/logger.cpp:    component_blacklist = move_if_optional(blacklist);
libcaf_core/src/logger.cpp:    msg += ", component-blacklist = ";
libcaf_core/src/logger.cpp:    msg += deep_to_string(component_blacklist);
libcaf_core/test/settings.cpp:    logger["component-blacklist"] = make_config_value_list(atom("caf"));
```

**Comment by Neverlord** [comment]
Thanks for opening the ticket! We'll clean up the docs. 

> Is there a central way to get all CAF command line options?

Yes. You can ask a CAF application (e.g. the `hello_world` example) for all valid options:

```
hello_world --long-help
(...)
  --logger.component-blacklist=<list of atom>        : excluded components for logging
(...)
```

You can also ask for a dump of the configuration used by default:

```
hello_world --dump-config
```

**Comment by dominiklohmann** [comment]
Ah, thanks for the quick reply. I had not seen either of these options before, that's exactly what I needed.
