### ISSUE TITLE
Error in debug build in MinGW: middleman.cpp.obj: 'File too big'

### ISSUE THREAD

**Issue by rakai93** [actor-framework/actor-framework#1088]
When building in a MinGW environment with gcc 8.1, everything works fine for a release build. However, debug builds fail with the following error:

    <user-home>/.conan/data/mingw_installer/1.0/conan/stable/package/4b8f5a096ecfd6aabff608521169f167b01837ec/bin/../lib/gcc/x86_64-w64-mingw32/bin/as.exe: 
    CMakeFiles\libcaf_io_static.dir\src\io\middleman.cpp.obj: too many sections (33330)
    <user-home>\AppData\Local\Temp\cca5aj28.s: Assembler messages:
    <user-home>\AppData\Local\Temp\cca5aj28.s: Fatal error: can't write 111 bytes to section .text of CMakeFiles\libcaf_io_static.dir\src\io\middleman.cpp.obj: 'File too big'
    <user-home>/.conan/data/mingw_installer/1.0/conan/stable/package/4b8f5a096ecfd6aabff608521169f167b01837ec/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\libcaf_io_static.dir\src\io\middleman.cpp.obj: too many sections (33330)
    <user-home>\AppData\Local\Temp\cca5aj28.s: Fatal error: can't close CMakeFiles\libcaf_io_static.dir\src\io\middleman.cpp.obj: File too big

Looks like the object file has grown too big. Is there anything wrong with my environment, any way to work around this, or is it simply too big and additional compile flags are needed (e.g. -mbig-obj)?

**Comment by Neverlord** [comment]
What version of CAF are you using? CAF 0.17.4?

> is it simply too big and additional compile flags are needed (e.g. -mbig-obj)?

That's most likely the case. Does it work if you pass in the extra flag?

**Comment by rakai93** [comment]
Sorry for the lack of details, I'm using CAF 0.17.3.
Yes, it works if I pass the extra compile flags `-Wa,-mbig-obj` using cmake's set_source_files_properties on src/io/middleman.cpp when using gcc.

**Comment by Neverlord** [comment]
MingGW is not an officially supported platform, so closing here. Would accept a PR, though.
