### ISSUE TITLE
Nested STL containers not being sent over middleman.

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1092]
I've got a message type response type

std::vector<std::pair<Uuid,actor>>

If I don't declare 

`config.add_message_type<std::vector<std::pair<Uuid,actor>>>("vec_uuid_actor");
`
I get the expected 
`cannot serialize message because a type was not added to the types list, typeid name: St6vectorISt4pairIN7xstudio7utility4UuidEN3caf5actorEESaIS6_EE
`

Once I do declare it and send a message to this actor, I never get the reply, it definitely received the message, but it's as if middleman is silently dropping the response. 

I'd expect to see an error on receiving the reply about not knowing how to handle the message type, but I get nothing back.

cheers!

**Comment by alatdneg** [comment]
If I return `std::pair<std::string,int> ` it works the remote actor gets the response.
If I return `std::vector<std::pair<std::string,int>> ` it fails with type not added to list.
If I then add 
`config.add_message_type<std::pair<std::string,int>>("ud_actor");`
I don't get the warning but I receive no message, adding 
`config.add_message_type<std::vector<std::pair<std::string,int>>>("vud_actor");` has no effect.

**Comment by alatdneg** [comment]
Looks like the fault is in my code, as I can see the events when tracing, just need to work out the message type id..

**Comment by Neverlord** [comment]
I like those questions that take care of themselves. ;)

Just a bit extra context:

CAF generally doesn't add 'derived' types when calling `add_message_type`. As of CAF 0.17, CAF does 'silently' add `vector<T>` and `stream<T>` to enable streaming. This won't be the case with 0.18, though. In 0.18, you'll have to explicitly give each type its own ID.
