### ISSUE TITLE
Frozen BASP nodes never disconnect

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1094]
We currently rely on TCP for detecting disconnect. However, (very rarely) we've observed frozen nodes where the TCP connection despite heartbeats appeared to remain intact while the remote side never responded to anything.

Rather than relying on TCP, we should actively monitor remote nodes and sever the connection after a (configurable) certain number of heartbeats were skipped.

**Comment by josephnoir** [comment]
There are other approaches to failure detection aside from just counting missing heartbeats, such as the [Phi Accrual Failure Detector](https://pdfs.semanticscholar.org/11ae/4c0c0d0c36dc177c1fff5eb84fa49aa3e1a8.pdf) which is available in [Akka](https://doc.akka.io/docs/akka/current/typed/failure-detector.html) and [Cassandra](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/gms/FailureDetector.java). Not sure if we just want to wing it or maybe give this some thought.

**Comment by Neverlord** [comment]
Gossip protocols certainly make sense in a cluster setup to agree on whether a node failed or not. I think the connection monitoring discussed here is complementary to that.

**Comment by Neverlord** [comment]
Sorry, next time I should click the link first. :)

This is not about the gossip protocol they're using in their cluster framework. I think a more sophisticated error detector would be nice to have, but I think it should go into `caf_net` instead. Connection timeout + heartbeat should do the trick for now.

**Comment by Neverlord** [comment]
Fixed via #1096.
