### ISSUE TITLE
What is the replacement for detail::singletons::set_scheduling_coordinator?

### ISSUE THREAD

**Issue by ElandKany** [actor-framework/actor-framework#1105]
i‘m newer for caf,  there is a question about singletons,  cause that latest version has deleted the section, i need to know what instead of that. thanks’

**Comment by Neverlord** [comment]
Singletons got the axe with 0.15, which released in 2016. If you are new to CAF, how did you get started on such an ancient release? Also, anything in `caf::detail` is considered private API and shouldn't get called by users.

What are you trying to do? Are you looking to configure the scheduling policy or do you wish to roll your own scheduler?

For configuring the scheduler:
- https://actor-framework.readthedocs.io/en/0.17.5/ConfiguringActorApplications.html#command-line-options-and-ini-configuration-files

More about the migration away from singletons:
- https://actor-framework.readthedocs.io/en/0.17.5/MigrationGuides.html#to-0-15
- http://blog.actor-framework.org/2016-05/a-glimpse-at-the-future-of-caf/
- http://blog.actor-framework.org/2016-06/0.15-pre-release/

**Comment by ElandKany** [comment]
emmm. it was referred by another developer before, i just request for the update...

**Comment by Neverlord** [comment]
There is no one-to-one replacement for that function. The function could be used to do one of several things. To provide guidance on what to call instead, we first need to understand why you were calling this private function.

**Comment by ElandKany** [comment]
understand,
