### ISSUE TITLE
scoped_actor with `hide = true` ctor param isn't actually hided

### ISSUE THREAD

**Issue by uentity** [actor-framework/actor-framework#1106]
After spawning `scoped_actor` with `hide = true` set I can observe that running actors counter gets actually incremented. Debug log also confirms this, as I'm getting lines like these:
```
10155 caf_flow DEBUG actor0 140046648248128 caf make_actor make_actor.hpp:43 SPAWN ; ID = 9 ; NAME = scoped_actor ; TYPE = caf.ANON.impl ; ARGS = (actor_config(detached_flag, hidden_flag)) ; NODE = BB3B10D9924D7A4AD18A1EC65F0D7F926253DC00#61033 ; GROUPS = []
10155 caf DEBUG actor9 140046648248128 caf.actor_registry inc_running actor_registry.cpp:102 value = 2
```
Then, for example, `actor_system::await_all_actors_done()` will block until scoped_actor quits.

1. Is this an expected behaviour or bug or am I missing something?
2. Where does `detached_flag` come from and what does it mean for scoped_actor?

PS. CAF v0.17.5.

**Comment by Neverlord** [comment]
@uentity why did you close the issue again?

**Comment by uentity** [comment]
I closed it only once, because this question isn't relevant for me any more. But issue exists and probably still need some fix.

I was fighting with proper termination of actor system and hangs because of misc actors, including scoped_actor instances, was still active because smb holds their handles.

One idea was to spawn scoped actors as hidden. But it didn't work out well and instead I end up with collecting all actors I need to kill at startup and killing them at once on exit.

BTW first approach was to add them to a group, but I discovered that unsubscribing from a group a lot of actors is very expensive.

**Comment by Neverlord** [comment]
Thanks for adding additional context. 🙂

Reopened, because the hiding flag still needs fixing.

> BTW first approach was to add them to a group, but I discovered that unsubscribing from a group a lot of actors is very expensive.

Looks like something we should look into. Unsubscribing requires locking a mutex and removing the caller from the list of subscribers. Maybe we can use a more efficient data structure here

**Comment by Neverlord** [comment]
> 2\. Where does `detached_flag` come from and what does it mean for scoped_actor?

The detached flag tells the actor that it's not running in the cooperatively managed thread pool. All blocking actors have this flag.

**Comment by uentity** [comment]
> > BTW first approach was to add them to a group, but I discovered that unsubscribing from a group a lot of actors is very expensive.
> 
> Looks like something we should look into. Unsubscribing requires locking a mutex and removing the caller from the list of subscribers. Maybe we can use a more efficient data structure here

Yeah, I've looked through the code and found that also. And now I discovered that I build CAF in ancient C++11 mode that don't even enable transparent `set` usage in `group_manager.cpp` :man_facepalming: After switching to C++17 all performance issues are gone (unsubscribing from a group is neglible). But if code fails into `find_if()` branch, then leaving a group is orders of magnitude slower, than joining it (checked that using profiler).

What I really miss about `group` API is 'kill all actors in a group and wait until they terminate'. I cannot directly send exit message to a group handle (why is that?). Also `scoped_actor::wait_for()` doesn't accept group handle. If that two pieces can be enabled then a task can be solved in two lines of code.

**Comment by uentity** [comment]
> Reopened, because the hiding flag still needs fixing.

I'm not quite sure, but I have a feeling (based on multiple experiments) that terminating instance of `caf::scoped_actor` **after** actor system has been actually destroyed can lead to problems (wrong memory free, segfaults, ...).

Can `scoped_actor` exit cleanly when actor system no longer exist? If no, then it's pointless to have `hide` flag exposed in constructor.

**Comment by Neverlord** [comment]
> Can `scoped_actor` exit cleanly when actor system no longer exist?

No, that will cause undefined behavior.

> If no, then what's the point to have `hide` flag exposed in constructor?

Mostly, the flag is meant for internal use. It allows CAF to have a couple of background actors that don't block the process from terminating when reaching the end of `main`. However, CAF still makes sure to destroy these actors before actually destroying the actor system.

You can do the same in user code, but you must make sure to not leave main before clearing up custom "background workers". Usually by having cleanup code behind `await_all_actors_done()`.

> What I really miss about `group` API is 'kill all actors in a group and wait until they terminate'.

Groups are meant for loose coupling. It's actually straightforward to implement a group module based on IP multicast. And because it's loose coupling, there's no way to know who joined the group. Due to the loose coupling, it also makes no sense for any actor to manage the lifetime of other members in the group.

The actor pools were supposed to fill the role of a 'managed' group, but the API feels clumsy and never left the experimental phase for that reason.

**Comment by Neverlord** [comment]
From what I can tell, the `scoped_actor` honors the `hide` flag:

```c++
scoped_actor::scoped_actor(actor_system& sys, bool hide) : context_(&sys) {        
  CAF_SET_LOGGER_SYS(&sys);                                                        
  actor_config cfg{&context_};                                                     
  if (hide)                                                                        
    cfg.flags |= abstract_actor::is_hidden_flag;                                   
  auto hdl = sys.spawn_impl<impl, no_spawn_options>(cfg);                          
  self_ = actor_cast<strong_actor_ptr>(std::move(hdl));                            
  prev_ = CAF_SET_AID(self_->id());                                                
}
```

@uentity closing here, but please feel free to ask followups here or on the mailing list.
