### ISSUE TITLE
Detached actors in the registry block shutdown

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#1110]
Issue: detached actors in registry must be removed explicitly for proper shutdown.

Version: CAF 0.17.5

Example:

```cpp
#include <caf/all.hpp>

using namespace caf;

behavior aut(event_based_actor* self) {
  return {
    [](std::string x) {
      return x;
    }
  };
}

int main() {
  actor_system_config cfg;
  actor_system sys{cfg};
  sys.registry().put(ok_atom::value, sys.spawn<detached>(aut));
  auto x = sys.registry().get(ok_atom::value);
  anon_send_exit(x, exit_reason::user_shutdown);
  // Comment to experience the hang.
  sys.registry().erase(ok_atom::value);
}
```

**Comment by sourcedelica** [comment]
Something that would be useful is a way to query the registry for all non-system actors.   A system actor would be something like the middleman.  That way a system could, at shutdown time, run that query and stop/kill all of the actors that are return before destroying the actor system.

**Comment by mavam** [comment]
> Something that would be useful is a way to query the registry for all non-system actors.

We use the registry only for actors that have global semantics, like a file system actor to encapsulate I/O for example. Of course it would be possible to pass it in the constructor to every other descendant actor, but it also clutters the interfaces if there are a handful of such components. For all other cases, we use a "user-space" actor that represents the own node state, like all user-spawned actors.

What's your use case for using the registry?

**Comment by sourcedelica** [comment]
We have very similar use cases.

**Comment by mavam** [comment]
I think this comment here may explain the deadlock:

```cpp
void actor_registry::erase(actor_id key) {
  // Stores a reference to the actor we're going to remove. This guarantees
  // that we aren't releasing the last reference to an actor while erasing it.
  // Releasing the final ref can trigger the actor to call its cleanup function
  // that in turn calls this function and we can end up in a deadlock.
  strong_actor_ptr ref;
  { // Lifetime scope of guard.
    exclusive_guard guard{instances_mtx_};
    auto i = entries_.find(key);
    if (i != entries_.end()) {
      ref.swap(i->second);
      entries_.erase(i);
    }
  }
}
```

**Comment by mavam** [comment]
Maybe the `erase` function leads down the wrong rabbit hole. We migrated away from the actor system registry, but an issue with detached actors persists: we don't get a DOWN message when monitoring and terminating them. Smaller examples don't reproduce the issue yet, unfortunately.

**Comment by mavam** [comment]
I ported the example to work with master and tried it out. The hang still persists. Then I checked out `issue/11961` after the possibly related fix. The issue is gone. I get a valid termination, closing this issue now.

For the record, here is the adapted example:

```cpp
#include <caf/all.hpp>

using namespace caf;

behavior aut(event_based_actor* self) {
  return {
    [](std::string x) {
      return x;
    }
  };
}

void caf_main(actor_system& sys) {
  sys.registry().put("aut", sys.spawn<detached>(aut));
  auto x = sys.registry().get("aut");
  anon_send_exit(x, exit_reason::user_shutdown);
  // Comment to experience the hang.
  sys.registry().erase("aut");
}

CAF_MAIN()
```
