### ISSUE TITLE
Warnings when building the OpenCL module

### ISSUE THREAD

**Issue by vklimovs** [actor-framework/actor-framework#1112]
Running following configure command:

`cmake -C /var/tmp/portage/dev-libs/caf-0.17.5/work/caf-0.17.5_build-abi_x86_32.x86/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCAF_BUILD_STATIC=no -DCAF_ENABLE_RUNTIME_CHECKS=yes -DCAF_LOG_LEVEL=DEBUG -DCAF_NO_EXAMPLES=no -DCAF_NO_OPENCL=no -DCAF_NO_OPENSSL=no -DCAF_NO_PYTHON=yes -DCAF_NO_TOOLS=no -DCAF_NO_UNIT_TESTS=no -DCMAKE_SKIP_RPATH=yes -DLIBRARY_OUTPUT_PATH=lib -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-libs/caf-0.17.5/work/caf-0.17.5_build-abi_x86_32.x86/gentoo_toolchain.cmake  /var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5`

Results in following errors:

`WARNING: Target "libcaf_opencl_shared" requests linking to directory "/var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5/libcaf_opencl".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "proper_matrix" requests linking to directory "/var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5/libcaf_opencl".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "simple_matrix" requests linking to directory "/var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5/libcaf_opencl".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "scan" requests linking to directory "/var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5/libcaf_opencl".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "curl_fuse" requests linking to directory "/var/tmp/portage/dev-libs/caf-0.17.5/work/actor-framework-0.17.5/libcaf_opencl".  Targets may link only to libraries.  CMake is dropping the item.`

(many more actual errors, probably from every target)

**Comment by vklimovs** [comment]
Sorry, I was imprecise: there are only warnings, many warnings as shown in the report. There are no other warnings or errors. It appears to successfully compile and tests pass after that, but still warnings like that does not look like its working as intended.

**Comment by Neverlord** [comment]
Ah, thanks for clarifying. The warnings are already "fixed" in `master` (what is going to be 0.18), simply because the OpenCL module no longer exists. We've also re-implemented the entire CMake scaffold to avoid similar warnings in the future.
