### ISSUE TITLE
Compiler error when using message types containing queues

### ISSUE THREAD

**Issue by jo-jstrm** [actor-framework/actor-framework#1114]
**Version:** CAF 0.17.4

**Issue:** 
- Despite providing begin(), end(), size(), and empty(), which is stated in the docs to be enough for a container to be supported as message type, sending `queue<>` inside of a  message causes a compiler error. On the contrary, using `deque<>` compiles and works.

**Steps to reproduce:** Compile code below. 

**Errors:**
- "/caf/data_processor.hpp:466:21: error: no matching function for call to ‘inspect(caf::serializer&, std::queue<double>&)’"
- "/caf/data_processor.hpp:501:18: error: no matching function for call to ‘caf::deserializer::apply(std::queue<double>&)’"
- ...

**Workaround:**
- Use `deque<>` instead of `queue<>`.

**Example:**
```
#include <queue>
#include <string>

#include "caf/all.hpp"
#include "caf/io/all.hpp"

using namespace caf;

//using start_atom = atom_constant<atom("start")>;

struct Data{
  double t;
  std::queue<double> values;
};
template <class Inspector>
typename Inspector::result_type inspect(Inspector& f, Data& x){
  return f(caf::meta::type_name("Data"), x.t, x.values);
}

class My_cfg : public caf::actor_system_config{
public:    
  bool start_talk; 

  std::string my_ip;
  int my_port;
  
  std::string buddy_ip;
  int buddy_port;

  My_cfg(){
    start_talk = false;

    my_ip = "localhost";
    my_port = 3332;
    
    buddy_ip = "localhost";
    buddy_port = 3333;

    add_message_type<Data>("Data");

    opt_group{custom_options_, "global"}
      .add(buddy_ip, "my_ip,i","set own address (default = 'localhost')")
      .add(buddy_port, "my_port,p","set own port (default = 3332)")
      .add(buddy_ip, "buddy_ip,j","set buddy's address (default = 'localhost')")
      .add(buddy_port, "buddy_port,q","set buddy's port (default = 3333)");
  }
};

behavior ping_actor(event_based_actor* self){
  return{
    [=](Data data){
      aout(self) << "*** Reveived data." << std::endl;
    }
  };
}

void caf_main(actor_system& system, const My_cfg& cfg){
  actor ping = system.spawn(ping_actor);

  auto published = io::publish(ping, cfg.my_port);
  if (!published){
    std::cerr << "*** publish failed: " << system.render(published.error()) << std::endl;
    return;
  }

  if(cfg.start_talk){
    Data data = Data();
    data.t = 0.5;
    data.values.push(1.1);
    data.values.push(2.2);

    auto buddy = system.middleman().remote_actor(cfg.buddy_ip, cfg.buddy_port);
    anon_send(*buddy, data);
  }  
}
CAF_MAIN(io::middleman)
```

**Comment by Neverlord** [comment]
Looking at the interfaces of [std::stack](https://en.cppreference.com/w/cpp/container/stack) and [std::queue](https://en.cppreference.com/w/cpp/container/queue): these data structures don't provide `begin()` and `end()`. This means CAF simply can't serialize them. The only way to iterate all elements of these data structures would be disassemble them via `pop` and then re-assemble then afterwards...
