### ISSUE TITLE
Any solution to callback hell?

### ISSUE THREAD

**Issue by xiewei20082008** [actor-framework/actor-framework#1136]
Hi,

We got a lot of nested requests in our project. I copied several lines of example as below. I know using make_function_view in an actor might cause dead lock, so is there any solution to such callback hell? Thank you in advance!

```
using inc_actor_t = typed_actor<
    replies_to<int>::with<int>
>;

inc_actor_t::behavior_type inc_impl(inc_actor_t::pointer self) {
    return {
        [=](int x) {
            return x+1;
        }
    };
}

void b_impl(event_based_actor *self, inc_actor_t a) {
    self->request(a, caf::infinite, 1).then(
        [=](int x) {
            self->request(a, caf::infinite, x).then(
                [=](int x) {
                    self->request(a, caf::infinite, x).then(
                        [=](int x) {
                            self->request(a, caf::infinite, x).then(
                                [=](int x) {
                                    cout << x << endl;
                                }
                            );
                        }
                    );
                }
            );
        }
    );
}

int main() {
    actor_system_config cfg;
    actor_system sys{cfg};
    inc_actor_t inc_actor = sys.spawn(inc_impl);
    sys.spawn(b_impl, inc_actor);
}
```

**Comment by Neverlord** [comment]
As long as your work flow is a sequence, where you need the output of each step as input to the next step, I don't think there's much CAF could do in this case to provide a better API without something like Monads in the language.

Coroutines may help eventually, but I don't think they're well supported at the moment.

**Comment by xiewei20082008** [comment]
I understand. Thank you for your reply.

**Comment by Neverlord** [comment]
Btw, we're always open for API suggestions should you have an idea how to streamline the code for such use cases. 🙂

**Comment by melg8** [comment]
My personal take on this would be, as suggested by @Neverlord using monadic bindings around types, returned by function view on actor.
Disclaimer: this is not production ready implementation, should be viewed only as code example.
Something like this:
``` C++
#include <iostream>
#include <vector>

#include "caf/all.hpp"
#include "caf/expected.hpp"

using namespace caf;

using inc_actor_t = typed_actor<replies_to<int>::with<int>>;

[[nodiscard]] inc_actor_t::behavior_type inc_impl(inc_actor_t::pointer self) {
  return {[=](int x) { return x + 1; }};
}

template <typename T, typename F>
[[nodiscard]] decltype(auto) mbind(const expected<T>& expected, F&& f) {
  using ReturnType =
    typename std::remove_cv<decltype(f(expected.value()))>::type;

  if (expected) {
    return f(expected.value());
  }
  if constexpr (!std::is_same_v<ReturnType, void>) {
    return ReturnType{expected.error()};
  }
}

template <typename T, typename F>
auto operator|(const expected<T>& expected, F&& f) {
  return mbind(expected, f);
}

void b_impl(event_based_actor* self, const inc_actor_t& a) {
  const auto increment = make_function_view(a);
  increment(1) | increment | increment | increment |
    [=](int x) { std::cout << x << std::endl; };
}

int main() {
  actor_system_config cfg;
  caf::core::init_global_meta_objects();
  actor_system sys{cfg};
  inc_actor_t inc_actor = sys.spawn(inc_impl);
  sys.spawn(b_impl, inc_actor);
}

```

**Comment by Neverlord** [comment]
I'd like to see first-class support for monads in C++ one day. Given that the `std::expected` proposal seems to go nowhere, I doubt we'll ever see it, though. I'd rather not go into this direction with CAF TBH. Once we go beyond small examples, supporting this comes with too many strings attached.

FWIW, you could use CAF's pipelining here instead:

```c++
void b_impl(event_based_actor* self, const inc_actor_t& a) {
  auto increment = make_function_view(a * a * a * a);
  std::cout << increment(1) << std::endl;
}
```

We're using `operator*`, because you cannot overload `.` in C++. The semantics is the same as the `.`-operator of function composition, i.e., `a.b = a(b(...))`.

I do have to admit that the pipelining is terribly documented at the moment, though.

**Comment by xiewei20082008** [comment]
> My personal take on this would be, as suggested by @Neverlord using monadic bindings around types, returned by function view on actor.
> Disclaimer: this is not production ready implementation, should be viewed only as code example.
> Something like this:
> 
> ```c++
> #include <iostream>
> #include <vector>
> 
> #include "caf/all.hpp"
> #include "caf/expected.hpp"
> 
> using namespace caf;
> 
> using inc_actor_t = typed_actor<replies_to<int>::with<int>>;
> 
> [[nodiscard]] inc_actor_t::behavior_type inc_impl(inc_actor_t::pointer self) {
>   return {[=](int x) { return x + 1; }};
> }
> 
> template <typename T, typename F>
> [[nodiscard]] decltype(auto) mbind(const expected<T>& expected, F&& f) {
>   using ReturnType =
>     typename std::remove_cv<decltype(f(expected.value()))>::type;
> 
>   if (expected) {
>     return f(expected.value());
>   }
>   if constexpr (!std::is_same_v<ReturnType, void>) {
>     return ReturnType{expected.error()};
>   }
> }
> 
> template <typename T, typename F>
> auto operator|(const expected<T>& expected, F&& f) {
>   return mbind(expected, f);
> }
> 
> void b_impl(event_based_actor* self, const inc_actor_t& a) {
>   const auto increment = make_function_view(a);
>   increment(1) | increment | increment | increment |
>     [=](int x) { std::cout << x << std::endl; };
> }
> 
> int main() {
>   actor_system_config cfg;
>   caf::core::init_global_meta_objects();
>   actor_system sys{cfg};
>   inc_actor_t inc_actor = sys.spawn(inc_impl);
>   sys.spawn(b_impl, inc_actor);
> }
> ```

Thank you for your reply. As using scoped_actor in an actor may cause a potential deadlock, so I am trying to keep myself avoiding using make_function_view here.

**Comment by xiewei20082008** [comment]
Hi @Neverlord, is that reasonable to add a feature for the request interface with signature:

request :: Actor, Ts ... -> Promise<R> 

Then we can do something like this.
```
void b_impl(event_based_actor *self, inc_actor_t a) {
    self->make_response_promise<int> rp;
    Promise<int> a= self->request(a, caf::infinite, 1);
    a.flatmap(
        [=](int v) {
            return self->request(v, caf::infinite, 1);
        }
    ).flatmap(
        [=](int v) {
            return self->request(v, caf::infinite, 1);
        }
    ).flatmap(
        [=](int v) {
            return self->request(v, caf::infinite, 1);
        }
    ).map(
        [=](int v) {
            return v+1;
        }
    );
    rp.deliver(a);
}
```

Thank you for your time.
