### ISSUE TITLE
CPU usage higher than before

### ISSUE THREAD

**Issue by lengye-cold** [actor-framework/actor-framework#1152]
when we update caf from 0.14.5 to 0.17.4 ，we find the CPU usage higher than before when the handset in screen-off status. we need some help, please. It's ours code:

using namespace caf;

actor_system_config g_cfg;
g_cfg.put("scheduler.policy", caf::atom("sharing"));
actor_system g_system {g_cfg};

actor_system *getActorSystem()
{
    return &g_system;
}

class CFilterDuplicatorFactory 
    : public CObjBase
    , public IObjectFactory
    , public IGlobalObject
{
private:
    static size_t const                         s_cWorkers;
    static size_t const                         s_cPage;
    static size_t const                         s_cMinSize;

    static void split(detail::actor_msg_vec& xs, message& msg)
    {
        msg.apply(
            [&] (uintptr_t pSrc, uintptr_t pDst, size_t cBuf) {
                size_t c = cBuf / xs.size();
                size_t cRemain = cBuf;
                size_t i = 0;
                for (; i != xs.size() - 1; i++) {
                    xs[i].second = make_message(pSrc, pDst, c);
                    pSrc += c;
                    pDst += c;
                    cRemain -= c;
                }
                xs[i].second = make_message(pSrc, pDst, cRemain);
            }
        );
    }

    static void join(size_t& cFinished, message& msg)
    {
        msg.apply(
            [&] (size_t cBuf) {
                cFinished += cBuf;
            }
        );
    }

    static behavior duplicator(event_based_actor* self)
    {
        std::ignore = self;
        return {
            [=] (uintptr_t pSrc, uintptr_t pDst, size_t cSize) -> size_t {
                if (pSrc + cSize < pDst || pDst + cSize < pSrc) {
                    ::memcpy_s(reinterpret_cast<void*>(pDst), cSize,
                               reinterpret_cast<void*>(pSrc), cSize);
                } else {
                    ::memmove_s(reinterpret_cast<void*>(pDst), cSize,
                                reinterpret_cast<void*>(pSrc), cSize);
                }
                return cSize;
            }
        };
    }

    actor                                       m_workers;

    TRetCode start() override
    {
        scoped_execution_unit context {getActorSystem()};
        m_workers = actor_pool::make(&context, actor_pool::split_join<size_t>(join, split));
        for (size_t i = 0; i != s_cWorkers; i++) {
            anon_send(m_workers, sys_atom::value, put_atom::value, getActorSystem()->spawn(duplicator));
        }
        return RC_OK;
    }

**Comment by Neverlord** [comment]
If you are already making such a big leap, why skip right ahead to 0.18? We've redesigned the messaging layer to make it more efficient, so it should perform better than the 0.17 series.

> handset in screen-off status

What hardware are we taking about? Also, which scheduler are you using? On devices with few cores, you might find the `sharing` policy to be a reasonable tradeoff for burning less CPU.

**Comment by lengye-cold** [comment]
> If you are already making such a big leap, why skip right ahead to 0.18? We've redesigned the messaging layer to make it more efficient, so it should perform better than the 0.17 series.
> 
> > handset in screen-off status
> 
> What hardware are we taking about? Also, which scheduler are you using? On devices with few cores, you might find the `sharing` policy to be a reasonable tradeoff for burning less CPU.

we find the reason, we used the work sharing policy in 0.14.5 ,but the work stealing in 0.17.4.
in 0.14.5 our code is :
detail::singletons::set_scheduling_coordinator(new scheduler::coordinator<policy::work_sharing>);

could I ask how to use work sharing in 0.17.4? thanks.

**Comment by Neverlord** [comment]
This is controlled by config parameters now: https://actor-framework.readthedocs.io/en/stable/ConfiguringActorApplications.html#command-line-options-and-ini-configuration-files. If you're switching to 0.18 right away (which I would recommend in your case), select the `latest` version of the manual instead of `stable`.

Btw, we also have a [Gitter chat](https://gitter.im/actor-framework/chat) for quick questions like this one.
