### ISSUE TITLE
Function would_block_or_temporarily_unavailable contains equal expressions

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1154]
Code in native_socket.cpp:121:
```
bool would_block_or_temporarily_unavailable(int errcode) {
  return errcode == EAGAIN || errcode == EWOULDBLOCK;
}
```
Trigger -Wlogical-op warning, because EWOULDBLOCK is defined with value EAGAIN, so here is the same check done twice.

**Comment by Neverlord** [comment]
Thanks for reporting! Reminds me that we wanted to revisit default warning levels when building CAF. There are also some warnings when building with GCC at the moment.
