### ISSUE TITLE
glibcxx assertations failure in examples for 0.17.6 release version

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1155]
# Preamble
Hello, I'm trying to check if CAF is suitable for my project and trying to integrate it.
I encountered sigabrt-s on examples, which I couldn't reproduce without any changes on the original library itself. Some time later I checked for differences in building flags and now that is purified version of the problem.

# Setup
1. Os: docker image of ubuntu 16
2. Compiler: gcc version 8.4.0 

# Steps to reproduce
1. Download CAF, checkout commit on tag 0.17.6
2. Add to cmake CMAKE_CXX_FLAGS:
  * -D_GLIBCXX_ASSERTIONS
  * -U_FORTIFY_SOURCE
  * -D_FORTIFY_SOURCE=0
  * -D_GLIBCXX_DEBUG_PEDANTIC
3. run cmake and build
4. try to run any of examples without any arguments. For example  distributed_calculator

## Expected behavior
Program should start with Usage: example and wait for finish (or just exit with 0 for other examples).

## Observed behavior
Program show Usage text, but crashes with core dumped, return code 134.
Example output:
```
Usage:
  quit                  : terminates the program
  connect <host> <port> : connects to a remote actor
  <x> + <y>             : adds two integers
  <x> - <y>             : subtracts two integers

*** no server received via config, please use "connect <host> <port>" before using the calculator
/usr/include/c++/8/bits/shared_ptr_base.h:1005: std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type& std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::operator*() const [with _Tp = std::tuple<>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2; bool <anonymous> = false; bool <anonymous> = false; std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type = std::tuple<>]: Assertion '_M_get() != nullptr' failed.
Aborted (core dumped)
```

This behavior affects at least this example programs, started with no arguments:
- aout
- caf-core-test
- caf-io-test
- caf-openssl-test (with report of unhandled exception std::bad_cast 
- caf-vec
- calculator
- calculator_behavior
- cell
- custom_types_1-2-3
- and so on.

What is more important - my own code, from a separate compilation unit with code from example - trigger the same behavior.
What is interesting - ctest doesn't report any problems:
```
100% tests passed, 0 tests failed out of 114.
```
Main cause of issue is flag:
_GLIBCXX_ASSERTIONS [which](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html) "enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers." 

# Ps.
I'm really glad that i found your library, and think it's great, really looking forward to rewriting messy code with clean actor-based solutions, but i can't just remove listed flags from my build, so would appreciate any help or hotfix solutions from developers and community.

**Comment by Neverlord** [comment]
Thanks for reporting! I'll look into it. Our debug builds run ASAN, so I'm a bit surprised.

> - caf-core-test
> - caf-io-test

These only exist since 0.18 RC1. Is 0.17.6 accurate? Or did you check bot versions?

> I'm really glad that i found your library

Out of curiosity, how did you find CAF? Do you see something we could/should do to make CAF more visible? 🙂

**Comment by melg8** [comment]
About caf-core-test/caf-io-test - that's maybe my mistake. I've started by using master branch, but encountered errors with examples, which I need to understand how to use CAF for my tasks, then - switched to the latest release 0.17.6 - and tried to integrate it - but encountered problems with assertion failure. So maybe on that moment - I got mixed build folder with additional tests from the new version.

About finding CAF. I've encountered a task where old code which run on a single tread with blocking calls is needed to split across several applications and several devices, but my knowledge of the field of networking is not so great, I've started to search for solutions. So I needed a framework that help me to split my single threaded application introducing networking, serialization, asynchronous without much pain. I've looked into different solutions - from boos asio, then learned about reactive programming and rxcpp, and then from some discussion about it on reddit - about CAF library.

I'm personally learned about libraries or new paradigms from several main sources - one is basically reddit /r/cpp, other is - youtube videos from some conferences. And I think CAF in that sense lack of video tutorials, which could help to introduce core concepts and explain how cool idea of actors really is. 

Btw. If you can guide me, what examples should use as base for such task: I have like 3 different applications - each should start on its own - with separate main. But they all live in a single node, and doesn't need to communicate out of that machine. 2 applications are clients, one - is gui (qt widgets example I guess) - and one is a client which need something like RPC - send a message with data, and block until the answer (good or bad) returned. 3 application is a server which need to handle commands from gui, can send commands to gui, and should handle commands from 2-nd app. My main question will be - should I use something like in group server example - with publish_local_groups, or this is overkill and I need more like distributed_calculator - type of solution. Thing about distributed calculator I don't really like - is too much boilerplate with establishing connected state with server.

**Comment by Neverlord** [comment]
Thanks for the feedback!

> something like RPC - send a message with data, and block until the answer (good or bad) returned. 3 application is a server which need to handle commands from gui, can send commands to gui, and should handle commands from 2-nd app. My main question will be - should I use something like in group server example - with publish_local_groups, or this is overkill and I need more like distributed_calculator - type of solution. Thing about distributed calculator I don't really like - is too much boilerplate with establishing connected state with server.

If you have an RPC-like structure then I wouldn't go with pub/sub. The distributed calculator implements automatic reconnections, the boilerplate code you need actually just boils down to `publish` (server) and `remote_actor` (client).

**Comment by Neverlord** [comment]
>     2. Add to cmake CMAKE_CXX_FLAGS:
> 
>     * -D_GLIBCXX_ASSERTIONS
>     * -U_FORTIFY_SOURCE
>     * -D_FORTIFY_SOURCE=0
>     * -D_GLIBCXX_DEBUG_PEDANTIC

The [GCC manual](https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html) states that:

> To use the libstdc++ debug mode, compile your application with the compiler flag `-D_GLIBCXX_DEBUG`.

@melg8: enabling the debug mode sets some of the flags you've used as far as I can tell. Was there a particular reason for you to pick flags individually?

When enabling the debug mode, CAF won't compile at the moment. We still need to look into that, just curious why you went with this set of flags over `-D_GLIBCXX_DEBUG`.

**Comment by Neverlord** [comment]
Seems like it's all been fixed up and one of the builds in our pipeline now passes `-D_GLIBCXX_DEBUG` to GCC (along with ASAN and UBSan). Feel free to open followup issues if you still experience issues. 🙂
