### ISSUE TITLE
Undefined behavior in string_view::compare on strncmp call

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1164]
# Problem
In file function  [string_view::compare](https://github.com/actor-framework/actor-framework/blob/f84a26cf1597995f846cd277dc3e6b9238999d50/libcaf_core/src/string_view.cpp#L104)
When string_view::compare is called and
1. s0 == s1
2. s0 == 0

Then strncmp is called with nullptr as values:
```return strncmp(data(), str.data(), s0);```

And calling [strncmp](https://en.cppreference.com/w/cpp/string/byte/strncmp) with nullptr arguments triggers undefined behaviour:
"The behavior is undefined when either lhs or rhs is the null pointer."

# Steps to reproduce
In order to separate this problem from other memory issues we will use branch with fixed memory leaks: issue/1160 or master if issue/1160 branch will be merged.
- Os: Docker image of Ubuntu 16
- Compiler: gcc 8.4.0

1. git clone https://github.com/actor-framework/actor-framework
2. cd actor-framework/
3. git checkout issue/1160
4. CXXFLAGS="-fuse-ld=gold -fno-sanitize-recover=undefined" ./configure --dev-mode
5. cd build/
6. cmake --build . 
7. ctest

# Expected behavior
All test should pass with no errors

# Observed behavior
4 tests failing:
```
The following tests FAILED:
	 30 - detail.config_consumer (Failed)
	 36 - detail.meta_object (Failed)
	107 - string_view (Failed)
	124 - uri (Failed)
```

Each of them points to the same root of problem, for example
```
ctest -VV -R "uri"
```
gives output
```
UpdateCTestConfiguration  from :/tmp/actor-framework/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/tmp/actor-framework/build/DartConfiguration.tcl
Test project /tmp/actor-framework/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 124
    Start 124: uri

124: Test command: /tmp/actor-framework/build/libcaf_core/caf-core-test "-r300" "-n" "-v5" "-s"^uri$""
124: Test timeout computed to be: 10000000
124: +----------------------------------------------------------------------+
124:                                   uri
124: +----------------------------------------------------------------------+
124: 
124: - default URIs are empty
124: ** /tmp/actor-framework/libcaf_core/test/uri.cpp:223  ::caf::test::equal_to(x.empty(), true)
124: /tmp/actor-framework/libcaf_core/src/string_view.cpp:111:19: runtime error: null pointer passed as argument 1, which is declared to never be null
1/1 Test #124: uri ..............................***Failed    0.06 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec

The following tests FAILED:
	124 - uri (Failed)
Errors while running CTest
```
So [actor-framework/libcaf_core/src/string_view.cpp:111:19](https://github.com/actor-framework/actor-framework/blob/f84a26cf1597995f846cd277dc3e6b9238999d50/libcaf_core/src/string_view.cpp#L111)

# Thoughts
I think it would be great if -fno-sanitize-recover=undefined flag and ubsan in general would be added at least for some compiler/targes into CI system, to prevent regression in the future.

**Comment by Neverlord** [comment]
Thank you once more for reporting! I've filed a PR to take care of this issue that also enables UBSan in our CI.
