### ISSUE TITLE
Equivalent if/else branches

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1171]
# Problem
Code could be simplified, or this is a bug, and should have different in types or values.
It contains todo, about c++14, so maybe 0.18 is perfect time to fix.

# Where
 https://github.com/actor-framework/actor-framework/blob/8528ff220c2728afb6675fcd4d93246815a90df5/libcaf_core/src/scheduled_actor.cpp#L941

Code snippet:
``` C++
  if (p.id_of(*ptr) == normal_queue_index) {
    auto& q = std::get<normal_queue_index>(qs);
    q.inc_total_task_size(q.policy().task_size(*ptr));
    q.cache().push_back(ptr.release());
  } else {
    auto& q = std::get<normal_queue_index>(qs);
    q.inc_total_task_size(q.policy().task_size(*ptr));
    q.cache().push_back(ptr.release());
  }
```

**Comment by Neverlord** [comment]
This one's actually a bug, the `else` tree should push to the cache of the urgent queue.
