### ISSUE TITLE
Comparison of values from different enums

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1175]
# Problem 
Inside macro expansion compared two values from different enumerations, maybe that's not intended?

# Where
https://github.com/actor-framework/actor-framework/blob/8528ff220c2728afb6675fcd4d93246815a90df5/libcaf_core/caf/detail/parser/read_floating_point.hpp#L121

# Expansion
Expansion:
``` C++
if (::caf::detail::parser::in_whitelist('-', ch)) {
  auto action_impl = [&]() -> decltype(auto) { return sign = minus; }; // Here is part from macro argument
  if constexpr (std::is_same<pec, decltype(action_impl())>::value) {
    if (auto code = action_impl(); code != pec::success) { // Here comparison takes place
      ps.code = code;
      return;
    }
  } else {
    action_impl();
  }
  ch = ps.next();
  goto s_has_sign;
}
```

Compared  pec::sucess from:
https://github.com/actor-framework/actor-framework/blob/8528ff220c2728afb6675fcd4d93246815a90df5/libcaf_core/caf/pec.hpp#L32-L35

With sign_t::minus from:
https://github.com/actor-framework/actor-framework/blob/8528ff220c2728afb6675fcd4d93246815a90df5/libcaf_core/caf/detail/parser/read_floating_point.hpp#L52

**Comment by Neverlord** [comment]
Did you find that with a tool? Looks like a false positive to me. The comparison cannot take place if `code` has type `sign_t` because of the `if constexpr` in the line above.

**Comment by melg8** [comment]
Yea, I've looked into it more carefully, that's a false positive.
