### ISSUE TITLE
Function with bool return type doesn't return value

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1176]
# Problem
Inside if branch there is no return statement, and no return statement by default at the end of function, so that path will trigger UB on call.

# Where
https://github.com/actor-framework/actor-framework/blob/8528ff220c2728afb6675fcd4d93246815a90df5/libcaf_core/test/nasty.hpp#L26-L36

**Comment by Neverlord** [comment]
Well, it *is* called nasty. 🤪

Just kidding.
