### ISSUE TITLE
Example dining_philosophers cannot be cleanly exited

### ISSUE THREAD

**Issue by XMatrixXiang** [actor-framework/actor-framework#1185]
I compiled the latest code (branch:master) with vs2019, I successfully ran the "dining_philosophers" example, and when I pressed Ctrl-C, the console showed that the program exit code was 1

**Comment by Neverlord** [comment]
Hm, the dining philosopher example never stops on its own (by design). If you kill it, then that's an abnormal exit. To you take issue with the example not having a "press enter to exit" or some other form of shutdown?
