### ISSUE TITLE
typed_actor rejects exit_msg

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1188]
It is currently impossible to send a `exit_msg` to a `typed_actor` with regular `send` (as opposed to `send_exit`) without using `actor_cast<actor>` on the `typed_actor` . This functionality is important because `delayed_send_exit` and `scheduled_send_exit` do not exist, and also because it should technically be possible to `delegate` an `exit_msg`.

**Comment by Neverlord** [comment]
> It is currently impossible to send a `exit_msg` to a `typed_actor` with regular `send`

This is a design choice, not a bug. 🙂

Exit, down and timeout messages are system messages that get handled outside of an actors regular behavior. CAF won't actively stop you from calling `send` with these types (at the moment), but it's not the intended use. Much like you wouldn't return `std::runtime_error` from a function to indicate an error; you'd throw it.

> `delayed_send_exit` and `scheduled_send_exit` do not exist

I'm not sure if I'm fully on board with adding them, though. Exit and down messages are generally generated by the system when actors terminate. `send_exit` allows actors to "fake their death" and the anonymous version can be useful to "inject" an exit signal to certain actors to cascade into a shutdown (usually with `exit_reason::user_shutdown`). I suppose in the later case one could make a point for the delayed versions. Feel free to file a feature request ticket for those two.

> it should technically be possible to `delegate` an `exit_msg`.

What would the semantics of that even be? Exit messages are never request messages. The notion of handling an exit signal on behalf of another actor makes no sense to me. Response promises deal with regular message flow, not with system-level events.
