### ISSUE TITLE
Why does CAF_ENABLE_TYPE_ID_CHECKS no longer exist?

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1217]
During the message refactoring, the compile-time type ID check feature was removed.

- If the removal was intentional, please add it to the changelog. It was introduced just recently with CAF 0.17.5, so I assumed it was here to stay.
- If the removal was unintentional, please add it back. The code used to live in `caf/make_message.hpp`, which is now a deprecated include.

I can also open a PR to add the feature back into `caf::make_message(Ts&&...)` in `caf/message.hpp` if desired.

**Comment by Neverlord** [comment]
From the 0.17.5 release:

> In order to allow users to start migrating towards upcoming API changes, CAF 0.17.5 includes a subset of the CAF 0.18 `type_id` API. (...) to opt into the compile-time checks for all message types, users can set the `CAF_ENABLE_TYPE_ID_CHECKS` (...).

There is no "opting in" any more, so this configuration parameter no longer applies. In fact, it never existed on the main branch of CAF. This parameter only exists on the `release/0.17` branch and makes no sense outside of the 0.17 `type_id` backport.

Making this more obvious in the release notes for 0.18-rc.1 may have been a good idea, but retrospectively updating release notes and changelog seems not worth the effort IMO.

**Comment by dominiklohmann** [comment]
Alright, thanks for the heads up. This wasn't clear at all from the 0.18 release notes to me.

**Comment by Neverlord** [comment]
> Alright, thanks for the heads up. This wasn't clear at all from the 0.18 release notes to me.

It isn't obvious, so you're probably not the only one. Thanks for opening the issue! At least people that wonder what happened to the parameter at least can find the answer here now. 🙂

**Comment by mavam** [comment]
Maybe we can move this issue to Discussions so that others find it as well?

**Comment by Neverlord** [comment]
I don't see how moving the issue would increase visibility. GitHub's search picks up this issue just fine for me: https://github.com/actor-framework/actor-framework/search?q=CAF_ENABLE_TYPE_ID_CHECKS.

**Comment by mavam** [comment]
My thinking was that a closed issue is only visible is you go via search. If you use Discussion, it's like looking at a recent thread, exposing it to everybody who browses there.

(I have no strong preference here, just thought this might benefit others.)
