### ISSUE TITLE
Python module and 0.18

### ISSUE THREAD

**Issue by al3ph** [actor-framework/actor-framework#1219]
Hi, I'm currently updating my code base to 0.18, but I've hit a snag with my python module, it's based off the old 0.17 caf_python code.

With the move to 0.18, I'm stumped as to what I need to change. As it seems there has been a fair bit of change to the message code.

https://github.com/actor-framework/actor-framework/blob/e0c8ff163e122a40f05a5f198eb6f682c548a7ef/libcaf_python/src/main.cpp#L459

This code no longer builds as type_erased_tuple isn't a thing anymore. I'm wondering about how I port this ?

Any help/pointers would be greatly appreciated.

cheers!

**Comment by al3ph** [comment]
I've worked it out from the headers/source. Yay for open source! And good documentation :)

**Comment by Neverlord** [comment]
> Yay for open source! And good documentation :)

Yay indeed! 🥳

Btw, we've removed the python module mostly because we felt it provided too little value as it was. Are you implementing custom bindings for your applications or are you working on a binding layer that could become generic enough to stand on its own?

**Comment by al3ph** [comment]
Custom I'm afraid, to be honest the implementation is very close to the original,  it obviously suffers from being a request/receive implementation. At some point it'll need to be a bit smarter but multithreading / python :(

I think the original has merit as a template for implementing other languages. With out that as a reference I'd have been stuck.

**Comment by Neverlord** [comment]
Hm, maybe we can revive it as an example or something like that if it's useful as a template.

**Comment by al3ph** [comment]
Yep, that sounds like a good idea.
