### ISSUE TITLE
CAF 0.19 API cleanup

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1236]
This is a meta issue for deprecating/removing obsolete API parts with 0.19.

We can replace some CAF classes with standard types now. TODOs are:

- [x] make `caf::byte` an alias for `std::byte` and deprecate the type alias
- [x] make `caf::string_view` an alias for `std::string_view` and deprecate the type alias
- [x] deprecate `caf::optional` and use `std::optional` in CAF instead, note that we can't switch to a type alias here because `caf::optional` has features that `std::optional` does not implement such as optional references
- [x] deprecate `caf::variant` and use `std::variant` in CAF instead, a simple type alias isn't enough since we'd also have to "import" `std::visit` and so on plus there might be API incompatibilities; thus it's probably better to leave `caf::variant` as it is and just deprecate it

Obsolete utilities that we can deprecate:

- [x] `caf::replies_to` and `caf::reacts_to`
- [x] the entire `SumType` API in `sum_type.hpp`

APIs that can leave the experimental phase:

- [x] connecting CAF nodes via `io::middleman::open`/`io::middleman::connect`
- [x] remote spawning of actors

Classes that are already obsolete and that we can remove:

- [x] `memory_managed`
- [x] `static_visitor`
- [x] `type_erased_value` (technically not deprecated, but simply has been overlooked and is now unused)
- [x] `caf::meta` API for legacy inspectors

Headers that are already obsolete and that we can remove:

- [x] `atom.hpp`

**Comment by jakobod** [comment]
I will start working on this now. Any objections?

**Comment by Neverlord** [comment]
> I will start working on this now. Any objections?

No, just recommendations: `byte` and `string_view` should be very straightforward. 🙂

**Comment by Neverlord** [comment]
Slight change of plans. The `sum_type` API and `variant` had some nasty templates that weren't properly guarded with `enable_if`. It would have been nice to give them a deprecation cycle as well, but the effort to 'sanitize' the implementation to behave nicely when mixing with `std::variant` isn't worth the time investment. So get the axe right away.
