### ISSUE TITLE
remote_actor never returns if remote actor_system is hung.

### ISSUE THREAD

**Issue by al3ph** [actor-framework/actor-framework#1240]
Is there a way of handling this ? I spawn my app then suspend it, when I then try connecting to it via middleman the remote_actor function doesn't return.

I'd expect it to fail, as the remote system won't be responding.

This might be happening at the network layer, via a connection timeout, but there doesn't seem to be any method to control that.

cheers

**Comment by Neverlord** [comment]
Which CAF version are you on?

If you're using current main branch or the 0.18 tag, this is probably the regression we've observed in #1235. We're currently testing a patch for this (which migrates the 0.17.5 connection timeout feature) in the branch `topic/pr-1096-integration`. Feel free to give the branch a shot if you're on 0.18. The default's are very conservative (10s heartbeat, 30s connection timeout), so feel free to set stricter timings.

**Comment by al3ph** [comment]
Yeah 0.18, I side stepped the issue by spawning the call from within another actor, and timeing out on the request.

I'll have a look when the PR gets merged. ta.

**Comment by Neverlord** [comment]
@al3ph the patch is available as 0.18.1 and also landed in the main branch. Please let us know if the issue still prevails.
