### ISSUE TITLE
Stabilize ABI and set CMake package compatibility to `SameMajorVersion`

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1254]
We don't have an official versioning policy yet, but we generally follow the policy that patch-level changes shall be backwards compatible. Hence, applications that expect CAF version 0.18.1 should be able to build against 0.18.4 (but not 0.19.0).

The logical step would be to relax the version check of our CMake package. For CMake, this means just applying this patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 11dd1e96..628ccee9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -450,7 +450,7 @@ install(EXPORT CAFTargets
 write_basic_package_version_file(
   "${CMAKE_CURRENT_BINARY_DIR}/CAFConfigVersion.cmake"
   VERSION ${CAF_VERSION}
-  COMPATIBILITY ExactVersion)
+  COMPATIBILITY SameMinorVersion)
 
 configure_package_config_file(
   "${CMAKE_CURRENT_SOURCE_DIR}/cmake/CAFConfig.cmake.in"
```

*However*, our CI currently doesn't check for ABI compatibility of changes. I'm not sure how CMake packages link targets. My assumption would be that this policy would also allow users to upgrade their local CAF installation without re-building applications. If that's the case then we need to figure out how to integrate ABI compatibility checks into our CI first (and whether we want to invest the time or just stick to the current yet restrictive `ExactVersion` policy).

**Comment by Neverlord** [comment]
There's a tool for checking ABI compatibility: https://github.com/lvc/abi-compliance-checker.

**Comment by Neverlord** [comment]
With 1.0 coming up, I thought about ABI compatibility again (yeah, I know, everyone's favorite topic). I think what we really want to support going forward is `SameMajorVersion`.

For this, I think we will need to introduce `inline namespace` for versioning into the code base. Basically, if we do any of that:

- Touch member variables of a class (add/remove/reorder)
- Touch virtual member functions of class (add/remove/reorder)
- Change (member) function parameters

We'll have to copy the thing into a new version namespace, do the changes there, and finally make the new version the `inline` (and remove `inline` from the old thing).

Here's a trivial example of what I mean:

```cpp
namespace caf {

inline namespace v1 {

struct foo {
  int8_t value1 = 0;
  int32_t value2 = 0;
  int8_t value2 = 0;
};

} // namespace v1

} // namespace caf
```

Say we want to change the order of the values around to reduce padding. The new header would then look like this:

```cpp
namespace caf {

inline namespace v2 {

struct foo {
  int8_t value1 = 0;
  int8_t value2 = 0;
  int32_t value2 = 0;
};

} // namespace v2

namespace v1 {

struct foo {
  int8_t value1 = 0;
  int32_t value2 = 0;
  int8_t value2 = 0;
};

} // namespace v1

} // namespace caf
```

The version would be per-class / block and has nothing to do with the CAF release version. This will allow us to keep the ABI stable while at the same time allowing us to keep improving the API.

Per convention, I think the current (i.e., latest) version should always come first, except maybe if we call the old version from the new version.

We would commit to keeping the ABI stable for major releases. Once a new major release rolls around, we can strip all of the old versions from the code base. This means a release may accumulate some baggage over its lifetime (in the form of almost-duplicates), but we have the major releases to get rid of old baggage eventually. Hence, users would have to re-compile their applications for major releases but they can (and should) update CAF on their system for the same major version without breaking existing applications. This will make it much easier to package CAF.

So the obvious task coming out of this is to add `inline namespace v1` to (almost) all of the CAF headers...

```
$ find . -name '*.hpp' | wc -l
     630
```

**Comment by Neverlord** [comment]
Well... turns out inline namespaces are not quite as useful as I had hoped.

This is forbidden by the standard:

```c++
namespace caf::v1 {
    int some_var = 0;
}

namespace caf { inline namespace v1 {
    int some_other_var = 6;
}}
```

(opening an namespace as `inline` if it hasn't been `inline` the first time the compiler sees it)

This gives a warning:

```c++
namespace caf { inline namespace v1 {
    int some_var = 0;
}}

namespace caf::v1 {
    int some_other_var = 6;
}
```

Let's say `some_other_var` is the thing that we want to replace with a `v2` version. I though that `inline namespace foo { class a; class b; }` would only inline the stuff in that block, i.e., would be like `namespace foo { class a; class b; } using foo::a; using foo::b;`.

However, it's actually more like `namespace foo { class a; class b; } using namespace foo;` (but making `foo` actually transparent at the outer scope). Which is why the compiler will warn about this: if you open `foo` again as non-inline, it will still be exposed to the outer namespace due to the earlier `using namespace foo`.

Looks like inline namespaces are only useful if you version an entire API, not classes. We could push everything into `inline namespace v1` now. But once we have the need for *any* class in CAF to create a `v2` for it, we'd have to remove the `inline` for `v1` entirely and then add `using` for all `v1` classes we need individually... That's a lot of boilerplate. If that's what we'd have to do anyways at some point, we could as well push everything into `v1` (without `inline`) and then `using v1::foo;`. That'd basically put the boilerplate work upfront (instead of doing it later if we first need a `v2`). We're talking about hundreds of `using ...` statements here. We would probably put all of the `using` statements into the forwarding headers, so at least we'd have them in one place. However, the forwarding headers would now become *much* bigger in order to cover all of the free functions.

One alternative could be to make the inline namespace somehow at a per-file basis. Using a macro? Like `CAF_OPEN_INLINE_NAMESPACE(v1)` that then magically expands to a unique namespace, e.g., by adding the file name. So it could expand to something like `inline namespace v1_foo_hpp`. I'd rather not use macros, though. It would also make writing the forward definitions awkward.

Slightly less awkward: `inline namespace foo_hpp { inline namespace v1 {`. Since the `v1` is now nested under `foo_hpp`, we can "un-inline" `foo_hpp::v1` and replace it with `foo_hpp::inline v2`. That would still make writing the forward declarations a bit awkward, but at least it isn't using macros and allows us to pick a version per file. I think that's much more manageable, but it will inflate type names quite a bit. If you get a compiler error for, say, `actor_system_config`, the name spelled out by the compiler would be something like `caf::actor_system_config_hpp::v1::actor_system_config`. Hm...

We could at least shorten this by hashing the file names. Using the FNV hash for the file name would give `caf::b2d0c237::v1::actor_system_config` (a hash might start with a number, so we'd have to use some prefix in practice). At least shorter, but we'd have a lot of these magic numbers in the code base. We could probably trim this down to 3 characters`*` with a bit of tooling to at least keep the actual type names readable in compiler errors.

The per-file versioning is probably the "least bad" option. We would have to write a tool to generate the magic numbers for the `hpp` files and maintaining the forwarding headers will be a bit of a hassle. Still better than juggling hundreds of individual `using` statements.

If anyone has a better idea: chime in. 🙂

`*` Simply enumerating all files. The first character goes from a-Z (52 possible characters) and character 2 and 3 may also use 0-9. This would give us ~200k unique "IDs" to work with.

**Comment by riemass** [comment]
> We'll have to copy the thing into a new version namespace...

Somebody stop this man.

To be honest, before reading this I thought the only way to achieve stable ABI in C++ is by using `extern "C"`, but it seems my knowledge is lacking behind the compiler vendors. As you mentioned, this method comes with a big overhead of chores. I suppose we could automate the forward declarations somehow, (with tools like `clang-query` or `treesitter` I guess we would be smart enough, given enough man-days).

There is also the programming overhead. I don't think you considered this in your analysis, but suppose we change the internal layout of one `class`. This would break ABI compatibility, and we would version the interface with a new `inline` namespace.

```cpp
inline namespace cde {
  class foo {
  // ...
  };
}
namespace abc {
  class foo {
  // ...
  };
}
```

All good and byte-sized (ignoring the `fwd.hpp` for now). However, now all the places where `foo` is used have broken ABI:

```cpp
inline napespace xyz {
  class bar {
    foo instance;
  };
}
```

Which means we would have split `bar` into two versions as well, and use the expanded type name for `foo`.

```cpp
inline napespace yza {
  class bar {
    cde::foo instance;
  };
}
napespace xyz {
  class bar {
    abc::foo instance;
  };
}
```

Now all structs that use `bar` have a broken ABI. This creates a considerable fan-out of chores to do on any ABI break. Considering this, if we opt in for this solution, we should use the full namespace name internally, so we can easier find all instances of a class. File-based version would introduce mental overhead (use version `abc` in version `xyz`, and version `cde` in `yza`). 

Don't know how often we have to break ABI in maintenece mode. Don't get me the wrong way, having `ExactMajorVersion` would be great. I'm trying to keep the fun in the project. Maybe by good branching strategies, and commiting to a major release every ~12 months we could plan ABI breaks in advance, and have the `ExactMinorVersion` mode for the 
CAF users to receive patches.

**Comment by Neverlord** [comment]
> To be honest, before reading this I thought the only way to achieve stable ABI in C++ is by using `extern "C"`, but it seems my knowledge is lacking behind the compiler vendors.

There's also good ol' interfaces and the PIMPL idiom to keep implementation details out of header files and to have opaque types that allow for flexibility "behind the scenes". That's why I'm quite adamant about pushing state out of interfaces like `logger` and `scheduler`. Probably the biggest API mistake we did in the past was class-based spawn, because it forces us to have the full implementations available. Now that we deprecate that, we will be able to have classes like `event_based_actor` as interfaces and completely hide the actor class implementations eventually (hopefully 2.0).

> There is also the programming overhead. I don't think you considered this in your analysis, but suppose we change the internal layout of one `class`. This would break ABI compatibility, and we would version the interface with a new `inline` namespace.
> 
> (...(
> 
> Which means we would have split `bar` into two versions as well, and use the expanded type name for `foo`.

True, if you split class `foo`, you'll also have to split all classes that depend on it. I don't really see a way around that, though.

It definitely means that we will do ABI breaks only if absolutely necessary *or* if a new major release comes around. And I think that's basically what a major release is there for, right? If I compile my application with CAF 1.x, I know the binary will be compatible with any 1.y release as long as y > x. However, once CAF 2 rolls around, I need to re-compile the application (which may involve updating my code if the API changed).

ABI compatibility certainly isn't a "fun" topic, but I think it's important. We want to see CAF in more package managers and this means we will have to care about the ABI.

And yes, it means there certainly are classes that we would not break the ABI mid-release cycle. Classes with tons of dependencies like `abstract_actor`, `actor_system`, `flow::observable`, and so on. Changing the ABI on any of those will basically fork the API for a large set of files.

The inline namespaces would at least give us the option to evolve some parts of the API mid-release. The question is whether the overhead is really worth it in the end. Maybe we should just have one inline namespace: `caf::inline v1` for CAF 1.x, `caf::inline v2` for 2.x, and so on. That would simply make sure that you can't run an application that has been compiled against CAF 1 with a CAF 2 release. That would mean that we cannot do any new APIs mid-release cycle that requires ABI changes in CAF. And maybe that's fine.

**Comment by Neverlord** [comment]
@riemass all right, how about this?

- We commit to keeping API and ABI stable during a major release cycle.
- We set the CMake compatibility to `SameMajorVersion`.
- We use `namespace caf::inline vX {`, whereas `X` is the CAF major version. That way, you cannot link against CAF 1.x and then accidentally load a CAF 2.x library.

In addition, we continue moving towards better separation of interfaces and implementations. We already made good progress on that front with `scheduler` and `logger` being pure interface classes now and the implementations are completely hidden. This already allows us to change/add logger and scheduler implementations without breaking changes. By deprecating class-based spawn, we can do the next step with CAF 2.0 and turn all actor classes into interfaces.

For 1.0, this means introducing a `CAF_OPEN_NAMESPACE` `CAF_CLOSE_NAMESPACE` macro pair (to have a central place to define the version). The other todo is setting up an ABI compatibility check in our CI.

**Comment by riemass** [comment]
Committing to the `SameMajorVersion` without introducing the full namespace mangling will take a lot of the initial load from us. Like you said, we can use the time to explore the problem space and prepare the codebase. 
Just to check if we are on the same page if we would need to break ABI compatibility for a future release, would it be acceptable to introduce the `namespace v2` while still developing `v1`, implement everything we need in `v2`, and let it cook whdile we wait for the v2 release?

**Comment by Neverlord** [comment]
> Just to check if we are on the same page if we would need to break ABI compatibility for a future release, would it be acceptable to introduce the `namespace v2` while still developing `v1`, implement everything we need in `v2`, and let it cook whdile we wait for the v2 release?

I would probably prefer not having any `caf::v2` symbols in a CAF 1 release and just give experimental features a different name until renaming them for CAF 2. Once it's time for a next release, we always do a release branch for the "old" version and then start breaking stuff in the main branch. But sounds like we have an agreement. Let's do it this way and see how it goes.

**Comment by Neverlord** [comment]
We did a ton of work here:
- the `scheduler` and `logger` are now pure interfaces with hidden default implementations
- classes like `actor_system` now use the PIMPL idiom
- in caf-net, we have drastically removed the amount of templates and pushed templated code that must be shared by multiple implementations into the new `caf::internal` namespace

I would really like to completely hide the implementation of our actor types, but that will have to wait for CAF 2.0 because it requires getting of class-based spawn first (will be deprecated with 1.0).

As for 1.0, I think that's about as far as we can push things for now.
