### ISSUE TITLE
Expose reference count of response promises

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1257]
As of CAF 0.18, the internal state of response promises is reference counted. However, it is impossible to get the reference count. I would like to see `unique()` and `get_reference_count()` exposed.

If a patch for this is welcome I can prepare a PR shortly.

My use case for this is that I want to send a response promise alongside a CAF stream so I can notify the source when the last sink I broadcast to is done, i.e., the reference count is exactly 2.

**Comment by Neverlord** [comment]
> I  want to send a response promise

I'm afraid I need to stop you right there. A response promise is private to an actor and it's unsafe to pass a response promises to another actor. Rather than forwarding the promise, CAF allows you to forward the original request to also delegate who's responsible for it.

**Comment by dominiklohmann** [comment]
In that case I have some UB to fix that happened to work. Tangential question then, other than that consider this resolved.

I've been looking into implementing some form of stream control lately. Here's the problem I'm looking to solve:

I have an actor of type A that hosts a stream source of X. It broadcasts to actors of type B hosting stream stages, which themselves broadcast to actors of type C. When the last C actor is done I want A to be notified.

Sadly, CAF does not allow for sending messages other than the stream type itself, so I need to change the stream type to include some form of header. Here's the current idea:

```cpp
struct header : caf::ref_counted {
  caf::typed_actor<caf::result<void> (stream_finished_atom)>
    handle = {};
};

template <class Body>
struct message {
  struct header header = {};
  Body body = {};
};
```

Then, instead of having a `caf::stream<X>`, I have a `caf::stream<message<Source, X>>`, and can detect whether the header's reference count is two and send a `stream_finished_atom` message to the handle embedded in the header.

However, this all feels very hacky. Is there a better way to send control messages in continuous streams?
