### ISSUE TITLE
actor_system blocking on shutdown.

### ISSUE THREAD

**Issue by al3ph** [actor-framework/actor-framework#1261]
``I've got a derived version of the python actor code, so far it's been working fine, but I've an instance that co exists in the same process as the remote system it talks to.  (Don't ask :))

The problem I'm having is that when shutting everything down the python components actor_system gets stuck waiting on a  mutex.

I've no idea why.

Here's a bit of code to give an idea of what should happen.

As far as I'm aware when the destructor is called, self_ should be destroyed, and then system_.
So self_ shouldn't block the system_. 

Is that correct or have I made a bad assumption about how scoped actors would behave here.

cheers

```
class py_context : public py_config {
  public:
    py_context(int argc = 0, char **argv = nullptr)
        : py_config(argc, argv), system_(*this), self_(system_), remote_() {
        system_.await_actors_before_shutdown(false);
    }

    // shutdown system
    virtual ~py_context() {
        disconnect();
    }
    // get's stuck in the system_ shutdown (I think). This happens without even connecting to the remote actor system.

 .. other code...

    actor_system system_;
    scoped_actor self_;
    actor remote_;
};
```

**Comment by al3ph** [comment]
I'll do a debug build of CAF to find out exactly where it's getting stuck.

**Comment by al3ph** [comment]
in actor_system stuck on the logger wait. 
```
  CAF_SET_LOGGER_SYS(nullptr);
  logger_.reset();
  std::unique_lock<std::mutex> guard{logger_dtor_mtx_};
  while (!logger_dtor_done_)
    logger_dtor_cv_.wait(guard);
}

```

**Comment by al3ph** [comment]
Side effect of two actor systems running in the same process ? Is the logger shared ?

**Comment by Neverlord** [comment]
> I've an instance that co exists in the same process as the remote system it talks to. (Don't ask :))\

I think I do have to ask, though. 😉

Running two CAF instances in the same process is only safe as long as you strictly separate the two and connect them over a localhost connection. Otherwise, you're asking for all kinds of trouble. So before going any deeper, are you doing that?

**Comment by al3ph** [comment]
Yep. :) I briefly tried the other way and it didn't end well.

**Comment by al3ph** [comment]
The python module is designed for doing python/api calls outside the application (pybind11), but it's also used inside the app for embedded python tasks. Hence the two actor systems, it's possible there's a better way of doing this but my knowledge of this stuff is limited.

**Comment by Neverlord** [comment]
Ok, should work as long as you use `publish` and `remote_actor` to connect the two instances and make sure they never share a thread. Another thing that looks suspicious is `await_actors_before_shutdown(false)`. There are only few cases where this is a good idea.

Could Python hold on to any CAF handles (actor or otherwise)? Unless you are consequently using `with` blocks on the Python side, you could just end up destroying things in the wrong order and thus try to destroy the actor system while other parts are still running.

**Comment by al3ph** [comment]
Seems to be okay, I wouldn't expect it to be getting stuck where it is if that was the problem. I'd expect segfaults.

**Comment by al3ph** [comment]
await_actors_before_shutdown(false). was just me checking that running actors was the problem, but it's the logger not shutting down that appears to be the problem. Though why it's not shutting down is beyond me.

**Comment by al3ph** [comment]
Doesn't calling CAF_SET_LOGGER_SYS(nullptr) mean that the logger can no notify the system that it's shutdown ?
```
  // reset logger and wait until dtor was called
  CAF_SET_LOGGER_SYS(nullptr);
  logger_.reset();
  std::unique_lock<std::mutex> guard{logger_dtor_mtx_};
  while (!logger_dtor_done_)
    logger_dtor_cv_.wait(guard);

```

**Comment by al3ph** [comment]
// Stores a pointer to the system-wide logger.
thread_local intrusive_ptr<logger> current_logger_ptr;

Or maybe this ? If there are two systems running int he same process, would there be a conflict ?

**Comment by Neverlord** [comment]
> Or maybe this ? If there are two systems running int he same process, would there be a conflict ?

That's why I said "make sure they never share a thread". 🙂

Did you run this in LLDB/GDB to see what other threads are running at the end?

**Comment by al3ph** [comment]
Ah sorry, it's a event_based actor, my mistake, I guess it should be a blocking one then it get's it's own thread ? I managed to get around it by calling CAF_SET_LOGGER_SYS on the main actor system after creating the secondary one. But I imagine that's not a safe solution.

Thank you for your help, I think we've found the mistake I was making.

**Comment by Neverlord** [comment]
Yeah, running two actor systems in one process does come with a couple of pitfalls. Glad you've found it! 👍
