### ISSUE TITLE
Why does demonitoring not drop already queued down messages?

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1301]
I ran into a weird issue today where I kept receiving unexpected DOWN messages in some situations. Turns out that we demonitored the target actor, but in some cases already had DOWN messages from the target actor queued in the actor's mailbox.

I think `self->demonitor(target_addr)` should go through the mailbox of `self`, and automatically remove all enqueued DOWN messages where the `down_msg::source` equals `target_addr`.

Note that I am still using CAF 0.17.6; we have yet to upgrade to 0.18, so if this is no longer an issue with the newer release then please just ignore this issue.

**Comment by Neverlord** [comment]
I believe there are some misconceptions what monitoring means and (doesn't). Monitoring an actor simply means "I'd like to receive a down message when this goes down". Not more, not less. If you call `monitor(foo)` twice, you'll receive two down messages.

In case of a demonitor, your simply saying you're no longer interested. But a down message may already be in your mailbox or in-flight. However, CAF has no way of telling whether the down message in your mailbox belongs to *this* `demonitor` right now or whether you've called `monitor` multiple times. In any case, the in-flight message would still arrive and CAF would actively need to maintain some state to ignore it. Monitors have no ID and they aren't supposed to have transactional semantics.
