### ISSUE TITLE
Why does serializing and actor_addr keep the actor system running?

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1340]
If I try to serialise the actor_addr it stops the actor system from exiting automatically.

If I skip the bs.apply, then the system exits cleanly, if I don't skip it, I manually have to send_exit to the StackActor.

Any idea what's going on here, as I'm confused. 

```
    auto t = f.self->spawn<StackActor>();
   {
       binary_serializer::container_type sbuf;
       binary_serializer bs{f.system, sbuf};
       auto e = bs.apply(caf::actor_cast<caf::actor_addr>(t));
   }

```

**Comment by alatdneg** [comment]
Just for some context I'm trying to store an actor addr as a string in a json structure, then destringify it elsewhere.

**Comment by Neverlord** [comment]
If you serialize an actor, the serializer will store the handle in the actor registry. In serialized form, the actor address is an actor ID plus a node ID. When deserializing, these two IDs need to somehow reproduce a handle to the original actor. Hence the registry.

By "clean exiting", you probably relied on the reference counting on actors before to dispose unreachable actors after throwing away all actor handles. The `StackActor` now has a reference count from the registry, so you either need to remove handle from the registry after you're done or (better) explicitly shut down the actor in question.

**Comment by alatdneg** [comment]
Ah thank you I wondered if that might be the reason, cheers.
