### ISSUE TITLE
Re-implement streams on top of the new flow API

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1347]
Flows currently only work locally and can transfer data through asynchronous buffers. The new streams should complement the async buffers with a way that also works in a distributed environment.

**Comment by dominiklohmann** [comment]
Nice to see this completed. Is there documentation for this already available?

**Comment by Neverlord** [comment]
Yeah, I've finally got around implementing the `buffer` operator. With that, implementing the new streaming was straightforward.

Documentation is not yet available. I'll focus on the remaining tickets and implementation work for 0.19 in order to have RC 1 go out by the end of the month. Once that's dealt with, I'll try to add more examples and documentation plus maybe squeeze in some benchmarking.

However, feedback is most welcome if you want to start playing around with it. The unit tests should be a good-enough starting point.

- dynamically typed: https://github.com/actor-framework/actor-framework/blob/4e9faecb4009ab812ec4985cacc9c6ddc217e600/libcaf_core/test/stream.cpp#L85
- statically typed: https://github.com/actor-framework/actor-framework/blob/4e9faecb4009ab812ec4985cacc9c6ddc217e600/libcaf_core/test/typed_stream.cpp#L82

**Comment by dominiklohmann** [comment]
That's great, thanks for pointing me to this. I'll make sure to give this a spin locally to see if it covers our needs.
