### ISSUE TITLE
Handler in Request Can Not Write Value 

### ISSUE THREAD

**Issue by zhihuiLiang** [actor-framework/actor-framework#1353]
I call the request function like this
```c++
    int response = 0;
    self->request(x, seconds(1), get_atom_v).then([&](int res) {
        response = res;  //res = 100
        std::cout << "receive response, response:" <<  response << std::endl;
    });
   std::cout << "response val: " << response << std::endl;
```
But it prints
```C++
receive response, response:100
response val: 0
```
I want to know why this happened

**Comment by Neverlord** [comment]
`request().then()` is asynchronous. Your code invokes UB, since the lambda captures a variable on the stack by reference. CAF invokes this handler at some point in the future, so the variable on the stack is long gone at that point.

**Comment by zhihuiLiang** [comment]
Thank you for your answer. I understood what I did wrong. Could you please tell me how I can write the results returned by other actors to the value of the current actor？
