### ISSUE TITLE
Middleman UDP backend

### ISSUE THREAD

**Issue by Hamdor** [actor-framework/actor-framework#1356]
Is the UDP backend of the middleman still present (https://actor-framework.readthedocs.io/en/latest/NetworkTransparency.html#transport-protocols-experimental)?
A grep for `middleman_enable_udp` only yield the documentation. Further it seems that `remote_actor_udp` is not present.

**Comment by Neverlord** [comment]
I think this has never been properly implemented to begin with. Maybe @josephnoir remember some details. 🙂

**Comment by josephnoir** [comment]
iirc, there was UDP for a while. The middleman even established order and might have sent retransmits for reliability.

But during one iteration of the middleman (or BASP?) it was removed to reduce the maintenance overhead. There were a few code paths that differed between UDP and TCP, including the BASP connection establishment.
