### ISSUE TITLE
All inheritance graphs and collaboration graphs in doxygen documentation are broken links

### ISSUE THREAD

**Issue by brunorijsman** [actor-framework/actor-framework#1360]
The CAF homepage (https://www.actor-framework.org/) links to the CAF doxygen documentation page (https://codedocs.xyz/actor-framework/actor-framework/).

On the doxygen documentation page, it appears that all inheritance graphs and collaboration graphs are broken links.

See for example:
- https://codedocs.xyz/actor-framework/actor-framework/classcaf_1_1actor.html
- https://codedocs.xyz/actor-framework/actor-framework/classcaf_1_1callback.html

**Comment by Neverlord** [comment]
Thanks for reporting! I'll take a look.

**Comment by Neverlord** [comment]
Looks like codedocs is running a very old Doxygen version and doesn't come with the CLI tool `dot`. So it's probably the choice between disabling inheritance graphs or look for an alternative like hosting Doxygen via GitHub pages (and generating the docs via GitHub actions).

**Comment by Neverlord** [comment]
After looking around, I think the easiest way for us going forward is just pushing Doxygen to our website. We don't need to build the documentation on each commit. We can just extend our release script to build and push the latest version after cutting a release. Also allows us to have older versions online like we have on RTD.

Our doxygen now lives under https://www.actor-framework.org/doxygen/. After browsing a bit through it, it seems like it could also use some love. Contributions welcome. 🙂

At least the images are back, so we can close this via the PR.
