### ISSUE TITLE
Surprising "broken promise" in some edge cases

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1361]
This was reported in chat by @dominiklohmann (thanks for starting the discussion! 👋).

While migrating to 0.18, they've run into some cases where a response promise would "break". Here's a test that illustrates the behavior:

```c++
struct bar_state {
  static constexpr const char* name = "bar";
  typed_response_promise<int> rp = {};
};

CAF_TEST(broken_promise_repro) {
  using namespace std::literals;
  actor_system_config cfg;
  put(cfg.content, "caf.logger.file.verbosity", "trace");
  actor_system sys{cfg};
  auto baz_fun = [](event_based_actor* self) -> behavior {
    self->set_exit_handler([=](const exit_msg& msg) {
      CAF_MESSAGE("6': " << msg.reason);
      self->quit(msg.reason);
    });
    return {
      [](int) {},
    };
  };
  auto bar_fun = [](stateful_actor<bar_state>* self) -> behavior {
    self->set_down_handler([=](const down_msg& msg) {
      CAF_MESSAGE("6: " << msg.reason);
      self->state.rp.deliver(42);
    });
    return {
      [=](actor baz) -> typed_response_promise<int> {
        CAF_MESSAGE("5");
        self->monitor(baz);
        self->state.rp = self->make_response_promise<int>();
        return self->state.rp;
      },
    };
  };
  using foo_actor = typed_actor<result<int>(open_atom), result<void>(actor)>;
  auto foo_fun = [=](foo_actor::pointer self,
                     actor baz) -> foo_actor::behavior_type {
    return {
      [=](open_atom) -> typed_response_promise<int> {
        CAF_MESSAGE("2");
        auto request_temporary_bar = [=](actor baz) {
          CAF_MESSAGE("3");
          auto bar = self->spawn(bar_fun);
          return self->request(bar, infinite, baz);
        };
        self->delayed_send(self, 3s, baz);
        auto rp = self->make_response_promise<int>();
        request_temporary_bar(baz).then(
          [rp](int x) mutable {
            CAF_MESSAGE("7: " << x);
            rp.deliver(x);
          },
          [rp](const error& err) mutable { rp.deliver(err); });
        return rp;
      },
      [=](actor baz) {
        CAF_MESSAGE("4");
        self->send_exit(baz, exit_reason::normal);
      },
    };
  };
  CAF_MESSAGE("1");
  auto baz_hdl = sys.spawn(baz_fun);
  auto f = make_function_view(sys.spawn(foo_fun, std::move(baz_hdl)));
  CAF_CHECK_EQUAL(f(open_atom_v), 42);
  CAF_MESSAGE("8");
}
```

Instead of waiting for the `down_msg` and then delivering the promise, the actor gets cleaned up by CAF as unreachable (and the promise consequently emits a `broken_promise`).

This is kinda "by design", since response promises only hold onto a weak reference to their parent actor. The original intention for this design was to prevent some edge cases (like storing a response promise directly in the actor object itself) from causing subtle memory leaks.

However, after seeing the example and thinking about it for a couple days, I think we should avoid the surprising behavior instead of avoiding memory leaks that result from bad CAF usage (we have implemented `stateful_actor` for a reason).

We should keep a close eye on the promises, though. During testing with a strong reference, I couldn't find any leaks in our tests and I can't think of a "legitimate" use of the promises that would result in a leak with the new implementation.

**Comment by dominiklohmann** [comment]
Thanks a bunch for fixing this for us. At least with how we use CAF and manage lifetimes I wasn't able to think of a case where this would cause a problem either, so the change is probably for the better.
