### ISSUE TITLE
Scheduled and delayed send could return a disposable

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1362]
Currently, there's no way to cancel a `delayed` or `scheduled` message. However, both internally use the actor clock, which already supports that. So it should be straightforward to re-implement these function on top of `actor_clock::schedule` and then simply return the `disposable` from that call.

**Comment by dominiklohmann** [comment]
Alternative idea: deprecate `delayed_send` and `scheduled_send` in favor of these:

```c++
// old
self->delayed_send(self, delay, ...);
self->scheduled_send(self, delay, ...);

// new
auto disp1 = self->delayed_run(delay, [self] { self->send(...); });
auto disp2 = self->scheduled_run(delay, [self] { self->send(...); });
```

This avoids the API bloat and makes it so you don't have to maintain separate ways of running something later on the actor clock.

**Comment by Neverlord** [comment]
Yes, it would reduce the API surface. However, it's semantically and performance-wise not the same.

With `delayed_send`, we cross two async boundaries:
- push from `self` to the actor clock
- send from the actor clock to the receiver

With `run_delayed -> send`, we have three:
- push from `self` to the actor clock
- send from the actor clock to the sender (the action with the actual `send`)
- send from `self` to the receiver

Further, `delayed_send` will deliver the message even if the original sender no longer exists. With `delayed_run` into `send`, the actor must stay alive for the message to happen. So I think `delayed_send` still has its place for now.

**Comment by dominiklohmann** [comment]
Does this mean that `self->delayed_send(...); self->quit()` will always send the message immediately, but then wait at the receiving end?

I must say that I find this to be a very surprising behavior, and that my assumption would've been that it behaves similar to `self->run_delayed_weak(delay, [self] { self->send(...) });`.

If my understanding is correct, then it'd be very hard to make delayed sends return a disposable, because you can't easily remove the message from the receiver again.

**Comment by Neverlord** [comment]
> Does this mean that `self->delayed_send(...); self->quit()` will always send the message immediately, but then wait at the receiving end?

Calling `delayed_send` pushes the message to the actor clock. There, it'll wait until timing out and then the actor clock is passing it to the mailbox receiver. While it's waiting at the clock, you can still dispose it.
