### ISSUE TITLE
Get Message_id  when using send

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1363]
Hi!

I'm using the QtWidget mixin, and so I only have access to sender type messages (send,anon_send etc), and I need some way of associating the response with the message I sent.

Correct me if I'm wrong but the response I receive, has the original message_id in it  (but not always) which is created by the send command, but as far as I can tell there is no way to capture this value.

Is there any method of doing this ?

I can't use the system() scoped_actor as this will bock the UI thread waiting for the response. 

cheers!

**Comment by alatdneg** [comment]
Ah the id that send creates is always 0, only Request creates unique values, so it can be matched to the then/await etc.

**Comment by Neverlord** [comment]
Right, the message ID won't help here. It's been a while since implementing the companion, so I don't know what's the reasoning behind not enabling `request` or if it's just been an oversight. You could try enabling `request` and see whether it'll work for the companions:

```diff
diff --git a/libcaf_core/caf/actor_companion.hpp b/libcaf_core/caf/actor_companion.hpp
index 487b73e59..3eeeb9eac 100644
--- a/libcaf_core/caf/actor_companion.hpp
+++ b/libcaf_core/caf/actor_companion.hpp
@@ -33,6 +33,7 @@ class CAF_CORE_EXPORT actor_companion
   // clang-format off
   : public extend<scheduled_actor, actor_companion>::
            with<mixin::sender,
+                mixin::requester,
                 mixin::subscriber,
                 mixin::behavior_changer> {
   // clang-format on
```

**Comment by alatdneg** [comment]
Hmm I'll have a go, not sure how that'll interact with actor_widget code though. It might be simpler to just find another method of working around my issue. But I'll certainly bear it in mind if I get stuck later.

cheers
