### ISSUE TITLE
Test net.udp_datagram_socket unstable on FreeBSD

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1397]
I've seen this test fail a couple of times. I didn't dig into whether that's a FreeBSD-specific issue, but so far I haven't seen this test fail anywhere else.

**Comment by Neverlord** [comment]
Haven't seen this test fail since then.

**Comment by riemass** [comment]
I'm not happy to pull this up, but while hunting my own failing tests in FreeBSD I noticed that `net.udp_datagram_socket` still fails on FreeBSD. It just so happens that we disabled the test in cirrus with commit 5f79a25.
