### ISSUE TITLE
Compile error for GNU 13.1.1

### ISSUE THREAD

**Issue by vollate** [actor-framework/actor-framework#1407]
The [new update of GNU compiler](https://gcc.gnu.org/gcc-13/porting_to.html) says the header `<cstdio>` need to be included explicitly for std::int8_t, std::int32_t etc. This error happened in file "libcaf_core//src/detail/ripemd_160.hpp" and ".../ripemd_160.cpp", and may be other files have same problem. The compile error is descripted at [this issue](https://github.com/microsoft/vcpkg/issues/31347) in vcpkg.

**Comment by Neverlord** [comment]
> I modified it wit 0.19.1's source files and it fixed.

👍

> is there any plan to update the package in vcpkg?

I don't know. 🙂

We don't maintain packages. They've been created by community members. I also have no idea how vcpkg works. Maybe you can just send them a PR to update the recipe?

**Comment by vollate** [comment]
I'll take a try. 🙂
