### ISSUE TITLE
Example "chat-server" have a 10093 runtime exception on windows

### ISSUE THREAD

**Issue by hoskylucky** [actor-framework/actor-framework#1409]
I build the projects on Win11 by native complier, and run example chat-server, I got a runtime exception, calling socket() at make_stream_socket_pair(), get a 10093([WSANOTINITIALISED]) error.

Please tell me where and when call WSAStartup(), thanks.

**Comment by Neverlord** [comment]
Thanks for reporting. Just loading the `caf::net` module via `CAF_MAIN` should take care of that. I'll take a look.

**Comment by Neverlord** [comment]
Seems like CI didn't complain about this because we aren't running the new Robot tests on Windows. They run the example binaries, so they should have detected this.
