### ISSUE TITLE
Provide abstraction for pool/set of actors 

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#141]
I scenario I face quite common is to maintain a group of actors. At first I always consider using the actual group class, but then quickly decide against it in favor of a `std::vector<actor>`. The reason is that I *(i)* want to manage group membership myself, as opposed the actor its memberships, and *(ii)* want to iterate over the members (or just determine the number of members) to drive a decision in the managing actor. 

Since an STL container of `actor` handles does not transparently act as an actor itself, there are many annoying explicit loops. Moreover, with an explicit container it is now necessary to monitor every actor and remove it from the container when it terminates. This is a lot of boilerplate which a libcppa primitive could nicely abstract away.

Thus, I suggest to introduce an actor "bag" abstraction: call it `pool` because it has thread pool semantics, or `client_set` to allude to the semantics of managing a group of actors.

**Comment by Neverlord** [comment]
Closed via f42f143eca801fdf3a198a66a31f9f0d06fb97fc.
