### ISSUE TITLE
crypto-policy-non-compliance-openssl /usr/lib64/libcaf_openssl.so.0.19.1 SSL_CTX_set_cipher_list, packaging for Fedora

### ISSUE THREAD

**Issue by topazus** [actor-framework/actor-framework#1410]
I tried to make RPM package of the library on Fedora, rpmlint tool reported built RPM package with `actor-framework.x86_64: W: crypto-policy-non-compliance-openssl /usr/lib64/libcaf_openssl.so.0.19.1 SSL_CTX_set_cipher_list` which needs to be properly fixed.

ref: https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2196274-actor-framework/fedora-rawhide-x86_64/05905027-actor-framework/fedora-review/review.txt
https://bugzilla.redhat.com/show_bug.cgi?id=2196274#c5
https://docs.fedoraproject.org/en-US/packaging-guidelines/CryptoPolicies/#_cc_applications

**Comment by Neverlord** [comment]
@topazus FYI, 0.19.2 has just been released with the fix.
