### ISSUE TITLE
Failing to deserialize a request should trigger an error at the sender

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1428]
Currently, when a type sent as part of a request to a remote actor fails to deserialize, the sender of the request receives no error. In fact, if the timeout for the request is set to infinite, the sender may never receive a reply at all.

To reproduce the issue, create a type like this that can be serialized but not deserialized:

```c++
struct foo {
  template <class Inspector>
  friend auto inspect(Inspector&, foo&) -> bool {
    return not Inspector::is_loading;
  }
};
```

Then use it in a request to an actor in another actor system than the sending actor (so the message must go through serialization and deserialization):

```c++
self->request(remote_dest, infinite, foo{}).then(
  []() {
    // This (expectedly) never gets called…
  },
  [](const error& err) {
    // …and (unexpectedly) neither does this.
  });
```

We're still using CAF 0.18.x, so please ignore if the issue is fixed for CAF 0.19.x.

If need be, I can also provide a unit test for this, and would appreciate some pointers to writing a test that involves two actor systems, whether that be in one process or two.

**Comment by Neverlord** [comment]
Yep, sounds reasonable.

**Comment by riemass** [comment]
Should be fixed after the PR is merged.
@Neverlord I was in doubt weather to return `sec::malformed_message` or `sec::load_callback_failed`?
