### ISSUE TITLE
Support config via environment variable

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1440]
Our current model for configurations is:

CLI Arguments > Config File > Hard-coded Defaults

However, another common way to configure applications is via environment variables. They usually sit between the config file and the CLI arguments:

CLI Arguments > Environment Variables > Config File > Hard-coded Defaults

Because they sit between CLI and the contents of the config file, user cannot easily implement this on their end.

**Comment by dominiklohmann** [comment]
We've implemented something similar in a CAF-based application, but it took a lot of effort to get the precedence as you described.

If you're doing this, what are your plans for translating environment variables to options? Is it an automatic mapping (e.g., `CAF_FOO_BAR__BAZ` mapping to `caf.foo-bar.baz`), or is the mapping explicitly specified by the user when adding an option?

**Comment by Neverlord** [comment]
> If you're doing this, what are your plans for translating environment variables to options? Is it an automatic mapping (e.g., `CAF_FOO_BAR__BAZ` mapping to `caf.foo-bar.baz`), or is the mapping explicitly specified by the user when adding an option?

Good question. Probably an auto-generated default with an option to override would make sense. Haven't thought about it too deeply yet. This came up in a different context recently and I've just wanted to add the ticket to not forget about it.
