### ISSUE TITLE
Requests to remote actors can remain unanswered if the remote actor quits

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1466]
This is similar in nature to #1428: I ran into a situation where I send a request to a remote actor, and if that quits in the meantime I never get a reply (assuming an infinite timeout).

```c++
// Assume that `remote_dest` quits before receiving this message.
self->request(remote_dest, infinite, …).then(
  [](…) {
    // This (expectedly) never gets called…
  },
  [](const error& err) {
    // …and (unexpectedly) neither does this.
  });
```

I would expect to receive a `caf::sec::request_receiver_down` error.

Note that when I monitor `remote_dest` I do get a down message, so at least that part is working as expected.

**Comment by Neverlord** [comment]
> I would expect to receive a `caf::sec::request_receiver_down` error.

Me too. Sounds like a straight up bug to me.

**Comment by dominiklohmann** [comment]
I cannot reproduce this since the fix to let awaited messages not block system messages. Closing for now; if this ever comes up again in the future I'll re-open this, but for now it's probably not worth spending time on.
