### ISSUE TITLE
Monitoring of remote actors monitors the middleman rather than the remote actor

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1472]
Monitoring a remote actor handle causes the down message to arrive only once the remote actor's actor system is no longer connected rather than when the remote actor dies.

This is very unexpected. I would expect that monitoring works equally for all actor handles, regardless of whether they're proxied in the middleman or not.

This effectively means that I cannot use monitoring unless I am absolutely certain that an actor lives in the same process, i.e., `self->spawn<caf::monitored>(...)` is always fine, but `self->monitor(handle)` may not always be.

**Comment by Neverlord** [comment]
How did you run into this? If the local system creates a proxy for a remote actor, this proxy observes the lifetime of the "original" and should exit when the remote actor does.

**Comment by dominiklohmann** [comment]
It's a rather complex setup, but effectively I have the following chain of actors:

Local managing actor M spawns actors L1, R1, L2, where L means local and R means remote.

M creates a vector of actor handles [L1, R1, L2] that represent a sequence of work that needs to be done in certain processes, removes the last handle from the list, and passes it to L2.

L2 monitors the actor handle at the end of this list it received (R1), removes the last handle, and passes the remaining list to L1. This one is empty, so we're done with the wiring process.

Every actor in this list is designed to gracefully stop after the monitored previous actor exited before quitting. When an actor is done early, it sends an exit message to the previous actor.

I am consistently observing that R1 being done early successfully sends an exit message to L1, but I am not receiving a down message in L2 until the local actor system shuts down.

This shutdown system does (1) not rely on refcounts (which are always problematic for remote actors), and (2) works as expected as long as there is at most one process boundary.

I'm happy to walk you through the code if you would like to take a look. It's really hard to create minimal examples for bugs that only occur with more than one actor system in play.

**Comment by Neverlord** [comment]
So these steps should reproduce this issue?

- L1 monitors R1
- L1 (eventually) tells L2 that it should monitor R1 as well
- R1 finishes before L2 starts monitoring it (?)
- L1 receives the `down_msg`, but L2 does not

**Comment by Neverlord** [comment]
@riemass could you please try to reproduce this with a (regression) test? 🙂

The test setup you've used for #1506 should work here as well.

**Comment by dominiklohmann** [comment]
I cannot reproduce this since #1592 landed. Not exactly sure why, but it's probably not worth pursuing further.
