### ISSUE TITLE
typed_response_promise::deliver incorrectly constructs the type

### ISSUE THREAD

**Issue by allspark** [actor-framework/actor-framework#1545]
Hi,

in 
https://github.com/actor-framework/actor-framework/blob/5bc61ca246c5542bd961ab2ba9e1132ceb907fd0/libcaf_core/caf/typed_response_promise.hpp#L78

i think it should be
```
template <class... Us>
  std::enable_if_t<(std::is_constructible<Ts, Us...>::value)>
  deliver(Us&&... xs) {
    promise_.deliver(Ts{std::forward<Us>(xs)...});
  }
```

**Comment by Neverlord** [comment]
Thank you for reporting! We'll look into it.

**Comment by allspark** [comment]
Hi,
ah I think it's correct, I didn't understood that the promise can have multiple types. but that means I can only construct each type with only one parameter.

Would be nice to have something like:
`promise.deliver(std::forward_as_tuple(1,2), std::forward_as_tuple(3,4))` where `1, 2` are forwarded to the first type, and `3, 4` to the second type

**Comment by Neverlord** [comment]
> Hi, ah I think it's correct, I didn't understood that the promise can have multiple types. but that means I can only construct each type with only one parameter.
> 
> Would be nice to have something like: `promise.deliver(std::forward_as_tuple(1,2), std::forward_as_tuple(3,4))` where `1, 2` are forwarded to the first type, and `3, 4` to the second type

What would be the benefit of doing it this way instead of just `promise.deliver(type1{1,2}, type2{3,4})`? "Auto-unboxing" tuples like this severely backfires if a type actually has a constructor accepting tuples.

Are you writing generic code that doesn't know the individual types? In this case, I'd rather add a utility for retrieving types by index. Something like `promise.deliver(type_at<0, promise_t>{1,2}, type_at<1, promise_t>{3,4})`.

**Comment by allspark** [comment]
I thought that this deliver function works like [`std::map::emplace`](https://en.cppreference.com/w/cpp/container/map/emplace). so that i don't have to explicitly specify the types of the promise

**Comment by Neverlord** [comment]
Since the promise is basically a tuple, I don't see a good way to construct individual values from multiple arguments without repeating the type. Closing, but feel free to post/reopen if you have some API ideas. 🙂
