### ISSUE TITLE
Incorrect encoding of chunk-size in caf::net::http::server::send_chunk

### ISSUE THREAD

**Issue by allspark** [actor-framework/actor-framework#1587]
According to www.rfc-editor.org/rfc/rfc9112#name-chunked-transfer-coding the chunk-size is a number in hex-format.

In `caf::net::http::server::send_end_of_chunks` the end-chunk-size is correctly encoded as `0` and not as `0000000000000000`  (8 Bytes for `std::size_t`)

example from (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chunked_encoding)
```
7\r\n
Mozilla\r\n
```

and output from `send_chunk`
```
0700000000000000\r\n
Mozilla\r\n
```

**Comment by Neverlord** [comment]
@riemass can you take a look? Just glimpsing at the code, I think this line looks suspicious:

https://github.com/actor-framework/actor-framework/blob/master/libcaf_net/caf/net/http/server.cpp#L69

`append_hex` will treat the 8 bytes basically as a byte-string. Hence the funny looking output. Should probably just use `detail::format` with `{:x}` or something like this.

Also, looks like there's no test for it yet.

**Comment by riemass** [comment]
Sure, leave it to me.
