### ISSUE TITLE
Custom logger for the deterministic fixture

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1593]
The deterministic fixture should implement its own logger that prints each log message by calling the appropriate print function on the `reporter`. This logger should then be automatically configured when using the `deterministic` fixture so that log output is automatically included in the test output.

**Comment by shariarriday** [comment]
@Neverlord I think that we can close this issue as the PR has been merged into master.

**Comment by Neverlord** [comment]
Got it. If you open a PR that closes a ticket, please refer to the ticket with `Closes #...` instead of just `Relates #...` to close the ticket automatically.
