### ISSUE TITLE
Remove signatures from typed actor handles

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#1600]
Since 1.0 is coming up, I think it makes sense to revisit the idea of making a breaking change to remove signatures from typed actor handles.

From my experience working with CAF in a code base where we require every actor to be strongly typed, it is a major pain especially for newer developers to our code base to read compiler errors. I propose to add an indirection for this reason.

```cpp
// old
using calculator_handle = caf::typed_actor<
  auto (add_atom, int lhs, int rhs) -> caf::result<int>,
  auto (subtract_atom, int lhs, int rhs) -> caf::result<int>
>;

struct calculator_state {
  static constexpr auto name = "calculator";
};

auto calculator(calculator_handle::stateful_pointer<calculator_state> self)
    -> calculator_handle::behavior_type {
  // …
}
```

```cpp
// new
using calculator_handle = caf::typed_actor<"calculator">;

template <>
struct caf::typed_actor_traits<"calculator"> {
  using behavior_type = caf::typed_behavior<
    auto (add_atom, int lhs, int rhs) -> caf::result<int>,
    auto (subtract_atom, int lhs, int rhs) -> caf::result<int>
  >;
}

struct calculator_state {
};

auto calculator(calculator_handle::stateful_pointer<calculator_state> self)
    -> calculator_handle::behavior_type {
  // …
}
```

The advantage of this change is that error messages will reference `caf::typed_actor<"calculator">` rather than `caf::typed_actor<auto (add_atom, int, int) -> caf::result<int>, auto (subtract_atom, int, int)->caf::result<int>>` when referencing the actor handle in a compiler error. Especially with longer signatures this will be a huge improvement for the developer experience.

**Comment by Neverlord** [comment]
> `caf::typed_actor<"calculator">`

Was there a recent C++ feature that allows using string literals in templates now?

I'm not so sure about the trait interface, though. What about this?

```c++
// new (2)
struct calculator_tag {
  using signatures = caf::type_list<
    auto (add_atom, int lhs, int rhs) -> caf::result<int>,
    auto (subtract_atom, int lhs, int rhs) -> caf::result<int>
  >;
}

using calculator_handle = caf::typed_actor<calculator_tag>;

struct calculator_state {
  // ...
};

auto calculator(calculator_handle::stateful_pointer<calculator_state> self)
    -> calculator_handle::behavior_type {
  // …
}
```

That might even be doable without introducing a breaking change.

Downsides:

- would need to fall back to signatures in the handle type when using `typed_actor::extend`, so we'll probably have to deprecate that
- not sure how well this is going to work with `typed_actor_view` (should be possible to use a view into a "sub-type")

**Comment by dominiklohmann** [comment]
> Was there a recent C++ feature that allows using string literals in templates now?

There's a neat hack that allows you to do that:

```cpp
/// A string literal wrapper for NTTPs, making it possible to use string
/// literals as template arguments, which would not normally be possible.
template <size_t N>
  requires(N >= 1)
struct string_literal {
  constexpr explicit(false)
    string_literal(const char (&str)[N]) noexcept { // NOLINT
    std::copy_n(str, N, value);
  }

  char value[N] = {}; // NOLINT

  [[nodiscard]] constexpr auto str() const noexcept -> std::string_view {
    return {&value[0], &value[N - 1]};
  }
};
```

> would need to fall back to signatures in the handle type when using `typed_actor::extend`, so we'll probably have to deprecate that

From our experience having something like `extend` is quite important. But you could also do this on the `caf::type_list` level:

```
using foo_signatures = caf::type_list::extend<bar_signatures,
  auto (get_atom) -> caf::result<int>,
  auto (put_atom, int) -> caf::result<void>,
  ...
>;
```

> I'm not so sure about the trait interface, though. What about this?

As long as it achieves the same purpose of reducing the length of my error messages from 1 MB down to 1 kB I'd be happy to have it.

**Comment by dominiklohmann** [comment]
> Neat indeed, but requires C++20. 🙂

It should just require C++17 if you replace the `requires(N >= 1)`; technically that's not even needed, it just makes the error message a bit prettier when you initialize the template argument with `{}` instead of `""`, which would be an error.

**Comment by Neverlord** [comment]
Doesn't compile for me unless I set the standard to C++20: https://godbolt.org/z/8WbjTerz4

**Comment by dominiklohmann** [comment]
Ah damn, I forgot that CTAD wasn't allowed for NTTPs before C++20. Then it's probably not an option, unless you want to bump the compiler requirements.

**Comment by Neverlord** [comment]
@riemass anything left to do?
