### ISSUE TITLE
Unstable test suite: dynamic_spawn

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1667]
The `dynamic_spawn` test suite from the legacy tests fails sporadically in Jenkins. Didn't dig into it yet, but the first question is whether it's an actual bug or just an issue with test itself.

**Comment by riemass** [comment]
I've reproduced this issue in `docker` locally, using the same debug build flags as we do in our pipeline. Interestingly, I couldn't reproduce the issue when using default build flags. 
Here are the (filtered) interesting lines:
```
- spawn_event_testee2_test
  -> remaining: 5 [line 77]
  -> remaining: 4 [line 77]
/actor-framework/libcaf_core/caf/actor_clock.cpp:52: requirement failed 'worker_ != nullptr'
/actor-framework/build/libcaf_core/libcaf_core.so.0.19.4(_ZN3caf6detail23thread_safe_actor_clock3runEPNS0_16sync_ring_bufferISt10unique_ptrINS1_14schedule_entryESt14default_deleteIS4_EELm64EEE+0x4e2)[0x7f344e09f164]
Aborted (core dumped)
```

**Comment by riemass** [comment]
It seems that this behavior was introduced after merging #1658. 
The mentioned PR touches the actor clock, and I've reverted to the parent commit of this PR and the core dump is no longer present.
