### ISSUE TITLE
Improve type-safety

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#172]
This code should not compile (but it currently does):

```cpp
using testee_a = typed_actor<replies_to<int, int>::with<int>>;
using testee_b = typed_actor<replies_to<float>::with<float>>;
testee_b::behavior_type testee_b_impl(testee_b::pointer self, testee_a buddy) {
  // oops, will send us an int ...
  self->send(buddy, 1, 2);
  return {
    [](float f) {
      return f;
    }
  };
}
```

**Comment by ufownl** [comment]
Does these code blow should compile? (They all currently do.)
```C++
using testee_a = typed_actor<replies_to<int, int>::with<int>>;
void testee_b_impl(event_based_actor* self, testee_a buddy) {
  self->sync_send(buddy, 1, 2).then([] {});
}
```
```C++
using testee_a = typed_actor<replies_to<int, int>::with<void>>;
void testee_b_impl(event_based_actor* self, testee_a buddy) {
  self->sync_send(buddy, 1, 2).then([] {});
}
```

**Comment by Neverlord** [comment]
The second example: yes. The runtime will generate empty messages to allow you to wait for completion of a task. Your test case revealed a bug nonetheless: the runtime sends `unit` instead. That was originally intended to indicate sync failures, but it blocks this legitimate use case for typed actors.

The first case is a bug. Thank you for providing the test cases.

**Comment by Neverlord** [comment]
Hm, turned out to be remnants of old `libcppa` code that once made sense. The first example now doesn't compile and the second example works as expected.

**Comment by ufownl** [comment]
Thanks for explaining, it help me understand the design about this more clearly. :)
