### ISSUE TITLE
Allow for constructing nested messages from other messages

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#173]
It would be nice to have the ability to next messages. Here is a fictitious example:

```cpp
message_handler h =
  [=](expensive const& e) {
     send(sink, make_message(unwrap(last_dequeued()), 42));
  };
```

The scenario is that a data structure with an expensive copy constructor exists already as a message (and thus internally as a reference-counted object). Then I'd like to be able to still reuse it in differently typed messages. It appears to be already possible to nest messages and extract them via `apply`, but as a user, I don't want to work with this extra level of type-erased indirection. Rather, I'd like to directly reuse the value. In the above example, the send statement with the fictitious `unwrap` would create a message of type `<expensive, int>` as opposed to `<message, int>`. I'm not saying that an `unwrap` function is the right primitive, but I hope it illustrates the point.

**Comment by Neverlord** [comment]
What about something like `message::concat`?

Here's an example snippet:

```cpp
auto msg1 = make_message(1, 2, 3);
auto msg2 = make_message(4, 5, 6);
auto msg3 = message::concat(msg1.drop(1), msg2.take(2));
assert(msg3 == make_message(2, 3, 4, 5));
```

**Comment by mavam** [comment]
Looks good to me. That's the final piece missing to make it possible slicing message values arbitrarily without copying.
