### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [actor-framework/actor-framework#182]
Some parameters (like "[${DOXYGEN_EXECUTABLE}](https://github.com/actor-framework/actor-framework/blob/8de46283fd3037a92b797b2572aea3de6bed77a3/CMakeLists.txt#L194)" and "[${CMAKE_CURRENT_SOURCE_DIR}](https://github.com/actor-framework/actor-framework/blob/e1643bbb13309e5db95fc0c12d49feaf7e4b6c61/libcaf_core/CMakeLists.txt#L4)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by Neverlord** [comment]
I'll close this since there wasn't any activity on this recently.
