### ISSUE TITLE
Build errors with clang using c++23

### ISSUE THREAD

**Issue by riemass** [actor-framework/actor-framework#1919]
While working on `std::format` support, I've noticed that we fail to build CAF using `clang` in c++23 mode. 
Here is the shortened error summary:
```
include/c++/14.1.1/tuple:956:36: error: no matching function for call to 'get'
  956 |             return __convertible<decltype(std::get<_Is>(std::declval<_UTuple>()))...>();
      |                                          ^~~~~~~~~~~~~
actor-framework/libcaf_core/caf/actor_system.cpp:136:25: note: in instantiation of member function 'std::unordered_map<std::basic_string<char>, std::pair<caf::message, std::unordered_set<caf::intrusive_ptr<caf::actor_control_block>>>>::operator[]' requested here
  136 |       self->state().data[key].second.erase(ptr);
      |                         ^
```

Interestingly, `GNU g++` using c++23 compiles fine, just as `clang` using c++20. Clang version is 17.0.6 running on Linux.

**Comment by uglyreptile** [comment]
Sad. Tried to compile it with `clang++-19 -std=c++23 -stdlib=libc++` The same problem.

**Comment by riemass** [comment]
Solved one minor error in the mentioned PR. 
The `std::get` error is somewhat weird, only appears on clang v17.0.6 version for me, clang v18 and v19 don't complain, and I'm really staring to blame the compiler here. I'll have experiment some more.

**Comment by riemass** [comment]
With the flags `-DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -lc++abi"`, the code compiles successfully even with Clang 17.

The issue appears to be with `libstdc++`'s implementation of `std::get` not working correctly with Clang 17 in C++23 mode. The error occurs in multiple places where `get` is used with indexes or index sequences. @Neverlord Since this seems to be an issue with the library/compiler pair, rather than our code, I suggest we close this with the previous PR.

**Comment by Neverlord** [comment]
Agree, if it's just a single Clang version that's broken I'd say it's not worth troubleshooting. Especially since Clang 17 only has "initial" support for C++23 anyways.
