### ISSUE TITLE
How to encapsulate a calculator to only provide a C function interface？

### ISSUE THREAD

**Issue by MiQter** [actor-framework/actor-framework#1928]
How to encapsulate the example calculator into a dynamic library that only provides a C function interface, call the C function to input a value and return the result?

**Comment by MiQter** [comment]
Because I am currently writing an astrodynamics simulation library with CAF, I need to encapsulate it into a dynamic link library and provide an external C function interface to facilitate integration and calling by others.

**Comment by Neverlord** [comment]
You can spin up everything you need and then use a `scoped_actor`.

```c++
scoped_actor self{sys};
auto res = self->request(worker, ...).receive<my_result>();
if (res) {
  // ... success, use *res ...
} else {
  // ... error handling ...
}
```

This will block the function until the response arrives (or an error occurs), so then you can convert your result to whatever the interface you're implementing is supposed to return.

**Comment by MiQter** [comment]
Thank you so much for your detailed and helpful response, @Neverlord ! Your explanation was clear and really helped me understand the issue. I appreciate the time and effort you put into answering my question. Keep up the great work on this project! 😊
