### ISSUE TITLE
CMake not finding OpenSSL

### ISSUE THREAD

**Issue by u32744** [actor-framework/actor-framework#1944]
cmake -S ../ -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.29.30153.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "3.3.1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindOpenSSL.cmake:657 (find_package_handle_standard_args)
  CMakeLists.txt:122 (find_package)

**Comment by Neverlord** [comment]
As the CMake error states, you'll have to install OpenSSL. There are installers available for Windows or you can use a package manager like Chocolatey. If you don't need the full feature set of CAF, you can also disable the modules `net` and `openssl` by setting `CAF_ENABLE_NET_MODULE` and `CAF_ENABLE_OPENSSL_MODULE` to `OFF`.

**Comment by u32744** [comment]
cmake -S ../ -B build CAF_ENABLE_NET_MODULE=OFF CAF_ENABLE_OPENSSL_MODULE=OFF
CMake Warning:
  Ignoring extra path from command line:

   "CAF_ENABLE_OPENSSL_MODULE=OFF"

**Comment by u32744** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2512	“caf::expected<std::string>”: 没有合适的默认构造函数可用	caf-core-test	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\future	196
