### ISSUE TITLE
There is a broken link bug on the website https://www.interance.io/learning.

### ISSUE THREAD

**Issue by MiQter** [actor-framework/actor-framework#1945]
At https://www.interance.io/learning, choose to view article "Distributed Actors", but go to article "Monitoring and Linking".

**Comment by Neverlord** [comment]
Fixed. Thank you for reporting it!

**Comment by MiQter** [comment]
> Fixed. Thank you for reporting it!

@Neverlord 

You haven't completely solved this problem. The current issue is that when you click on the word 'Actor' in the title 'Distributed Actor', you will be redirected to the wrong article. When you click on the word 'Distributed' in the title 'Distributed Actor', you will be redirected to the correct article.

**Comment by Neverlord** [comment]
@MiQter thanks again! I hope we got it right this time, sorry for the inconvenience! 🤦‍♂️
