### ISSUE TITLE
CAF printtlp.cpp cann't run

### ISSUE THREAD

**Issue by qingshi666666** [actor-framework/actor-framework#1948]
I build the file by:
g++ -std=c++17 println.cpp -lcaf_core -lcaf_io -ohello_world -L /usr/local/lib
But when i run:
./println.cpp
it give error :
./println.cpp: line 10: using: command not found
./println.cpp: line 12: constexpr: command not found
./println.cpp: line 14: syntax error near unexpected token `('
./println.cpp: line 14: `behavior printer(event_based_actor* self, int32_t num, int32_t delay) {'

**Comment by Neverlord** [comment]
Are you trying to run the `.cpp` file in bash? From your compiler invocation, it seems like the binary you're building is `hello_world`.
