### ISSUE TITLE
Improve parser for `from_string`

### ISSUE THREAD

**Issue by ellcs** [actor-framework/actor-framework#195]
Adding signatures to messages is quite annoying. We need a parser for input of `send`. 
Notations of input:
* Bool - {true, false}
* String - "text"
* Atom - 'atom'
* Numbers
   * Integer
      * Deci: 42
      * Hex: 0x2a (beginning with 0x)
      * Octo: 043 (beginning with 0)
      * http://en.cppreference.com/w/cpp/language/integer_literal
   * Floating point
      * Double: 0.3
      * Float: 1.3f (ending with F or f)
      * http://en.cppreference.com/w/cpp/language/floating_literal

### Open questions:
* How to differentiate between int8_t and int16_t?

**Comment by Neverlord** [comment]
Obsoleted by `libcaf_python`.
