### ISSUE TITLE
Cannot spawn function-based actor with given arguments 

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1973]
Hi all, I'm looking at moving our playback app from 0.18.4 to 1.0.2, there have certainly been a lot of changes :)

So I'm trying to resolve all the build issues, and this one is stumping me. I'm guessing somethings changed, I check the changelog, but didn't spot anything.

Some help would be very much appreciated.

cheers!

```
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/local_actor.hpp: In instantiation of ‘caf::infer_handle_from_fun_t<F> caf::local_actor::spawn(F, Ts&& ...) [with caf::spawn_options Os = caf::spawn_options::no_flags; F = void (*)(caf::blocking_actor*, caf::response_promise, const caf::actor&, const xstudio::utility::UuidActor&, const caf::uri&, const std::__cxx11::basic_string<char>&); Ts = {caf::typed_response_promise<bool>&, caf::actor, xstudio::utility::UuidActor, const caf::uri&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; caf::infer_handle_from_fun_t<F> = caf::actor]’:
/u/al/dev/xstudio/src/timeline/src/timeline_actor.cpp:2639:21:   required from here
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/local_actor.hpp:151:19: error: static assertion failed: cannot spawn function-based actor with given arguments
  151 |     static_assert(spawnable,
```

Snippet of code being used.

```
            spawn(
                timeline_importer,
                rp,
                caf::actor_cast<caf::actor>(playlist_),
                UuidActor(base_.uuid(), actor_cast<caf::actor>(this)),
                path,
                data);
            return rp;
        }};
}


void timeline_importer(
    blocking_actor *self,
    caf::response_promise rp,
    const caf::actor &playlist,
    const UuidActor &dst,
    const caf::uri &path,
    const std::string &data) {


```

**Comment by Neverlord** [comment]
1. The compiler output says the function expects `caf::response_promise` but you're passing in `caf::typed_response_promise<bool>`
2. Passing a `response_promise` (typed or not) to another actor is unsafe and invokes UB.

If you need another actor to respond to something, the safe idiom is delegating the original message to that actor and then it can respond to it as-if it was the original recipient.

**Comment by alatdneg** [comment]
Hold on...
caf::response_promise rp

should be

caf::typed_response_promise<bool> rp

**Comment by alatdneg** [comment]
Whoops, okay'll I'll look at refactoring that code, I assume rp.delegate() is safe ?

**Comment by alatdneg** [comment]
Thanks for the help ! And all the hard work you put into this project.

**Comment by Neverlord** [comment]
> rp.delegate() is safe ?

As long as you call that on the actor that has created `rp`: yes. :)
