### ISSUE TITLE
Enums No longer work with CAF_ADD_TYPE_ID 

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1974]
Sorry another 0.18->1.0  hiccup.

Previously this worked, but it now no longer does.  Do enums now require inspector handlers ?

cheers

`typedef enum { LM_PLAY_ONCE = 0, LM_LOOP, LM_PING_PONG } LoopMode;`

`CAF_ADD_TYPE_ID(xstudio_simple_types, (xstudio::playhead::LoopMode))`

```
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/inspector_access.hpp: In instantiation of ‘std::enable_if_t<(! accepts_opaque_value_v<Inspector, T>), bool> caf::detail::save(Inspector&, T&, caf::inspector_access_type::none) [with Inspector = caf::binary_serializer; T = xstudio::playhead::LoopMode; std::enable_if_t<(! accepts_opaque_value_v<Inspector, T>), bool> = bool]’:
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/inspector_access.hpp:243:16:   required from ‘bool caf::detail::save(Inspector&, const T&) [with Inspector = caf::binary_serializer; T = xstudio::playhead::LoopMode]’
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/save_inspector_base.hpp:101:24:   required from ‘bool caf::save_inspector_base<Subtype>::apply(const T&) [with T = xstudio::playhead::LoopMode; Subtype = caf::binary_serializer]’
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/detail/make_meta_object.hpp:45:48:   required from ‘bool caf::detail::default_function::save_binary(caf::binary_serializer&, const void*) [with T = xstudio::playhead::LoopMode]’
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/detail/make_meta_object.hpp:94:3:   required from ‘caf::detail::meta_object caf::detail::make_meta_object(std::string_view) [with T = xstudio::playhead::LoopMode; std::string_view = std::basic_string_view<char>]’
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/init_global_meta_objects.hpp:58:47:   required from ‘void caf::init_global_meta_objects_impl(std::integer_sequence<short unsigned int, Is ...>) [with ProjectIds = caf::id_block::xstudio_simple_types; short unsigned int ...Is = {1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374}]’
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/init_global_meta_objects.hpp:69:44:   required from ‘void caf::init_global_meta_objects() [with ProjectIds = caf::id_block::xstudio_simple_types]’
/u/al/dev/xstudio/src/python_module/src/py_xstudio.cpp:55:5:   required from here
/builds/actor_framework/1.0.2/0d7a2c6bf5/include/caf/inspector_access.hpp:230:13: error: static assertion failed: please provide an inspect overload for T or specialize inspector_access
  230 |     detail::assertion_failed_v<T>,
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

```

**Comment by Neverlord** [comment]
> Do enums now require inspector handlers ?

Yes, but you can opt-in to the default implementation (as shows in [this example](https://github.com/actor-framework/actor-framework/blob/main/examples/message_passing/divider.cpp)):

```
template <class Inspector>
bool inspect(Inspector& f, math_error& x) {
  return caf::default_enum_inspect(f, x);
}
```

**Comment by alatdneg** [comment]
Sounds like that should work, we have some actors that send themself delayed messages, I'm assuming an anon_mail that's delayed sent to an actor is implictly weak ? 
I need to read up on the new mail api, to be honest, I'm currently just use the deprecated functions, as there are a huge number of statements that will need refactoring in our code base. 
I just want to get it at least running on v1.0 before I start the rest of this refactor.

**Comment by alatdneg** [comment]
> > Do enums now require inspector handlers ?
> 
> Yes, but you can opt-in to the default implementation (as shows in [this example](https://github.com/actor-framework/actor-framework/blob/main/examples/message_passing/divider.cpp)):
> 
> ```
> template <class Inspector>
> bool inspect(Inspector& f, math_error& x) {
>   return caf::default_enum_inspect(f, x);
> }
> ```

Does that mean I need to also implement these things,  for all 30 enums in my code .. "crying into coffee"

```
std::string to_string(math_error x) 
bool from_string(std::string_view in, math_error& out) 
bool from_integer(uint8_t in, math_error& out) 
```

**Comment by Neverlord** [comment]
> Does that mean I need to also implement these things, for all 30 enums in my code .. "crying into coffee"

Only if you actually want these. If you have that many enums, you could also just do what CAF used to do for enums: treat it as an integer.

Something like this should work:

```
template <class Inspector>
bool inspect(Inspector& f, my_enum& x) {
  using int_t = std::underlying_type_t<my_enum>;
  auto getter = [&x] { return static_cast<int_t>(x); };
  auto setter = [&x](int_t val) { x = static_cast<my_enum>(val); };
  return f.apply(getter, settter);
}
```

**Comment by Neverlord** [comment]
> Sounds like that should work, we have some actors that send themself delayed messages, I'm assuming an anon_mail that's delayed sent to an actor is implictly weak ?

Those should use strong references.

**Comment by alatdneg** [comment]
> > Does that mean I need to also implement these things, for all 30 enums in my code .. "crying into coffee"
> 
> Only if you actually want these. If you have that many enums, you could also just do what CAF used to do for enums: treat it as an integer.
> 
> Something like this should work:
> 
> ```
> template <class Inspector>
> bool inspect(Inspector& f, my_enum& x) {
>   using int_t = std::underlying_type_t<my_enum>;
>   auto getter = [&x] { return static_cast<int_t>(x); };
>   auto setter = [&x](int_t val) { x = static_cast<my_enum>(val); };
>   return f.apply(getter, settter);
> }
> ```

Well that's a relief :)

**Comment by alatdneg** [comment]
After bit of fiddling the app is up and running !
A final question, is there a way of dumping the actors that are stopping the actor system from shutting down, I can see it's listing a count of actives (with debug logging on), but it'd be handy to tell which actors these are to narrow the search for bad behaviour.

**Comment by dominiklohmann** [comment]
> it'd be handy to tell which actors these are to narrow the search for bad behaviour.

This is one of our biggest pain points as well in development with CAF: accidentally hanging on shutdown because some actor is keeping the actor system alive. So +1 from me on wanting to have something to track this down.

**Comment by Neverlord** [comment]
> So +1 from me on wanting to have something to track this down.

The best tool at the moment is analyzing the logs. There's not really a guide about that at the moment though. We should definitely provide some guidance on that and/or provide some additional observability support for what actors are currently active coming next year.
