### ISSUE TITLE
Add migratable actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#199]
Add a new base class for migratable actors, implement state transfer and message forwarding.

**Comment by ufownl** [comment]
I think the implementation of this can be based on `stateful actor` which has been described in #293 .

**Comment by Neverlord** [comment]
Yes, the new stateful actors make things easier. In fact, thinking about a good design for the migratable actors led to the stateful actor proposal.

**Comment by Neverlord** [comment]
Postponed until we know which direction our new distribution layer by @josephnoir goes (also see https://github.com/actor-framework/actor-framework/wiki/The-CAF-Network-Layer).
