### ISSUE TITLE
Extend BASP to allow nodes to establish new connection when needed

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#204]
BASP is able to route messages from A to B over C, but A and B should have some way to get a direct connection in case there are a lot of messages to avoid the additional overhead.

**Comment by Neverlord** [comment]
Any progress on this topic?

**Comment by mavam** [comment]
It will go into testing pretty soon!

**Comment by Neverlord** [comment]
Sounds good. :)

**Comment by mavam** [comment]
@Neverlord: Would you mind merging `develop` into the revised topic branch? I'm going to give this a shot now, but it might be quicker for you to resolve the merge conflicts.
