### ISSUE TITLE
Error in source code in manual section 8.1 Links

### ISSUE THREAD

**Issue by samaust** [actor-framework/actor-framework#224]
I'm a beginner in C++11 and lambda programming so please be lenient if I'm mistaken.

In the pdf manual in section 8.1 Links there's the line :
`[](const exit_msg& e) >> [=] {`

I believe it should be :
`[=](const exit_msg& e) {`

Edited : added "\`" to code

**Comment by Neverlord** [comment]
I suppose you meant the line `[](const exit_msg& e) >> [=] {`? That's indeed wrong and should read `[=](const exit_msg& e) {`. Thanks for the hint.

**Comment by samaust** [comment]
That's right. I'm new to GitHub and did not know I had to use "\`" to post code and did not notice it was wrong when I copy pasted.
