### ISSUE TITLE
Support typed groups

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#225]
It's currently not possible to stuff typed actors into groups while preserving their type information. It would be nice to have a `typed_group` in the same vein as a `typed_actor`.

**Comment by ufownl** [comment]
It seems hard to implement, because `group::get`.

**Comment by Neverlord** [comment]
Yes, we would basically need to register groups instead of just getting them on-the-fly. Otherwise we can't ensure that groups always have the same types. That would be a breaking change, though... I didn't see an easy solution for this either.

**Comment by Neverlord** [comment]
I close this as `wontfix` for now. Though I would love too see typed groups, I don't see how we can achieve this without a complete redesign.
