### ISSUE TITLE
Implement fall-through as dual to or_else

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#227]
The function `or_else` enables composition of message handlers. When two handlers A and B joined with `A.or_else(B)` share a match expression with signature F, then only the one in A gets invoked.

To make composition more flexible, it would be great to also have a "fall-through" option, e.g., `A.fall_through(B)` which would mean that both F in A and F in B get invoked.

More formally, this new feature would complete the following duality: `fall_through` is to `or_else` what *universal* is to *existential* quantification.

**Comment by Neverlord** [comment]
Closed (see discussion in VAST).
