### ISSUE TITLE
Improve extraction of command line arguments

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#230]
Currently we extract values from the command line message builder as follows:

```cpp
message_builder{argv + 1, argv + argc}.apply({
    on("-c", spro<uint16_t>)>> [](uint16_t port) {
      CAF_PRINT("run in client mode");
      run_client("localhost", port);
    }, ...
```

In most cases we want the string projection `spro<T>` to have the same type as the lambda, so why not have a `string_match` analogously to `arg_match` for that purpose.

**Comment by Neverlord** [comment]
Since we've talked about this in the meantime and `extract_cli` covers your use case... Are you ok with closing this one?

**Comment by mavam** [comment]
Sure, we can reopen it at some later point.
