### ISSUE TITLE
Port the old Boost.Actor ASIO backend to CAF as optional feature

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#232]
The old ASIO backend from Boost.Actor is outdated, but porting it to the new multiplexer API should be straightforward.

**Comment by andreihu** [comment]
Sorry, it's a bit off topic. I have started to work on the feature, but i haven't found any info about how it should be done regarding source control. Should i do it in the "develop" branch or create a new branch and that will be integrated into develop by someone else?

**Comment by Neverlord** [comment]
The usual work flow is to create a topic branch from `develop` in you fork, e.g., `topic/asio-multiplexer`, and then open a pull request into `develop` once you are ready. Before opening the pull request, please make sure to squash your commits into a single one. This makes it easier for us to keep track of changes etc.

**Comment by andreihu** [comment]
thx, will do that way

**Comment by andreihu** [comment]
Just linking in supporting material for this topic:
https://groups.google.com/forum/#!topic/actor-framework/m9mt7VJTTzs
