### ISSUE TITLE
caf::wildcard_position::nil makes compiler error on objective-c++ (nil is a reserved word)

### ISSUE THREAD

**Issue by araste** [actor-framework/actor-framework#261]
I am testing LibCAF with iOS projects. Xcode runs example codes nicely but there is an issue. To use libcaf actors in iOS projects we should use Objective-C++. 

In Objective-C++ 'nil' is a reserved word. In caf::wildcard_position of caf/wildcard_position.hpp enum 'nil' is used so it makes compile errors. If we replace 'nil' with another keyword like 'none' it works like a charm. This is the only problem in LibCAF headers to use LibCAF for iOS development. Can you please consider it for iOS developers?

**Comment by Neverlord** [comment]
The fix is even simpler... `wildcard_position` is an artifact from previous versions of CAF and can be simply removed. Thanks for the hint.
