### ISSUE TITLE
MinGW

### ISSUE THREAD

**Issue by osblinnikov** [actor-framework/actor-framework#262]
I'm trying to compile caf on Windows with MinGW with C++11 threads from [here](http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.1/32-bit/threads-posix/dwarf/)

But I run into several problems.
1. During compilation of `libcaf_core\src\get_root_uuid.cpp` I got:

      libcaf_core\src\get_root_uuid.cpp: In function 'std::string caf::detail::get_root_uuid()':
      libcaf_core\src\get_root_uuid.cpp:180:3: error: 'string' was not declared in this scope
         string uuid;
         ^
      libcaf_core\src\get_root_uuid.cpp:180:3: note: suggested alternative:
       In file included from mingw32\lib\gcc\i686-w64-mingw32\4.8.1\include\c++\string:39:0,
                 from libcaf_core/caf/detail/get_root_uuid.hpp:23,
                 from github.com\actor-framework\libcaf_core\src\get_root_uuid.cpp:21:
                 mingw32\lib\gcc\i686-w64-mingw32\4.8.1\include\c++\bits\stringfwd.h:62:33: note:'std::string'
        typedef basic_string<char>    string;
                                       ^
            libcaf_core\src\get_root_uuid.cpp:180:10: error: expected ';' before 'uuid'
        string uuid;
               ^
          
When I declare `std::string uuid;` instead of `string uuid;` the compilation succeeded.

2. Another problem occurs during compilation of `libcaf_io/src/interfaces.cpp`

The headers `
#include <netdb.h>
#include <net/if.h>
#include <ifaddrs.h>
#include <sys/ioctl.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
` could not be found. I don't expect that someone ever launched it on MinGW but any hint on how to fix this for Windows can help me

**Comment by Neverlord** [comment]
MinGW support is currently quite user-driven and I'm afraid we're guilty of braking it every once in a while with new releases. The Problem with MinGW is that we have no Windows user in our team and no Jenkins setup for it (not yet, anyways). We have a Visual Studio setup for Jenkins and a branch for the required patches... Only that Microsoft hasn't done its homework yet. So we don't merge the changes back until we know for sure what workarounds are really needed and what can be dropped. Hopefully with the next CP iteration we start supporting Windows as "first class citizen".

Does it work on MinGW if you replace the file with the version from `topic/visual_studio` [1]?

[1] https://github.com/actor-framework/actor-framework/blob/topic/visual_studio/libcaf_io/src/interfaces.cpp

**Comment by osblinnikov** [comment]
Thank you for the detailed answer. I will be able to try it after easter on 9 of April when I'll finally get an access to my laptop. )

**Comment by Neverlord** [comment]
I merged the changes from the visual studio branch and fixed some minor issues. Should work again now. Please re-open if it doesn't for you.

**Comment by osblinnikov** [comment]
Yes, I've got the build running on mingw x86 with only one small problem:
libcaf_riac\src\init_probe.cpp : 51 tries to call gethostname(buffer, max_hostname_size);
but mingw can't find it, after inclusion of winsock2.h in init_probe.cpp the compilation finishes successfully:

#ifdef CAF_WINDOWS
 #include <winsock2.h>
#endif

**Comment by Neverlord** [comment]
Thanks, I will add the include.
