### ISSUE TITLE
Redundant configure script

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#264]
I do not understand why you have separate `./configure` step and simulate in-source builds? Of course, there is a well-known `./configure && make && sudo make install` magic spell, but in many developers' minds there is a strong association "configure == autotools". Why not just write another magic sequence in user manual:

    mkdir build && cd build
    cmake .. [OPTIONS]
    make
    make test

and describe all options as `-D${OPTION_NAME}`.

To my mind, people must be exactly noted which build system they actually use. Moreover, looking to the above commands, everybody can easily get how to perform the build on Windows (just remove `mkdir` with `md`, and the rest is fine), while your script will not be functional unless Cygwin or something similar installed. Also, many people do not want to manually build the code at all, they would just add your repository as Git submodule and do `add_subdirectory` CMake command.

So, the `configure` script is truly redundant. The only its purpose is to make ugly CMake's `-D` parameters look nicer. Remove it, be honest to people.

**Comment by Neverlord** [comment]
The configure script is not redundant at all and neither is it about simulating in-source builds. CMake has the most obnoxious command line syntax one can possibly imagine. I would go as far as to call our configure script self-defense...

To be quite frank, I don't care about build systems. I do care about daily work flows. We use the script quite heavily during development to turn on or off certain features or configurations for testing purposes. Using CMake directly does not fit into any work flow (unless you're some kind of masochist, I suppose).

That being said, I do agree that we should document the CMake options to allow others to integrate CAF into their build process more easily. I think adding a Wiki Page with all CMake arguments would be in order, plus a link to it in the readme file.
