### ISSUE TITLE
Deprecate 'sb_actor'

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#265]
Below is an extract from the user manual (bold is mine):
> A class-based actor is a subtype of **`event_based_actor`** and must implement the pure virtual member function `make_behavior` returning the initial behavior. Another way to implement class-based actors is provided by the class **`sb_actor`** (“State-Based Actor”). This base class simply returns `init_state` (defined in the subclass) from its implementation for `make_behavior`.

What a screaming inconsistence! I think we should rename state-based actor root class to `state_based_actor` in future releases and keep a deprecated alias for `sb_actor` (and, preferably, mark it with [`[[deprecated]]`][1] attribute).

[1]: http://josephmansfield.uk/articles/marking-deprecated-c++14.html

**Comment by Neverlord** [comment]
Hm, that's probably because the state-based actor was originally named `fsm_actor`. Its a weird actor anyway. Maybe we just deprecate it and move on until we add "real" finite-state machines with entry/exit actions etc.

**Comment by Neverlord** [comment]
I think deprecating `sb_actor` and remove it in favor of the new `stateful_actor` [1] is the right decision in the long term.

[1] #293

**Comment by ralphjzhang** [comment]
Warmly welcome this, btw, 'sb' in Chinese stands for 'asshole/idiot', so I never ever let it appear in code  :+1:

**Comment by Neverlord** [comment]
> btw, 'sb' in Chinese stands for 'asshole/idiot', so I never ever let it appear in code

lol, good to know! :smile:
