### ISSUE TITLE
Create atoms directly from datatypes

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#266]
As far as I can get from reading the manual and Doxygen documentation, there is only one way currently to obtain an atom value: 
```cpp
using specific_atom = atom_constant<atom("specific")>;
```
But using string literals (with quite strict requirements put on them!) is error-prone. I think it would be a good idea to be able to instantiate an atom from the specific data type directly. The example above rewritten:
```cpp
class SpecificType {};
using specific_atom = atom_constant<SpecificType>;
—or—
using specific_atom = atom_constant<atom<SpecificType>()>;
```
Is something like this possible?

> This mapping is guaranteed to be collision-free and invertible, but limits atom literals to ten characters and prohibits special characters. Legal characters are “_0-9A-Za-z” and the whitespace character.

Brief computation give the address space of 1.2⋅10<sup>16</sup> items. That's a pretty large number, and I think that hash collisions are inevitable, so mapping data types to the same address space is not going to change things a lot.

I would also be glad to see the dash character in the list of allowed characters. It reminds me the Lisp's syntax for symbols, which is nice and cute, but entirely the matter of taste.

**Comment by Neverlord** [comment]
Why do you think creating atom constants from strings is error-prone? After you have declared the constant, you will never re-type the string again. I don't see any benefit from this other than having more types to maintain.

By the way, your suggested approach is not possible anyways. Maybe if at some point C++ provides "static reflections" as proposed by some. Even if it were possible, I still would prefer the existing solution, though.

**Comment by firegurafiku** [comment]
> Why do you think creating atom constants from strings is error-prone? After you have declared the constant, you will never re-type the string again. I don't see any benefit from this other than having more types to maintain.

For example, literal strings are not refactoring-friendly. Moreover, the ten-characters limit for their names is a quite strict (like 8.3 file names, but one character shorter) to express difficult concepts, so users would have to invent cryptic names if they want a lot of descriptive names for atoms. If we are able to obtain atom's hash from the data type meta information, we could avoid such limits altogether.

> By the way, your suggested approach is not possible anyways. Maybe if at some point C++ provides "static reflections" as proposed by some. Even if it were possible, I still would prefer the existing solution, though.

That a pity. But what about at least the dash support? But I think I already know the answer :).

**Comment by Neverlord** [comment]
> For example, literal strings are not refactoring-friendly.

That's not a valid point IMO. Atom constants have a *type*. If you use the recommended style, i.e., `using some_atom = ...`, you'll have all the refactoring-friendliness you can get. Repeating the string literal is not a good idea, yes. But its not the recommended way. Our recommendation is to use a single header per project with all defined atom constants (just like you would maintain an `enum`). No one stops you from shooting yourself in the foot by doing silly stuff, but's that's your problem. We embrace the same philosophy as C++ does. :)

> That a pity. But what about at least the dash support? But I think I already know the answer :).

I would add all sorts of special characters if I could. Atoms don't use a hash algorithm. It's a 6-bit encoding (like Base64). The reason for not using hashing is that we want a reversable mapping. Debugging and logging would be a pain without proper `to_string` for atoms. Unfortunately, we already use all of the 64 possible characters... The 6-bit encoding is also the reason for the 10-characters limit. There's just no way to put more characters in a 64 bit variable (the remaining four bits are used as start sequence to differenciate `" a"` from `"a"`). Using a larger storage (two 64 bit integers for instance) would only offset the problem but cause significant runtime overhead. We opted to take a bit of inconvenience in favor of faster execution speed.
