### ISSUE TITLE
Extract user manual's LaTeX sources into a separate repository

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#272]
*(In the assumption that I haven't yet completely bothered you with my cool ideas,)* should not we have manual as a separate repository? As I understand, manual receives tweaks before a new version released, but in the meantime it may stay inconsistent with the code base. So it seems reasonable to me to have it put away from the code itself.

Also, considering the presence of `Boost.Actor`, what is your policy for manuals synchronization? What about writing single LaTeX source with some [conditionally defined][1] commands like the following:
```tex
\newif\ifboost
\ifboost
    \newcommand\caf{CAF\xspace}
\else
    \newcommand\caf{Boost.Actor\xspace}
\fi
```
where running text looks like "Before diving into the API of \caf, we would like...". But I expect some difficulties with verbatim blocks in code examples, though.

[1]: http://tex.stackexchange.com/questions/33576/conditional-typesetting-build

**Comment by Neverlord** [comment]
> As I understand, manual receives tweaks before a new version released, but in the meantime it may stay inconsistent with the code base.

The manual should not become inconsistent with code base. In the worst case, it lags a bit behind when adding new features. However, the manual is an essential component of the CAF distribution. As such, I don't think it's a good idea separating it.

> Also, considering the presence of Boost.Actor, what is your policy for manuals synchronization?  What about writing single LaTeX source with some conditionally defined commands like the following:

Already exists:

```
$ cat manual/variables.tex.in 
\newcommand{\lib}{CAF\xspace}

\newcommand{\libtitle}{%
\texttt{\huge{\textbf{\lib}}}\\~\\A C++ framework for actor programming\\~\\~\\~\\%
}

\newcommand{\libsubtitle}{%
User Manual\\\normalsize{\lib version @CAF_VERSION@}\vfill%
}
```

**Comment by firegurafiku** [comment]
> The manual should not become inconsistent with code base. In the worst case, it lags a bit behind when adding new features.

As for me, writing a good user manual is a completely different kind of work, hardly ever related with writing code. It may be inconvenient to keep synced code, Doxygen documentation and the manual. If I were you, I'd prefer to work on manual specifically after the API for coming release is stable, most of coding work is already done and there is some time for belletristic writing.

> However, the manual is an essential component of the CAF distribution.

People do not usually read LaTeX sources. Moreover, many Linux package distributions do not see documentation as the essential part, thus extracting it into a separate `-doc` package.

> Already exists: `...`

That's not exactly the same thing. Converting manual from CAF version to Boost one requires a lot more that just creating macro definition for library name. We need also properly converting examples (replace `using namespace caf;` to `using namespace boost::actor;` in them), remove the section about `caf::optional` in favour of `boost::optional`, or do something else. So, your current setup is not sufficient.
