### ISSUE TITLE
Add Pony benchmark

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#279]
The [Pony](http://ponylang.org) language offers first-class actor support. The authors also compare it against CAF 0.13 in [a set of benchmarks](http://ponylang.org/benchmarks_all.pdf). It would be great to reproduce these numbers.

**Comment by Neverlord** [comment]
Sources are here: https://github.com/CausalityLtd/ponyc/tree/master/examples

It's merely a matter of copying the sources to our benchmark repository and patch the CMake setup.

**Comment by mavam** [comment]
The Pony examples appear not to be 100% comparable at this point. In addition to integrating them in the benchmark repo, we should also tweak them so that we're dealing with apples only.
