### ISSUE TITLE
Clean error message for incompartible data type announcement

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#284]
I tried to announce a (quite simplistic) custom data type
```c++
struct InitializationRequest { caf::actor_addr domainAddr; };

inline void announceMessages() {
    caf::announce<InitializationRequest>(
        "rvlm::fdtd::InitializationRequest",
        &InitializationRequest::domainAddr);
    ... 
}
```
but got a very long and cryptic error message from the compiler. After discussion on Gitter I have been given an explanation that my type should implement `operator==` in order to be announced, but that was not very obvious.  I think it really should be made clear for user to spot their error, `static_assert` should be fine.

**Comment by Neverlord** [comment]
This code will now give you the compile-time error `T is neither a POD, nor empty, nor comparable with '=='`.
