### ISSUE TITLE
New stateful actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#293]
That's something I'm thinking of implementing for a while now and I would like to get some feedback on the idea.

The only benefit the "old" `sb_actor` did provide was saving 1-2 lines of code: `behavior init_behavior = ...` instead of `behavior make_behavior() override { ... }`. It would make more sense to focus on viability of non-class based actors instead, which I personally almost always prefer anyways. The new `stateful_actor` could have an interface like this:

```cpp
using inc_and_fetch_atom = atom_constant<atom("IncFetch")>;

struct counter_state {
  int counter = 0;
};

behavior counter(stateful_actor<counter_state>* self) {
  [](inc_and_fetch_atom) {
    return *self->counter += 1;
  }
}

int main() {
  auto cntr = spawn(counter);
}
```

Note the `*self->` syntax. This is how a stateful actor could access its state. The more verbose version would be `self->state.counter += 1`. Since accessing the state is expected to be a very common operation, some syntactic sugar might be in order (even though it's a bit hacky).

A *huge* benefit of this design is the following:

```cpp
struct slave_state {
  actor master;
};

struct master_state {
  actor slave;
};

behavior master(stateful_actor<master_state>* self) {
  *self->slave = spawn<monitored>(slave, self);
  // ... more stuff ...
}
```

When modeling the same with `event_based_actors`, killing the master is a memory leak. The slave keeps a reference to the master and vice versa. Actors have to actively break the cycle by setting references to `invalid_actor` in `on_exit`. Decoupling the state in this way allows the runtime to safely run the destructor for the state once the actor has finished execution!

Opinions?

**Comment by mavam** [comment]
> The only benefit the "old" sb_actor did provide was saving 1-2 lines of code: behavior init_behavior = ... instead of behavior make_behavior() override { ... }.

Yeah, I never used `sb_actor` anyway, it conflicted with my member naming style. :unamused: 

> It would make more sense to focus on viability of non-class based actors instead, which I personally  almost always prefer anyways. 

:+1:
This is the right step forward into promoting a functional programming mindset in C++: treating state separate from functions and using this dichotomy as primary form of composition. (Because we don't have laziness built into C++, it doesn't make sense to go one step further and require purity, i.e., each function executed over the actor's state yields a new state instance.)

> Note the *self-> syntax.

I think you want to overload the pointer-to-member function operator `->*`. However, this syntax places `*` after `->`. That would be `self->*counter` instead of the ordinary dereference `*self->counter`.

> Actors have to actively break the cycle by setting references to invalid_actor in on_exit.

Indeed, the current situation is annoying and error-prone in fast-moving code bases.

**Comment by Neverlord** [comment]
> I think you want to overload the pointer-to-member function operator `->*`. However, this syntax places `*` after `->`. That would be `self->*counter` instead of the ordinary dereference `*self->counter`.

You have to dereference `self` in any case because of the way operator overloading works. You cannot apply `->*` to `T*`. `*self->x` is the shortest notation you can get.

> Indeed, the current situation is annoying and error-prone in fast-moving code bases.

I count this as +1. :)

**Comment by mavam** [comment]
> You have to dereference self in any case because of the way operator overloading works. 

Ah, I see. So you're just overloading `operator*(T)` then.

**Comment by firegurafiku** [comment]
@Neverlord 

I think most programmers not familiar with Haskell and friends would find this concept hard to reason. Simply using class based actors is much more obvious.

@mavam 

> Yeah, I never used sb_actor anyway, it conflicted with my member naming style. :unamused:

Isn't Hungarian notation considered harmful? ^__^

> Note the *self-> syntax.
> 
> I think you want to overload the pointer-to-member function operator ->*. However, this syntax places * after ->. That would be self->*counter instead of the ordinary dereference *self->counter.

No, no, no, that would be *way* counter-intuitive. Ideally we should have `stateful_actor<master_state> const& self` and `self->counter`, like `shared_ptr` do. But I guess this is barely possible for actors.

**Comment by mavam** [comment]
> Isn't Hungarian notation considered harmful? ^__^

In this case, I think the `sb_` prefix does try to be a Hungarian prefix but rather a short name for `state_based_actor`. Regarding code style: as long as a code base is consistent, I accept any style, even the Hungarian. :wink:

**Comment by Neverlord** [comment]
> I think most programmers not familiar with Haskell and friends would find this concept hard to reason. Simply using class based actors is much more obvious.

No one stops you from still using them. :)

> No, no, no, that would be *way* counter-intuitive. Ideally we should have `stateful_actor<master_state> const& self` and `self->counter`, like `shared_ptr` do. But I guess this is barely possible for actors.

This would imply that `stateful_actor` would need to extend `master_state`. That would suffer the same problems as before. Composition > Inheritance. I'm a bit torn about the `*self->x` thing. The alternative is writing `self->state.x` each and every time, which is terribly verbose.

**Comment by mavam** [comment]
> I'm a bit torn about the *self->x thing. The alternative is writing self->state.x each and every time, which is terribly verbose.

Now knowing that you were not planning to use pointer-to-member syntax, I think the proposed form `*self->x` is too ambiguous. The first reaction is "oh, you're accessing a pointer-like thingy", which is not the case here. Almost nobody has an association with pointer-to-member syntax, it's a rather obscure C++ feature. The problem is that `(*self)->*x` doesn't look any prettier. Can you define `operator->*` in the actor handle itself (maybe SFINAEd out for non-state-based actors)?

**Comment by Neverlord** [comment]
> The problem is that `(*self)->*x` doesn't look any prettier. Can you define `operator->*` in the actor handle itself (maybe SFINAEd out for non-state-based actors)?

I would rather keep an orthogonal design. Using `event_based_actor*` in one case but `stateful_actor_ptr<state_class>` in the other is no good design IMO. Operator `->*` is also binary... so that probably wouldn't work.

Too bad Stroustrup's proposal for `operator.` is not implemented already: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4477.pdf

**Comment by Neverlord** [comment]
> I think most programmers not familiar with Haskell and friends would find this concept hard to reason. Simply using class based actors is much more obvious.

@firegurafiku C++ has always been a hybrid language where OO co-exists with other concepts such as templates and free functions. I generally see a shift away from "OO thinking" in the community, which is a good thing. The new `<functional>` header is one example. Working with higher order functions is still a bit clumsy in C++, but doable, and the new lambda expressions give a lot of expressive power to the language. The design philosophy beyond CAF always was to embrace the hybrid nature of C++ and provide both an "OO-like" and a more functional-oriented style.

I think as long as we keep a good balance and explain the concepts and reasoning behind the code, developers will see the benefits and can make "educated decisions" on which way solves their problem best. Even without Haskell background. I know you already have some tweaks to the manual in the pipeline. Maybe we can add a "design philosophy" or "programming concepts" section that summarizes this topic. :)

OO has many downsides and classes are heavily over-used in my opinion. That the multi-core revolution is such a big deal is a direct consequence and the industry still struggles.

> > Note the *self-> syntax.
>
> [firegurafiku] No, no, no, that would be *way* counter-intuitive.
> [mavam] I think the proposed form `*self->x` is too ambiguous.

All right then. Maybe that's a bit too "progressive" (read *hacky*). Since the state needs to be separated from the type (in order to call its dtor befor the actor is destroyed), the only remaining syntax is `self->state.x`.

**Comment by firegurafiku** [comment]
@Neverlord 
Let me clarify some points. 

> I generally see a shift away from "OO thinking" in the community, which is a good thing. The new <functional> header is one example.

I can see that shift too. But the more I see it, the more I get convinced that C++ should be replaced with a new language, better designed from the very beginning, but backward-compartible to a reasonably high level. Current C++ is extremely hard to keep every its detail in mind. The operator-dot proposal is going to destroy the last thing I could be sure it cannot be indirected with operator overloading behind my back.

> Note the *self-> syntax.
> 
> [firegurafiku] No, no, no, that would be way counter-intuitive.
> [mavam] I think the proposed form *self->x is too ambiguous.

Here my no-no comment was about @mavam's proposal to change `*self->` to `self->*`, your original syntax is better understandable, to my mind.

**Comment by Neverlord** [comment]
> I can see that shift too. But the more I see it, the more I get convinced that C++ should be replaced with a new language, better designed from the very beginning, but backward-compartible to a reasonably high level.

There is D and Go and some others... But I don't see a replacement for C++ coming in the near or even mid future. You choose C++ because it gives you control over performance. In particular because it does *not* enforce garbage-collection-nonsense to each tiny object you create. Reliably called destructors with scoping rules are a big deal. There is inherent complexity to this approach (objects on the stack vs. objects on the heap, for instance). Unfortunately C++ also adds a metric ton of accidently and even unnecessary complexity. A lot of the accidently complexity comes from C compatibility on the source level. Still, this compatibility is also the reason for the success of C++.

As stroustrup put it: "There are only two kinds of programming languages: those people always bitch about and those nobody uses." C++ is also a bright example that we can actually have real platform-independent, standardized programming languages with several compilers. I could have gone the "easy" way and define yet another programming language based on actors with shiny features and well-though concepts. In other words: another language nobody uses. :wink:

C++ is here to stay. I also put my trust into the committee to put even more unnecessary complexity to the language (*sigh*). Still, the advantages of using C++ outweigh the disadvantages and occasional frustration. 

> Here my no-no comment was about @mavam's proposal to change `*self->` to `self->*`, your original syntax is better understandable, to my mind.  

Ah, sorry I messed that up. So... +1 on the `*self->x`? :smile:
Or would you still prefer `self->state`?

**Comment by mavam** [comment]
> Ah, sorry I messed that up. So... +1 on the `*self->x`? 
> Or would you still prefer `self->state.x`?

Anything against keeping both? With my sweet tooth, I don't want to be the one tearing down syntactic sugar. In other words, why not have `*self->x` simply as shorthand for `self->state.x` and let the user decide which style they would like in their codebase.

**Comment by Neverlord** [comment]
Hm, I forgot about the operator precedence. `*self->x` is parsed as `*(self->x)` in C++. Users would have to use `(*self)->x`, which is not very elegant. Make noise if you see a good alternative. :)

**Comment by mavam** [comment]
`state(self)->x` where `state` is a free function?

**Comment by ufownl** [comment]
The latter one expose internal data member to the user of `stateful_actor`. It may not be a good choice. @mavam

**Comment by mavam** [comment]
Am I understanding you correctly in that you're saying that `self->state.x` exposes internal members? Actually, I don't think so, if `state` is the only publicly accessible member, then it shouldn't be a problem, no?

**Comment by ufownl** [comment]
You are right, but it has a little conflict with code conventions.

**Comment by mavam** [comment]
Yeah, finding the right syntax is the issue here.

The pathetic fact is that if we did *not* overload the pointer-to-member-function operator, we would be close to the right semantics ([§5.5.3](http://eel.is/c++draft/expr.mptr.oper)):

> The binary operator ->* binds its second operand, which shall be of type “pointer to member of T” to its first operand, which shall be of type “pointer to U” where U is either T or a class of which T is an unambiguous and accessible base class. The expression E1->*E2 is converted into the equivalent form (*(E1)).*E2.

That is, LHS is a pointer (`self` kinda is that, but not a real pointer) and RHS a member function pointer, but overloading makes `->*` just an ordinary function. :unamused:

Whether to go with `self->state.x` or `state(self)->x` depends also whether it makes sense to have a free function `state(...)` for other types as well. I am still leaning towards `self->state.x` because it's the easiest to write.

@Neverlord: what if `stateful_actor` inherits from the state struct, as in CRTP? Then you could get away with `self->x`.  So something along the lines of:

```cpp
template <class State>
struct stateful_actor : State
{
...
};
```

**Comment by Neverlord** [comment]
> @Neverlord: what if `stateful_actor` inherits from the state struct, as in CRTP? Then you could get away with `self->x`.

The whole point of this idea is to have the state in a `union` to be able to call ctor/dtor independent of the actor's actual lifetime. There's no such thing as partially constructed objects in C++.

**Comment by Neverlord** [comment]
I didn't like the free function approach to be honest. I settled with `self->state().x` for now (see latest commit). Comments and opinions of course welcome, the new actors live in the `experimental` namespace for now, so the code is still open for change.

**Comment by mavam** [comment]
The form `self->state().x` looks good to me, except that the parentheses still bother me. Can we get rid of them? You could simply write `union { State state; };` instead and make it a public, as it becomes the API. Usually I'd refrain from exposing a union like this, but in this case the user doesn't know what's going on under the hood.

**Comment by Neverlord** [comment]
I did hide the union by making `state` a reference to `state_` [1]. Also plays nice with auto-completion of IDEs.

[1] https://github.com/actor-framework/actor-framework/commit/cc944f6480d8105bd5b6ebb68acf7a41d7b0a328

**Comment by mavam** [comment]
That'll do. :+1:

**Comment by Neverlord** [comment]
This feature is used in quite a lot of places in CAF already. Does anyone still have some ideas or change requests for this feature? Otherwise, I'll move this to the `caf` namespace next week to make this feature "official".

**Comment by mavam** [comment]
In general, the API looks ready to go.

One more question about the semantics: when are the ctor and dtor of the `state` class called? Intuitively, I would think the ctor is called immediately after the actor spawned (e.g., in `make_behavior`) and the destructor immediately before the actor exits. Then the state would only exist while the actor is running.

Now, I remember we had a discussion in the chat about the need for a separate `init()` function for a scenario, where the ctor logs the actor creation and the dtor its termination. Given the need for this extra function, I assume that my assumptions on construction and destruction are false. It seems the actor is only partially constructed in the state ctor (which doesn't exit in C++), otherwise an `init` function would not be necessary.

Would you mind filling in what I'm missing here?

**Comment by Neverlord** [comment]
Your assumption is correct. You confused this with a discussion about a common base for states.

**Comment by mavam** [comment]
I realize that I still haven't found the right solution in this framework that makes it easy to hook logging without adding too much own boilerplate. I care about the state name and the actor ID. The best I came up with is this:

```cpp
template <class State, class Base = event_based_actor>
struct basic_actor : stateful_actor<State, Base> {
  using super = stateful_actor<State, Base>;

  void initialize() override {
    super::initialize();
    LOG("spawned " << this->name() << '#' < this->id());
  }

  // would currently not work because base class method is marked "final"
  void on_exit() override {
    LOG("terminated " << this->name() << '#' < this->id());
    super::on_exit();
  }
};
```

Do you see another solution that does not require introducing a new actor class? I don't recall how a common base for states alone would suffice, since there's no way to get the actor ID inside the state.

**Comment by Neverlord** [comment]
> I don't recall how a common base for states alone would suffice, since there's no way to get the actor ID inside the state.

The state gets a pointer to the actor in its ctor. Here's a simple base that does the job:

```cpp
class basic_state {
  actor_id aid;
  std::string name;
  basic_state(local_actor* self, std::string self_name)
    : aid(self->id()),
      name(std::move(self_name)) {
    LOG("spawned " << name << '#' < aid);
  }
  ~basic_state() {
    LOG("terminated " << name << '#' < aid);
  }
};
```

The class stores the actor ID to access it later in the dtor. You could also store the pointer instead. Taking `local_actor*` means that you can use this base state with *all* kinds of actors, e.g., typed actors and event-based actors.

This is what a derived state would look like:

```cpp
struct my_state : basic_state {
  my_state(event_based_actor* self) : basic_state(self, "my_actor") {
    // nop
  }
  int x;
  int y;
  // ...
};

behavior my_actor(stateful_actor<my_state>* self) {
  return { /* ... */ };
}
```

**Comment by mavam** [comment]
Thanks, that's pretty much what I'm looking for. A few more questions:

- Why do you use an `event_based_actor` in the ctor of `my_state`? (As opposed to `local_actor`, which you use in `basic_state` ctor.)

- I don't quite see yet why passing arguments to the state constructor is something CAF does automagically for me. From the source of `stateful_actor`:

     ```cpp
  template <class T>
  typename std::enable_if<std::is_constructible<State, T>::value>::type
  cr_state(T arg) {
    new (&state_) State(arg);
  }
    ```

    The unit tests don't show how this is used. I doubt you provided that overload because I makes my use case fly, no? :wink:

**Comment by Neverlord** [comment]
> Why do you use an `event_based_actor` in the ctor of `my_state`?

There's no particular reason. When writing `stateful_actor<my_state>`, you'll get an event-based actor, so you can as well catch the more derived pointer.

> I don't quite see yet why passing arguments to the state constructor is something CAF does automagically for me.

CAF will try to construct the state with a pointer to the actor. If such a constructor does not exist, CAF assumes a default constructor. There's really no magic involved here. ;)

The actor constructs the state right before it calls `make_behavior`, so there's no way to inject extra constructor arguments or something along those lines.

**Comment by mavam** [comment]
> CAF will try to construct the state with a pointer to the actor. If such a constructor does not exist, CAF assumes a default constructor.

Yes, I observed that. My question was rather: what is the use case that *you* had in mind where having actor pointer as first argument is convenient. Where you anticipating that many people use stateful actor in this way? I am asking because I couldn't find a scenario within CAF where this is used and provides benefit. (I didn't look beyond unit tests, though.)

**Comment by Neverlord** [comment]
> My question was rather: what is the use case that you had in mind where having actor pointer as first argument is convenient. Where you anticipating that many people use stateful actor in this way?

Yes, I did anticipate this and I'm using this in CAF (e.g. for BASP).
