### ISSUE TITLE
Evaluate timeouts in receive functions

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#294]
The blocking API currently does not evaluate timeouts. This bug needs to be fixed.

**Comment by Neverlord** [comment]
Specifically `receive_loop` and friends.

**Comment by Neverlord** [comment]
I'm sorry. I did not pay enough attention to this. The original question to this was how to skim through a mailbox and my answer was "use a receive loop". This is the equivalent of installing a behavior in an event-based actor:

```cpp
behavior eager_actor(event_based_actor* self) {
  return {
    [](int i) { /* ... */ },
    after(std::chrono::seconds(10)) >> [] {
      aout(self) << "received nothing within 10 seconds..." << endl;
      // ...
    }
  };
}
```

However, the the behavior is *not* removed once a timeout occurs. The code above would print "received nothing within 10 seconds..." every ten seconds if no other message is ever received. The receive loops work in the same way.

This was your original question:

> Is there a version of `receive` that consumes all messages in the mailbox and unblocks when it's done? For non-blocking actors, I would just add 0-timeout.

In event-based actors you would still need to call `unbecome()` in the 0-timeout. In blocking actors, this is what you could do:

```cpp
bool timeout_occurred = false;
self->do_receive(
  [](int i) { /* ... */ },
  after(std::chrono::seconds(10)) >> [&] {
    aout(self) << "received nothing within 10 seconds..." << endl;
    timeout_occurred = true;
  }
).until([&] { return timeout_occurred; });
```

**Comment by mavam** [comment]
> In event-based actors you would still need to call unbecome() in the 0-timeout. In blocking actors, this is what you could do

I see. Could I still use a 0-zero timeout as a means to consume all mailbox entries (modulo scheduler throughput) of, say, type `int`? Would this snippet work?

```cpp
bool got_nothing = false;
auto sum = 0;
self->do_receive(
  [](int i) { sum += i; },
  after(std::chrono::seconds(0)) >> [&] {
    got_nothing = true;
  }
).until([&] { return sum > 0 || got_nothing; });
```

**Comment by Neverlord** [comment]
Your snipped would stop a the first message (`sum > 0`). The 0-timeout gets invoked once you hit the end of the mailbox, so `got_nothing` suffices.

**Comment by mavam** [comment]
Ah, sure.
