### ISSUE TITLE
Bug in shortcut-version of options parser

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#295]
The sneaked-in shortcut notation does not work properly:

````
fails:
./build/bin/caf-test -v5 -s spawn

works:
./build/bin/caf-test -s spawn -v5
```

**Comment by mavam** [comment]
My apologies. :disappointed:

In addition to the fix, I've beefed up the unit tests...which I should have done in the first place.

**Comment by Neverlord** [comment]
At least we caught the bug before the feature went live in `master`. :)
