### ISSUE TITLE
Provide Linux Packages

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#301]
Setting up CAF on, e.g., https://build.opensuse.org/

**Comment by firegurafiku** [comment]
Okay, this seems to be doable. I've just built my first RPM for `libcaf_core` using OBS.

So I'd like to discuss some information about packages structure and naming. As far as I can judge, we need a bunch of packages:

* `libcaf_core-VER.rpm` (for `/usr/lib/libcaf_core*`)
* `libcaf_core-devel-VER.rpm` (for headers of core library only)
* `libcaf_core-examples-VER.rpm` (for examples of core only)
* `libcaf_core-doc-VER.rpm` (for Doxygen generated from core sources only)

and the same stuff for `libcaf_io`, `libcaf_riac`, `libcaf_opencl`. I not sure what to to with `nexus` and `cash` things, because I've never built CAF with them yet.

Unfortunately, where is some mess with examples (they require both `libcaf_core` and `libcaf_io`, and some of them also Qt and Protocol Buffers), and Doxygen (there is a single Doxyfile for the entire repository). So we may prefer having just `libcaf-examples-VER.rpm` and `libcaf-doc-VER.rpm` not related to exact subproject. Or just omit them for now.

So, the questions are:

* Which way would you prefer to deal with `-doc` and `-examples`,
* Shouldn't we use dashed instead of underscores in `libcaf_core-various-stuff`?

**Comment by firegurafiku** [comment]
Another question.
We can trigger build on OBS using GutHub web hooks. But I'm *very* unpleasant with the idea to trigger a clear rebuild and repack after *every* single commit. 

* Maybe we should trigger only for version tags or selected branch?
* Maybe it's better to use Jenkins to trigger that repack instead of GitHub?

**Comment by Neverlord** [comment]
Thank you very much for tackling this. Packaging is very tedious, so this is much appreciated! :)

I propose the following package layout based on the packaging of Boost etc.:

```
legend:
<   depends
+   includes
:   provides

caf
  + libcaf_core
  + libcaf_io
  + libcaf_io_asio
  + libcaf_opencl
  + libcaf_test
caf-devel < caf : all-headers
caf-doc-html : HTML-manual & Doxygen-generated-documentation
caf-doc-pdf : PDF-manual
libcaf_core : libcaf_core<version>.so
libcaf_io < libcaf_core : libcaf_io<version>.so
libcaf_io_asio < boost < libcaf_core : libcaf_io_asio<version>.so
...
```

> and the same stuff for `libcaf_io`, `libcaf_riac`, `libcaf_opencl`. I not sure what to to with `nexus` and `cash` things, because I've never built CAF with them yet.

The RIAC tools are still early alpha, so maybe we should skip them for now.

> We can trigger build on OBS using GutHub web hooks. But I'm *very* unpleasant with the idea to trigger a clear rebuild and repack after *every* single commit. 
> 
> * Maybe we should trigger only for version tags or selected branch?
> * Maybe it's better to use Jenkins to trigger that repack instead of GitHub?
> * How to trigger "nightly" packages build?

Triggering nightly builds via Jenkins definitely seems like the way to go. This also makes sure that only tested commits get shipped.

> Unfortunately, there is some mess with examples (they require both `libcaf_core` and `libcaf_io`, and some of them also Qt and Protocol Buffers), and Doxygen (there is a single Doxyfile for the entire repository). So we may prefer having just `libcaf-examples-VER.rpm` and `libcaf-doc-VER.rpm` not related to exact subproject. Or just omit them for now.

I think the examples are not worth shipping. I agree that there's a mess with dependencies, but they don't offer any utility other than providing source examples. Any developer interested in the examples should be able to find them via the documentation (adding a link to the manual in the "getting started" part is probably a good idea).

**Comment by firegurafiku** [comment]
@Neverlord 
@mavam 

Hi! I've tried to resemble your scheme within OBS and succeeded with Fedora, RHEL and CentOS, but SuSE distros have a very strict policy about `SONAMEs` and their RPMLint complains a lot. They want me to name library packages to reflect the whole `SONAME`. But according to the following 
```
$ readelf -a build/lib/libcaf_core.so.0.13.2 | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libcaf_core.so.0.13.2]
```
I would have to rename `libcaf_core` to `libcaf_core0.13.2` to accommodate SuSE's requirements. We try to keep library backward-compartible, so should we really have such a strict `SONAME` policy? Maybe the first digit would be enough?

BTW, the project is currently here: https://build.opensuse.org/package/show/home:firegurafiku:caf/caf.
I especially want you to take a look on a [build log for ARM arch][log], where library builds but some tests fail.

[log]: https://build.opensuse.org/package/live_build_log/home:firegurafiku:caf/caf/openSUSE_Factory_ARM/armv7l

**Comment by Neverlord** [comment]
We set the `SONAME` to the full version in our current CMake setup. In the future it might be a good idea to guarantee ABI compatiblity as long as `MAJOR.MINOR` is equivalent. Right now we have no policy to enforce this.

To avoid runtime errors due to ABI-breaking changes, I would for now just the full version as `SONAME`. That's what I meant with:

```
libcaf_core : libcaf_core<version>.so
```

> They want me to name library packages to reflect the whole SONAME. But according to the following

Does that mean you cannot provide a version-independent package name at all? As long as `zypper install caf` can redirect to latest version I'd say it's good enough. I don't expect many users to individually pick library components.

**Comment by firegurafiku** [comment]
> Does that mean you cannot provide a version-independent package name at all?

No, I can. But then we cannot expect it to be ever included into SuSE-based distros. Currently, I have configured a successful build by suppressing that `rpmlint` error.

But there is another thing I would like to ask you about. Can I safely suppress the following warning too?
```
libcaf_io.i586: W: shared-lib-calls-exit /usr/lib/libcaf_io.so.0.13.2 exit@GLIBC_2.0
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.
```

**Comment by Neverlord** [comment]
> No, I can. But then we cannot expect it to be ever included into SuSE-based distros. Currently, I have configured a successful build by suppressing that `rpmlint` error.

Is there maybe a difference in SuSE for meta packages? The official SuSE repository does have meta packages without version numbers:

```
~ $ zypper search boost-devel
Loading repository data...
Reading installed packages...

S | Name              | Summary                           | Type   
--+-------------------+-----------------------------------+--------
i | boost-devel       | Development package for Boost C++ | package
  | boost-devel-32bit | Development package for Boost C++ | package
```

Maybe `rpmlint` is just overly verbose here?

> But there is another thing I would like to ask you about. Can I safely suppress the following warning too?

Yes, CAF calls `exit` only for non-recoverable errors. Not being able to initialize epoll for example. Maybe we should instead call `abort()` or `std::terminate()` instead: I'm not sure what's the preferred policy for Linux/C++ here, to be honest.

**Comment by firegurafiku** [comment]
> Maybe rpmlint is just overly verbose here?

No, it's the policy of SuSE project. Try searching `libboost*` instead, you should see versions as part of each of individual library of Boost (like `libboost_atomic_1_58_0`). Their [RPM spec file](https://build.opensuse.org/package/view_file/openSUSE:Factory/boost/boost.spec?expand=1) states so. Fedora, for example, has different name convention.

> `libcaf_io_asio < boost < libcaf_core : libcaf_io_asio<version>.so`

Maybe we should better depend on plain `asio-devel` instead of Boost?

**Comment by Neverlord** [comment]
> No, it's the policy of SuSE project. Try searching `libboost*` instead, you should see versions as part of each of individual library of Boost (like `libboost_atomic_1_58_0`). Their [RPM spec file](https://build.opensuse.org/package/view_file/openSUSE:Factory/boost/boost.spec?expand=1) states so. Fedora, for example, has different name convention.

I can see why they would complain for a `lib...` package without version number. But it should recognize meta packages IMO and not complain in this case. Anyway, it seems to work and that's all that counts.

> Maybe we should better depend on plain asio-devel instead of Boost?

The non-Boost version of ASIO uses a different namespace, so this won't work.

**Comment by firegurafiku** [comment]
@Neverlord 

BTW, do you have Doxygen, LaTeX and Hevea installed on your Jenkins instances?

**Comment by Neverlord** [comment]
How could we integrate our Jenkins builds with OBS? The prebuild PDF manual is already part of the main repository, so we could just include the HTML version of the manual.

**Comment by firegurafiku** [comment]
> so we could just include the HTML version of the manual.

Please, no! I've written a shell script to ease interaction with OBS from within of Jenkins. As I see the problem, it should be as simple as issuing the following series of commands:

     $ make
     $ make test
     $ make doc                          <-- this is a necessary step!
     $ obs-commit-version.sh --release   <-- for release build
     -or-
     $ obs-commit-version.sh --nightly   <-- for nightly build

The script will automatically pick up version from `config.hpp`, prepare source tarball and adjust version number into OBS spec files.

**Comment by firegurafiku** [comment]
@Neverlord 

I've just [requested][1] `devel:libraries:caf` namespace from OBS team. And I think that you, as the project owner, should create an OBS account too, in order to trigger OBS builds from your Jenkins and generally make package maintaining more bus-proof.

[1]: https://bugzilla.opensuse.org/show_bug.cgi?id=933860

**Comment by Neverlord** [comment]
> Please, no! Just install Doxigen, LaTeX and Hevea into your Jenkins image :)

All right, then. Makes indeed more sense. :)

I'll setup one VM for building the documentation. We don't have a single image, btw, because we have a variety of systems and only one VM for each system we support.

**Comment by firegurafiku** [comment]
Good news: OSC satisfied my namespace request.
Now we have two projects:

* [`devel:libraries:caf/caf`][1] for release builds, I'll deal with this manually.
* [`devel:libraries:caf:nightly/caf`][2] for nightly builds, this would be automatically updated by Jenkins.

[1]: https://build.opensuse.org/package/show/devel:libraries:caf/caf
[2]: https://build.opensuse.org/package/show/devel:libraries:caf:nightly/caf

@Neverlord

I see next steps like the following:
* You register another account for you and/or for your Jenkins.
* I transfer project ownership to you.
* You install [`osc`][osc] tool into the Jenkins image.
* You configure Jenkins to commit nightly builds with the [script I wrote][script]. You should also configure `osc` to use your credentials, like this:
```text
$ cat >> ~/.oscrc
[https://api.opensuse.org]
user = USERNAME
pass = PASSWORD
^D
```

[osc]: https://packages.debian.org/wheezy/osc
[script]: https://gist.github.com/firegurafiku/6567488cdcaaae4a56c7

**Comment by Neverlord** [comment]
Awesome news!

> devel:libraries:caf/caf for release builds, I'll deal with this manually.

I think that's ok for the first release. In the long run, we really want to have everything running smoothly and automated. I'll make a new account for me and Jenkins and get back to you.

**Comment by mavam** [comment]
> Awesome news!

:+1:

**Comment by firegurafiku** [comment]
@Neverlord 
@mavam 

Help me, guys. For packaging I must provide short and long descriptions of each package component. Currently, my descriptions are as following, please, check if they're okay, and propose something for OpenCL. Any additions are also welcome.

> **caf:** C++ actor framework
> CAF is an open source C++11 actor model implementation featuring lightweight & fast actor implementations, pattern matching for messages, network transparent messaging, and more.
>
> **libcaf_core:** C++ actor framework: core library
> This library contains basic support for class-based and function-based actors, typed and untyped. It also provides atoms and pattern matching facilities as well as some other helper classes.
> 
> **libcaf_io:** C++ actor framework: IO library
> Allows actors to communicate via TCP/IP network. Also contains optional Boost.ASIO backend.
>
> **libcaf_opencl:** C++ actor framework: OpenCL support library
> TEST
>
> **caf-devel:** C++ actor framework: header files
> C++ header files for all "libcaf_*" packages for application development using CAF. This package will also install all of them.
> 
> **caf-doc:** C++ actor framework: documentation in HTML format
> This package includes documentation for CAF developer, available in HTML or plain text format. This includes README and LICENSE files, reference documentation, generated by Doxygen, and current version of programmer's manual.
>
> **caf-doc-pdf:** C++ actor framework: documentation in PDF format
> This package includes documentation for CAF developer, available in PDF format. This includes current version of programmer's manual.

**Comment by Neverlord** [comment]
That's what I propose (note: `caf-doc -> caf-doc-html`):

**caf**: C++ actor framework
CAF is an open source C++11 actor model implementation featuring lightweight & fast actor implementations, pattern matching for messages, network transparent messaging, and more.

**libcaf_core**: Run-time component of CAF's core library
The core library of CAF provides all components necessary for concurrent applications. This includes lightweight actor implementations running in an efficient user-space scheduler.

**libcaf_io**: Run-time component of CAF's IO library
The IO library of CAF enables distributed applications and adds so-called brokers that enable message-driven network IO.

**libcaf_opencl**: Run-time component of CAF's OpenCL binding
The OpenCL-binding enables heterogeneous applications by creating actors directly from OpenCL Kernels. Any messaging between CPU- und GPU-bound actors is transparently forwarded by the runtime of CAF and no manual OpenCL management is required.

**caf-devel**: Development package for CAF
This package contains all headers and libraries needed to develop/compile applications that use CAF.

**caf-doc-html**: HTML documentation for CAF
This package contains the documentation of CAF in HTML format, including a user manual and a Doxygen-generated class reference.

**caf-doc-pdf**: PDF documentation for CAF
This package contains a printer-friendly PDF version of the CAF user manual.
