### ISSUE TITLE
Typed Brokers

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#309]
Brokers are currently always dynamically typed, which is only due to historic reasons (brokers existed before typed actors). The interface to the MM needs to be re-shaped to allow typed brokers as well.

**Comment by Neverlord** [comment]
Closed via #311.

**Comment by Neverlord** [comment]
I gave this some thought and the brokers are currently not "100% type safe". Brokers can receive any message type from the [system_messages header](https://github.com/actor-framework/actor-framework/blob/master/libcaf_io/caf/io/system_messages.hpp). So either we make it mandatory for all typed brokers to handle *all* of these messages or we restrict what a typed broker is allowed to to based on its type.

The former is straightforward to implement, but would mean that an average typed broker would have quite a lot of empty message handlers, which is not idea. The latter requires probably quite a lot of tweaking... For example, `add_doorman()` would need a static assertion that the broker is able to receive `new_connection_msg`. The `spawn_io_*` family would need similar checks. So this might turn out to be quite a lot of work.

In any case, it is probably a good idea to move the typed brokers to an `experimental` namespace in the meantime.

**Comment by ufownl** [comment]
Good suggestion! I'll look into and try to improve it. :)

**Comment by ufownl** [comment]
@Neverlord There is a problem.
If the broker is used as client, it only need to handle `new_data_msg` and `connection_closed_msg`. But if it's used as server, I can't determine whether or not it should handle `new_data_msg` and `connection_closed_msg`.

**Comment by Neverlord** [comment]
Yes, it's definitely tricky. My idea was to restrict access to `add_broker` and `add_doorman` based on the defined interface. An actor without `new_data_msg` would not be allowed to add any scribe. This only works if we have a CRTP base for the typed broker or if we move those function into the broker directly. It's not going to be pretty in any case.

**Comment by ufownl** [comment]
> An actor without `new_data_msg` would not be allowed to add any scribe.

When the broker is used as server, adding scribes is inevitable. But if we fork all of the connections, it doesn't need handle `new_data_msg` and `connection_closed_msg`.

**Comment by Neverlord** [comment]
That's right. So we might end up just enforcing all message handlers on all typed actors.

**Comment by Neverlord** [comment]
@ufownl do you still see any need for action here or can we close this via #317?

**Comment by ufownl** [comment]
I think we can close this. :)

**Comment by Neverlord** [comment]
:+1:
