### ISSUE TITLE
Use different network IO backend on Windows?

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#312]
It appears that `WSApoll` is buggy: http://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/

**Comment by grahamreeds** [comment]
To be honest I wouldn't bother.  Something very similar to asio will appear in c++20 (possibly 23).  If it would simplify/reduce complexity I would rip out the Windows own stuff and just go with asio.

**Comment by Neverlord** [comment]
I'd like to agree, but...

Let's say they manage to ship in C++20. We need to give our user base a sufficient grace period when it comes to compiler compatibility. This means we have to wait another 2-4 years before all major Linux distributions and compilers (and in turns CAF users) have moved to the new C++ goodness. At best, we can make use a standard C++ networking interface in 2022. That's too long if `WSApoll` is in fact broken. That being said, I cannot tell whether CAF is affected by the `WSApoll` bug. We are not using Windows actively for development. All we can say is that unit tests pass and no one complained about CAF bugs on Windows so far. 

Furthermore, if performance turns out to be a problem on any system (e.g. because `epoll`/`kpoll`-based solutions outperform the new C++ API) then we should rely on platform-dependent networking code regardless.

**Comment by Neverlord** [comment]
2022 and no networking in sight. C++23 may ship networking or it may not. Probably not.

ASIO isn't just sockets and networking, it's a whole concurrency model and it seems like the committee is very uncomfortable with committing to something like that. Because once that's in the standard, it has to run everywhere and has to make sense in every environment (including printers and toasters).

**Comment by Neverlord** [comment]
No one actually complained about this in the past 8 years, so it seems like it's not an issue for CAF. Closing.
