### ISSUE TITLE
caf::io::network::protocol causing conflict on riac::anounce_message_types()

### ISSUE THREAD

**Issue by admsyn** [actor-framework/actor-framework#313]
This occurs on OS X, Xcode 6.3.2
```c++
#include "caf/all.hpp"
#include "caf/io/all.hpp"
#include "caf/riac/all.hpp"
 
int main(int argc, const char * argv[]) {
 
	caf::riac::announce_message_types();
	caf::riac::init_probe("localhost", 1234);
	
	// just waiting to make the error message show up in the console
	caf::await_all_actors_done();
	caf::shutdown();
	
    return 0;
}
 
// Output:
//
// [ERROR] NONE::uniform_typeid: uniform_typeid(): N3caf2io7network8protocolE has not been announced
//
```

[As mentioned in chat](https://gitter.im/actor-framework/chat?at=555de9a3d3bef97f1b596cfd):
> Neverlord: @admsyn that's a conflict with riac::protocol and io::network::protocol. I'll look into this once I get the riac examples running again.

**Comment by ufownl** [comment]
I have tried removing `riac::protocol` and using `io::network::protocol` in riac, it worked fine.

**Comment by Neverlord** [comment]
Thanks for making the issue. I almost forgot about this. Fixed in develop.
