### ISSUE TITLE
Forwarding to and from typed actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#319]
The current facility for forwarding messages (`forward_to`) does only cover dynamically typed actors. This should be extended to allow forwarding to and from typed actors, e.g. with an API like this:

```cpp
// inside a typed actor
[](int a, int b, int c) -> typed_response_promise<int> {
  return delegate(buddy, a + b, b + c);
}
```

Note that the forwarded message is not necessarily the received message. This enables a much more flexible way of forwarding. The return type of `delegate` is a typed response promise to verify the guarantee type safety in statically typed actors.

**Comment by mavam** [comment]
How does this forward the current message? It seems you're taking the data from an existing message to construct a new one. I assume `delegate` passes through the message ID so that responses make it back to the original sender. Perhaps a call to `delegate(buddy)` would simply forward `current_message()`?

**Comment by Neverlord** [comment]
> I assume `delegate` passes through the message ID so that responses make it back to the original sender.

Yes.

> Perhaps a call to `delegate(buddy)` would simply forward `current_message()`?

This is not possible in a type-safe way. Otherwise we could just tweak `forward_to` to behave this way. The problem is that the calling side of `forward_to` does not have the necessary type information and only sees the type-erased `current_message()`. `delegate` would add an alternative that works for type-safe actors as well and also adds more flexibility, since it allows actors to "enrich" a message before forwarding it. With `move`-aware data, this can also be quite cheap.
