### ISSUE TITLE
Q: Why Eigen matrices work?

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#321]
Hi again.
Not so long time ago we had discussed using Eigen matrices as CAF datatypes and had come to conclusion that each individual instantiation of `Eigen::Matrix` needed its own announcement. But today I've decided to actually write that announcement, made a unit test for this and prepared myself for its failure. But it worked. Did I miss something? Or 0.14 comes with lots of magic bundled? :)

```cpp
#include <eigen3/Eigen/Dense>
#include <caf/all.hpp>
#include <boost/test/unit_test.hpp>
using namespace caf;
using namespace Eigen;

behavior mirror(event_based_actor* self) {
    return {
        [=](const Matrix<double,21,31>& m) -> Matrix<double,31,21> {
            self->quit();
            return m.transpose();
        }
    };
}

void hello_world(event_based_actor* self, const actor& buddy) {
    Matrix<double,21,31> m;
    m.setRandom();

    self->sync_send(buddy, m).then(
        [=](const Matrix<double,31,21>& tm) {
            BOOST_REQUIRE_EQUAL(tm, m.transpose());
        }
    );
}

BOOST_AUTO_TEST_CASE(TestEigenInCaf) {
    auto mirror_actor = spawn(mirror);
    spawn(hello_world, mirror_actor);
    await_all_actors_done();
    shutdown();
}
```

**Comment by Neverlord** [comment]
As long as you stay in one process, no serialization will ever take place. That's why you can get away with not announcing types in this scenario. Once you distribute your application, you will have to make it serializable by announcing it.

**Comment by firegurafiku** [comment]
Aaaa... Thank you for explanation.
So, writing the right unit test for this becomes painful. Is there an option of some kind to force serialization even if direct copy can be taken?

**Comment by Neverlord** [comment]
Writing unit tests using two processes is actually not that hard with CAF's tool box. Have a look at the IO unit tests, for example [typed_remote_actor](https://github.com/actor-framework/actor-framework/blob/develop/libcaf_io/test/typed_remote_actor.cpp). The unit test opens some port and then creates a new process using `detail::run_program` connecting to it. Maybe boost has some equivalent for this functionality (in case you don't like using `detail`s from CAF).

**Comment by firegurafiku** [comment]
Hm. If I just `fork()` the unit-testing process, will it work?

**Comment by Neverlord** [comment]
If you're going for a `fork`-based approach, I would suggest to fork *before* calling any CAF function to be on the safe the side. Make a pipe to connect child and parent, then fork and tell the child process via the pipe where to connect to. Should work this way. I'm not sure if it would work once you have published an actor though (I'm not a `fork`-expert though).
