### ISSUE TITLE
Scheduler policies with less CPU usage

### ISSUE THREAD

**Issue by j6lim** [actor-framework/actor-framework#326]
work stealing scheduler performs great with tasks with complex dependency but it drains cpu heavily because idle threads do not rest and try to steal tasks too many times. For mobile device it is a problem because it increases CPU usage about 3x times.

For tasks with simple dependency graph (ex. 1 interface actor + 2~4 worker actors which communicates only with the interface actor) greedy scheduling or work shared scheduling would be sufficient and use less cpu to prevent battery draining. It will be good to have those schedulers so users can choose in favor of thier use cases.

**Comment by Neverlord** [comment]
@Hamdor seems ok after the fixes. Please rebase/squash and commit to `develop`
