### ISSUE TITLE
CAF_ERROR Macro for Unit Tests

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#330]
The unit test framework of CAF currently has no macro function for creating error (`CAF_LOG_ERRORS` only prints an error, but the unit test still yields 100% success rate).

**Comment by mavam** [comment]
Yeah, the `CAF_(MESSAGE|VERBOSE|INFO|ERROR|...)` macros only do logging; they map simply to a severity level. How about `CAF_FAIL` for an error message that also results in aborting the current test (but doesn't bail out completely like `CAF_REQUIRE`)?

**Comment by Hamdor** [comment]
`CAF_FAIL` or `CAF_FAILURE` sounds good. In my opinion just the current test should be aborted.
