### ISSUE TITLE
OSX Build issue

### ISSUE THREAD

**Issue by bowlofstew** [actor-framework/actor-framework#342]
I am observing some interesting build behavior on OSX starting at commit 7ede7f2af53a0a1b0f4d148f8197e4d92a2e92b5.  Prior to that commit (example: d9e99842449752ec777beca1c21aff1c45a5008b), it appears to be building fine.

Here is a link to both files showing the behavior, https://www.amazon.com/clouddrive/share/1ZQvFDOicY19fMGjgEiHC50tdkYjCqwHtFbdmyFFsRb?ref_=cd_share_link_copy

Is this expected behavior?  If not, I can dive in and investigate further.

**Comment by Neverlord** [comment]
This issue seems to be not related to OSX, see #347.
