### ISSUE TITLE
Create first-class abstraction for typed state machines

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#345]
FSMs are a common type of actor. The current `typed_actor` is not conducive to expressing FSMs, however: one has to implement the union of all handlers in all states, using `skip_message` to forego irrelevant messages. Not only is this cumbersome to write, but it also induces a performance penalty for each handler invocation.

@Neverlord proposed a straw-man interface in the chat:

``` cpp
using handle = typed_actor<replies_to<put, int>::with<void>>;
struct state {
  vector<int> values;
};
using pointer = handle::stateful_pointer<state>;
handle::behavior_type empty(pointer) { ... }
handle::behavior_type filled(pointer) { ... }
handle::behavior_type full(pointer) { ... }
handle make_fsm() {
  fsm_builder<state> fb;
  // transition: from, to, guard
  fb.init_state(empty)
    .transition(empty, filled, [](state* s) { return ! s->values.empty(); })
    .transition(filled, empty, [](state* s) { return s->values.empty(); })
    .transition(filled, full, [](state* s) { return s->values.size() == 10; })
    .transition(full, filled, [](state* s) { return s->values.size() < 10; })
    .entry_action(empty, [](state* s) { cout << "entering empty state"; })
    .exit_action(empty, [](state* s) { cout << "leaving empty state"; })
    .entry_action(filled, [](state* s) { cout << "entering filled state"; })
    // ...
    ;
  return fb.make();
}
```

This still needs further thought, because the states should not receive an actor pointer, which would allow them to change their behavior violating the transition declarations.

**Comment by Neverlord** [comment]
Still a neat idea, but I don't see much demand for a feature like this TBH. No one pushed for it and I don't think anyone wants to invest cycles here, so I'm closing this.
