### ISSUE TITLE
Fix `profiled_coordinator` on Linux

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#346]
The `profiled_coordinator` uses `getrusage` which seems to be too coarse grained on Linux. As a result, the generated output on Linux is pretty much useless.

**Comment by mavam** [comment]
The [manpage for getrusage](http://man7.org/linux/man-pages/man7/time.7.html) says:
```
 The software clock, HZ, and jiffies
       The accuracy of various system calls that set timeouts, (e.g.,
       select(2), sigtimedwait(2)) and measure CPU time (e.g., getrusage(2))
       is limited by the resolution of the software clock, a clock
       maintained by the kernel which measures time in jiffies.  The size of
       a jiffy is determined by the value of the kernel constant HZ.

       The value of HZ varies across kernel versions and hardware platforms.
       On i386 the situation is as follows: on kernels up to and including
       2.4.x, HZ was 100, giving a jiffy value of 0.01 seconds; starting
       with 2.6.0, HZ was raised to 1000, giving a jiffy of 0.001 seconds.
       Since kernel 2.6.13, the HZ value is a kernel configuration parameter
       and can be 100, 250 (the default) or 1000, yielding a jiffies value
       of, respectively, 0.01, 0.004, or 0.001 seconds.  Since kernel
       2.6.20, a further frequency is available: 300, a number that divides
       evenly for the common video frame rates (PAL, 25 HZ; NTSC, 30 HZ).

       The times(2) system call is a special case.  It reports times with a
       granularity defined by the kernel constant USER_HZ.  User-space
       applications can determine the value of this constant using
       sysconf(_SC_CLK_TCK).

 High-resolution timers
       Before Linux 2.6.21, the accuracy of timer and sleep system calls
       (see below) was also limited by the size of the jiffy.

       Since Linux 2.6.21, Linux supports high-resolution timers (HRTs),
       optionally configurable via CONFIG_HIGH_RES_TIMERS.  On a system that
       supports HRTs, the accuracy of sleep and timer system calls is no
       longer constrained by the jiffy, but instead can be as accurate as
       the hardware allows (microsecond accuracy is typical of modern
       hardware).  You can determine whether high-resolution timers are
       supported by checking the resolution returned by a call to
       clock_getres(2) or looking at the "resolution" entries in
       /proc/timer_list.

       HRTs are not supported on all hardware architectures.  (Support is
       provided on x86, arm, and powerpc, among others.)
```

So unless you're using HRTs (check `/proc/timer_list`), you're stuck in milliseconds land. We could make the availability of the profiler dependent on HRTs.

**Comment by Neverlord** [comment]
> We could make the availability of the profiler dependent on HRTs.

That's not an option. We need this to run on our 64 core benchmark machine, which runs Linux and produces garbage output currently. So... whatever it takes (reading proc file system or using Linux kernel calls), we need to find a way.

**Comment by mavam** [comment]
It will probably boil down to reading `/proc`. In particular `/proc/[PID]/task/[TID]/stat` contains a per-thread summary of what's also available process-wide via `/proc/[PID]/stat`. The `stat` output includes fields for user time, system time, and RSS. This is all that the profiler needs.

**Comment by Neverlord** [comment]
Jiffies are used by the kernel to update the `/proc/` file system. In other words, reading `/proc/.../stat` only gives you time values with tick resolution: http://man7.org/linux/man-pages/man5/proc.5.html

This is extremely annoying. Also, the high resolution timers in Linux only give you a way to get high-resolution timestamps, but I see no way how to get separate sys/user times in higher resolution.

**Comment by mavam** [comment]
> Also, the high resolution timers in Linux only give you a way to get high-resolution timestamps, but I see no way how to get separate sys/user times in higher resolution.

We could fall back to [clock_gettime](http://man7.org/linux/man-pages/man2/clock_gettime.2.html) with `CLOCK_THREAD_CPUTIME_ID`. While this would enable high-resolution CPU time measurements, it wouldn't allow for differentiating user and system contributions.

**Comment by Neverlord** [comment]
Yes, I've found that function too. The question is: is there any way to get sys/user time on Linux on a reasonable resolution? Not having this information on Linux would make the `profiled_coordinator` a lot worse, as it completely hides away I/O and synchronization bottlenecks (although in theory actors shouldn't do IO, but that's a different matter).

**Comment by mavam** [comment]
> The question is: is there any way to get sys/user time on Linux on a reasonable resolution? 

I'm presently not aware of any other mechanism. If you have no control over the kernel (to enable HRT), the answer to your question is most likely *no*.

**Comment by Neverlord** [comment]
HRT is already enabled. The problem is that the `/proc` file system is still bound to the jiffies. HRT only gives you high resolution in calls like `clock_gettime`. I understand that they can't change the format of `/proc/[PID]/task/[TID]/stat` for compatibility reasons, but there's no high-resolution alternative either. *sigh*
