### ISSUE TITLE
Support move-only types for functional spawn

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#348]
It's currently impossible to pass spawn arguments which are move-only types, such as  `std::unique_ptr`. This restriction should be relaxed to allow for ownership passing semantics at spawn time.

**Comment by Hamdor** [comment]
Small example given:
```c++
#include <caf/all.hpp>
#include <memory>

using namespace std;
using namespace caf;

void uptr_actor(event_based_actor* self, unique_ptr<int> uptr) {
  self->quit();
}

int main() {
  unique_ptr<int> uptr = make_unique<int>(42);
  auto act = spawn(uptr_actor, move(uptr));
  await_all_actors_done();
  shutdown();
}
```

**Comment by mavam** [comment]
Any progress on this so far?

**Comment by Neverlord** [comment]
I'm afraid not.

**Comment by Neverlord** [comment]
@mavam enjoy ;)

**Comment by mavam** [comment]
Wow, thanks for the prompt delivery! I should keep bugging you more often. :wink:
