### ISSUE TITLE
How to send typed actors across network

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#349]
I've encountered an issue (-> hanging) when sending typed actors over the network.

1. When replacing the problematic statements with the commented code the example "works".
2. The line marked with `:-(` has no effect: the client fails to shutdown the server remotely. I'm not sure if this a bug or a feature.

```cpp
#include <iostream>

#include <caf/all.hpp>
#include <caf/io/all.hpp>

using namespace caf;
using namespace std;

struct state {
  state(local_actor*) { }
};

using actress_type = typed_actor<reacts_to<int>>;

auto director(actress_type a) -> behavior {
  return {
    others >> [=] {
      //return make_message(actor_cast<actor>(a));
      return make_message(a);
    }
  };
}

auto actress(actress_type::stateful_pointer<state> self) 
  -> actress_type::behavior_type {
  return [=](int i) {
    cout << i << endl;
    self->quit();
  };
}

auto main(int argc, char** argv) -> int {
  scoped_actor self;
  if (argc < 2) {
    auto a = self->spawn(actress);
    io::publish(self->spawn(director, a), 42000);
    cerr << "at your service" << endl;
  } else {
    auto d = io::remote_actor("localhost", 42000);
    self->sync_send(d, "my lady, please").await(
      //[&](const actor& a) {
      [&](const actress_type& a) {
        self->send(a, 42);
        self->send_exit(d, exit_reason::normal); // :-(
      }
    );
  }
  self->await_all_other_actors_done();
}
```

To reproduce, compile and then run as follows:
```sh
./aout # server
./a.out whaterver # client
```

Tested on OS X.

**Comment by ufownl** [comment]
Because actors ignore `exit_reason::normal` sent by other actors, so I think if you change the exit reason such as `exit_reason::kill`, it will work fine.

**Comment by ufownl** [comment]
I'm so sorry, I made a mistake, the remote actor seems be different than local actor when receiving a `exit_msg`.

**Comment by mavam** [comment]
> I'm so sorry, I made a mistake, the remote actor seems be different than local actor when receiving a exit_msg.

What do you mean by "seems [to] be different"? Have you tested the example code? Neither `normal` nor `kill` will send the `director` into his coffin.

> For your first issue, you should announce actress_type.

Duh, now that you mention it I remember that part. I guess I should have looked at the examples. @Neverlord The manual needs an update in this regard: the section about typed actors should highlight the need for announcing actor types. I think it's not obvious that this falls under §15.1.

I also suggest that CAF should provide a better error message in such a scenario, as opposed to simply hanging.

**Comment by ufownl** [comment]
> What do you mean by "seems [to] be different"? Have you tested the example code? Neither normal nor kill will send the director into his coffin.
I mean that the first comment of mine was wrong. After that comment, I tested the example and came to the same result.

**Comment by mavam** [comment]
>  I tested the example and came to the same result.

Ah, got it. Hopefully @Neverlord can shed light into this issue. :dizzy:

**Comment by Neverlord** [comment]
Here comes the light:

```cpp
#include <iostream>

#include <caf/all.hpp>
#include <caf/io/all.hpp>

using namespace caf;
using namespace std;

struct state {
  state(local_actor*) { }
};

using actress_type = typed_actor<reacts_to<int>>;

auto director(event_based_actor* self, actress_type a) -> behavior {
  self->link_to(a);
  return {
    others >> [=] {
      return a;
    }
  };
}

auto actress(actress_type::stateful_pointer<state> self) 
  -> actress_type::behavior_type {
  return [=](int i) {
    cout << i << endl;
    self->quit();
  };
}

auto main(int argc, char** argv) -> int {
  announce<actress_type>("actress_type");
  { // scope for self
    scoped_actor self;
    if (argc < 2) {
      auto a = self->spawn(actress);
      io::publish(self->spawn(director, a), 42000);
      cerr << "at your service" << endl;
    } else {
      auto d = io::remote_actor("localhost", 42000);
      self->sync_send(d, "my lady, please").await(
        [&](const actress_type& a) {
          self->send(a, 42);
          self->send_exit(d, exit_reason::kill); // :-(
        }
      );
    }
    self->await_all_other_actors_done();
  }
  shutdown();
}
```

You forgot to link your actress to the director. That's why she refused to die.

**Comment by ufownl** [comment]
> You forgot to link your actress to the director. That's why she refused to die.

I don't think it is the key of the issue, the actress will quit when it receives a int. And I have reviewed the log, the director didn't receive the `exit_msg`.

**Comment by Neverlord** [comment]
Hm. All I did was adding the `link_to`, the `announce`, the scope around `self`, and `shutdown` at the end. If you send a message to a remote actor without calling `shutdown` at the end, this message might get lost, since you simply don't wait until the data reached its destination.

**Comment by ufownl** [comment]
Got it! `shutdown` is the key. :)

**Comment by mavam** [comment]
> Got it! shutdown is the key. :)

Glad we got that sorted out. :+1:
