### ISSUE TITLE
Support array members in `announce`

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#350]
From the mailing list:

> I'm attempting to send messages including Boost uuids over a network using CAF:
    caf::announce<uuid>("uuid", &ID::data);
However, ID::data is a uint8_t[], and I get the error:
libcaf_core/caf/uniform_type_info.hpp:62:39: error: array used as initializer
         value_(std::forward<Ts>(xs)...) {

**Comment by tbenthompson** [comment]
Awesome. Thanks Dominik. I'm thinking I will actually work on this. I'll submit a pull request once I have something working. I'll post again if I get stuck or decide to abandon the problem.

**Comment by tbenthompson** [comment]
Just in case it wasn't clear, I am the poster from the mailing list...

**Comment by tbenthompson** [comment]
Further discussion in #351.

**Comment by Neverlord** [comment]
Fixed via https://github.com/actor-framework/actor-framework/commit/1cf9ca9bb644805b22064a094610ff43211d9ba9
