### ISSUE TITLE
Improve support for constructing typed response promises

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#353]
`type_response_promise` lacks a viable constructor to support this pattern:
```cpp
    using P = typed_response_promise<either<T>::or_else<U>>;

    [=](X) -> P {
      return T{};
      // ...
      return U{};
    }
```
The workaround involves creating a `P p` and invoking `p.deliver(T{})`. However, CAF should support the above more idiomatic syntax.

**Comment by Neverlord** [comment]
Automatic conversion from values to promises can get a bit tricky. Especially when considering:

```cpp
using P = typed_response_promise<either<int, double>::or_else<bool, float>>;

[=](X) -> P {
  return ???;
};
```

The "standard" workaround is to return a `std::tuple`, but this gets really ugly quickly.

What about a `make_ready_promise` function converting `T => typed_response_promise<T>`? By allowing implicit conversion from both `typed_response_promise<T>` and `typed_response_promise<U>` to `typed_response_promise<either<T>::or_else<U>>`, this would get close to your proposed syntax:

```cpp
    using P = typed_response_promise<either<T>::or_else<U>>;

    [=](X) -> P {
      return make_ready_promise(T{});
      // ...
      return make_ready_promise(U{});
    }
```

A bit more typing, but at the same time more flexible and deals with multiple return values. I'm not too keen on the name, though. Maybe you have a good idea for a better name.

**Comment by mavam** [comment]
Per our discussion, `return response(x, y, z)` would be my favorite for a name.

**Comment by Neverlord** [comment]
Does anything change for this issue when removing `either<...>::or_else<...>` from the picture?

**Comment by mavam** [comment]
`typed_response_promise` would probably get a non-explicit construct overload for an `error_condition`, no?
