### ISSUE TITLE
Easier error handling

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#367]
Writing message interfaces in CAF 0.14 is quite verbose and repetitive once you start integrating error handling. Also, adding error handling later on is *painful*.

Just consider the current code for the middleman actor:

```cpp
using middleman_actor =
  typed_actor<
    replies_to<publish_atom, uint16_t, actor_addr,
               std::set<std::string>, std::string, bool>
    ::with_either<ok_atom, uint16_t>
    ::or_else<error_atom, std::string>,

    replies_to<open_atom, uint16_t, std::string, bool>
    ::with_either<ok_atom, uint16_t>
    ::or_else<error_atom, std::string>,

    replies_to<connect_atom, std::string, uint16_t>
    ::with_either<ok_atom, node_id, actor_addr, std::set<std::string>>
    ::or_else<error_atom, std::string>,

    replies_to<unpublish_atom, actor_addr, uint16_t>
    ::with_either<ok_atom>
    ::or_else<error_atom, std::string>,

    replies_to<close_atom, uint16_t>
    ::with_either<ok_atom>
    ::or_else<error_atom, std::string>,

    replies_to<spawn_atom, node_id, std::string, message>
    ::with_either<ok_atom, actor_addr, std::set<std::string>>
    ::or_else<error_atom, std::string>>;
```

The only reason `with_either<...>::or_else<...>` exists is to support error handling. However, writing and implementing this turned out to be too much boilerplate code.

After thinking a while about a better approach, I think the best solution would be to revise the whole messaging and make use of `std::error_condition`. My idea is outlined as follows:

- Remove `with_either<...>::or_else<...>` and make errors *implicit*
- When implementing statically typed actors, you can return `maybe<T>` instead of `T`
  + `maybe` is like `optional` but instead of "either `T` or `none`", this type is "either `T` or `error_condition`"
  + not part of the messaging interface, thus easy to add error handling later on
  + the response message automatically unwraps the `maybe<T>` (invisible to the caller)
- *Any* request receives either a valid response or a `std::error_condition`
- We get rid of `on_sync_failure` without replacement (the runtime simply generates `error_conditon` messages, e.g., if the receiver no longer exists)

Open questions:
- Should asynchronous messages silently drop errors ("fire-and-forget" semantics)?
- How should requests behave?
  + Alternative 1: kill the actor if no error handler was provided
  + Alternative 2: generate a compiler error if no handler for `std::error_condition` exists

I lean towards Alternative 2, as it makes error handling "in your face", but it goes against the "let it crash" mentality.

This relates https://github.com/actor-framework/actor-framework/issues/365, since we could make use of the name change for changing the semantics as well (that's why I didn't merge yet, @Hamdor).

Thinking a few steps ahead:
- Should we embrace `error_condition` further and use it for exit and down messages instead of sending plain old integers?
- This proposal obviously means that we add `error_condition` to the list of "builtin types" that are announced per default (and means users must be able to add custom error categories)

Since we are already discussing breaking changing (see the proposed `actor_system` change), I think this is a good time to tweak key aspects of CAF to get the semantics right (and give lean interfaces to end users).

**Comment by mavam** [comment]
Per our discussion, I'm much in favor of this error handling style.

> Should asynchronous messages silently drop errors ("fire-and-forget" semantics)?

Yes. Otherwise you'd be in trouble in send-become scenarios, when you all of a sudden get an `error_condition` instead of something else. And if you don't handle them, you'd silently introduce leaks.

> How should requests behave?
- Alternative 1: kill the actor if no error handler was provided
- Alternative 2: generate a compiler error if no handler for std::error_condition exists
I lean towards Alternative 2, as it makes error handling "in your face", but it goes against the "let it crash" mentality.

I much favor compile-time safety over the let-it-crash mindset.

> Should we embrace error_condition further and use it for exit and down messages instead of sending plain old integers?

Exit and down messages do not strike me as errors exclusively, but rather status messages. I wonder whether we're on the way to abuse an error-signaling channel just to unify the API.

**Comment by Hamdor** [comment]
> Alternative 2: generate a compiler error if no handler for std::error_condition exists

Maybe we should generate a warning (which is disabled by default) and kill the actor on error.

>> Should we embrace error_condition further and use it for exit and down messages instead of sending >> plain old integers?

> Exit and down messages do not strike me as errors exclusively, but rather status messages.

I think the same, we should keep the exit and down messages as they are and don't abuse `error_condition` here.

**Comment by Neverlord** [comment]
> > Should asynchronous messages silently drop errors ("fire-and-forget" semantics)?
> Yes. Otherwise you'd be in trouble in send-become scenarios, when you all of a sudden get an `error_condition` instead of something else. And if you don't handle them, you'd silently introduce leaks.

Agree.

> I much favor compile-time safety over the let-it-crash mindset.

If we make error handling optional (with the kill-on-error default), we could provide a shortcut syntax, though:

```cpp
self->request(kv_store, get_atom::value, "user.address", "neverlord") >> [=](const string& address) {
  aout(self) << "neverlord is living at " << address << endl;
};
```

This would be equivalent to:

```cpp
self->request(kv_store, get_atom::value, "user.address", "neverlord").then(
  [=](const string& address) {
    aout(self) << "neverlord is living at " << address << endl;
  },
  [=](error_condition& ec) {
    self->quit(ec);
  }
);
```

> Exit and down messages do not strike me as errors exclusively, but rather status messages.

Actually, exit and down messages *are* for error propagation and not for status messages. Changing the field `reason` of `exit_msg` and `down_msg` to `error_condition` would improve the current situation and make it extensible. The namespace `exit_reason` would become an `enum class` which would be convertible to `error_condition`. Hence, existing code like `msg.reason == exit_reason::normal` would remain valid. In other words, this change is downward compatible but allows us to spread the actual error directly in a linked set of actors instead of turning it into an ambiguous `unhandled_sync_failure` (which is the current solution).

> Maybe we should generate a warning (which is disabled by default) and kill the actor on error.

A warning at compile time that's disabled? In other words: no warning? Im strongly against turning things on or off using macros. We should make our mind up and provide a clean definition what happens when (and why).

**Comment by mavam** [comment]
> ```cpp
> self->request(kv_store, get_atom::value, "user.address", "neverlord").then(
>   [=](const string& address) {
>     aout(self) << "neverlord is living at " << address << endl;
>   },
>   [=](error_condition& ec) {
>     self->quit(ec);
>   }
> );
> ```

LGTM. We have to communicate that this is "implicit linking" of actors, unless the user properly handles error messages. That fits the desired "fail early" semantics, though, which I am favoring. 

> Actually, exit and down messages are for error propagation and not for status messages. Changing the field reason of `exit_msg` and `down_msg` to `error_condition` would improve the current situation and make it extensible. The namespace `exit_reason` would become an enum class which would be convertible to `error_condition`. Hence, existing code like `msg.reason == exit_reason::normal` would remain valid. In other words, this change is downward compatible but allows us to spread the actual error directly in a linked set of actors instead of turning it into an ambiguous `unhandled_sync_failure` (which is the current solution).

I see the benefits of this method now, you convinced me.

In Chris' ASIO blog post series introducing the error handling mechanisms, he even uses them for 200 HTTP OK, which is technically just a return code for success. I think my qualms were more along these lines; I would preferred the standard would use more neutral naming to make this feature applicable as more general signaling mechanism for the status of an operation.

**Comment by Neverlord** [comment]
I'll change this to "task" since I see no controversy here. :)
