### ISSUE TITLE
Replace singleton-based environment with actor_system class

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#370]
Discussion and original proposal can be found in the mailing list: https://groups.google.com/forum/#!topic/actor-framework/XjkOyHTa588

**Comment by Neverlord** [comment]
Some issues that came up while implementing this:

- `to_string(message)` and `from_string()` need access to unified type information (UTI) map
  + messages do not have (or need) a reference to an actor system
  + no access to UTI -> no access to (de)serialization code
  + possible solution: make `to_string` and `from_string` member functions of `actor_system`
  + impact: actors would need to call `self->to_string(...)` instead of simply `to_string`
-  how to best deal with modules?
  + `io::middleman` and `opencl::metainfo` only exists if the module has been loaded on startup
  + possible solution: provide `middleman` getter in `actor_system` that throws a `std::logic_error` if the I/O module is not available and users can query whether this would throw using `has_middleman()`
  + impact: `remote_actor()` becomes `system().middleman().remote_actor()`
  + alternative: we could use a `maybe`-based API instead of a throwing getter [1]
    * requires more typing by the user
    * I'm actually in favor of a throwing getter in this case, since users are unlikely to have a reasonable fallback strategy if the middleman does not exist

[1] example API using `maybe`
```cpp
// inside of an actor
auto mm = self->system().middleman();
// sys has type maybe<io::middleman>
if (mm) {
  auto buddy = mm->remote_actor(...);
  // ...
} else {
  // ...
}
```

**Comment by mavam** [comment]
> to_string(message) and from_string() need access to unified type information (UTI) map

That's too bad. `to_string` is a customization point by convention. Users expect it to be a free function using ADL.

> possible solution: make to_string and from_string member functions of actor_system

Alternative: `to_string(x, as)`.

> I'm actually in favor of a throwing getter in this case, since users are unlikely to have a reasonable fallback strategy if the middleman does not exist

:+1:

**Comment by Neverlord** [comment]
@mavam this is well underway with https://github.com/actor-framework/actor-framework/commit/0e33f68ec0ae4b7cfcbad5412b463be48785cba1. I'm waiting for your green light for merging to `develop`.

**Comment by mavam** [comment]
Good to know it's ready! Gimme 1-2 weeks, then I can start the transition.
