### ISSUE TITLE
local_group "leak"

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#376]
local_groups are never deleted (and their memory released) even long after no one is subscribed to them anymore. Is this a feature (ie. if re-using a group, it won't have to be re-instatiated) ?

In  `void local_group::unsubscribe(const actor_addr& who)` (libcaf_core/src/group_manager.cpp:118), no action is taken when the last subscribed actor unsubscribes from the group; especially the `local_group_module` holding it is not notified in any way, thus cannot erase it.

**Comment by Neverlord** [comment]
> Is this a feature (...) ?

I wouldn't exactly call it "feature". The original use case we had in mind when designing the pub/sub layer was to have well-known groups as rendezvous points. Later, we added the anonymous groups to coordinate a set of "loosely coupled" workers.

This clearly doesn't fit the dynamic, topic-based approach you are using. Allowing groups to expire is a reasonable request. The question is whether to delete the group immediately or to give it some timeout to avoid create/delete cycles in cases an application re-uses a group name frequently.

**Comment by Neverlord** [comment]
Groups are going to get deprecated in 0.19. Closing.
