### ISSUE TITLE
Feature request: ability to extend a typed_actor type with another type_actor type

### ISSUE THREAD

**Issue by StephenRudolph** [actor-framework/actor-framework#384]
Currently, `typed_actor`s can be extended with the `extend` method, which accepts the same parameters as the typed_actor template itself - a list of message signatures. It would be nice if there was a corresponding `extend_with` method for creating a supertype of two `typed_actor` types. It would look something like:

```C++
using a_type = typed_actor<replies_to<int>::with<bool>>;
using b_type = typed_actor<replies_to<double>::with<bool>>;
using super_type = a_type::extend_with<b_type>;
```

**Comment by firegurafiku** [comment]
Looks like a [mixin][1] to me.

[1]: https://en.wikipedia.org/wiki/Mixin
