### ISSUE TITLE
CAF and Visual Studio 2015

### ISSUE THREAD

**Issue by mvbaffa** [actor-framework/actor-framework#396]
Hi,

Is it CAF now ready to be used with Visual Studio 2015?

Is there still any issue associated with VC 2015 ? If yes should it be solved with Intel C++ compiler ?

Thanks

**Comment by Hamdor** [comment]
CAF should be useable with Visual Studio 2015, the only restriction is, that you can't use advanced match cases.

Advanced match cases (example from User Manual [1])
```c++
behavior verbose_bhvr1{
  on<int>() >> [](int i) { /*...*/ },
  on<int, float>() >> [](int i, float f) { /*...*/ },
  on<int, int, int>() >> [](int a, int b, int c) { /*...*/ }
};
```

If you don't plan to use advanced match cases, Visual Studio 2015 should work. If you experience any problems feel free to open a ticket on GitHub or join our chat at Gitter.
Further we don't have a ICC in our Jenkins setup, but feedback about ICC and CAF is welcome. :)

[1]http://www.actor-framework.org/manual/#sec20

**Comment by mvbaffa** [comment]
Thanks Marian,

I have used C++ for a long time and I am coming back. I am working now with
NET and Scala with AKKA.

I would like to continue working with the Actors Model in C++ and QT.

I am just starting to look at the new features of the language it seems
promising.

Thanks for your message.
Em 01/01/2016 13:43, "Marian Triebe" <notifications@github.com> escreveu:

**Comment by mvbaffa** [comment]
One more thing.

What about the Intel compiler. Should it work ok?

Thanks
Em 01/01/2016 13:43, "Marian Triebe" <notifications@github.com> escreveu:

**Comment by Hamdor** [comment]
Currently we do not official support Intel's C++ Compiler (ICC). I don't know if ICC works with CAF, we don't tested it (yet).

**Comment by mvbaffa** [comment]
Thanks

**Comment by kareemshaik80** [comment]
is there any installed steps to use CAF on visual stduio.

**Comment by Neverlord** [comment]
Please don't post in closed issues unless it's relevant to the topic (e.g. bug still exists).

You can build CAF just like any other CMake-based project: Get CMake, create a Visual Studio project file, open that file, build the project. Please ask the search engine of your choice for CMake tutorials if you're not familiar with it yet.
