### ISSUE TITLE
Unit test program hangs when actor connecting operation throws

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#408]
Seems like a compiler bug or something. Anyway, here is the code in question.

~~~~~C++
behavior simple_bhvr() {
  return {
    [](int v) {
      return v;
    }
  };
}

using simple_typed_actor_t = typed_actor<replies_to<int>::with<int>>;

CAF_TEST(foo_main) {
  actor_system_config cfg;
  cfg.load<io::middleman>();
  actor_system system{cfg};
  auto& mm = system.middleman();
  auto simple_actor = system.spawn(simple_bhvr);
  auto port = *mm.publish(simple_actor, 0, "127.0.0.1");
  auto remote_actor = mm.typed_remote_actor<simple_typed_actor_t>(
                        "127.0.0.1", port);
  anon_send_exit(simple_actor, exit_reason::kill);
}
~~~~~

The program is expected to throw [here](https://github.com/actor-framework/actor-framework/blob/topic/actor-system/libcaf_io/src/middleman.cpp#L301) and then terminate because of this exception. The problem is, the program simply hangs there. I've verified that the exception object has been successfully constructed before the program hangs. If I try to throw something else, say `throw 0`, problem solved. If I put the code into a normal `main` instead of `CAF_TEST`, problem solved.

I'm using Eclipse on Mac OS X. The Eclipse should be using the tool chain from Xcode. Following is the output by running `g++ --version`.

~~~~~
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
~~~~~

This issue doesn't seem a big deal. But I think it's still worth reporting.

**Comment by ufownl** [comment]
Reproduced this on `CentOS 7` `GCC 4.8`.

**Comment by Neverlord** [comment]
Do you see the output of the "default-catch" surrounding `caf::test::main` in https://github.com/actor-framework/actor-framework/blob/master/libcaf_test/caf/test/unit_test_impl.hpp#L587?

**Comment by ufownl** [comment]
There is no output except the content below:
```
./hello 
+----------------------------------------------------------------------+
                                foo_test
+----------------------------------------------------------------------+

- foo_main
WATCHDOG: unit test did not finish within 30s, abort
Abort trap: 6
```

**Comment by Neverlord** [comment]
Looking at the code a bit more, this is expected behavior. `simple_actor` is not killed in case of an exception. However, the exception causes stack unwinding, ultimately calling the destructor of `system`, which waits for all actors to terminate per default. Since `simple_actor` never stops, the program never returns from main.

**Comment by Lingxi-Li** [comment]
So, having destructor perform wait operation may result in confusing situations like this.
