### ISSUE TITLE
Propose to make typed interface subset of untyped

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#409]
Currently, one cannot assign an `actor` to a `typed_actor`. It's considered that the message passing interface (MPI) of a typed actor is not a subset of that of an untyped actor. This seems incorrect to me. There is no restriction on the MPI of untyped actors. One can practically send any kinds of messages to an untyped actor. It thus seems reasonable to consider an untyped actor's MPI to be the universal set. Given an untyped actor, one could narrow down its MPI and apply restrictions by assigning it to a typed actor handle. Let's consider another example. Some clients have used untyped actors for simplicity, while others have used typed ones. Regardless of the client-side complexity, the server regulates/normalizes different cases by using typed remote actor handles uniformly. The transformation does not involve much work.

**Comment by Neverlord** [comment]
With the same argument you could say `void*` should be implicitly assignable to any other pointer type. I think dynamically and statically typed interfaces should remain apart to avoid subtle errors and unexpected behavior. Putting an `actor_cast` in your code to convert between the two worlds is a better solution, as it explicitly puts the responsibility to the programmer (and makes you aware that you better double-check if that cast is correct).
