### ISSUE TITLE
CAF_TEST_ERROR ignored in success rate

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#411]
The macro `CAF_TEST_ERROR` only prints the error. The unit test still reports 100% success rate.

**Comment by Lingxi-Li** [comment]
I guess `CAF_TEST_ERROR()` is expected to do what it does now: simply printing an error message and nothing else. Although I think that a better name could be given, like `CAF_TEST_LOG_ERROR()`. For want you want, you should probably try `CAF_FAIL()`.

**Comment by Neverlord** [comment]
@Lingxi-Li Renaming doesn't solve the problem. One design goal was compatibly with Boost.Test (by simply replacing macro names) and Boost.Test does what the name implies and any user expects: http://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_error.html

**Comment by Lingxi-Li** [comment]
How about adding a `CAF_ERROR()` macro that behaves equivalently to `BOOST_ERROR()`?

**Comment by Lingxi-Li** [comment]
I just find that `CAF_FAIL()` has problem with the success rate also.

**Comment by Neverlord** [comment]
Hm, I would rather just rename `CAF_TEST_ERROR` to `CAF_ERROR` in the process. Technically, all functions from the test module [should](https://github.com/actor-framework/actor-framework/blob/master/CONTRIBUTING.md) use `CAF_TEST_`, but we settled on using the `CAF_` prefix for brevity. So it really makes no sense to have some macros using the `CAF_TEST_` prefix in the first place.

**Comment by Lingxi-Li** [comment]
`CAF_TEST_ERROR()` is used internally by unit testing. I don't think it's expected to be part of the interface. And for now, CAF unit testing does not have a counterpart to `BOOST_ERROR()`. Even if we renamed `CAF_TEST_ERROR()`, something else should take its place, for its functionality is needed anyway.

**Comment by Neverlord** [comment]
Ok, I didn't grep through the code yet. I think you're right, the current function should be named `CAF_TEST_LOG_ERROR` (because that describes clearly what it does) a new macro `CAF_ERROR` should be added.

**Comment by Neverlord** [comment]
Actually, I think `CAF_TEST_PRINT_ERROR` would be better to avoid confusions with the logging API.

**Comment by Lingxi-Li** [comment]
Sounds nice. I can work on this. A fix should be out by tomorrow. Really late now here in China.

**Comment by Neverlord** [comment]
Closed via https://github.com/actor-framework/actor-framework/commit/0b167399a8dee39be1ee49fab698f4c6a7e755de
