### ISSUE TITLE
Should we prefer `xxx{}` syntax to `xxx::value` using `std::bool_constant::operator bool ()`?

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#418]
The `xxx{}` syntax is simpler and streamlines code reading when put in large and complex meta expressions. Unlike the shorthand `xxx_t` for `typename xxx::type`, which is a C++14 feature, `std::bool_constant::operator bool ()` is available in C++11. See [here](http://en.cppreference.com/w/cpp/types/integral_constant).

**Comment by Neverlord** [comment]
I don't think `xxx{}` is much better than `xxx::value`. In particular in complex expressions I dislike the `{}` code noise. However, it makes little sense to discuss which of the both uglinesses is better. C++14 brings variable templates and that's what we will use going forward anyways. It's only a matter of time until we drop C++11 support, so the changes to the code base aren't worth the effort IMO.

**Comment by Lingxi-Li** [comment]
Variable template is a C++17 feature ~>_<~

**Comment by Neverlord** [comment]
Doesn't change my statement, though. It only takes a bit longer. :)

**Comment by Lingxi-Li** [comment]
> Doesn't change my statement, though. It only takes a bit longer. :)

Agreed. By the way. I were wrong just now. Variable template is introduced since C++14. But the `xxx_v` shorthand is introduced since C++17, e.g., see `is_same_v` [here](http://en.cppreference.com/w/cpp/types/is_same).
