### ISSUE TITLE
Potential performance issue with the use of std::random_device

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#421]
I see that `std::random_device` has been used in CAF to seed pseudo-random number generators. According to [cppreference](http://en.cppreference.com/w/cpp/numeric/random/random_device), *the performance of many implementations of `random_device` degrades sharply once the entropy pool is exhausted*. Considering that a CAF server application may be running for a long time, would it be a good idea to use `std::chrono::high_resolution_clock::now().time_since_epoch().count()` instead?

**Comment by Hamdor** [comment]
It would be interesting to know which implementations have this problem. As far as I know, the default source of `random_device` is "/dev/urandom", which not affect the performance.

**Comment by Lingxi-Li** [comment]
I don't have an answer either. All I know is that the implementation and performance characteristics of `std::random_device` is unspecified by the standard. Ultimately, it may not be that portable. The statement is quoted from the example at the cppref page I referenced.

**Comment by Neverlord** [comment]
I think there's no reason to proactively change code unless we measure actual performance issues in implementations of the standard library.
