### ISSUE TITLE
Website is dead

### ISSUE THREAD

**Issue by polkovnikov-ph** [actor-framework/actor-framework#423]
Cannot open almost any page of the site, including manual. Getting `ERR_CONNECTION_TIMED_OUT`.

**Comment by Hamdor** [comment]
All pages works fine for me, do you used a link from a tweet? (http://t.co/...)
[Main-Page](https://actor-framework.org/)
[Blog](http://blog.actor-framework.org/)
[Manual](https://actor-framework.org/pdf/manual.pdf)

**Comment by josephnoir** [comment]
I think we moved the website. Could be that the browser has still the cold address in its cache? (I can reach if I use a different browser.)

**Comment by josephnoir** [comment]
Oh. It seems I can reach the address via `https`.

**Comment by polkovnikov-ph** [comment]
These links work perfectly. The ones in the wiki do not. I can confirm that the difference is in the protocol, `http` vs `https`.

**Comment by Hamdor** [comment]
The website is broken if used with www prefix

**Comment by smlng** [comment]
Should be working again, there was an issue with a webserver of our working group.

**Comment by Neverlord** [comment]
Thx. :+1:
