### ISSUE TITLE
Switch to C++14

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#424]
GCC 4.8 released in 2013. Since it is more than two years old at this point, we can finally drop support for it. With 4.8 out of the way, there's no reason not to use C++14 goodness any more. This means CAF would become a C++14 library and we could start removing workarounds for C++11 shortcomings. Further, new code can make use of new language features and additions to the standard library.

The first thing we need to do before making heavy use of C++14 features is to identify the subset that is supported by all major compiler released in 2014 and later, i.e., Clang >= 3.4, GCC >= 4.9, Visual Studio 2015. For example, VS does not neither support Expression SFINAE nor Variable Templates [1].

[1] https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by Lingxi-Li** [comment]
> The first thing we need to do before making heavy use of C++14 features is to identify the subset that is supported by all major compiler released in 2014 and later...

I think this doesn't make a task itself. IMHO, we should begin using C++14 where we see fit and identify the subset along the way.

**Comment by Neverlord** [comment]
In any case, we should wait for feedback from the community before creating precedents. In particular from big projects we now of.

@nq-ebaratte would this change break your toolchain?

@mavam what about Bro/Broker? You recently upgraded to C++11, do you still need support for GCC < 4.9? Is ft feasible for you to take the next step or is your toolchain is holding you back?

**Comment by nq-ebaratte** [comment]
Good for us: we use `gcc-4.9`, with `-std=c++14`, and consider moving to gcc-5.something.

**Comment by rsmmr** [comment]
Let me chime in here: A switch to C++14 would be very problematic for Bro/Broker. We  just switched to C++11 finally during the current development cycle, and it will take a while before we can go any further. If CAF went ahead, we couldn't upgrade to newer versions for the foreseeable future. If the switching is critical for you guys, could you see keeping at least something like a "long maintenance version" around that would still get bug fixes and potentially some smaller feature updates?

**Comment by StephenRudolph** [comment]
No specific needs here, but I know that RHEL and CentOS are quite common as target Linux platforms for larger projects and industries. The current versions of each are limited to GCC 4.8.5 [1](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Developer_Guide/compilers.html#sect-Changes_in_Version_2.0-GCC), [2](http://distrowatch.com/table.php?distribution=redhat), [3](http://distrowatch.com/table.php?distribution=CentOS). My experience is that sticking to what the latest versions of RHEL/CentOS can handle will help reach a larger audience.

**Comment by Neverlord** [comment]
Thanks for the feedback guys. While I would like to stick to the 2-year compiler rotation in CAF, to catch up to new C++14 features and eventually to C++17, there is no doubt that community needs come first.

C++14 would make code less repetitive and easier to read and write (i.e. easier to maintain). But there is no "killer feature" that we would need to rush to. We can wait until all major Linux distributions ship with GCC 4.9 and the Bro devs are ready to go the step with us.

**Comment by rsmmr** [comment]
Thanks, I really appreciate it. I realize this is painful and I'd be more than happy to move more quickly, but we'd be breaking quite a bit on our end if we tightened the requirements further at this time.
