### ISSUE TITLE
build issue: -std=c++11 is not passed on to the GCC

### ISSUE THREAD

**Issue by tomboy-64** [actor-framework/actor-framework#430]
When GCC is used and ```CMAKE_CXX_FLAGS``` is defined, cmake just passes through the given flags and does not update them to at least include c++11 - which in turn results in a build failure.
Given, consumers should be aware of that - and cmake pre-defines a good default for ```CMAKE_CXX_FLAGS``` if unset, but in this particular case it might not be the behavior you desire.

Relevant version CAF: 0.14.4
Relevant version GCC: 5.3

**Comment by Neverlord** [comment]
That's actually the intended behavior. When passing `CMAKE_CXX_FLAGS` manually, we won't touch it. For example, users might wish to compile their project (including CAF as a submodule) using `std=c++14` or `std=c++1y` instead. Or even use a compiler that is not supported by our build chain and wouldn't understand the `std=c++11` flag.
