### ISSUE TITLE
Improve receive performance of CAF brokers.

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#432]
The network layer of CAF does not perform as well as it should. These results compare the raw throughput of a CAF application using brokers and a native application using sockets:

```
native sender -> native receiver
567520085 Bytes/s

CAF sender -> native receiver
511333973 Bytes/s

native sender -> CAF receiver
229689173 Bytes/s

CAF sender -> CAF receiver
222102755 Bytes/s
```

While send performance seems OK, performance drops significantly when using CAF at the receiver. The profiler output does not point to an individual bottleneck that would explain this behavior. So it's either the sum of all the little functions called for each receive operation or the `epoll_wait`-based loop is implemented inefficiently.

Source files for reproducing this issue (topic/actor-system branch required) as well as profiler outputs are attached.

[caf-client.pdf](https://github.com/actor-framework/actor-framework/files/154795/caf-client.pdf)
[caf-server.pdf](https://github.com/actor-framework/actor-framework/files/154794/caf-server.pdf)
[caf_impl.txt](https://github.com/actor-framework/actor-framework/files/154796/caf_impl.txt)
[Makefile.txt](https://github.com/actor-framework/actor-framework/files/154797/Makefile.txt)
[native_impl.txt](https://github.com/actor-framework/actor-framework/files/154798/native_impl.txt)

**Comment by Neverlord** [comment]
Shortcutting most of the invocation chain for `new_data_msg` gives only negligible performance increase. Attached is the profiler output for the "shortcut scribe" version. Seems like the implementation of the `epoll_wait` loop itself is the problem.

[caf-server.pdf](https://github.com/actor-framework/actor-framework/files/155241/caf-server.pdf)

**Comment by Neverlord** [comment]
Using a simple `epoll`-based receiver has a slight drop in performance, but CAF is still far from this.

```
native sender -> epoll receiver
556979501.176
```

[epoll_impl.txt](https://github.com/actor-framework/actor-framework/files/156734/epoll_impl.txt)

**Comment by Neverlord** [comment]
Looks better in 307cb3e. The default settings allows for 50 consecutive reads per I/O event:

```
native sender -> CAF receiver
386003911 Bytes/s
```

That gives us about 70% of the best case performance (the low-level epoll loop). Bumping the number of allowed reads up to 500 (i.e. decreasing fairness among brokers) increases throughput to `406257777`. I'm not sure if there are still significant performance gains possible. Reaching 80-90% territory would be awesome of course.

@mavam can you double-check this on FreeBSD?

**Comment by mavam** [comment]
Sure, can you give me some instructions how to run/compile it?

**Comment by Neverlord** [comment]
The files are attached in the first post (caf_impl.txt, Makefile.txt, native_impl.txt). You need to rename the file ending, because GitHub didn't let me upload `.cpp` files. Then you need to edit the Makefile. Btw, you can safely remove the boost parts (only needed when running CAF with the ASIO backend).

Then you start the receiver using `./caf_impl` and the sender using `./native_impl -s`. The benchmark will stop after 10s.

**Comment by mavam** [comment]
> You need to rename the file ending, because GitHub didn't let me upload .cpp files.

Sigh, what a half-hearted new feature.

> Then you start the receiver using ./caf_impl and the sender using ./native_impl -s. The benchmark will stop after 10s.

Thanks, that worked for me. Here's the output from `caf_impl`:

```
client has connected
116083200/s
138214400/s
143321600/s
147872000/s
143411200/s
147673600/s
142982400/s
143897600/s
141728000/s
```

And here from `./native_impl -s`:

```
opts: ["sender"]
run in sender mode, port = 4242, chunk size = 128
116117760/s
137776640/s
142421760/s
142881280/s
141990400/s
141386240/s
142461440/s
143070720/s
141190400/s
140748800/s
send failed
```

**Comment by mavam** [comment]
And here's the missing native-to-native comparison.

First, `./native_impl`:

```
opts: []
147790592/s
158567168/s
158118272/s
158179328/s
158177280/s
158269440/s
158240128/s
158251776/s
158244096/s
158207104/s
158198016/s
158214144/s
157844480/s
157865856/s
157782272/s
157866112/s
157803008/s
157865984/s
157829376/s
```

Then, `./native_impl -s`:

```
opts: ["sender"]
run in sender mode, port = 4242, chunk size = 128
148113920/s
158673920/s
158126080/s
158192640/s
158201600/s
158263040/s
158289920/s
158256640/s
158257920/s
158223360/s
158209280/s
158256640/s
157864960/s
157864960/s
157799680/s
157895680/s
157794560/s
157854720/s
157827840/s
157822720/s
157766400/s
```

**Comment by Neverlord** [comment]
@mavam thanks for the results. Seems like we're closer to the maximum performance on BSD.

**Comment by Neverlord** [comment]
@mavam I copy this in here from your mail for context.

> Before the changes, we could blast around
> 80K messages/sec through two remotely connected CAF nodes. After your
> changes, I am now measuring peak rate of up to 190K/sec on my FreeBSD
> box. That's more than double. Really cool! But: the benchmark no longer
> terminates and the server quickly stops getting data, and I would like
> to know why. Here is the modified actor-system code:
> 
>    ```cpp
>    // Client
>    using namespace caf;
>    using namespace caf::io;
>    using namespace std;
> 
>    int main(int argc, char** argv) {
>      actor_system_config cfg{argc, argv};
>      cfg.load<io::middleman>();
>      actor_system system{cfg};
>      auto server = system.middleman().remote_actor("127.0.0.1", 6666);
>      cerr << "connected to 127.0.0.1:6666, blasting out data" << endl;
>      auto i = 0;
>      scoped_actor self{system};
>      self->monitor(server);
>      for (auto i = 0; i < 1000000; ++i)
>        self->send(server, i++);
>      self->receive(
>        [&](down_msg const& msg) {
>          cerr << "server terminated" << endl;
>        }
>      );
>      self->await_all_other_actors_done();
>    }
> 
>    // Server
>    using namespace caf;
>    using namespace caf::io;
>    using namespace std;
>    using namespace std::chrono;
> 
>    CAF_ALLOW_UNSAFE_MESSAGE_TYPE(high_resolution_clock::time_point)
> 
>    behavior server(event_based_actor* self, int n = 10) {
>      auto counter = make_shared<int>();
>      auto iterations = make_shared<int>(n);
>      self->send(self, *counter, high_resolution_clock::now());
>      return {
>        [=](int i) {
>          ++*counter;
>        },
>        [=](int last, high_resolution_clock::time_point prev) {
>          auto now = high_resolution_clock::now();
>          auto secs = duration_cast<seconds>(now - prev);
>          auto rate = (*counter - last) / static_cast<double>(secs.count());
>          cout << rate << endl;
>          if (rate > 0 && --*iterations == 0) // Count only when we have data.
>            self->quit();
>          else
>            self->delayed_send(self, seconds(1), *counter, now);
>        }
>      };
>    }
>    ```

**Comment by Neverlord** [comment]
@mavam feel free to reopen if new results pop up. From the results in this thread I think the performance reached a reasonable level. Problems resulting from overloading the middleman should be resolved in the future by using the streaming API.

**Comment by mavam** [comment]
> Problems resulting from overloading the middleman should be resolved in the future by using the streaming API.

Alright, let's focus on that aspect in the future.
