### ISSUE TITLE
Invalid initialization of non-const reference of type caf::io::middleman&

### ISSUE THREAD

**Issue by virspace** [actor-framework/actor-framework#436]
Just checked out the topic/actor-system branch and got this when trying to make:

`[ 59%] Building CXX object CMakeFiles/caf-test.dir/libcaf_io/test/remote_actor.cpp.o
/home/michael/projects/actor-framework/libcaf_io/test/remote_actor.cpp:49:61: error: invalid initialization of non-const reference of type ‘caf::io::middleman&’ from an rvalue of type ‘<brace-enclosed initializer list>’
   caf::io::middleman& server_side_mm{server_side.middleman()};
                                                             ^
/home/michael/projects/actor-framework/libcaf_io/test/remote_actor.cpp:50:61: error: invalid initialization of non-const reference of type ‘caf::io::middleman&’ from an rvalue of type ‘<brace-enclosed initializer list>’
   caf::io::middleman& client_side_mm{client_side.middleman()};
                                                             ^
make[3]: *** [CMakeFiles/caf-test.dir/libcaf_io/test/remote_actor.cpp.o] Error 1
make[3]: Leaving directory `/home/michael/projects/actor-framework/build'
make[2]: *** [CMakeFiles/caf-test.dir/all] Error 2
make[2]: Leaving directory `/home/michael/projects/actor-framework/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/michael/projects/actor-framework/build'
make: *** [all] Error 2
`

If I'm reporting this incorrectly please inform me, thanks.

**Comment by Neverlord** [comment]
@virspace should be fixed via cdd9a0e6c8a1254d4875031abff34131b1ed95e7
