### ISSUE TITLE
Rethink interaction of groups and statically typed actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#441]
Statically typed actors and groups don't go well together. All actors inherit `join` via `local_actor`, but it's debatable whether this is a good idea or not (what is the point of statically typed actors without type-checking the sender?).

**Comment by Neverlord** [comment]
My solution for now would be to remove all group-related function (`join`, ...) from `local_actor` and allow them only in dynamically typed actors (`blocking_actor` and `event_based_actor`).

**Comment by josephnoir** [comment]
Using typed actors and groups together does indeed not sound like a good idea. Separating the groups as they from typed actors sounds like a good idea.

Since you didn't mentioned it: would it be desirable to have typed groups, i.e., be able to specify which messages types are distributed by the group? Although I remember implementing groups with HAMcast, I do not remember how the default groups are implemented. Hence, I am not sure if there is any technological detail which would prevent us from restricting messages in groups.

**Comment by Neverlord** [comment]
The problem is that groups are created on demand. If you call `group::get("my module", "/foo/bar")`, where should the type information come from? We could mangle the name with the type (in the same way @Hamdor evaluates to do for the data replication module), but that has its own set of problem when thinking to implement this on top of multicast.

**Comment by daedric** [comment]
I'm not too fond of the type name mangling.

Why not creating a special type of typed actor that accept registration from another compatible typed actor (free checks thanks to the C++ typing system) this actor would forward to every registered actor the messages it receives,  The registry could be used to make this actor available.

We loose a bit the "group" semantic but we have the same effect.

**Comment by Neverlord** [comment]
@daedric I'm not advocating the mangling, actually. I think we should simply make the current group communication a feature for dynamically typed actors only.

The idea of the group module is to provide a loosely coupled publish/subscribe communication model that can be mapped easily to network-layer multicast technologies. That doesn't fit well into the statically typed actor world.

An API that only does registering at actor level doesn't scale well, though. If you have something that behaves like a group, you should at least make sure no message is transferred more than once to each node (which can have any number of local subscribers). What we could do, however, is to have only the equivalent of anonymous groups in the typed world. A typed anonymous groups would basically be the equivalent of what you proposed, but provide more scalable communication.

**Comment by daedric** [comment]
> The idea of the group module is to provide a loosely coupled publish/subscribe communication model that can be mapped easily to network-layer multicast technologies. That doesn't fit well into the statically typed actor world.

I'm not sure to understand how it would not scale well as what I'm proposing is close to what the Broker/Middleman does. If the serialization part contains type id, this middleman should be able to accept/reject whatever is not matching what the typed actor group is capable of processing.

About the last part, admitting that it does not scale well,  I don't see how the anonymous group solve the problem ?

**Comment by Neverlord** [comment]
If you have an actor and others are registering to you, you have to store all participants in some sort of container. Now, whenever you receive a message, you iterate your container and send a copy to each registered actor. If your actor lives on node A and it has 10 registered actors on node B, you ship the message 10 times over the wire.

Anonymous groups are integrated into the runtime and treated differently. If you send a group handle across the wire, the receiving node will make a local mirror/proxy for that group. Every actor subscribes to the local mirror and this mirror subscribes to the original group. When sending a message to the group, the message is transferred only once to each mirror, which in turn distributes its locally to all subscribers.

I hope that makes clear what I mean with scalable communication.

**Comment by daedric** [comment]
I see thanks !

**Comment by Neverlord** [comment]
The fix for 0.15 is that only dynamically typed actors are able to join groups.

**Comment by Neverlord** [comment]
I close this for now.
