### ISSUE TITLE
Recently broke build for VS2015?

### ISSUE THREAD

**Issue by toddbluhm** [actor-framework/actor-framework#443]
Did a recent commit break this lib for VS2015? I just pulled down master a few days ago and got it built and started using it today. Ran into a compile error when attempting to run. Maybe I am missing something in my build. This is the error I get from VS2015:
```
caf/detail/type_traits.hpp(260): error C2988: unrecognizable template declaration/definition
caf/detail/type_traits.hpp(267): note: see reference to class template instantiation 'caf::detail::is_memory_cached<T>' being compiled
caf/detail/type_traits.hpp(260): error C2059: syntax error: '<end Parse>'
caf/detail/type_traits.hpp(260): error C2238: unexpected token(s) preceding ';'
caf/detail/type_traits.hpp(263): error C2988: unrecognizable template declaration/definition
caf/detail/type_traits.hpp(263): error C2059: syntax error: '<end Parse>'
caf/detail/type_traits.hpp(263): error C2238: unexpected token(s) preceding ';'
caf/detail/type_traits.hpp(267): fatal error C1903: unable to recover from previous error(s); stopping compilation
```

It appears to be coming from a recently added line of code in the `simplified memory manager` commit. I'm not super familiar with the differences between compilers and msvc's weirdness so I'm afraid I can be much help other than to report this. 

I wanted to check out jenkins because I know you were running CI tests on that to see if maybe it was just an issue on my end first, but I could not manage to get through to the jenkins server to see if it was passing msvc there.

Do I need to turn off the memory management with the cmake flag to get this to work on vs2015? I thought I had read in one of the posts that the memory stuff had been switched to c++11 and was now working for msvc, but I certainly could be wrong.

**Comment by Neverlord** [comment]
I wasn't aware that the memory management worked, to be quite frank. Our recent Jenkins tests are all good, but we compile it with memory management disabled (`-DCAF_NO_MEM_MANAGEMENT:BOOL=yes`). However, we put this on the todo list to see if we can get the memory management to work.

> I wanted to check out jenkins because I know you were running CI tests on that to see if maybe it was just an issue on my end first, but I could not manage to get through to the jenkins server to see if it was passing msvc there.

The URL of our Jenkins changed recently. Sorry for the inconvenience. The latest MSVC build is here: https://jenkins.inet.haw-hamburg.de/job/CAF/job/develop%20branch%20msvc/label_exp=msbuild/216/console

**Comment by toddbluhm** [comment]
Oh okay. Thanks for the clarification. I will use the flags from the jenkins build.

**Comment by toddbluhm** [comment]
So I managed to get it all compiled without memory management (Yay!), but I get these linker errors when linking against just a simple win32 console application. 
```
caf_core.x64.lib(singletons.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in ConsoleApplication1.obj
1>caf_core.x64.lib(singletons.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in ConsoleApplication1.obj
1>caf_core.x64.lib(actor_registry.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in ConsoleApplication1.obj
1>caf_core.x64.lib(actor_registry.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in ConsoleApplication1.obj
```

I tried compiling the lib and running it in both debug and release mode, but still the same error. I am including both the `header` files and the `.lib` file when requiring this in to my project. Are there certain header files my win build should not include?

I again tried to compare my cmake settings with the jenkins build...but it seems to be down again :(

Sorry for all the problems.

**Comment by josephnoir** [comment]
The Jenkins server crashed over the weekend, but should be up and running again. I can't say much about the Windows problems though. Maybe @Neverlord or @Hamdor can help with that.

**Comment by Neverlord** [comment]
@toddbluhm [this SO thread](http://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt) suggests to check whether you use either `/MDd` or `/MD` in both cases (and don't mix them). We never use the Visual Studio compiler outside of Jenkins, so we are not of much help when it comes to this kind of errors, I'm afraid.

So please keep us posted if you figured out the solution to help out other Windows users that want to use CAF.

**Comment by toddbluhm** [comment]
Yeah that fixed my issue. I have it working now. Thank you!
