### ISSUE TITLE
New `report_unexpected` feature

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#444]
Almost all event-based actors have an `others >>` handler to discard unexpected messages, usually printing the message.

This is quite clumsy and repetitive. We could either provide a default handler (e.g. `others >> report_unexpected`) or allow actors to specify a handler for unexpected messages separately. If defined, this handler would be used to consume all uncaught messages, essentially overriding the default of leaving the message in the mailbox.

**Comment by Neverlord** [comment]
Another alternative is to remove `others` and only offer an API to catch unexpected messages.

**Comment by mavam** [comment]
Agreed. Since reporting is something very application-specific, I would allow users to make that choice. Here's my little helper function I use in VAST: 

```cpp
auto log_others = [](auto self) {
  return others >> [=] {
    VAST_ERROR_AT(self, "got unexpected message from",
                  self->current_sender() << ':',
                  to_string(self->current_message()));
  };
};
```

**Comment by nq-ebaratte** [comment]
Definitely a nice feature ! I'd find it perfect if it used an exception-free `caf::to_string()`. Indeed, `to_string` throws a `std::runtime_error` when trying to log an unannounced type, and I find that both errors (unannounced types, unexpected messages) are frequently linked.

Note: for now, I wrap to_string() in a custom function that catches the runtime error to extract the type name of the unannounced field of the message; yes, this feels clunky (!)

**Comment by Neverlord** [comment]
> yes, this feels clunky (!)

Uh.... that is more than just clunky. I'm glad to say that `to_string` in 0.15 will indeed not throw and in fact will no longer rely on announced types. Instead, CAF will pick up free `to_string` functions via ADL and simply print `<unprintable>` whenever it is unable to find one.

**Comment by nq-ebaratte** [comment]
Oh, great !

**Comment by mavam** [comment]
If you generate `to_string` via ADL, might as well consider injecting `std::ostream operator<<(std::ostream& out, const T& x)` via expression SFINAE that does `out << to_string(x)`.

**Comment by Neverlord** [comment]
Actors now have the member function `set_unexpected_handler`, which takes a function with signature `result<message> (local_actor* self, const type_erased_tuple*)`. The function takes a pointer of type `local_actor*` to allow implementations via free functions.

There is also a set of free functions for convenience that cover the most common strategies:

- `mirror_unexpected`
- `mirror_unexpected_once`
- `skip_unexpected`
- `print_and_drop_unexpected`
- `silently_drop_unexpected`

The first two are primarily for testing purposes. The `skip_unexpeced` function is the default behavior for blocking actors and `print_and_drop_unexpected` is the default for event-based actors.

If you don't like the names, please complain now. :)

**Comment by mavam** [comment]
> If you don't like the names, please complain now. :)

Okay. :-)

I would remove `silently` from `drop_unexpected`, because that would my expectation anyway. In addition, `print_and_drop_unexpected` already contains `print` to indicate it's relying on an output channel.

I cannot infer would `mirror` should mean. Mirroring a message sounds odd. If it should convey a send operation, then perhaps `reflect` would be a good fit.

**Comment by Neverlord** [comment]
Sounds reasonable. I renamed the functions:

- `reflect_unexpected`
- `reflect_unexpected_and_quit`
- `skip_unexpected`
- `print_and_drop_unexpected`
- `drop_unexpected`

**Comment by Neverlord** [comment]
Since @Hamdor seems to have lost his voice: he is in favor of `set_default_handler ` instead of `set_unexpected_handler `. Opinions on this?

**Comment by mavam** [comment]
What's the rationale behind this? Everything else has the name `*_unexpected_*`. I don't see why the function to set any of these should be called differently.

**Comment by nq-ebaratte** [comment]
Sometimes these `others() >>` messages are actually expected. For instance an actor may have specific behaviour for some types of messages, all others have the same behavior (eg. forward to someone)

There is a philosophical question here: are messages not explicitely matched by the current actor behavior considered errors ('unexpected') or a normal event ('default')?

**Comment by mavam** [comment]
> There is a philosophical question here: are messages not explicitely matched by the current actor behavior considered errors ('unexpected') or a normal event ('default')?

That's precisely the semantic gap. Right now we have handler names that impose erroneous semantics, e.g., `skip_unexpected`. I think we should not make the error judgement for the user and use most general wording where possible. That would mean renaming the existing handlers to something more neutral, e.g., `s/unexpected/others/`. Then `set_default_handler` would in fact make sense, akin to a `switch` statement.

**Comment by nq-ebaratte** [comment]
Thinking about it, how would the new system handle the case of an actor with several behaviors, only one of them catching others>>(). As I understand the current modifications, the handler would be registered by the actor itself, ie. independently of the current behavior.

In the following (contrived) sample, what would happen of messages with atomA, atomB, atomC received while the actor is in the second behavior ?

    caf::behavior MyActor::make_behavior() override {
        set_unexpected_handler([=] {
            logAnError(current_message());
        });
        
        return {
            [=] (atomA) {
                // ...
            },
            [=] (atomB) {
                // ...
            },
            [=] (atomC) {

                doSomething();
                become(keep_behavior) {
                    [=] (atomOK) {
                        unbecome();
                    },
                    [=] (atomKO) {
                        unbecome();
                    },
                    after(...) >> [] {}
                }
                send(someActor, somethingExpectingAResponseSometimes);
            },
           // implementation of caf <= 0.14.4
           // others() >> [=] {
           //     logAnError(current_message());
           // }
        }
    }

**Comment by Hamdor** [comment]
> I think we should not make the error judgement for the user and use most general wording where possible.

If we use `set_default_handler`, then we should also rename the default handlers:
* `reflect_others`
* `reflect_others_and_quit`
* `skip_others`
* `print_and_drop_others`
* `drop_others`

Or maybe:
* `default_reflect`
* `default_reflect_and_quit`
* `default_skip`
* `default_print_and_drop`
* `default_drop`

My personal preference is `_others`, which plays nice with the old `others() >>` ...

**Comment by nq-ebaratte** [comment]
> That would mean renaming the existing handlers to something more neutral, e.g., s/unexpected/others/
I'd even argue that they could drop the `_unexpected_` part completely: these functions could very well be applied to a 'standard' message handler (like the current `skip_message()` function)

**Comment by Neverlord** [comment]
@nq-ebaratte In your example above, you would need to call `set_unexpected_handler` every time you call `become` or `unbecome`. However, I don't think there are not many uses cases for nesting behaviors with the new multiplexed `request`.

The uses I found in CAF is that an actor expects some initialization message before setting its "actual" behavior. In this case, you start with `skip_unexpected` and once you call become set some other default, usually `print_and_drop_others `.

**Comment by Neverlord** [comment]
Ok, I think it's time to cast a vote on this one.

👍  if you are in favor of `default_handler`
👎  if you are in favor of `unexpected_handler`

You have time until Tuesday, April 26. :)

**Comment by Neverlord** [comment]
Well, that was one-sided. 5 votes in favor of `default_handler` and 0 against it. Plus one vote in favor of ... celebration? :)
