### ISSUE TITLE
Manual overhaul for 0.15

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#445]
This issue bundles #383, #403, #337, #335, and #336.

**Comment by marcoben73** [comment]
Hi,
in the new manual there's no chapter about Projections (Projections are only mentioned in chpater 19.2 0.9 to 0.10)
Is this feature still present?

**Comment by Neverlord** [comment]
The advanced match cases were removed with https://github.com/actor-framework/actor-framework/commit/a441111d08bdbc8fe4bb60c688268d1224d13010 (see commit message for more details).
