### ISSUE TITLE
Remove `message` from the interface of actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#446]
The tight coupling of `message` into the API of actors severely limits design space and optimization opportunities going forward. This means we need to remove things like `forward_to` (superseeded by `delegate`) and `current_message` (without replacement). The primary use case for `current_message` was to print unexpected messages in event-based actors. This use case is addressed in #444.

**Comment by Neverlord** [comment]
Closed due to fa5ad15fc2b4183d2447c0739cbddb9fcb433b56 and 406f2f1e213f36ca3aca780263015ec6ac2e8c92

As consequence of removing wildcards from CAF, pattern matching is now a bit faster. Here are the results for the `micro` benchmark before and after the changes:

| benchmark | old | new | speedup |
|-----------|-----|-----|---------|
| builtin types (make_message) | 247.6 | 198.4 | ~25% |
| builtin types (message builder) | 245.3 | 215.2 | ~15% |
| user-defined types (make_message) | 149.8 | 118.7 | ~25% |
| user-defined types (message builder) | 150.7 | 126.3 | ~20% |

The results for old and new are the average over 10 runs, as produced by the `micro` benchmark. A speedup of 15-25% in the pattern matching is probably barely measurable for real-world applications, but it's definitely a nice side effect.

**Comment by mavam** [comment]
> As consequence of removing wildcards from CAF, pattern matching is now a bit faster.

Cool!

Are there any alternatives to `anything` & friends planned?

**Comment by Neverlord** [comment]
> Are there any alternatives to anything & friends planned?

No.
