### ISSUE TITLE
Memory leaks in branch topic/actor-system

### ISSUE THREAD

**Issue by ufownl** [actor-framework/actor-framework#454]
In the last two days, I found that the memory usage curve chart of my project(which depends on branch `topic/actor-system`) was far from normal. So I suspected that some of commits in branch `topic/actor-system` might lead memory leaks.

I ran the unit tests using valgrind, there was no leaks in `master`:
```
HEAP SUMMARY:
    in use at exit: 0 bytes in 0 blocks
  total heap usage: 59,125 allocs, 59,125 frees, 11,952,467 bytes allocated

All heap blocks were freed -- no leaks are possible

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)
```

But there were leaks in `topic/actor-system`:
```
HEAP SUMMARY:
    in use at exit: 83,774 bytes in 331 blocks
  total heap usage: 245,635 allocs, 245,304 frees, 18,947,514 bytes allocated

LEAK SUMMARY:
   definitely lost: 40,176 bytes in 42 blocks
   indirectly lost: 43,598 bytes in 289 blocks
     possibly lost: 0 bytes in 0 blocks
   still reachable: 0 bytes in 0 blocks
        suppressed: 0 bytes in 0 blocks
Rerun with --leak-check=full to see details of leaked memory

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
```

**Comment by Neverlord** [comment]
Thanks for reporting this, I'll have a look.

**Comment by Neverlord** [comment]
ASAN tracked this down the BASP broker. For some reason, it gets never deleted. I couldn't track down where the extra reference is coming from yet.

**Comment by ufownl** [comment]
I tracked down to the local groups and brokers in the unit tests via valgrind. But in my own test, it can only tracked down to the BASP broker and local groups. I can not repeat the cases in the unit tests that lead to leaking yet.

**Comment by Neverlord** [comment]
@ufownl I don't see any leaks with leak sanitizer after d32b78d. Please reopen this issue if you can still reproduce one.

**Comment by ufownl** [comment]
See this case:
```C++
#include <caf/all.hpp>
#include <iostream>
#include <string>

struct foo_state {
  foo_state(caf::event_based_actor* ptr)
    : self(ptr) {
    caf::aout(self) << __FUNCTION__ << std::endl;
  }

  ~foo_state() {
    caf::aout(self) << __FUNCTION__ << std::endl;
  }

  caf::event_based_actor* self;
};

caf::behavior foo(caf::stateful_actor<foo_state>* self) {
  return {
    [=](const std::string& str) {
      caf::aout(self) << str << std::endl;
    }
  };
}

int main(int argc, char* argv[]) {
  caf::actor_system_config config(argc, argv);
  caf::actor_system system(config);
  system.spawn(foo);
  return 0;
}
```

The deconstruct is never called. If `foo_state` has dynamic allocated memory, it will leak.

BTW, I found that the deconstructor of `local_actor` call a virtual function `cleanup` (see [here](https://github.com/actor-framework/actor-framework/blob/topic/actor-system/libcaf_core/src/local_actor.cpp#L104)). It seems that calling a virtual function in deconstructor of class is not recommend.

**Comment by Neverlord** [comment]
> BTW, I found that the deconstructor of `local_actor` call a virtual function `cleanup`

Seems like I didn't think this through during refactoring. Thanks for your great input!

**Comment by ufownl** [comment]
It still has issues, the case above will crash at the end.

OS X
```
[ufownl@RangerUFO-Macbook-Pro build]$ ./hello 
foo_state
~foo_state
libc++abi.dylib: Pure virtual function called!
Abort trap: 6
```

CentOS
```
[ufownl@localhost build]$ ./hello 
foo_state
~foo_state
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

**Comment by Neverlord** [comment]
Ah, I found the cause. Using `caf::aout(self)` in the destructor of the state causes the crash. Will fix soon, thx again.

**Comment by Neverlord** [comment]
Ok, you example no longer crashes for me after b86b6c30dc4df86d4a3dafbb97af26acd5974301
