### ISSUE TITLE
Non-null Guarantee for Actor Handles

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#461]
While thinking about new actor handle semantics in 0.15 and optimization potential, I had the idea to implement a non-null guarantee for actor handles. Currently, each call to `send`, `request`, `monitor`, etc. has to check its argument for `nullptr` (or `invalid_actor`). This is also true for using `actor::id()` and other member functions. While one `if (x) { ... }` doesn't seem much, it sure adds up. Branch prediction helps, but not branching in the first place is simply more efficient. Especially on low-end hardware. A non-null guarantee also has the very nice property of "if it compiles, it runs as expected".

I don't think there are enough valid uses that justify the current pessimization. So my suggestion is as follows:
- `actor` and `typed_actor` no longer have default constructors
- `actor_cast<T>(x)` returns an `optional<T>` when casting to one of the handle types

Consequently, the following code would no longer compile:
```cpp
actor x;
x = system.spawn(...);
```

Instead, users would always have to initialize variables immediately:

```cpp
auto x = system.spawn(...);
```

The latter is also a much better coding style.

The two questions that remain are: (1) whether or not we allow to move handle types and (2) are there crucial use cases that this change would break that I didn't consider yet.

I'm in favor of allowing move. Using an object in moved-from state is UB. It's essentially the same as calling `delete` on a pointer and then trying to use it.

**Comment by mavam** [comment]
> The two questions that remain are: (1) whether or not we allow to move handle types and 

Yes, moving seems important to support flexible actor "factories."

> (2) are there crucial use cases that this change would break that I didn't consider yet.

A common use case is keeping actors in a container. This should be fine, because most containers can handle move-only types, at least those in the standard library.

What's the workaround when copying handles is needed? Will you just use a "weak handle?"

**Comment by ufownl** [comment]
I think this use case would break: store an actor handle in the state of an actor and it need to be requested from another actor.

**Comment by Neverlord** [comment]
> I think this use case would break: store an actor handle in the state of an actor and it need to be requested from another actor.

That's true, but I think the fix here is straightforward. Spawn another actor that first collects all required state. Separating it like this also can make code easier to follow, since the setup code isn't mixed with the other behavior.

**Comment by ufownl** [comment]
> Spawn another actor that first collects all required state.

Err... I'm not quite understand.

**Comment by JimHewes** [comment]
I'm just a beginner with CAF and actors I'm probably not understanding. But I had similar thoughts as mavam and ufownl above. Currently I'm using some class based actors. For example, Actor A owns and has a handle to actor B. Now say actor C needs to communicate with actor B, so actor A sends a copy of actor B's handle to actor C to use.
If the handle that actor C holds on to is not set to invalid_actor when the program ends, class destructors do not get called and there are memory leaks. If handles become non-nullable, then when are classes deleted?
Sounds like there are two different things talked about: one is non-nullable handles (that is, handles are analogous to C++ references rather than pointers) and the other is ownership (that is, handles are analogous to std::unique_ptr rather than std::shared_ptr).

**Comment by Neverlord** [comment]
Ok, I think I should give more background here to get everyone on the same page.

# Weak and Strong Handles / Pointers

Version 0.15 introduces the notion of weak and strong references. In 0.14, monitoring and linking create cycles that prevent actor destructors from being called. 0.15 breaks the cycles by giving `actor_addr` *weak reference semantics*. Further, CAF now terminates unreachable actors automatically.

This means CAF needs a new type with 0.15: a strong reference to actors without type information (which is the role `actor_addr` previously had). This new type is `strong_actor_ptr`.

This is the complete list of pointers and handles in 0.15:
- `weak_actor_ptr` weak *pointer* without type information (only used internally)
- `strong_actor_ptr` strong *pointer* without type information
- `actor_addr` weak *handle* without type information
- `actor` strong *handle* for dynamically typed actors
- `typed_actor<...>` strong *handle* for statically typed actors

The proposed change would further differentiate *pointers* from *handles*  by giving the latter a non-null guarantee.

# Benefits

`actor` and `typed_actor<...>` are used ubiquitously in CAF. Since bot handles are only a thin wrapper around pointers, CAF has to perform `nullptr` checks on several layers. For example when calling `send` or simply querying `x.node()`. The `nullptr` check is repeated over and over again, wasting CPU cycles in the process. Implementing the non-null guarantee would allow us to drop all checks.

It also makes sense semantically. A *handle* is something that *references* a resource (or actor in this case). Or as @JimHewes put it:

> handles are analogous to C++ references rather than pointers

# Downsides

As @ufownl pointed out, actors can no longer have default-constructed handles that are updated later. However, I argue half-constructed actors are not a good design in the first place. If an actor requires references to others in order to work, these actors should be known at construction time.

Say, actor A spawns actor B. B then requests an actor handle from another actor C. After receiving the handle to actor D, it sets it "proper" behavior.

In this case, A should spawn an "intermediate" actor X that requests D from C and then spawns B after receiving the handle. Essentially, spawning B involves a stateful operation (getting a handle to D), which  can be modeled as actor. This design also clears up the code of B, because the initialization is now done externally and B only implements the actual logic.

# Breaking Cycles with States

@JimHewes breaking cycles manually is quite error-prone and hopefully a relict of the past in CAF. The new stateful actors tackle exactly this issue. In short, stateful actors *construct* their state when spawned and *destroy* their state when terminated. This decouples the lifetime of the state from the lifetime of the actor object. In other words, there is no need for nulling handles manually when using stateful actors.

**Comment by mavam** [comment]
I understand the distinction between pointers and handles from a semantic perspective. But from a performance perspective: have you actually measured the impact of the non-null checks? I'd imagine the branch prediction would do a pretty good job at rendering them insignificant in practice.

> Say, actor A spawns actor B. B then requests an actor handle from another actor C. After receiving the handle to actor D, it sets it "proper" behavior.

I'm still confused. The relative clausr containing two times "it" is still ambiguous. Could you give a code example?

**Comment by ufownl** [comment]
> A should spawn an "intermediate" actor X that requests D from C and then spawns B after receiving the handle.

@Neverlord In my scenario, D may handle a unique device and I want to release it automatically when B is terminated, so D need monitor to B even if B is a `scoped_actor` in `function_view`. But in your scenario, this use case seems hard to be implemented.

**Comment by ufownl** [comment]
> In this case, A should spawn an "intermediate" actor X that requests D from C and then spawns B after receiving the handle.

@Neverlord In my scenario, D may handle a unique device and I want to release it automatically when B is terminated, so D need monitor to B even if B is a `scoped_actor` in `function_view`. But in your scenario, this use case seems hard to be implemented.

**Comment by Neverlord** [comment]
Ok, here's what I came up with in the `topic/non-null-handles` branch. Actor handles no longer have a default constructor. Instead, users can explicitly initialize a handle with `unsafe_actor_handle_init`. An *unsafe* handle will cause undefined behavior (dereferencing NULL) when used. It is the users responsibility to never give CAF an unsafe handle. No function in CAF ever returns an unsafe handle.

A handle is considered unsafe when constructed via `unsafe_actor_handle_init` or if it is in moved-from state. In other words, CAF assumes all handles to be never NULL, but users can violate this assertion for end-of-lifetime handles (moved-from) or to delay initialization. I think this is a reasonable compromise. It allows for more complex initialization phases like the one @ufownl mentioned while giving handles a reference-like semantics.

> from a performance perspective: have you actually measured the impact of the non-null checks?

Performance isn't the main motivation for this change. Collecting data is always a good thing, though.

In the _mixed case_ (token passing rings + number crunching), I didn't expect a difference. The benchmark always sends exactly one message from one actor to another. Main overhead here is memory allocation and communication to the scheduler. And indeed, difference in the measurements is within the 95% percentile.

```
--- old ---
cores            , CAF              , CAF_yerr
64               , 10.5264          , 0.233315
--- new ---
cores            , CAF              , CAF_yerr
64               , 10.4674          , 0.259678
```

Next, we have our _actor creation_ suite (recursively creating 1M actors in steps of 2). Again, less branching has not much effect if the main overhead is memory allocation and queue operations.

```
--- old ---
cores            , CAF              , CAF_yerr
64               , 0.4283           , 0.0257146
--- new ---
cores            , CAF              , CAF_yerr
64               , 0.4129           , 0.00660371
```

Finally, our _mailbox performance_ benchmark (sending messages from multiple senders to a single receiver). In this case, I did expect some improvements. Actors send messages in a tight loop, so the missing branches should make a difference. And it looks that way. The fastest run with the new implementation took 108s, while the fastest run with the old implementation took 113s.

```
--- old ---
cores            , CAF              , CAF_yerr
64               , 122.606          , 4.30625
--- new ---
cores            , CAF              , CAF_yerr
64               , 117.557          , 6.05411
```

The results are produced from 10 independent runs.

To wrap this up, I think the non-null assumption for handles is semantically sound and can deliver small performance gains. The `unsafe_actor_handle_init` also allows users to break this assumption if it "gets in the way".

**Comment by Neverlord** [comment]
This is now live in `topic/actor-system` via c57e7e9272590b648966c3c33ddd4c3583a6ab3a. Hopefully this is the last breaking API change.

The last piece in the puzzle API-wise is #441. It probably boils down to prohibit `join` in typed actors. This was never safe to begin with.

Next stop: Manual update. :)
