### ISSUE TITLE
Improve PR builder in Jenkins

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#466]
The pull request builder should:
- build on MSVC
- enable address sanitizer
- use more compilers

Omitting this three steps means many errors only occur after merging to `develop`.

**Comment by Neverlord** [comment]
@josephnoir is this part of your current tweaks to the Jenkins setup?

**Comment by josephnoir** [comment]
Getting the PR builder to run on Windows was one of my main goals with the tweaks. Moreover the new config should use the same compilers and options for all builds and remove the redundant (and differing) setups for PRs and "normal" builds. That should allow us to catch problems earlier and reduce the maintenance overhead in the long run.

tldr: Yes.

**Comment by Neverlord** [comment]
Seems like this is obsoleted by our current `Jenkinsfile`-based redesign.
