### ISSUE TITLE
Support auto-initialization of actor_system_configuration

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#467]
A default-constructed `actor_system_config` is (counter-intuitively) not yet read to use. Once has to call `init()` or `parse()`. After construction, an instance should be in a usable state.

Alternatively, we could let the `actor_system` call `init`, but then have to make sure that calls to `parse` do not double-initialize the config. This requires an extra flag in `actor_system_config`.

**Comment by Neverlord** [comment]
As discussed in the chat, we'll get rid of `init` and have users just implement a default ctor.

**Comment by Neverlord** [comment]
See #468.
