### ISSUE TITLE
Support user-defined magic cookies

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#478]
Add a new config parameter to the middleman to support magic cookies. This allows applications to fail during handshake, e.g., to prevent errors due to incompatible versions.

**Comment by ufownl** [comment]
It means the magic number?

**Comment by Neverlord** [comment]
No, maybe "app identifier" is a better name. It is simply a user-defined string that is used to authenticate nodes during connect. During handshake, each node sends the CAF magic number, the BASP version, and (new) the app identifier / cookie. If any of those mismatches, connection is refused. This allows users to make sure incompatible versions of an application fail to connect, rather than failing later with some obscure error.
