### ISSUE TITLE
New and better memory management

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#481]
While refactoring the code base for 0.15, the old memory management also got the axe. Not because it serves no practical purpose, but because it does not a good enough job at what it's supposed to do.

Mid- to long-term, we should re-visit memory management in CAF and implement a more sophisticated version to improve performance.

The new memory management should provide allocators to allow users to make use of the optimization. I currently envision three "memory regions":
- actor-local "scratch space" (configurable size?)
  - objects that are bound to the actor's lifetime
  - objects that are never exposed to others, e.g., `behavior`
- worker-local, NUMA-friendly memory caching (thread-local)
  - objects that usually don't travel between threads
  - primary use case is `mailbox_element` and actors themselves
- heap
  - good' ol `new/delete`
  - fallback if out of scratch space
  - "unoptimized" user code

**Comment by Hamdor** [comment]
Sounds good, but can you give more examples for "worker-local" data? I don't see that actors can live in thread local storage ("worker-local?"), since actors can be executed in different worker threads

**Comment by Neverlord** [comment]
Actors can migrate between threads as a result of stealing, but usually they stick to their original thread. Stealing is a rare event, unless the application is running out of work.

As a result "worker-local" memory can be used by others. That's not an issue, as long as "borrowing" threads return the memory to its origin. Probably via an atomic stack. To improve performance further, we could tweak the stealing algorithm to prefer NUMA neighbors. In this way, cost of memory access is further reduced on average.

However, workers can still use caching mechanism. This is the ideal scenario: Actor A sends a message B, then yields. B handles the message and sends one message. If the memory chunk A used for the message is large enough to fit the message of B, B can just re-use that memory instead of allocating new storage. This memory is very likely to be hot in the cache (because B just loaded it into the cache for message processing).
