### ISSUE TITLE
More Code Examples (especially network related)

### ISSUE THREAD

**Issue by NLKNguyen** [actor-framework/actor-framework#487]
Hi there,
I'm still trying to wrap my head around the Actor model and get myself familiar with CAF.
Would you mind provide more [hello-world](https://actor-framework.readthedocs.io/en/latest/FirstSteps.html#hello-world-example) kind of examples for newcomers? 
Currently, I'm interested in an example that involves networking such as a simple chat program.

Thanks

**Comment by Neverlord** [comment]
What is wrong with our current [group chat example](https://github.com/actor-framework/actor-framework/tree/3acc6e1/examples/remoting)?

**Comment by NLKNguyen** [comment]
Sweet, thanks. I didn't notice that while reading the documentation.

**Comment by Neverlord** [comment]
Ok. By the way, it's better to learn the API in `develop` instead: https://github.com/actor-framework/actor-framework/tree/develop/examples/remoting

The group part got some convenience changes in the meantime. You no longer need to use the clumsy `middleman().remote_group()`.
