### ISSUE TITLE
Problem with behavior reconnecting in distributed_calculator example 

### ISSUE THREAD

**Issue by duanjp8617** [actor-framework/actor-framework#501]
If only the client side of distributed_calculator is created (no server side), the client side is supposed to stay in behavior reconnecting function and trying to reconnect after receiving "const error& err" message.

But when I do this test, I found that "const error& err" message will never be received by the client side of distributed_calculator. I print some log messages and found out that in the following code (line 119~123 in middleman_actor.cpp):

       // connect to endpoint and initiate handhsake etc.
        auto y = system().middleman().backend().new_tcp_scribe(key.first, port);
        if (!y) {
          rp.deliver(std::move(y.error()));
          return {};
        }

After calling rp.deliver, the message sent to client side of distributed_calculator can't match any of the message handler. 

I try to modify the rp.deliver(std::move(y.error())) into rp.deliver(1) and add a message handler for handling int message in distributed_calculator. That int message could be successfully received. So I guess that there might be some bugs for matching caf::error.

**Comment by duanjp8617** [comment]
I have tested both the v0.15.0a2 and the development branch. All of them have the same issue.

**Comment by duanjp8617** [comment]
This may not a bug. The const error& err message will be captured by the default error message handler. So the message handler defined in behavior reconnect won't react to the error message. Overriding the default error message handler using set_error_handler could solve the problem.

**Comment by Neverlord** [comment]
You are right, it's not a bug in CAF. After reviewing the example, I decided to redesign it completely. I think it is now much easier to comprehend with the FSM-style of connection management.

**Comment by duanjp8617** [comment]
Thank you Neverlord for fixing the problem, but I think there is a similar problem remaining in middleman_actor.cpp.

I think in line 127~150 of middleman_actor.cpp of the develop branch, the middleman_actor handles the error& err message using request.then, causing the error& err message to be captured by the default error message handler instead of the error message handler defined in side request.then. 

This is confirmed by another test, I create a ssh tunnel over 127.0.0.1:5555 (port 5555 of 127.0.0.1 is used by ssh). Then I run distributed_calculator with command:

distributed_calculator -p 5555 -H 127.0.0.1

No error message is captured by error message handler inside the connecting behavior.

**Comment by Neverlord** [comment]
Thanks for the bug report, I'll have a look.

**Comment by Neverlord** [comment]
> I think in line 127~150 of middleman_actor.cpp of the develop branch, the middleman_actor handles the error& err message using request.then, causing the error& err message to be captured by the default error message handler instead of the error message handler defined in side request.then.

@duanjp8617 I'm not quite sure what you are suggesting. The call side (lines 127-150 in `middleman_actor.cpp`) looks good to me. Whether you accept `const error&` or `error&` in the second handler does not matter.

I can confirm that the program hangs indefinitely if the remote side is not responding. For example when connecting the distributed calculator example to a local web server. In this case, CAF waits for the handshake data of the server, while the HTTP server of course awaits the HTTP request. This is an issue in the BASP broker, however. It simply waits forever instead of running into a timeout eventually if the remote side is not responding.

**Comment by duanjp8617** [comment]
@Neverlord That is exactly what I'm suggesting. Is this a bug of BASP broker?

**Comment by Neverlord** [comment]
> Is this a bug of BASP broker?

Yes, the BASP broker should use a timeout for the handshake.

**Comment by Neverlord** [comment]
I'm created a new ticket for the BASP issue.
