### ISSUE TITLE
Implement `make_typed_message`

### ISSUE THREAD

**Issue by Hamdor** [actor-framework/actor-framework#506]
Currently CAF does not allow to send a message to multiple typed actors. A `make_typed_message` function should be implemented to support the use case.

Example:

``` c++
using typed = typed_actor<reacts_to<std::string>>;
std::vector<typed> some_actors = ...;
auto msg = make_typed_message<std::string>("hello");
for (auto& e)
  send(e, msg);
```

**Comment by Neverlord** [comment]
With the messaging redesign, we already have the typed views. So in general it'd be a good fit for 0.18. Implementing this would be very straightforward, but there are lots of places where we'd have to add the overloads for typed messages.

@actor-framework/developers any takers? 🙂

**Comment by Neverlord** [comment]
Branch `issue/506` contains a `typed_message` class. It needs more unit testing and the actual bulk of the work is integrating the class into CAF's messaging. Anyone who wants to take it from here can go ahead. Otherwise this won't make it into 0.18.

**Comment by Neverlord** [comment]
For actor-to-actor-communication, we need the type-erased type `message`. For restoring the type information on the receiver, we have the tuple views. On the sender, we have the new `mail` API now that will keep the type information around as long as necessary. Hence, closing as obsolete.
