### ISSUE TITLE
Create a platform independent timestamp type

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#510]
Along the same lines of `caf::duration`, we need a `caf::timestamp` that captures a clock-independent representation of absolute time. As with the chrono library, the timestamp can use a `caf::duration` relative to the UNIX epoch.

**Comment by nq-ebaratte** [comment]
Are you suggesting that these timestamps would be synchronized across different nodes (compensating for clock differences and drifting)? That would be totally awesome!

**Comment by mavam** [comment]
I also wish magic took place and we have globally synchronized timestamps. 💫 

What I'm suggesting is slightly less ambitious: a platform-indpendent *representation* of a timestamp. The problem with the standard is that `std::chrono::time_point<Clock, Duration>` is that the first template parameter is not portable. All a clock does is getting time relative to an epoch, but the standard doesn't define the epoch. So a `std::chrono::steady_clock` can have vastly different meanings on different systems, even though they have the same value! (Rant: It's unbelievably short-sighted to ratify a standard that has no well-defined semantics in a distributed setting. Is the committee still stuck in 1990?)

With our own `caf::timestamp`, we would at least agree globally on what that timestamp means. Specifically, the epoch would be the UNIX epoch 1970/1/1.

**Comment by firegurafiku** [comment]
@mavam 

Isn't it worth to have time representation and synchronization features put into a separate library, such that it's possible to use it without the rest of CAF? Or maybe Boost already have something for that?

**Comment by firegurafiku** [comment]
How about picking [NTP timestamps][1] (and, in perspective, their synchronization scheme) instead of inventing custom ones? Unfortunately, the NTP epoch is 1900-01-01, which doesn't look so cool and arbitrary as 1970-01-01. :sunglasses:

[1]: https://en.wikipedia.org/wiki/Network_Time_Protocol#Timestamps

**Comment by mavam** [comment]
Means for synchronizing timestamps is not a feature in scope for CAF. Indeed, it's the job of NTP & friends. However, the C++ standard library offers duration and timestamp types. We already have `caf::duration` that represents a portable duration, allowing users to express a time period in an unambiguous way. The idea with `caf::timestamp` is the same: a uniform representation for an absolute point in time. Something that `std::chrono::time_stamp` only does in a *local* fashion. The choice of the UNIX epoch seems natural, because that's the most common timestamp anchor.

**Comment by firegurafiku** [comment]
> Means for synchronizing timestamps is not a feature in scope for CAF.

Surely. But wouldn't it be great if CAF uses synchronization-friendly timestamp format, so it can be easily implemented sometimes? It seems like some people (@nq-ebaratte, anyone else?) feel like it would be cool for CAF to be able to have synced time.

**Comment by nq-ebaratte** [comment]
The idea of synchronized timestamps is clearly not trivial, and probably not in the scope of CAF. For instance, you either need a unique master (how would the system decide who the master is ?), or some sort of P2P consensus for every node to agree upon. Plus the whole jitter compensation algorithms (see eg. NTP).
On our side, we've implemented a bit of clock sync. by restricting the problem:
- we have a unique time master known by everyone
- all nodes are less than 1 ms of each other
- we don't need sub millisecond precision.

**Comment by mavam** [comment]
>  But wouldn't it be great if CAF uses synchronization-friendly timestamp format, so it can be easily implemented sometimes?

That's exactly the point of this ticket. :)

I could see a timestamp synchronization as an "app" on top of CAF in the future. We are already considering a distributed consensus module (based on Raft) that operates on simple key-value store. That would the C and P part of [CAP](https://en.wikipedia.org/wiki/CAP_theorem). Moreover, we have an effort on [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) underway, which would give you A and P of CAP.

With distributed state machines, millisecond synchronization is indeed a realistic target, as consensus module have heartbeats in that order of magnitude. CRDTs can have potentially lower latency due to the absence of synchronization.

**Comment by mavam** [comment]
Instead of rolling our own type, I could see anchoring the clock a sufficient solution. This is how it's done in [date](https://github.com/HowardHinnant/date) to represent the opposite, a host-specific timestamp:

```cpp
struct local_t {};

template <class Duration>
using local_time = std::chrono::time_point<local_t, Duration>;
```

**Comment by Neverlord** [comment]
You mean something along those lines in CAF?

```cpp
struct unix_time {};

using timestamp = std::chrono::time_point<unix_time, std::chrono::duration<uint64_t>, std::nano>;
```

This has the downside of pinning the resolution to nanoseconds. Probably not a big deal. I don't think femtosecond-precision is required any time soon... 64-bit timestamps with nanosecond resolution overflow sometime in the 2260s.

**Comment by mavam** [comment]
> You mean something along those lines in CAF?

Exactly. A 64-bit timestamp as duration with nanosecond precision. That gives us +/- 292 years away from the UNIX epoch. I would like to ditch `caf::duration` entirely, because it doesn't interoperate with `std::chrono`, and instead propose this API:

```cpp
struct unix_time {
  // model clock concept
};

using interval = std::chrono::duration<int64_t, std::nano>;
using timestamp = std::chrono::time_point<unix_time, interval>;
```

I'm not sold on the name (time) `interval`, but didn't want to re-use duration either, because I anticipate frequent use of `using namespace std::chrono`. Do you have a better idea? I had once used `extent`, but find it too obscure. I also like `timespan`, except for its low edit distance to `timestamp`.

(On a related note, I chatted with Howard Hinnant yesterday, and he's fortunately pushing for standardization of the clock's epoch to be the UNIX epoch in future standards. He also mentioned that all vendors he came across use the UNIX epoch consistently, though he had to talk out one vendor to choose a different one.)

**Comment by Neverlord** [comment]
> I would like to ditch `caf::duration` entirely, because it doesn't interoperate with `std::chrono`

I think ditching `caf::duration` is a step down. Right now you can define timeouts in requests and `after(...)` with microseconds, milliseconds, seconds, or minutes. Simply because `caf::duration` has conversion constructors. Using your `interval` instead would force users to use `duration_cast` or to always use nanosecond duration. The alternative is to roll out template magic and automatically call `duration_cast` internally, which makes compile times worse and the code base more complex.

**Comment by mavam** [comment]
Okay, ditching is probably going to far. At the same time, a `nanosecond` timestamp would work just fine in `after(...)` and I'd be curious how much work it really is to support `std::chrono` instead of `caf::duration`. That said, I don't see a reason that would prevent keeping a variant-like `caf::duration` internally. But I don't see much use for it in the public API. I'd just call it `duration_variant` or something obvious to avoid a name clash with `std::chrono::duration`.

What I'm concerned with is to maintain the `chrono` API, i.e., have types that can lean on the powerful existing `duration` and `time_point` arithmetic. All this means is having one extra public type alias `interval`/`timespan` that works with `timestamp`.
