### ISSUE TITLE
using CAF in mac

### ISSUE THREAD

**Issue by zhejiangxiaomai** [actor-framework/actor-framework#513]
I install caf successfully in max os 10.11.6, and use --build-static-only option, so i got two static lib  libcaf_io_static.a and libcaf_core_static.a 。
And I pass the " make test". 
but when i want to build hello_world.cpp by myself in examples that you provide.  I always get 

> zhejiangxiaomai@zhejiangxiaomaideMacBook-Pro caf$ g++ hello_world.cpp libcaf_core_static.a libcaf_io_static.a -o hello
hello_world.cpp:4:10: fatal error: 'caf/all.hpp' file not found
#include "caf/all.hpp"
         ^
1 error generated. 

please provide some guides for me , thanks

**Comment by josephnoir** [comment]
Hi, CAF installs to `/usr/local/` per default. Have you tried passing the related include dir to the compiler (`-I/usr/local/include`)?

**Comment by Neverlord** [comment]
You can change the default with `./configure --prefix=...`. If you are using CMake in your project, you can alternatively use the `FindCAF.cmake` [1] module and tell CMake directly where to find CAF.

[1] https://github.com/actor-framework/actor-framework/blob/master/cmake/FindCAF.cmake
