### ISSUE TITLE
Multiplexing in blocking actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#516]
Mixing request/response communication with regular actor messaging is not well supported by the current interface of `blocking_actor`. We need a convenient way to achieve multiplexing in blocking actors in the same way event-based actors do with `.then`.

**Comment by skorokhod** [comment]
the same issu needed for actor_widget & actor_companion

**Comment by Neverlord** [comment]
Since opening this, we generally advise users to not use blocking actor in the first place with the exception of `scoped_actor`. Regarding the widget & companion classes: we have recently added a cleaner but similar abstraction in the incubator: https://github.com/actor-framework/incubator/blob/master/libcaf_net/caf/net/actor_shell.hpp. Maybe we should just move the actor shell to the core to replace the companion class (and re-implement the widget example with the shell).
