### ISSUE TITLE
Issue with offsetof under Linux/Clang/libc++

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#519]
While setting up Travis CI for Broker, I encountered an issue with Clang and libc++ under Linux (Trusty):

```
[  0%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_actor.cpp.o
In file included from /home/travis/build/bro/broker/caf/libcaf_core/src/abstract_actor.cpp:33:
In file included from /home/travis/build/bro/broker/caf/libcaf_core/caf/actor_system.hpp:34:
In file included from /home/travis/build/bro/broker/caf/libcaf_core/caf/make_actor.hpp:29:
/home/travis/build/bro/broker/caf/libcaf_core/caf/actor_storage.hpp:49:28: error: 
      'actor_storage' does not refer to a value
    static_assert(offsetof(actor_storage, ctrl) == 0,
                           ^
/home/travis/build/bro/broker/caf/libcaf_core/caf/actor_storage.hpp:40:7: note: 
      declared here
class actor_storage {
      ^
/home/travis/build/bro/broker/caf/libcaf_core/caf/actor_storage.hpp:52:28: error: 
      'actor_storage' does not refer to a value
    static_assert(offsetof(actor_storage, data) == CAF_CACHE_LINE_SIZE,
                           ^
/home/travis/build/bro/broker/caf/libcaf_core/caf/actor_storage.hpp:40:7: note: 
      declared here
class actor_storage {
      ^
2 errors generated.
```

Is there an elegant fix other than ifdef'ing the static assertion?

**Comment by mavam** [comment]
I tried a few obvious fixes, e.g., to create a static constexpr member variable, adding an explicit template parameter to `actor_storage<T>`. None worked. 😒

**Comment by Neverlord** [comment]
Unfortunately there is no way to implement offsetof in standard-legal C or C++. This is why there is this macro in the standard...

However, if you look at the source file, there is a 4th check that is commented out. Pointer arithmetic (even if every pointer is constexpr) is not considered to be constexpr by some compilers. Clang does compile the 4th check, so maybe we can get around offsetof on Clang by using constexpr pointer arithmetic.

Check 1: see if reinterpret_cast'ing an actor storage pointer to actor_control_block* points to the same address as ptr->ctrl.

Check 2: cast to void*, add CAF_CACHE_LINE_SIZE and see if the address is equal to &(ptr->data).

Ugly, but might work (on Clang).

**Comment by mavam** [comment]
> lang does compile the 4th check, so maybe we can get around offsetof on Clang by using constexpr pointer arithmetic.

I like that thought in general...

> Check 1: see if reinterpret_cast'ing an actor storage pointer to actor_control_block* points to the same address as ptr->ctrl.

...but a constexpr `reinterpret_cast` is UB in C++11, IIRC. In the current standard draft, `reinterpret_cast` and certain pointer arithmetic are explicitly forbidden ([§5.20.2](http://eel.is/c++draft/expr.const#2))

**Comment by Neverlord** [comment]
> UB in C++11, IIRC

UB is standard-speech for "whatever the compiler chooses to do". In this case, the only thing that matters is what Clang does. We wouldn't have this discussion if Clang followed the standard and correctly implemented `offsetof`. So either they allow for *some* kind of non-standard-compliant workaround or disabling the check is the only viable solution.

**Comment by mavam** [comment]
> However, if you look at the source file, there is a 4th check that is commented out. Pointer arithmetic (even if every pointer is constexpr) is not considered to be constexpr by some compilers. Clang does compile the 4th check, so maybe we can get around offsetof on Clang by using constexpr pointer arithmetic.

Enabling the 4th check seems to work on Linux/Clang.

> Check 1: see if reinterpret_cast'ing an actor storage pointer to actor_control_block* points to the same address as ptr->ctrl.
> 
> Check 2: cast to void*, add CAF_CACHE_LINE_SIZE and see if the address is equal to &(ptr->data).

This doesn't work, because `reinterpret_cast` is not `constexpr` (unlike `static_cast`). I even tried [a nasty hack](http://stackoverflow.com/a/12812237/1170277), but the compiler tells you right in your face nowadays that a `reinterpret_cast` is disallowed in a `constexpr` function.

**Comment by Neverlord** [comment]
Thanks for double-checking. Hm, I don't see how we can emulate `offsetof` without `constexpr` `reinterpret_cast`. Maybe it's worth considering putting a runtime `assert` into `spawn`. In this way we would provide at the very least some diagnostic (for debug builds).

**Comment by Neverlord** [comment]
Unfortunately there is no way to implement offsetof in standard-legal C or C++. This is why there is this macro in the standard...

However, if you look at the source file, there is a 4th check that is commented out. Pointer arithmetic (even if every pointer is constexpr) is not considered to be constexpr by some compilers. Clang does compile the 4th check, so maybe we can get around offsetof on Clang by using constexpr pointer arithmetic.

Check #1: see if reinterpret_cast'ing an actor storage pointer to actor_control_block* points to the same address as ptr->ctrl.

Check #2: cast to void*, add CAF_CACHE_LINE_SIZE and see if the address is equal to &(ptr->data).

Ugly, but might work (on Clang).

    Dominik
