### ISSUE TITLE
Improving forward/backwards compatability and delegations

### ISSUE THREAD

**Issue by Ulimo** [actor-framework/actor-framework#520]
Hi!
I have been working on creating a prototype delegation class for CAF for a few days now to ease the usage of delegations. But I have come to a situation where I might think a better solution would be possible if some core functionality is added into CAF message handling system.

The main motivation behind this was at first to simplify the workflow when adding delegations to other actors and being able to mass-add several message-handlers.

My first solution used the statically typed message classes, (caf::typed_actor).
To add a delegation you wrote for instance:

`delegate_to<peersampling_type>(peersampler);`

Which would delegate all messages that are defined in the peersampling_type to the peersampler.
This type of solution was quite limited though since it does not allow for conditions to consider when to delegate and when not to. So I implemented condition functions which allows the user to specify when the delegation should be triggered or not:

```
delegate_to<peersampling_type>(peersampler, [](_, int v, _R){
   return v == 10;
 });
```

This example uses the implementation of a dont_care class which is typedefed to "_", and a rest class (typedefed "_R") which then means that the condition function checks that if the second variable in a function is an integer and it is equal to 10 the message should be delegated. The rest class means that it will trigger on functions with more input than 2 variables. The dont care functionality and rest class is influenced by Prolog and Erlangs function handling.

My problem came up when working with this system, it is implementing functionality which is not usable in normal message handlers. I thought that a better solution would be to implement a dont_care class and rest class aswell as optional parameters in CAF message handling system. 

The idea is then to allow the following message handlers:
```c++
//Simple delegation to delegate all messages that start with peersampling_atom to the peersampler.
b.assign([=](peersampling_atom, _R){
   this->delegate(peersampler, peersampling_atom::value, _R);
},
//Message transformations
[=](flood_atom, _, int TTL, _R){
   if(TTL == 0)
      return;
   this->delegate(neighbor, flood_atom::value, _, TTL - 1, _R);
},
//Optional parameters to allow older messages to still be recievable
[=](backwardcompatible_atom, int a, int b, int newParam = -1, int newParam2 = 2){
    if(newParam == -1) //Old message
    { ... }
},
//A forward compatible message, can recieve messages with additional input but skips the new parameters
[=](forwardscompatible_atom, int a, int b, _R){
    
});
```

The addition of optional parameters and rest class would be great to allow forwards and backwards compatability and smart message design to allow rolling upgrades etc.

I have started investigating possible solutions for this, but would like to check if I might have missed something and there may be a better solution to solve this or if this is perhaps something that would help many?

**Comment by Neverlord** [comment]
Did you consider a custom message type to achieve backward/forward compatibility? A struct allows you to add new fields without breaking existing message handlers.

You only need to put some extra effort into serializing/deserializing such types if your requirement is that multiple versions of a single message type are allowed to exist. However, libraries such as protobuf already do this for you and give you a lot of flexibility in this regard.

We got rid of more advanced pattern matching facilities in CAF over the years because they add runtime overhead to all actors and complexity to the library (not to mention the cryptic compiler error messages users can get).

**Comment by Ulimo** [comment]
Ah I see!
So I guess that you are not interested in having such a system in CAF?
Would you think that the first solution is better then to solve easier to use mass-delegations? And is that something that would be imported into CAF?

**Comment by Neverlord** [comment]
> So I guess that you are not interested in having such a system in CAF?

At this point I am just asking questions to see what alternatives exist.

> `delegate_to<peersampling_type>(peersampler);`

What would this thing return? A `message_handler`? A possible alternative solution I see is to install the delegation logic as default handler to keep it entirely out of the actor logic itself.
