### ISSUE TITLE
how to avoid "too many open files" about sockets when i use remote_actor in caf 1.5 

### ISSUE THREAD

**Issue by zhejiangxiaomai** [actor-framework/actor-framework#522]
hello, i meet a problem when i use remote_actor.  
What i want to know is how to avoid "too many open files" problem about sockets.  Because i can't create handler to save a remote_actor. **So i have to create remote_actor when i want to send a remote_actor. So it cause my problem.**

When CAF version is 0.14. for example,
i will create a handler for one remote_actor. and **everything is fine**. if i want to send it, i just need to send to master_actor_.
class A{
   A(){
       master_actor_ =
          caf::io::remote_actor(master_addr_.first, master_addr_.second);  
     }
protected :
   actor master_actor_;
}

But, in caf 0.15 version, i can't use it anymore. And my code example is show as following.

    #include <string>
    #include <iostream>
    #include "caf/all.hpp"
    #include "caf/io/all.hpp"
    using std::endl;
    using std::string;
    using namespace caf;

    using OkAtom = caf::atom_constant<caf::atom("ok")>;
    using AskExchAtom = caf::atom_constant<caf::atom("askEx")>;

    struct ExchangeID{
    ExchangeID():exchange_id(0),partition_offset(0){};
    ExchangeID(unsigned long long int exchange_id,unsigned         
        partition_offset):exchange_id(exchange_id),partition_offset(partition_offset){};
    bool operator==(const ExchangeID& r)const{
        return exchange_id==r.exchange_id&&partition_offset==r.partition_offset;
    }
     unsigned long long int exchange_id;
      unsigned partition_offset;
    };

    template <class Inspector>
    typename Inspector::result_type inspect(Inspector& f, ExchangeID& x) {
        return f(caf::meta::type_name("ExchangeID"), x.exchange_id, x.partition_offset);
    }

    class CafConfig : public actor_system_config {
    public:
    CafConfig() {
    load<io::middleman>();
    add_message_type<ExchangeID>("ExchangeID");
     }
    };

    class simple_mirror : public event_based_actor {
    public:
        simple_mirror(actor_config& cfg) : event_based_actor(cfg){ }
        ~simple_mirror() { }
       behavior make_behavior() override {
        return {
          [=](AskExchAtom, ExchangeID exid)-> message {
            std::cout<<"haha"<<std::endl;
            return make_message(OkAtom::value,"127.0.0.2", "12000");
             }
          };
        }
      };

    class A{
    public:
    A():master_actor_(actor(unsafe_actor_handle_init)){
         CafConfig* cfg = new CafConfig();
         actor_system system{*dynamic_cast<actor_system_config *>(cfg)};
         master_actor_ = system.middleman().remote_actor("219.228.147.11",28000);
         if (!master_actor_) {
              std::cout <<"failed!" << std::endl;
             }
         };
        caf::expected<caf::actor> master_actor_;
    };

    int main(){
       ExchangeID exchange_id;
       CafConfig* cfg = new CafConfig();
       actor_system system{*dynamic_cast<actor_system_config *>(cfg)};
   
      auto mirror = system.spawn<simple_mirror>();
     system.middleman().publish(mirror,28000,"219.228.147.11",true); 
     A *a = new A();
     scoped_actor self{system};
     self->request((*(*a).master_actor_), std::chrono::seconds(5), AskExchAtom::value,
                 exchange_id)
        .receive([&](OkAtom, const string& ip, const string& port) {
                   std::cout << "ip ~~~:" << ip << "port ~~~"
                             << port << endl;
                },
                 [&](const error& err) {
                   std::cout << self->system().render(err) << std::endl;
                   std::cout << "asking exchange connection info, but timeout "
                          "5s!!! times= " << endl;
                 });
        }
This code can be compiled , but i don't  know why the remote_actor can't receive and feedback. what do i miss when i use remote_actor ? **please help me to solve "too many open files" problem.**

**Comment by Neverlord** [comment]
This code has memory leaks since `CatConfig` objects are never deleted. Your remote actor stays unresponsive because you use a short-lived actor system in the constructor of A. The system will shut down its middleman in its destructor. Also, casting to a supertype with `dynamic_cast` is unnecessary.

Please look at the 0.15 manual and examples. At the very least:

- Use a single actor system in your application
- Place the config on the stack to have the system and the config go out of scope at the end of main

**Comment by zhejiangxiaomai** [comment]
thank you!
