### ISSUE TITLE
Accessing remote groups hangs indefinitely if target host fails during connect

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#524]
Via https://groups.google.com/forum/#!topic/actor-framework/PmnpxBdCN24

> I've run into an edge-case scenario in CAF 0.15.1 where, if I kill the process hosting a group at the same time that I try to get the group, it hangs trying to get the group.
> 
> `auto groupExp = this->actorSystem.system().groups().get("remote", connectionString);`
> 
> I haven't been able to pinpoint exactly where in the CAF code it happens because if I use the debugger it fails correctly.
> 
> There's no way to set a timeout on this call.  Is there another way to get the group where I can set a timeout?

**Comment by sourcedelica** [comment]
Our scenario is a primary/backup setup.  The "client" actor is connected to both primary and backup.  I execute 

kill primary; sleep 1; kill backup

As it's failing over to the backup the backup gets killed.  It is an actor thread handling a down msg that gets hung.

**Comment by sourcedelica** [comment]
I got your message on the mailing list - thanks.  Actually that makes sense.  I believe we have seen the same sort of hang when trying to get a remote actor at the same time the remote system gets killed.  But we don't have a reproducing test case for it yet.  Probably today.  I'll let you know.

**Comment by Neverlord** [comment]
Groups are going to get deprecated in 0.19. Closing.
