### ISSUE TITLE
Segment fault when enabling log

### ISSUE THREAD

**Issue by ufownl** [actor-framework/actor-framework#527]
The test case "char_name" of test "stateful_actor" will crash when enabling log. I debugged it and reviewed the backtrace:
```C++
frame #4: 0x0000000102da6110 libcaf_core.0.15.2.dylib`caf::scheduled_actor::launch(this=0x0000000103307f30, eu=0x00007fff5fbfa780, lazy=false, hide=false) + 176 at scheduled_actor.cpp:166
   163 	}
   164 	
   165 	void scheduled_actor::launch(execution_unit* eu, bool lazy, bool hide) {
-> 166 	  CAF_LOG_INIT_EVENT(name(), lazy, hide);
   167 	  CAF_LOG_TRACE(CAF_ARG(lazy) << CAF_ARG(hide));
   168 	  CAF_ASSERT(!getf(is_blocking_flag));
   169 	  if (!hide)
```
And then I reviewed the code of `scheduled_actor` and `stateful_actor`, I found that if the state of `stateful_actor` has member named "name", the member function "name" will return that menber in the state. But at that time, the state of `stateful_actor` has not construct.

**Comment by sourcedelica** [comment]
I've seen this too.

**Comment by Neverlord** [comment]
I apologize for the inconvenience. I couldn't fix it Friday in time.
