### ISSUE TITLE
SIGSEGV calling set_down_handler from a down_handler

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#528]
// in an event_based_actor
    set_down_handler([=] (const caf::down_msg& d) {
        set_down_handler([=] (const caf::down_msg&) {});
        set_default_handler(caf::skip);   // <-- poof!
    });

It seems one can't "nest" down_handlers. The code above segfaults on `set_default_handler()` - it would segfault on any method on the actor.
Looking at the stack trace, I understand that we try to access a non-static member of the first lambda (`this`) after the lambda has been deleted (when re-assigning `this->down_handler_`).

I am not sure if this is something that could be protected against, or just documented: *Don't nest* `set_XXXX_handlers`!

**Comment by Neverlord** [comment]
We can protect against this by swapping the default handler into a temporary before calling it and only swapping it back if it hasn't been replaced by the user. I think it's reasonable to do so and avoid segfaults whenever we can.

**Comment by Neverlord** [comment]
@nq-ebaratte can you check if 57257de90b2d9e3dd036acca64abf5fa115508fe fixes the issue?

**Comment by nq-ebaratte** [comment]
It does, great work.

A related matter: setting a handler to an empty `std::function` (nullptr) segfaults when the handler is called.

I'd recommend that either:
- in set_xxx_handler, set xxx_handler to default_xxx_handler if an empty function is set. 
- or in call_handler, check that the handler is non empty before calling it

**Comment by Neverlord** [comment]
Good suggestion. Fixed in https://github.com/actor-framework/actor-framework/commit/1031dae6ec89dc39738fc7ee7614946d953c3b78.
