### ISSUE TITLE
std::bad_alloc in basp_broker

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#529]
While running performance tests involving several nodes, we eventually get an unhandled exception in basp_broker:

    *** unhandled exception: [id: 5, name: basp_broker, exception typeid: St9bad_alloc]: std::bad_alloc

Running in gdb allows to get the stack trace, and to identify the source of the issue: the buffer in which message sent to other nodes are serialized goes too large (we get the crash when it tries to expand to 5GB...).
Is it a symptom of another issue with our application? eg. data is enqueued on the network faster than it can be sent/received on the other side ?

Relevant stack trace (on 0.15.2):

    (gdb) where
    #0  0x00007ffff71238bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #1  0x00007ffff7123ebc in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #2  0x000000000186f2e2 in __gnu_cxx::new_allocator<char>::allocate (this=0x7fffdc008c08, __n=5350728768)
        at /usr/include/c++/4.9/ext/new_allocator.h:104
    #3  0x000000000186ffb4 in std::allocator_traits<std::allocator<char> >::allocate (__a=..., __n=5350728768)
        at /usr/include/c++/4.9/bits/alloc_traits.h:488
    #4  0x000000000186e99e in std::_Vector_base<char, std::allocator<char> >::_M_allocate (this=0x7fffdc008c08, __n=5350728768)
        at /usr/include/c++/4.9/bits/stl_vector.h:170
    #5  0x000000000196e0f4 in std::vector<char, std::allocator<char> >::_M_emplace_back_aux<char const&> (this=0x7fffdc008c08)
        at /usr/include/c++/4.9/bits/vector.tcc:412
    #6  0x000000000196e06b in std::vector<char, std::allocator<char> >::push_back (this=0x7fffdc008c08, __x=@0x7fffe7fddd76: 52 '4')
        at /usr/include/c++/4.9/bits/stl_vector.h:923
    #7  0x000000000196dfee in std::back_insert_iterator<std::vector<char, std::allocator<char> > >::operator= (this=0x7fffe7fddb40, 
        __value=@0x7fffe7fddd76: 52 '4') at /usr/include/c++/4.9/bits/stl_iterator.h:439
    #8  0x000000000196df6e in std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<char const*, std::back_insert_iterator<std::vector<char, std::allocator<char> > > > (__first=0x7fffe7fddd76 "4", __last=0x7fffe7fddd78 "", __result=...)
        at /usr/include/c++/4.9/bits/stl_algobase.h:336
    #9  0x000000000196ddb6 in std::__copy_move_a<false, char const*, std::back_insert_iterator<std::vector<char, std::allocator<char> > > >
        (__first=0x7fffe7fddd74 ":54", __last=0x7fffe7fddd78 "", __result=...) at /usr/include/c++/4.9/bits/stl_algobase.h:398
    #10 0x000000000196da7c in std::__copy_move_a2<false, char const*, std::back_insert_iterator<std::vector<char, std::allocator<char> > > > (__first=0x7fffe7fddd74 ":54", __last=0x7fffe7fddd78 "", __result=...) at /usr/include/c++/4.9/bits/stl_algobase.h:436
    #11 0x000000000196d3af in std::copy<char const*, std::back_insert_iterator<std::vector<char, std::allocator<char> > > > (
        __first=0x7fffe7fddd74 ":54", __last=0x7fffe7fddd78 "", __result=...) at /usr/include/c++/4.9/bits/stl_algobase.h:468
    #12 0x000000000196c19a in std::__copy_n<char const*, long, std::back_insert_iterator<std::vector<char, std::allocator<char> > > > (
        __first=0x7fffe7fddd74 ":54", __n=4, __result=...) at /usr/include/c++/4.9/bits/stl_algo.h:779
    #13 0x000000000196abe6 in std::copy_n<char const*, long, std::back_insert_iterator<std::vector<char, std::allocator<char> > > > (
        __first=0x7fffe7fddd74 ":54", __n=4, __result=...) at /usr/include/c++/4.9/bits/stl_algo.h:804
    #14 0x0000000001968ed8 in caf::containerbuf<std::vector<char, std::allocator<char> > >::xsputn (this=0x7fffe7fde590, 
        s=0x7fffe7fddd74 ":54", n=4)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/streambuf.hpp:205
    #15 0x000000000196120a in caf::stream_serializer<caf::containerbuf<std::vector<char, std::allocator<char> > > >::apply_raw (
        this=0x7fffe7fde580, num_bytes=4, data=0x7fffe7fddd74)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/stream_serializer.hpp:97
    #16 0x000000000196a7bf in caf::stream_serializer<caf::containerbuf<std::vector<char, std::allocator<char> > > >::apply_int<unsigned int> (this=0x7fffe7fde580, x=976565248)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/stream_serializer.hpp:184
    #17 0x0000000001968ab8 in caf::stream_serializer<caf::containerbuf<std::vector<char, std::allocator<char> > > >::apply_builtin (
        this=0x7fffe7fde580, type=caf::data_processor<caf::serializer>::float_v, val=0x7fffdb51d6e8)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/stream_serializer.hpp:140
    #18 0x00000000013ab2ad in caf::data_processor<caf::serializer>::apply<float> (x=@0x7fffdb51d6e8: 0.000691235065, this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:141
    #19 caf::data_processor<caf::serializer>::operator()<float&, float&> (x=@0x7fffdb51d6e8: 0.000691235065, this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:512
    #20 caf::data_processor<caf::serializer>::operator()<float&, float&, float&> (x=@0x7fffdb51d6e4: 0.000691235065, this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:513
    #21 caf::data_processor<caf::serializer>::operator()<float&, float&, float&, float&> (x=@0x7fffdb51d6e0: 0.000691235065, 
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:513
    #22 caf::data_processor<caf::serializer>::operator()<float&, float&, float&, float&> (this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:487
    #23 caf::inspect<caf::serializer> (f=..., q=...) at /my-workspace/Infra/include/NQ/CAFTypes.hpp:43
    #24 0x00000000013f48db in caf::data_processor<caf::serializer>::apply<glm::tquat<float, (glm::precision)0> > (x=..., 
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:460
    #25 caf::data_processor<caf::serializer>::operator()<glm::tquat<float, (glm::precision)0>&, glm::tvec3<double, (glm::precision)0>&, unsigned long&, unsigned long&, unsigned int&, float&, unsigned long&, glm::tvec3<double, (glm::precision)0>&, glm::tquat<float, (glm::precision)0>&, NQ::TimePoint&> (x=..., this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:512
    #26 caf::data_processor<caf::serializer>::operator()<glm::tvec3<double, (glm::precision)0>&, glm::tquat<float, (glm::precision)0>&, glm::tvec3<double, (glm::precision)0>&, unsigned long&, unsigned long&, unsigned int&, float&, unsigned long&, glm::tvec3<double, (glm::precision)0>&, glm::tquat<float, (glm::precision)0>&, NQ::TimePoint&> (x=..., this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:513
    #27 caf::data_processor<caf::serializer>::operator()<glm::tvec3<double, (glm::precision)0>&, glm::tquat<float, (glm::precision)0>&, glm::tvec3<double, (glm::precision)0>&, unsigned long&, unsigned long&, unsigned int&, float&, unsigned long&, glm::tvec3<double, (glm::precision)0>&, glm::tquat<float, (glm::precision)0>&, NQ::TimePoint&> (this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:487
    #28 caf::inspect<caf::serializer> (f=..., x=...)
        at /my-workspace/Infra/../Shared/include/NQ/PlayerUpdate.hpp:96
    #29 0x000000000142eb80 in caf::data_processor<caf::serializer>::apply<NQ::PlayerUpdate> (x=..., this=0x7fffe7fde580)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:460
    #30 caf::data_processor<caf::serializer>::consume_range<std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> > > (xs=..., 
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:235
    #31 std::enable_if<caf::serializer::reads_state&&(!caf::detail::is_byte_sequence<std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> > >::value), caf::error>::type caf::data_processor<caf::serializer>::apply_sequence<caf::serializer, std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> > >(caf::serializer&, std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> >&)::{lambda()#2}::operator()() const (__closure=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:288
    #32 caf::error::eval<caf::data_processor<Derived>::apply_sequence(D&, T&) [with D = caf::serializer; T = std::vector<NQ::PlayerUpdate>; Derived = caf::serializer; typename std::enable_if<(D:: reads_state && (! caf::detail::is_byte_sequence<T>::value)), caf::error>::type = caf::error]::<lambda()>, caf::data_processor<Derived>::apply_sequence(D&, T&) [with D = caf::serializer; T = std::vector<NQ::PlayerUpdate>; Derived = caf::serializer; typename std::enable_if<(D:: reads_state && (! caf::detail::is_byte_sequence<T>::value)), caf::error>::type = caf::error]::<lambda()> > (f=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/error.hpp:178
    #33 caf::error::eval<caf::data_processor<Derived>::apply_sequence(D&, T&) [with D = caf::serializer; T = std::vector<NQ::PlayerUpdate>; Derived = caf::serializer; typename std::enable_if<(D:: reads_state && (! caf::detail::is_byte_sequence<T>::value)), caf::error>::type = caf::error]::<lambda()>, caf::data_processor<Derived>::apply_sequence(D&, T&) [with D = caf::serializer; T = std::vector<NQ::PlayerUpdate>; Derived = caf::serializer; typename std::enable_if<(D:: reads_state && (! caf::detail::is_byte_sequence<T>::value)), caf::error>::type = caf::error]::<lambda()>, caf::data_processor<Derived>::apply_sequence(D&, T&) [with D = caf::serializer; T = std::vector<NQ::PlayerUpdate>; Derived = caf::serializer; typename std::enable_if<(D:: reads_state && (! caf::detail::is_byte_sequence<T>::value)), caf::error>::type = caf::error]::<lambda()> > (f=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/error.hpp:179
    #34 caf::data_processor<caf::serializer>::apply_sequence<caf::serializer, std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> > > (xs=..., self=...) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:289
    #35 caf::data_processor<caf::serializer>::apply<std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> > > (xs=..., 
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:343
    #36 caf::data_processor<caf::serializer>::operator()<std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> >&> (x=..., 
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:512
    #37 caf::data_processor<caf::serializer>::operator()<std::vector<NQ::PlayerUpdate, std::allocator<NQ::PlayerUpdate> >&> (
        this=0x7fffe7fde580) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:487
    #38 caf::inspect<caf::serializer> (f=..., x=...)
        at /my-workspace/Infra/../Shared/include/NQ/PlayerUpdate.hpp:104
    #39 0x000000000142eda0 in caf::data_processor<caf::serializer>::apply<NQ::PlayerUpdates> (x=..., this=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:460
    #40 caf::data_processor<caf::serializer>::operator()<NQ::PlayerUpdates&> (this=<optimized out>, x=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:512
    #41 0x00000000015c99a8 in caf::detail::tuple_inspect_delegate<1ul, 1ul, std::tuple<caf::atom_value, NQ::PlayerUpdates>, caf::serializer> (data=..., f=...) at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/detail/tuple_vals.hpp:48
    #42 0x00000000015c9bce in caf::detail::tuple_vals_impl<caf::detail::message_data, caf::atom_value, NQ::PlayerUpdates>::dispatch<caf::serializer> (f=..., pos=<optimized out>, this=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/detail/tuple_vals.hpp:176
    #43 caf::detail::tuple_vals_impl<caf::detail::message_data, caf::atom_value, NQ::PlayerUpdates>::save (this=<optimized out>, 
        pos=<optimized out>, sink=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/detail/tuple_vals.hpp:167
    #44 0x000000000182daad in caf::<lambda()>::operator()(void) const (__closure=0x7fffe7fde380)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/message.cpp:412
    #45 0x000000000182dba8 in caf::<lambda()>::operator()(void) const (__closure=0x7fffe7fde340)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/message.cpp:419
    #46 0x000000000182f5cf in caf::error::eval<caf::inspect(caf::serializer&, caf::message&)::<lambda()>, caf::inspect(caf::serializer&, caf::message&)::<lambda()> >(<unknown type in /home/ubuntu/build/dual-node, CU 0x3b42668, DIE 0x3b70f0e>) (
        f=<unknown type in /home/ubuntu/build/dual-node, CU 0x3b42668, DIE 0x3b70f0e>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/error.hpp:178
    #47 0x000000000182eda6 in caf::error::eval<caf::inspect(caf::serializer&, caf::message&)::<lambda()>, caf::inspect(caf::serializer&, caf::message&)::<lambda()>, caf::inspect(caf::serializer&, caf::message&)::<lambda()> >(<unknown type in /home/ubuntu/build/dual-node, CU 0x3b42668, DIE 0x3b6e380>) (f=<unknown type in /home/ubuntu/build/dual-node, CU 0x3b42668, DIE 0x3b6e380>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/error.hpp:179
    #48 0x000000000182dece in caf::inspect (sink=..., msg=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/message.cpp:420
    #49 0x00000000013c4ba0 in caf::data_processor<caf::serializer>::apply<caf::message> (x=..., this=<optimized out>)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:460
    #50 caf::data_processor<caf::serializer>::operator()<caf::message&> (this=<optimized out>, x=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:512
    #51 0x000000000191093a in caf::data_processor<caf::serializer>::operator()<std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::message&> (this=0x7fffe7fde580, 
        x=std::vector of length 0, capacity 0)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/data_processor.hpp:513
    #52 0x000000000195f669 in caf::io::basp::instance::<lambda(caf::serializer&)>::operator()(caf::serializer &) const ( __closure=0x7fffe7fde6c8, sink=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/instance.cpp:359
    #53 0x0000000001960a7d in caf::callback_impl<caf::io::basp::instance::dispatch(caf::execution_unit*, const strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block> >&, const strong_actor_ptr&, caf::message_id, const caf::message&)::<lambda(caf::serializer&)>, caf::serializer&>::operator()(caf::serializer &) (this=0x7fffe7fde6c0, xs#0=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/callback.hpp:59
    #54 0x000000000195fac3 in caf::io::basp::instance::write (this=0x23ba4f0, ctx=0x23b6180, 
        buf=std::vector of length 2675364384, capacity 2675364384 = {...}, hdr=..., pw=0x7fffe7fde6c0)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/instance.cpp:380
    #55 0x000000000195f8d2 in caf::io::basp::instance::dispatch (this=0x23ba4f0, ctx=0x23b6180, sender=..., forwarding_stack=std::vector of length 0, capacity 0, receiver=..., mid=..., msg=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/instance.cpp:364
    #56 0x00000000018fab72 in caf::io::basp_broker::<lambda(caf::forward_atom, caf::strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::strong_actor_ptr&, caf::message_id, const caf::message&)>::operator()(caf::forward_atom, caf::strong_actor_ptr &, const std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > > &, caf::strong_actor_ptr &, caf::message_id, const caf::message &) const (__closure=0x7fffdc000d08, src=..., fwd_stack=std::vector of length 0, capacity 0, dest=..., mid=..., msg=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/basp_broker.cpp:538
    #57 0x0000000001907bf4 in caf::lfinvoker<true, caf::io::basp_broker::make_behavior()::<lambda(caf::forward_atom, caf::strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::strong_actor_ptr&, caf::message_id, const caf::message&)> >::operator()<caf::atom_constant<(caf::atom_value)68982408375785u>&, caf::intrusive_ptr<caf::actor_control_block>&, std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::intrusive_ptr<caf::actor_control_block>&, caf::message_id&, caf::message&>(void) (this=0x7fffe7fde930)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/match_case.hpp:94
    #58 0x0000000001906f22 in caf::detail::apply_args<caf::lfinvoker<true, caf::io::basp_broker::make_behavior()::<lambda(caf::forward_atom, caf::strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block> >&, caf::strong_actor_ptr&, caf::message_id, const caf::message&)> >, 0l, 1l, 2l, 3l, 4l, 5l, caf::detail::pseudo_tuple<caf::atom_constant<(caf::atom_value)68982408375785u>, caf::intrusive_ptr<caf::actor_control_block>, std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >, caf::intrusive_ptr<caf::actor_control_block>, caf::message_id, caf::message> >(caf::lfinvoker<true, caf::io::basp_broker::make_behavior()::<lambda(caf::forward_atom, caf::strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::strong_actor_ptr&, caf::message_id, const caf::message&)> > &, caf::detail::int_list<0l, 1l, 2l, 3l, 4l, 5l>, caf::detail::pseudo_tuple<caf::atom_constant<(caf::atom_value)68982408375785>, caf::intrusive_ptr<caf::actor_control_block>, std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >, caf::intrusive_ptr<caf::actor_control_block>, caf::message_id, caf::message> &) (f=..., tup=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/detail/apply_args.hpp:40
    #59 0x00000000019058d3 in caf::trivial_match_case<caf::io::basp_broker::make_behavior()::<lambda(caf::forward_atom, caf::strong_actor_ptr&, const std::vector<caf::intrusive_ptr<caf::actor_control_block>, std::allocator<caf::intrusive_ptr<caf::actor_control_block> > >&, caf::strong_actor_ptr&, caf::message_id, const caf::message&)> >::invoke(caf::detail::invoke_result_visitor &, caf::type_erased_tuple &)    (this=0x7fffdc000cf8, f=..., xs=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/match_case.hpp:164
    #60 0x00000000017e84f4 in caf::detail::behavior_impl::invoke (this=0x7fffdc000bc0, f=..., xs=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/behavior_impl.cpp:105
    #61 0x00000000017ed959 in caf::behavior::operator() (this=0x7fffdc000e00, f=..., xs=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/caf/behavior.hpp:111
    #62 0x0000000001846475 in caf::scheduled_actor::consume (this=0x23b9ff0, x=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/scheduled_actor.cpp:453
    #63 0x0000000001846a39 in caf::scheduled_actor::reactivate (this=0x23b9ff0, x=...)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/scheduled_actor.cpp:553
    #64 0x00000000018451dd in caf::scheduled_actor::resume (this=0x23b9ff0, ctx=0x23b6180, max_throughput=18446744073709551615)
        at /my-workspace/ThirdParty/actor-framework/libcaf_core/src/scheduled_actor.cpp:228
    #65 0x00000000019244bb in caf::io::abstract_broker::resume (this=0x23b9ff0, ctx=0x23b6180, mt=18446744073709551615)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/abstract_broker.cpp:213
    #66 0x00000000018fc03f in caf::io::basp_broker::resume (this=0x23b9ff0, ctx=0x23b6180, mt=18446744073709551615)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/basp_broker.cpp:688
    #67 0x000000000192bb8f in caf::io::network::pipe_reader::handle_event (this=0x23b61e8, op=caf::io::network::operation::read)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/default_multiplexer.cpp:1043
    #68 0x000000000192a1df in caf::io::network::default_multiplexer::handle_socket_event (this=0x23b6180, fd=5, mask=1, ptr=0x23b61e8)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/default_multiplexer.cpp:675
    #69 0x0000000001929b61 in caf::io::network::default_multiplexer::run (this=0x23b6180)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/default_multiplexer.cpp:342
    #70 0x000000000188abc4 in caf::io::middleman::<lambda()>::operator()(void) const (__closure=0x23b9178)
        at /my-workspace/ThirdParty/actor-framework/libcaf_io/src/middleman.cpp:267
    #71 0x00000000018912ce in std::_Bind_simple<caf::io::middleman::start()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (
        this=0x23b9178) at /usr/include/c++/4.9/functional:1700
    #72 0x0000000001890ea4 in std::_Bind_simple<caf::io::middleman::start()::<lambda()>()>::operator()(void) (this=0x23b9178)
        at /usr/include/c++/4.9/functional:1688
    #73 0x0000000001890b74 in std::thread::_Impl<std::_Bind_simple<caf::io::middleman::start()::<lambda()>()> >::_M_run(void) (
        this=0x23b9160) at /usr/include/c++/4.9/thread:115
    #74 0x00007ffff714ec80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #75 0x00007ffff7bc16fa in start_thread (arg=0x7fffe7fff700) at pthread_create.c:333
    #76 0x00007ffff68b3b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by Neverlord** [comment]
> Is it a symptom of another issue with our application? eg. data is enqueued on the network faster than it can be sent/received on the other side ?

Yes. You might want to checkout for the new streaming API that's currently in development. Maybe you can restructure some parts of your application to get the benefits of backpressured streaming. Expect more details on the new feature early next year.

**Comment by Neverlord** [comment]
This is the related issue, btw: https://github.com/actor-framework/actor-framework/issues/531
