### ISSUE TITLE
Unable to compile CAF on windows

### ISSUE THREAD

**Issue by nitinroy** [actor-framework/actor-framework#532]
I am a newbie in CAF, and wanted to compile CAF on windows. I installed cmake and even loaded the project files on VS2013. But when I am compiling, I am getting below error. There are more errors which probably runs in thousands, I am sure I am missing something, but need some help !!

Any help would be highly appreciated !! Thanks -- Nitin

![image](https://cloud.githubusercontent.com/assets/25015790/22387837/89814598-e503-11e6-98aa-559da7bece22.png)

**Comment by ufownl** [comment]
CAF doesn't support vs2013. You could compile it using vs2015.

**Comment by mavam** [comment]
If you're still facing trouble with VS2015, come by our chat or ask on the mailing list. If you believe you encountered a bug, feel free to reopen this issue.

**Comment by wwg2018new** [comment]
@nitinroy  Is it successful in Windows compilation?

**Comment by wwg2018new** [comment]
@mavam  how to use  cmake  for vs2015

**Comment by wwg2018new** [comment]
@nitinroy "install Library TARGETS given no DESTINATION!" when i use cmake
