### ISSUE TITLE
Test to_string failed for Raspbian 8

### ISSUE THREAD

**Issue by randyransier** [actor-framework/actor-framework#534]
Compiler: gcc (Raspbian 4.9.2-10) 4.9.2
OS: Raspbian 8 (jessie)
[LastTest.log.txt](https://github.com/actor-framework/actor-framework/files/768138/LastTest.log.txt)

**Comment by ufownl** [comment]
It seems that it is because chars on ARM are unsigned by default. Maybe you could use the compiler option `-fsigned-char` to avoid the issue.

**Comment by Neverlord** [comment]
@randyransier does compiling with the flag fix the issue? This bug only affects `to_string`, all other tests passed. So using CAF is not an issue, since this only affects user-generated (mostly debug) output.

**Comment by randyransier** [comment]
Yes, compiling with the `-fsigned-char` flag allows the `to_string` test to succeed. I cloned the repository clean and performed the following steps:
```
export CXXFLAGS="-std=c++11 -Wextra -Wall -pedantic -ftemplate-depth=512 -ftemplate-backtrace-limit=0 -pthread -fPIC -fsigned-char"
./configure
make
make test
```
