### ISSUE TITLE
Potential deadlock in link implementation

### ISSUE THREAD

**Issue by felixjendrusch** [actor-framework/actor-framework#536]
I'm currently looking through a few actor model implementations and think there is a potential deadlock in the link implementation. The sending actor [enters its critical section exclusively](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/src/monitorable_actor.cpp#L140), then [attempts to establish the backlink](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/src/monitorable_actor.cpp#L147), which [enters the receiver's critical section exclusively](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/src/monitorable_actor.cpp#L167). If both actors attempt to link to each other at the same time, they will deadlock if both enter their critical section.

Erlang avoids that by taking locks in a specific [order](https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/erts/emulator/beam/erl_process_lock.h#L189-L203) (and [here](https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/erts/emulator/beam/erl_process_lock.c#L582-L587)).

fyi, my C++ knowledge is very limited 🙈

**Comment by Neverlord** [comment]
Seems like you're right, thank you for pointing this out. I'll investigate this further and patch it.
