### ISSUE TITLE
Cannot Serialise std::vector<bool>

### ISSUE THREAD

**Issue by S4H** [actor-framework/actor-framework#540]
Hitting compile errors when trying to build on OSX (XCode 8.0 + Clang 4.0.0). The issue is with serialising std::vector<bool>'s, CAF's automatic translation seems to be failing due the iterator proxies that the container type uses.

The culprit appears to be in a for loop in `detail/stringification_inspector.hpp` taking an `auto&` instead of a universal reference as it can't extend the lifetime of the PR value returned.

Relevant SO Article: http://stackoverflow.com/questions/34079390/range-for-loops-and-stdvectorbool

minimal example:
```cpp
#include <caf/typed_event_based_actor.hpp>

#include <caf/actor_system.hpp>
#include <caf/actor_system_config.hpp>
#include <caf/send.hpp>

using FooActor = caf::typed_actor< caf::reacts_to<std::vector<bool> >>;

FooActor::behavior_type make_actor(FooActor::pointer self)
{
    return [](std::vector<bool> foo)
    {};
}

int main(int argc, char* argv[])
{
    caf::actor_system_config cfg;
    caf::actor_system system{cfg};
    auto a = system.spawn(make_actor);
    std::vector<bool> foo(10, false);
    caf::anon_send(a, foo);
}
```

**Comment by mavam** [comment]
As a side note: serializing large `vector<bool>` instances is very inefficient because you end up inflating a single bit into a byte on the wire, resulting in a 8x blow-up. I'd recommend use some simple packing scheme, such as stuffing bits into a `uint32_t` or `uint64_t`.

Given that `vector<bool>` is a part of the standard library, it's something CAF could do as well. It should be straight-forward to add. (PRs always welcome.)

**Comment by Neverlord** [comment]
Yes, the 8x size overhead is unfortunate. A proper size-optimized serialization would be a simple, straightforward side project for any potential contributor. Maybe we should start documenting such "low hanging fruit" optimizations for people that are interested in contributing to CAF.

**Comment by mavam** [comment]
We could introduce something along the lines of http://www.firsttimersonly.com, with the emphasis on complexity as opposed to seniority.

**Comment by mavam** [comment]
I like the idea of a `low-hanging-fruit` label. Shall we?

**Comment by Neverlord** [comment]
Yes, but please let's move the offtopic discussion someplace else. ;)
