### ISSUE TITLE
Add new OpenSSL module

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#544]
The OpenSSL module will provide secure alternatives to `publish` and `remote_actor`.

ToDo:

- [x] Module scaffold in branch `topic/openssl`
- [x] CMake setup
- [x] Skeleton and necessary glue code
- [x] Implement `caf::openssl::publish`
- [x] Implement `caf::openssl::remote_actor`
- [x] Implement core functionality (`middleman_actor.cpp`)
- [x] Allow users to set certificates via config
- [x] Unit testing
- [x] Merge module back to `develop`
- [x] Add manual entry
- [x] Launch as experimental feature

**Comment by mavam** [comment]
Why namespace `caf::openssl` instead of, say, `caf::ssl`? Do you want to make it explicit that this is only for OpenSSL and no other SSL/TLS library?

**Comment by Neverlord** [comment]
> Do you want to make it explicit that this is only for OpenSSL and no other SSL/TLS library?

Yes. Keeping this generic/pluggable is not on my agenda. Besides, we can have a `ssl` namespace with inlines `openssl` or any other available implementation later should we have need for it.

**Comment by mavam** [comment]
> Besides, we can have a ssl namespace with inlines openssl or any other available implementation later should we have need for it.

I like that approach.

**Comment by Neverlord** [comment]
@0xxon glue code and skeleton are in place now (`topic/openssl`). I've put `TODO` entries in the code at all place where OpenSSL-specific code is required. The overall design is as follows:

- CAF provides a module API for plugging in functionality for I/O, OpenCL, etc.
- System-wide state (and modules) are managed by the `actor_system`
- The connection between your module and the `actor_system` is `openssl::manager`
- The manager creates a `middleman_actor` actor that opens ports and connections in the background
- The `openssl::middleman_actor` re-uses the actor from the I/O module
- The functions `remote_actor` and `publish` offer a blocking API
- Talking to the middleman actor directly allows users to have a nonblocking API

I tried to re-use as many parts as possible from the I/O module to keep the code base small. Let me know if there are any limitations in the current design that don't work for you. For example if you need to customize more parts of the `middleman_actor` or need to extend the messaging interface.
