### ISSUE TITLE
vcpkg package and support for building as a DLL

### ISSUE THREAD

**Issue by mmha** [actor-framework/actor-framework#547]
I created an early portfile for CAF 0.15.3 to be included with the vcpkg package manager. You can find it on my [vcpkg fork](https://github.com/mmha/vcpkg/commit/c5b513ed374a1135f9f54aec80a89f657ee862df).

Along with the portfile I modified the build system to be able to build CAF as a shared library on Windows if the user is using CMake 3.4 or greater. This is included in my vcpkg fork as `fix-dll-build.patch`. I am going to create a proper CAF fork with the patch applied later that day and ~~will edit my post here~~ [here it is](https://github.com/mmha/actor-framework/tree/develop).

I am mostly asking for some feedback and want to upstream my changes before I create a pull request over at the vcpkg repository.

There are still a couple of issues left:
- I am making use of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` (thus the dependency on CMake 3.4). This covers classes and functions just fine, but does not work for global variables
- Fortunately, I found only two global variables in the headers, but in order to properly export them I would still need to provide a macro that conditionally evaluates to `__declspec(dllexport)`, `__declspec(dllimport)` or nothing
- I cannot really switch the definition of the macro automatically as long as the build system is able to build static and shared libraries simultaneously or is stuck with CMake 2.8 (CMake 3.0 introduces `target_compile_definitions`, which would solve the problem)
- The OpenCL module is not included yet
- So is the FindCAF.cmake
- At least some of the examples do not build with VS2017. I have only found issues with `examples/message_passing/fixed_stack.cpp` so far. I don't think this is related to my packaging efforts

**Comment by Neverlord** [comment]
Thank you so much! Much appreciated. One little nitpick: I think the macro name `CAF_API` is a bit confusing on first sight. Maybe `CAF_EXPORT_SYMBOL` or some other more explanatory name? This won't be used often, so I'm not concerned about the length of the name.

I'm looking forward to the PR. 👍

**Comment by Neverlord** [comment]
Any progress on the PR?

**Comment by mmha** [comment]
Sorry for not keeping you up to date. There were a couple of other things that I had to prioritize, but I did not forget about CAF on vcpkg.

I think I can make it work even on CMake 2.8.12. I will probably make a PR in the next couple of days.

**Comment by Neverlord** [comment]
No Problem. I'm asking because we will release the next CAF version soon and I would like to see this to make its way into 0.15.4.

**Comment by skorokhod** [comment]
any news there? :)

**Comment by Neverlord** [comment]
https://github.com/actor-framework/actor-framework/pull/992 added support for building DLLs.
