### ISSUE TITLE
Can't nest request(...).await(...) constructs

### ISSUE THREAD

**Issue by ebaratte** [actor-framework/actor-framework#550]
Consider the following sample:

    self->request(someone, std::chrono::seconds(1), someAtom::value).await(
        [=] (someResponseAtom) {
            self->request(someoneElse, std::chrono::seconds(1), someOtherAtom).await(
                [=] (someOtherResponseAtom) {
                     // Unreachable code
            });
    });

The second lambda will never be reached (nor a timeout occurs, it seems). The reason lies at scheduled_actor.cpp:380

    invoke_message_result scheduled_actor::consume(mailbox_element& x) {
      CAF_LOG_TRACE(CAF_ARG(x));
      current_element_ = &x;
      // short-circuit awaited responses
      if (!awaited_responses_.empty()) {
        auto& pr = awaited_responses_.front();
        // skip all messages until we receive the currently awaited response
        if (x.mid != pr.first)
          return im_skipped;
        if (!pr.second(x.content())) {
          // try again with error if first attempt failed
          auto msg = make_message(make_error(sec::unexpected_response,
                                             x.move_content_to_message()));
          pr.second(msg);
        }
        awaited_responses_.pop_front();    // <<== popping the wrong awaited_response
        return im_success;
      }
     // etc.

The handled awaited_response is `popped` after its message handler has been called. This works correctly only if said message handler does not push any new awaited_response.

Is there a workaround ?

**Comment by Neverlord** [comment]
That's a silly bug, sorry. Fixed in `develop`.

**Comment by ebaratte** [comment]
Wow, that was fast !
Thanks

**Comment by mavam** [comment]
Could be worthwhile adding this as unit test while fixing it.
