### ISSUE TITLE
proxy_registry.hpp won't build -> Parse Issue, Expected ')'

### ISSUE THREAD

**Issue by DaveChambers** [actor-framework/actor-framework#551]
Hi,

Today I installed CAF with brew and it won't build due to a Parse Issue, Expected ')', on line 92:

![screen shot 2017-04-14 at 23 00 23](https://cloud.githubusercontent.com/assets/419144/25054600/ca846896-2166-11e7-861d-baceac95ede9.png)

For a reason unknown to me, Xcode doesn't like the sequence of characters 'inf' so since C++ allows me to, I changed the 'inf' to 'ing' to compile the code.

Thanks

Dave

**Comment by mavam** [comment]
It looks like XCode considers `inf` a keyword, event though it's not an [official C++ keyword](http://en.cppreference.com/w/cpp/keyword). Is it possible to tell XCode to behave in a standard-compliant way?

**Comment by josephnoir** [comment]
I use Xcode at times and didn't run into that problem yet. I create the xcodeproj file using the CAF configure script with the `--generator=Xcode` argument which relies on the CMake functionality. So there should be a way to configure an Xcode project accordingly. Not sure what option to look for, though.

**Comment by DaveChambers** [comment]
Thanks for the comments guys.  For now anyway it's ok for me just to rename inf but it is slightly annoying Xcode behaves that way!

**Comment by Neverlord** [comment]
Not sure what's going on with your XCode, but I renamed the parameter anyways.
