### ISSUE TITLE
`current_sender` must be called before calling `make_response_promise`

### ISSUE THREAD

**Issue by ufownl** [actor-framework/actor-framework#559]
I found that the `sender` field of `mailbox_element` is moved to the `source_` field of the `response_promise`:
```C++
response_promise::response_promise(execution_unit* ctx, strong_actor_ptr self,
                                   mailbox_element& src)
    : ctx_(ctx),
      self_(std::move(self)),
      id_(src.mid) {
  // form an invalid request promise when initialized from a
  // response ID, since CAF always drops messages in this case
  if (!src.mid.is_response()) {
    source_ = std::move(src.sender);
    stages_ = std::move(src.stages);
  }
}
```
So we must call `current_sender` before calling `make_response_promise` in the message handlers, otherwise we'll get an "invalid node" from `current_sender`. Is this a feature or an issue?

**Comment by Neverlord** [comment]
Once you create a response promise you are telling CAF that you are done with this message in your handler. So there's no reason not to move, since creating the promise should be the last thing your handler does (modulo sending a request where you use the promise in the response handler).
