### ISSUE TITLE
Joining a group may prevent proper actor release

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#574]
I believe there is an issue with the reference counting on class actors that join a group.

Here is the smallest reproduction case I could put together:

    #include <iostream>
    #include <vector>
    
    #include "caf/all.hpp"
    
    
    using namespace std;
    using namespace caf;
    
    
    using atomTerminate = atom_constant<atom("plz_die")>;
    using atomInit = atom_constant<atom("plz_init")>;
    
    class B: public event_based_actor {
    public:
        B(actor_config& cfg) : event_based_actor(cfg) {}
    
        ~B() {
            std::cout << "B::dtor" << std::endl;
        }
    protected:
        behavior make_behavior() override {
            join(system().groups().get_local("some_group"));
            return {
                [=](atomTerminate) {
                    quit();
                }
            };
        }
    
        void on_exit() override {
            leave(system().groups().get_local("some_group"));
        }
    };
    
    class A: public event_based_actor {
    public:
        A(actor_config& cfg) : event_based_actor(cfg) {}
    
        ~A() {
            std::cout << "A::dtor" << std::endl;
        }
        
    protected:
        behavior make_behavior() override {
            return {
                [=](atomInit) {
                    b = spawn<B>();
                },
                [=](atomTerminate) {
                    send(b, atomTerminate::value);
                    quit();
                }
            };
        }
    
        void on_exit() override {
            destroy(b);
        }
    
    private:
        actor b;
    };
        
    int main(){
        actor_system_config cfg;
        actor_system sys(cfg);
    
        std::vector<actor> a;
        for (int i = 0; i < 10; ++i) {
            a.push_back(sys.spawn<A>());
            anon_send(a.back(), atomInit::value);
        }
    
    
        for (int i = 0; i < 10; ++i)
            anon_send(a[i], atomTerminate::value);
    
        a.clear();
    
        actor dont_terminate_because_an_actor_is_still_alive = sys.spawn<A>();
        sys.await_all_actors_done();
        return 0;
    }

I expect to see 10 calls to ~A, and 10 calls to ~B; yet, when running this, only 0 to 5 B objets are deleted effectively (all As seem to be deleted properly).

- if B actors don't join any group, the issue does not occur
- leaving the group before exiting does not prevent the issue
- if B are spawned directly from the actor_system (instead of A), the issue does not occur.

I reproduce the issue on the `master `branch, as well as `develop`.

**Comment by josephnoir** [comment]
I can observe the same behavior with the example you provided. It seems that the actors are not removed from the group properly, leaving them with a higher reference count, preventing their deletion.

This [commit](https://github.com/actor-framework/actor-framework/commit/886aaabd7eed240fb70c5ed76cf2f90dcc1161ff) fixes the behavior for me. However, I am not sure what the original intentions of the `lower_bound` usage were, maybe @Neverlord can take a look at the commit before I open a PR.

**Comment by nq-ebaratte** [comment]
Ha!
I was preparing a PR with similar changes. It fixes it for me too.

I'd go further and ask why does the `unsubscribe()` method take an `actor_control_block*` while `subscribe()` takes a `strong_actor_ptr `? Changing to a `strong_actor_ptr `allows for a simple `find()`

The std::lower_bound() is indeed unneeded - it won't go faster than a regular find on the (already sorted) set. I couldn't figure what was wrong with it, though; the cmp predicate seems consistent with the default sort on the set.

**Comment by nq-ebaratte** [comment]
OK I was mistaken on that last sentence; the subscribers_ set is sorted according to the address of the actor_control_block, while cmp compares the ids of the actors. Hence the issue.

**Comment by josephnoir** [comment]
Aha ^^ If you have a nicer solution, feel free to submit the PR!

**Comment by nq-ebaratte** [comment]
```
--- a/libcaf_core/src/group_manager.cpp
+++ b/libcaf_core/src/group_manager.cpp
@@ -88,7 +88,7 @@ public:
     CAF_LOG_TRACE(""); // serializing who would cause a deadlock
     exclusive_guard guard(mtx_);
     auto cmp = [](const strong_actor_ptr& lhs, const actor_control_block* rhs) {
-      return actor_addr::compare(lhs.get(), rhs) < 0;
+      return lhs.get() < rhs;
     };
     auto e = subscribers_.end();
     auto i = std::lower_bound(subscribers_.begin(), e, who, cmp);
```

**Comment by josephnoir** [comment]
Not sure if I understand this correctly, but we should use the `lower_bound` or `find` member function of the set if possible and not the `std::` one.

The latter one only provides logarithmic lookup if the iterator is a random access iterator, see [here](http://en.cppreference.com/w/cpp/algorithm/lower_bound), while the member function always has a logarithmic lookup time, see [here](http://en.cppreference.com/w/cpp/container/set/lower_bound). However, that requires creation of the container with a suitable comparator as the member functions only accept a key as an argument. However, we can only do that if add and erase use the same type to access the set?

Or maybe, I am just overthinking this and your fix is the clean and easy one.

**Comment by Neverlord** [comment]
> Not sure if I understand this correctly, but we should use the `lower_bound` or `find` member function of the set if possible and not the `std::` one.

The member functions do not allow a compare function object.

**Comment by nq-ebaratte** [comment]
@Neverlord Hence my question: why taking an actor_control_block* as an argument to unsubscribe(), rather than a strong_actor_ptr ?

**Comment by josephnoir** [comment]
I asked the same thing. IIRC, there are cases where you only have a weak ptr to an actor, but you still want to kick it out of the group. E.g., if your actor quit already ... ? Anyway, your fix looks like the straight forward solution!

**Comment by nq-ebaratte** [comment]
I had another attempt at it this morning, see PR #576 

It makes use of a functionnality introduced in C++14: the ability to use a type that "compares equivalent" to the keys of an` std::set<>` in its `find()` method. See (4) at http://en.cppreference.com/w/cpp/container/set/find

Adding an `operator<` to compare an `intrusive_ptr<T>` to a raw `T*` allows the find method to accept a `const actor_block*` parameter.

As an added bonus, the deletion is now O(log(N)), instead of O(N)
