### ISSUE TITLE
Bugs found with PVS-studio to be fixed

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#583]
V655 The strings were concatenated but are not utilized. Consider inspecting the 'result_ + "<null>"' expression. stringification_inspector.hpp 173

V690 The 'type_erased_tuple_view' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class.

V564 The '&' operator is applied to bool type value. You've probably forgotten to include parentheses or intended to use the '&&' operator. libcaf_core_static abstract_coordinator.cpp 206

V794 The copy operator should be protected from the case of 'this == &x'. libcaf_core_static error.cpp 62

V530 The return value of function 'allow_sigpipe' is required to be utilized. libcaf_io_static default_multiplexer.cpp 1012

**Comment by Neverlord** [comment]
Thank you for sharing the warnings. V530 makes no sense to me, but I fixed the others.
