### ISSUE TITLE
Allow user-defined logger classes

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#588]
Original discussion see [stackoverflow](https://stackoverflow.com/questions/45589227/customizing-c-caf-framework).

**Comment by rsmmr** [comment]
+1 

It'd  be great if an application could leverage CAF's logging capabilities for its own debug logging even if CAF isn't specifically compiled with debugging support .

**Comment by Neverlord** [comment]
> It'd be great if an application could leverage CAF's logging capabilities for its own debug logging even if CAF isn't specifically compiled with debugging support.

FYI, this is now the case with [0.17](https://github.com/actor-framework/actor-framework/releases/tag/0.17.0). Users can't replace the logger as of yet, but they can use CAF's logging infrastructure regardless of CAF's build configuration now.
