### ISSUE TITLE
make_response_promise and response shoukd accept caf::result 

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#592]
now _self->response(caf::result<type>) trys to send result as it is insted of extracting error or good resonse from caf::result<...>

**Comment by Neverlord** [comment]
`result` has four states: *value*, *error*, *delegated*, or *skip*. I don't think there's a reasonable thing `response_promise::deliver` could do when getting a `result` that's neither a value nor an error.

Currently it can be surprising that the promise simply sends the `result` over. Silently doing nothing or throwing an exception in `response_promise::deliver` could cause equally unexpected outcomes, though.

I currently think putting a `static_assert` into `deliver` that rejects `result` altogether at compile time would catch potential bugs best.
