### ISSUE TITLE
add some methods to control actor's queue

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#594]
I think about count & empty for messages and request's , waiting for responses/timeouts.
It will be very helpfull to debbug and monitor actor's state.

**Comment by Neverlord** [comment]
You can already call `self->mailbox().empty()` and `self->mailbox().count()`. Is this what you had in mind?

**Comment by skorokhod** [comment]
Does count&empty corespond to mailbox elements to be processed or it can contain smth like awaiting teimouts and response promices? I mean, every time when empty=false it is guaranted that mailbox contains messages to be proccesed now.

I'd preffer to have the same methods for multiplexed_responses to control memory consumption.

**Comment by Neverlord** [comment]
The mailbox contains timeouts, responses, etc. The mailbox is a simple queue, so there's no intelligence at this layer. The actor decides whether a message is treated differently or not.

The mailbox has a new `peek_all` member function in the `develop` branch that you could use to scan the mailbox for particular messages. In your case, messages that aren't timeouts and have a message ID with `is_response() == false`. Maybe that's useful to you.

**Comment by skorokhod** [comment]
great! waiting for release ;)

**Comment by Neverlord** [comment]
We're working on a release and will ship as soon as the unit tests for our new features are all green. Hopefully sooner rather than later. ;)
