### ISSUE TITLE
Build configuration support for standard library, architecture

### ISSUE THREAD

**Issue by sourcedelica** [actor-framework/actor-framework#597]
While doing the Conan work I ran into a few build configuration related items.

- Select old vs. new `libstdc++` ABI.  Currently CAF builds with the default `libstdc++` ABI, which is usually `new` on GCC 5.1+.  Conan requires that you specify a standard library so it can tag the built package with it.
- Select architecture.  Currently CAF builds with the default architecture (typically `x86_64`).  Conan requires that you specify an architecture so it can tag the built package with it.  

I can submit a PR to add support for these.  Let me know what you think.

**Comment by Neverlord** [comment]
> I can submit a PR to add support for these. Let me know what you think.

Sure, I'm happy to accept PRs that make packaging easier.

**Comment by sourcedelica** [comment]
Sorry for the delay on this, I had forgot about it.  I am still going to do it :)

**Comment by Neverlord** [comment]
It's been a while, so I'm closing here.
