### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by selforganized** [actor-framework/actor-framework#598]
Hi,

Just stumbled upon this project. It looks great. I noticed the last commit was made back in Jan. And the twitter account hasn't been updated since 2016. Is this project still active?

**Comment by grahamreeds** [comment]
Check-ins are to develop, plus there are many branches that are in various
stages of development.

It is very much active!

GR

**Comment by Neverlord** [comment]
Alive and kickin'. Next release is also underway at the moment.
