### ISSUE TITLE
remote_actor() may freeze the actor system

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#599]
Hello,

When N actors (on an N-threads cpu) simultaneously call remote_actor(), they won't return until they receive a response from the middleman. If the middleman is not spawned with the detached flag, it will never wake up (no worker thread is available) - remote_actor() calls will never receive a response, the system is deadlocked forever.

Note that it is a bit subtle to trigger, because all actors need to precisely enter the remote_actor call simultaneously.

This situation is easily fixed by using the `middleman_detach_utility_actors` option. 
Note that this option has no default set; it may be randomly true or false if the user does not specify it explicitely. 

I am not sure if we should call it a bug - the system is working as it should. But this is something one should be aware of!

**Comment by Neverlord** [comment]
An uninitialized value is always a bug in my eyes. In this case, `middleman_detach_utility_actors` must be `true` per default. It only exists for testing purposes to allow a fully deterministic execution.
