### ISSUE TITLE
libcaf_openssl compile errors on Windows

### ISSUE THREAD

**Issue by sourcedelica** [actor-framework/actor-framework#601]
In 0.15.4, if `CAF_NO_OPENSSL=OFF` (OpenSSL is enabled) Windows 2015 and 2017 fail with errors like:

```
C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(221): error C2011: 'sockaddr': 'struct' type redefinition (compiling source file C:\Users\appveyor\.conan\data\caf\0.15.4\actor-framework\stable\build\f121568f99cbb51abc2e1e9ab27da0d602a74a7d\actor-framework-0.15.4\libcaf_openssl\src\manager.cpp) 

C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock.h(1002): note: see declaration of 'sockaddr' (compiling source file C:\Users\appveyor\.conan\data\caf\0.15.4\actor-framework\stable\build\f121568f99cbb51abc2e1e9ab27da0d602a74a7d\actor-framework-0.15.4\libcaf_openssl\src\manager.cpp)

C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(421): error C2059: syntax error: 'constant' (compiling source file C:\Users\appveyor\.conan\data\caf\0.15.4\actor-framework\stable\build\f121568f99cbb51abc2e1e9ab27da0d602a74a7d\actor-framework-0.15.4\libcaf_openssl\src\manager.cpp)
```

See [this Appveyor build](https://ci.appveyor.com/project/sourcedelica/conan-caf/build/1.0.30/job/48hnvv3uk81e0tpm) for a full list.

**Comment by Hamdor** [comment]
I just installed VS 2017 and OpenSSL 1.1.0f but could not reproduce this problem. But I had problems building the unit tests for the OpenSSL module. @Neverlord, is that a known issue?

**Comment by sourcedelica** [comment]
I just updated the Conan recipe to CAF 0.15.5 but I'm getting the same errors with `CAF_NO_OPENSSL=OFF`  [Here's the Appveyor run](https://ci.appveyor.com/project/sourcedelica/conan-caf/build/1.0.32/job/vcbjd81ig8ji08l4) where their installed OpenSSL is 1.0.2l.

My local setup with VS 2017 is using OpenSSL 0.9.8h has the same errors.

**Comment by Hamdor** [comment]
@sourcedelica could you test the following patch for me?
```
diff --git a/libcaf_io/caf/io/network/default_multiplexer.hpp b/libcaf_io/caf/io/network/default_multiplexer.hpp
index 0f785332..60d2ca59 100644
--- a/libcaf_io/caf/io/network/default_multiplexer.hpp
+++ b/libcaf_io/caf/io/network/default_multiplexer.hpp
@@ -59,8 +59,8 @@
 #   define WINVER WindowsVista
 #   include <w32api.h>
 # endif
-# include <windows.h>
 # include <winsock2.h>
+# include <windows.h>
 # include <ws2tcpip.h>
 # include <ws2ipdef.h>
 #else
```

**Comment by sourcedelica** [comment]
Running - jobs are at https://ci.appveyor.com/project/sourcedelica/conan-caf.
 I'll check them tomorrow.


-- Eric

**Comment by sourcedelica** [comment]
The patch itself was applied in sourcedelica/actor-framework at this [commit](https://github.com/sourcedelica/actor-framework/commit/f00d06a210ca5e96db3220c21e2b268d7435a013).     There's a corresponding [branch](https://github.com/sourcedelica/conan-caf/commits/0.15.5.x) in the CAF/Conan project that points to that specific commit for testing/CI.

**Comment by sourcedelica** [comment]
Hi @Hamdor - that fix worked.   The CI failed for a different reason that I'm investigating but it compiled successfully.

**Comment by sourcedelica** [comment]
CI fixed.   https://ci.appveyor.com/project/sourcedelica/conan-caf/build/1.0.39
