### ISSUE TITLE
Hooks for new threads in CAF

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#603]
(feature request from a private conversion)

CAF starts new threads as scheduler workers or whenever a thread is detached. Adding a hook that gets executed whenever a new thread gets started by CAF would give users more control. For example, users could wish to log new threads or set signal handlers.

**Comment by Hamdor** [comment]
What are the callbacks we need?
* before_join_thread_cb
* after_join_thread_cb
* detach_thread_cb

**Comment by Neverlord** [comment]
Not all threads CAF starts are joined. For example, the `private_thread` runs fully detached. However, we could still give a callback that gets called before the thread dies. `thread_started` and `thread_terminates` maybe?

**Comment by Hamdor** [comment]
👍 We should also think about a more general hook solution. Currently we only have hooks in caf-io, since this would affect caf-core we might should handle these callbacks somewhere in caf-core. Maybe something like a `hook_mgr` class in caf-core?

**Comment by Neverlord** [comment]
I don't see use cases for dynamic hooks at this point, so I think we can just put the callbacks into the actor system config.

It's a bit unfortunate the that I/O hook is simply called `hook`. A better name would have been `communication_hook`. Maybe we can rename it eventually. What about this interface for the threading hook?

```cpp
class thread_hook {
public:
  virtual ~thread_hook();

  // Called by the actor system once before starting any threads.
  virtual void init(actor_system&) = 0;

  // Called whenever the actor system has started a new thread.
  // @warning must the thread-safe
  virtual void thread_started() = 0;

  // Called whenever a thread is about to quit.
  // @warning must the thread-safe
  virtual void thread_terminates() = 0;
};
```

And adding this hook type to the config could be done in this way:

```cpp
cfg.add_thread_hook<my_hook_impl>(/* ... args ... */);
```

Or with a custom config type:

```cpp
struct config : actor_system_config {
  // ...
  config() {
    add_thread_hook<my_hook_impl>(/* ... args ... */);
    // ...
  }
};
```

And calling it:

```cpp
// client code
system_.thread_started();
// actor system code
void thread_started() {
  for (auto& ptr : cfg_.thread_hooks)
    ptr->thread_started();
}
```

**Comment by Hamdor** [comment]
Looks good to me.

**Comment by Hamdor** [comment]
I'am not happy with the fact that we don't provide arguments for the callbacks itself. I think it could be useful to have at least a reference to the std::thread object. What do you think?

**Comment by Neverlord** [comment]
The thread object is redundant. You can get that with `std::this_thread` anyway. What could be useful is a reference to the `actor_system`.
