### ISSUE TITLE
Re-use Node IDs instead of creating a new object each time

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#607]
Currently, deserializing a `node_id` creates a new instance each time. A simple lookup table for known remote IDs could avoid many copies of the same node ID (`node_id` is immutable and uses a reference counted data member that could easily be shared). Node IDs are transmitted often, for example each time one sends an actor to a remote node. This ramps up quickly to thousands of `node_id` objects per second that are created and destroyed, causing avoidable heap allocations.

**Comment by Hamdor** [comment]
So, you mean the `make_counted<data>` in the following block should be optimized out, right?

```c++
  template <class Inspector>
  friend detail::enable_if_t<Inspector::writes_state,
                             typename Inspector::result_type>
  inspect(Inspector& f, node_id& x) {
    data tmp;
    // write changes to tmp back to x at scope exit
    auto sg = detail::make_scope_guard([&] {
      if (!tmp.valid())
        x.data_.reset();
      else if (!x || !x.data_->unique())
        x.data_ = make_counted<data>(tmp);
      else
        *x.data_ = tmp;
    });
    return f(meta::type_name("node_id"), tmp.pid_,
             meta::hex_formatted(), tmp.host_);
  }
```

**Comment by Neverlord** [comment]
Generally yes, but that most likely requires some sort of node ID registry/cache. Currently there's a registry for actors that is required to get the actual actor handle from a deserialized ID. We probably need something similar to that.

I'm a bit hesitant to add another registry/cache type, though. I would prefer a solution that is general enough to allow the same optimization (i.e. caching) for arbitrary types. The node ID is most certainly not a unique snow flake in this regard. I'd like to give users a nice way to integrate a caching optimization to any type where it makes sense that CAF uses itself.

**Comment by Hamdor** [comment]
I just started with a first draft. @Neverlord, do you have further ideas or requirements?

**Comment by Neverlord** [comment]
@Hamdor thanks a lot for your effort. I'm hesitant to push this further, though. @josephnoir is currently exploring design ideas for improving the network layer. Part of this would remove the node IDs from BASP headers. This in turn would cause CAF to serialize/deserialize significantly less node IDs as a result. My hunch is that caching simply isn't worth the increase in complexity after the redesign.

I put this on hold until we have the new BASP layer to work with.

**Comment by Neverlord** [comment]
We removed the node IDs from BASP message headers via https://github.com/actor-framework/actor-framework/pull/816. That change removes the need to serialize and deserialize `node_id` objects drastically. Since `node_id` itself is likely going to be replaced soon-ish, I think we can close this now.
