### ISSUE TITLE
Unit tests fail with OpenSSL versions newer than 1.0.1

### ISSUE THREAD

**Issue by sep2** [actor-framework/actor-framework#625]
./configure
make
make test
give me the following result:

> 60/63 Test #60: io_typed_remote_actor ............   Passed    0.01 sec
>       Start 61: io_unpublish
> 61/63 Test #61: io_unpublish .....................   Passed    0.01 sec
>       Start 62: openssl_authentication
> 62/63 Test #62: openssl_authentication ...........   Passed    0.02 sec
>       Start 63: openssl_dynamic_remote_actor
> 63/63 Test #63: openssl_dynamic_remote_actor .....***Exception: Other  0.48 sec
> 
> 98% tests passed, 1 tests failed out of 63
> 
> Total Test time (real) =   1.17 sec
> 
> The following tests FAILED:
> 	 63 - openssl_dynamic_remote_actor (OTHER_FAULT)
> Errors while running CTest
> make[1]: *** [Makefile:130: test] Error 8
> make[1]: Leaving directory '/home/felix/github/actor-framework/build'
> make: *** [Makefile:7: test] Error 2
>

**Comment by Neverlord** [comment]
Thanks for the report. Can you please provide us with more details about your setup? OS, Compiler, OpenSSL version, etc.

**Comment by sep2** [comment]
I am using Archlinux and here is my info:

% uname -a
Linux LA 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux

%gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.2.0 (GCC) 


% openssl version
OpenSSL 1.1.0g  2 Nov 2017

**Comment by Neverlord** [comment]
The issue with OpenSSL 1.1 is actually a [known bug](https://github.com/actor-framework/actor-framework/issues/591#issuecomment-335439759). Sorry that there wasn't an open ticket for this.

Btw, I've updated the issue title so that others can find it more easily.
