### ISSUE TITLE
Segfault when result<T> is not returned explicitly

### ISSUE THREAD

**Issue by rkfg** [actor-framework/actor-framework#631]
I want to either return an error from an actor or nothing after performing some work. But еру `result<void>` reply type doesn't prevent from _not_ writing `return` explicitly and the program segfaults. Example:

```cpp
#include <iostream>
#include <caf/all.hpp>

using namespace std;
using namespace caf;
using test_actor_type = typed_actor<replies_to<int>::with<void>>;

test_actor_type::behavior_type test_actor() {
    return {[](int x) -> result<void> {
        }};
}

int main(int argc, char* argv[]) {
    actor_system_config conf;
    actor_system system(conf);
    auto act = system.spawn(test_actor);
    scoped_actor(system)->request(act, 1s, 5);
}
```

Here we segfault on `caf::result<void>::~result() at result.hpp:110 0x55555562f676`. It's easy to fix with this:
```cpp
test_actor_type::behavior_type test_actor() {
    return {[](int x) -> result<void> {
            return {};
        }};
}
```
Expiclitly constructed return value does not cause segfault. But it's easy to miss it in more complex code and the `result` abstraction starts to leak.

**Comment by Neverlord** [comment]
That's not something CAF can fix, this is simply a limitation of C++. However, every compiler I know of (given the right flags) will warn you about undefined behavior for not returning a value.

By the way, the canonical CAF way is to `return unit`. The name `unit` is borrowed from languages that have a sane implementation of what `void` is in C++. To be fair, though, that's one of the quirks and issues C++ inherited from C.
