### ISSUE TITLE
Reply from group doesn't quite work

### ISSUE THREAD

**Issue by rkfg** [actor-framework/actor-framework#632]
```cpp
#include <caf/all.hpp>

using namespace std;
using namespace caf;

int main(int argc, char* argv[]) {
    actor_system_config conf;
    actor_system system(conf);
    auto grp = system.groups().get_local("test");
    for (int i = 0; i < 5; ++i) {
        system.spawn_in_group(grp, [=](event_based_actor* self) {
            return behavior {
                [=](const string& msg) {
                    aout(self) << msg << endl;
                    return 1;
                }
            };
        });
    }
    scoped_actor self(system);
    self->request(grp, 2s, string("test")).receive([&](int i) {
        aout(self) << "OK " << i << endl;
    }, [&](const error& e) {
        aout(self) << "Error: " << system.render(e) << endl;
    });
}

```
The result is:
```
test
test
test
test
test
Error: system_error(request_timeout)
```
It's like the response never arrives. It works fine if I send a request to a specific actor but I'd like to receive from them as a group.

Another approach:
```cpp
    system.spawn([&](event_based_actor* self) {
        self->request(grp, 2s, string("test")).then([=](int i) {
                    aout(self) << "OK " << i << endl;
                }, [=](const error& e) {
                    aout(self) << "Error: " << self->home_system().render(e) << endl;
                });
    });
```
One of the possible outputs:
```
test
*** unexpected message [id: 11, name: scheduled_actor]: (1)
test
*** unexpected message [id: 11, name: scheduled_actor]: (1)
test
*** unexpected message [id: 11, name: scheduled_actor]: (1)
test
test
*** unexpected message [id: 11, name: scheduled_actor]: (1)
*** unexpected message [id: 11, name: scheduled_actor]: (1)
Error: system_error(request_timeout)
```
So the workers respond but the response doesn't arrive to the `then` lambda and instead goes to the main actor handler.

So, a working but ugly behavior:
```cpp
    system.spawn([&](event_based_actor* self) {
        self->request(grp, 2s, string("test"));
        return behavior {
            [=](int i) {
                aout(self) << "OK " << i << endl;
            }, [=](const error& e) {
                aout(self) << "Error: " << self->home_system().render(e) << endl;
            }
        };
    });
```
Output:
```
test
test
test
OK 1
OK 1
OK 1
test
OK 1
test
OK 1
```
This approach doesn't support associating the request to the response hence I don't like it. It would require additional fields to distinct between the submitted tasks and results. Is a simple request-reply pattern not supported for groups?

**Comment by Neverlord** [comment]
> Is a simple request-reply pattern not supported for groups?

No, and how could it? Request/response protocols only make sense in one-to-one communication or at least if the number of receivers is fixed and known to the sender. CAF's `request` in particular implements one-to-one communication. If an actor would receive multiple responses to a single request than it would have to drop all responses but the first one.

CAF groups implement loose coupling based on publish/subscribe. Loose coupling means that the sender simply does not and can not know how many receivers there are. I think the best we can do to avoid a mismatch in semantics like this is to raise a compile-time error when trying to `request` to a group.

I believe the abstraction you are looking for is the actor *pool*. They allow several different setups, in particular split/join operations. See [the manual](http://actor-framework.readthedocs.io/en/stable/ManagingGroupsOfWorkers.html) for more details.

**Comment by rkfg** [comment]
>If an actor would receive multiple responses to a single request than it would have to drop all responses but the first one.

I've been confused by [this example](http://actor-framework.readthedocs.io/en/stable/MessagePassing.html#sending-requests-and-handling-responses) where `then/await` group multiple responses together. But actually there are multiple requests as well so it's a completely different scenario. Then probably disabling `request` for groups with a clear error message describing the reason would be the best.

>I believe the abstraction you are looking for is the actor pool.

Yes, though it's marked as experimental, and I just skimmed it. Thanks for your help!
