### ISSUE TITLE
ASIO multiplexer does not compile in master

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#638]
The boost asio-based multiplexer does not compile in the master branch as the new UDP-related multiplexer functions are missing here. I see two ways forward:

1. Add stubs that raise an error when trying to use ASIO with UDP
2. Implement UDP in the ASIO multiplexer

To get things working quickly, I'd suggest adding the stubs but I would like to do things "the right way" eventually.

**Comment by josephnoir** [comment]
The first one won't work because the io test are automatically generated for ASIO if it is available and that will lead to failures.

**Comment by josephnoir** [comment]
Should we keep this open until UDP is implemented for the asio multiplexer?

**Comment by Neverlord** [comment]
> Should we keep this open until UDP is implemented for the asio multiplexer?

No, it's still possible that we drop ASIO support alltogether.
