### ISSUE TITLE
The udp basp autoconnection test has a leak

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#647]
According to asan, there is a leak in the unit test `io_basp_udp` that can be seen on Linux using gcc 6.3, gcc 7.2 or clang. The leak occurs in the test case `automatic_connection_udp`,  [here](https://gist.github.com/josephnoir/ff6057d5596944553e0058e686ed4045) is the output.

**Comment by josephnoir** [comment]
So, it seems the broker to help with establishing communication ([`datagram_connection_broker`](https://github.com/actor-framework/actor-framework/blob/master/libcaf_io/src/connection_helper.cpp#L35)) is never shut down. 

Printing a message in the constructor and destructor of the the class `abstract_broker` I can observe that the constructor is called twice and the destructor is only called once in the test case. Valgrind points to the creation of this broker in its trace, sooooo, I guessing that this is the one that is not deconstructed.

If I attach a functor such as the one below it will be called. Probably called from quit?
```cpp
self->attach_functor([=](const error& reason) {
  std::cerr << "datagram connection broker exited: "
            << self->home_system().render(reason) << std::endl;
});
```

**Comment by Neverlord** [comment]
When the destructor gets never called than it should be easy to find out where handles to that particular actor are stored, i.e., to see where the extra reference is coming from. If this is a leak, though, then there can't be another actor holding the reference (in this case they would form a cycle and you would see two leaks). Can the actor end up with a reference to itself somehow? Just a hunch.

**Comment by Neverlord** [comment]
> Is there a way deregister from the timeout?

Not yet. I'm working on it.

**Comment by Neverlord** [comment]
@josephnoir Actors should cancel their pending timeouts automatically now.

**Comment by josephnoir** [comment]
One of the VMs still has an error. 😟 Seems like the same error. Maybe the test doesn't shut down properly ... or something like that. I'll take a closer look at it tomorrow!

**Comment by josephnoir** [comment]
From what I can tell the tests don't fail due to memory leaks anymore. So,  b8b76c3606fcb9b7aa3d71d125c367f3885d27e3 fixed that \o/

New problem: the timeout I choose is too small messages are delivered before the test can check them (should have expected that). And one build failed because it was missing a configuration parameter (only `CAF_FORCE_NO_EXCEPTIONS` was set, but not `CAF_NO_EXCEPTIONS`).

So ... I'll close this error and think of something to address the timeout thing.
