### ISSUE TITLE
comment error

### ISSUE THREAD

**Issue by blacktrain** [actor-framework/actor-framework#649]
in the file actor-framework/libcaf_core/caf/detail/type_traits.hpp line:551 ,comment for 
/// Checks whether T is convertible to either `std::function<void (T&)>`
/// or `std::function<void (const T&)>`.
template <class F, class T>
struct is_handler_for {
  static constexpr bool value =
      std::is_convertible<F, std::function<void (T&)>>::value
      || std::is_convertible<F, std::function<void (const T&)>>::value;
};
is error, should be /// Checks whether F is convertible to either `std::function<void (T&)

**Comment by Neverlord** [comment]
Thanks, I'll fix it.
