### ISSUE TITLE
Configure error with cmake for LDFLAGS has leading whitespace

### ISSUE THREAD

**Issue by langxiong** [actor-framework/actor-framework#653]
**Description**

Configure error with cmake

**Steps to reproduce the issue:**
1. git clone https://github.com/actor-framework/actor-framework.git
2. cd actor-framework/build/
3. cmake ../

**Describe the results you received:**

```
Install prefix:        C:/Program Files (x86)/caf
Generator:             Visual Studio 15 2017

===========================================================

-- Configuring done
CMake Error at CMakeLists.txt:614 (add_executable):
  Target "caf-test" links to item " ws2_32 iphlpapi" which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.
```

**Describe the results you expected:**

Configure done with no error.

**Output of `cmake version`:**

```
cmake version 3.10.1
```

**Comment by langxiong** [comment]
[CMP0004](https://cmake.org/cmake/help/v3.10/policy/CMP0004.html?highlight=cmp0004)

Add `cmake_policy(SET CMP0004 OLD)` could pass this error, but the OLD behavior of a policy is deprecated by definition and may be removed in a future version of CMake.

**Comment by Neverlord** [comment]
@langxiong thanks! Should work after e227f3dd049ce20bb64978815ed5846086596682. I got it configured with CMake without warnings on Windows and got it compiling in Visual Studio.

**Comment by Neverlord** [comment]
@langxiong I close this for now since it seems fixed. Please reopen if you still get warnings.

**Comment by langxiong** [comment]
Thanks.

LGTM

**Comment by wwg2018new** [comment]
@langxiong how to compile in windows

**Comment by wwg2018new** [comment]
@Neverlord how to compile in windows
