### ISSUE TITLE
Functions marked as noexcept throw

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#659]
There are two functions in [`type_erased_tuple.cpp`](https://github.com/actor-framework/actor-framework/blob/d6be91aab8bc62d6a85b9173839134899aa56d21/libcaf_core/src/type_erased_tuple.cpp#L102) that throw exceptions. Should we remove the `noexcept` or change their body?

**Comment by Neverlord** [comment]
Neither. The function `empty_type_erased_tuple::get_mutable(size_t)` calls `CAF_RAISE_ERROR`, which ultimately throws an exception. However, any program attempting to call `get_mutable(n)` on any `type_erased_tuple` with `n >= size` is malformed and violates the precondition of the function. This is just like accessing an array via `xs[n]` with `n >= sizeof(xs)`.

Throwing an exception inside a `noexcept` function will call `std::terminate`, which is exactly what should happen.
