### ISSUE TITLE
how to use cmake with vs2015 in windows 

### ISSUE THREAD

**Issue by wwg2018new** [actor-framework/actor-framework#668]

**Comment by Neverlord** [comment]
Usually the easiest way is to generate a VS project file using the CMake GUI, but please ask only CAF-related questions on this platform. It's easy to find CMake tutorials or guides.

**Comment by wwg2018new** [comment]
@Neverlord  but CMake Error at CMakeLists.txt:563 (message):
  OpenSSL library version does not match headers

**Comment by Neverlord** [comment]
This means CMake's `find_package(OpenSSL)` is unable to detect your installation correctly. You can either refer to their docs for help or build CAF without OpenSSL support by using `-DCAF_NO_OPENSSL:BOOL=yes`.

**Comment by wwg2018new** [comment]
@Neverlord  do you have cmake cmake.bat，
mkdir build

cd build

cmake   ../actor-framework -G "Visual Studio 14 2015 Win64"
  -DCAF_BUILD_STATIC_ONLY:BOOL=yes
 -DCAF_NO_BENCHMARKS:BOOL=yes 
-DCAF_NO_EXAMPLES:BOOL=yes 
-DCAF_NO_MEM_MANAGEMENT:BOOL=yes 
-DCAF_NO_OPENCL:BOOL=yes 
-DCAF_NO_RIAC:BOOL=yes
