### ISSUE TITLE
Caching Actor References in an Array

### ISSUE THREAD

**Issue by mvbaffa** [actor-framework/actor-framework#670]
I am new to CAF and I would like to create, let's say 1000 actors, cache them in an array and send messages to them. Very basic

Create them:
```
actor ventureBN_actor[numOfRuns];
for(int i = 0; i < numOfRuns; i++) {
        ventureBN_actor[i] = system.spawn(ventureBN_net);
}
```
Send Messages

```
for(int i = 0; i < numOfRuns; i++) {
    system.spawn(hello_net, ventureBN_actor[i], i);
}
```
hello_net is like this:

```
void hello_net(event_based_actor* self, const actor& buddy, const int index) {
    self->request(buddy, std::chrono::seconds(10), index).then(
            // ... wait up to 10s for a response ...
            [=](const string& what) {
                // ... and print it
                aout(self) << what << endl;
            }
    );
}
```
In fact the code is an updated copy of the original Hello World example.

When I have numOfRuns = 100, sometimes I receive the error:

> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

When I have numOfRuns = 1000, sometimes I receive the error:

> * Error in `./ClassesAndObjects': double free or corruption (fasttop): 0x00007fca20009d40 * ======= Backtrace: ========= /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fca2dac17e5] /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fca2daca37a] /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fca2dace53c] ./ClassesAndObjects[0x5c3bc8] ./ClassesAndObjects[0x41b394] ./ClassesAndObjects[0x40fbdd] /usr/local/lib/libcaf_core.so.0.15.6(_ZN3caf6detail13behavior_impl6invokeERNS0_21invoke_result_visitorERNS_17type_erased_tupleE+0x4f)[0x7fca2e9ead3f] /usr/local/lib/libcaf_core.so.0.15.6(_ZN3caf15scheduled_actor7consumeERNS_15mailbox_elementE+0x38d)[0x7fca2ea35f7d] /usr/local/lib/libcaf_core.so.0.15.6(_ZN3caf15scheduled_actor10reactivateERNS_15mailbox_elementE+0x26)[0x7fca2ea348e6] 

I have a VM with 4 cores and 16GB with an Ubuntu 16. In htop the memory is Ok and the cores reach 100%. 

What could be the problem ?

Thanks

**Comment by josephnoir** [comment]
Hello, I tried to reproduce this, but failed to do so on macOS, Ubuntu 14.04 (gcc 4.8.4), and Ubuntu 16.04 (server, gcc 5.4). Here is the code I used:

```cpp
#include <iostream>

#include "caf/all.hpp"

using namespace caf;
using namespace std;

behavior ventureBN_net(event_based_actor* self) {
  return {
    [=](const int i) {
      self->quit();
      return to_string(i);
    }
  };
}

void hello_net(event_based_actor* self, const actor& buddy, const int index) {
  self->request(buddy, std::chrono::seconds(10), index).then(
    // ... wait up to 10s for a response ...
    [=](const string& what) {
      // ... and print it
      if (index % 1000 == 0)
        aout(self) << what << endl;
    }
  );
}

int main() {
  auto numOfRuns = 10000;
  actor_system_config conf;
  actor_system system{conf};
  actor ventureBN_actor[numOfRuns];
  for(int i = 0; i < numOfRuns; i++) {
    ventureBN_actor[i] = system.spawn(ventureBN_net);
  }
  for(int i = 0; i < numOfRuns; i++) {
    system.spawn(hello_net, ventureBN_actor[i], i);
  }
  system.await_all_actors_done();
}
```

* Could you provide a minimal example that triggers the error?
* What compiler version do you use?

**Comment by mvbaffa** [comment]
Hi,

My ventureBN_net actor calls a bayesian network framework. The problem is in the inference of the network. If I remove the call to the framework the actors work perfectly.

I had already found the problem but I did not return here as I should. 

Thanks you very much and sorry for the delay.

**Comment by Neverlord** [comment]
No problem. Glad you found the issue. :)
