### ISSUE TITLE
I have a error in QtCreator with caf_core_static.lib

### ISSUE THREAD

**Issue by testwwg** [actor-framework/actor-framework#671]
GetAdaptersAddresses， "class std::vector<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > __cdecl caf::detail::get_mac_addresses(void)"

**Comment by Neverlord** [comment]
Please provide more information about your setup and how we could reproduce this. In particular:
- Operating System and Version
- Configuration options / CMake invocation
- Compiler version
- What you are compiling:
  * Is this output from compiling CAF examples / unit tests?
  * Is this output you get when compiling your own software?

From the little information you've provided I assume you are using Windows and MinGW. Please note that MinGW is not on the list of officially supported compilers. We accept MinGW-related patches, but we're not supporting it.

As far as the error is concerned: it seems like the library providing `GetAdaptersAddresses` isn't provided in the linker flags. Figuring out which system library provides `GetAdaptersAddresses` and adding it to the build setup should fix the error.

**Comment by testwwg** [comment]
@Neverlord   cmake  vs2015  libcaf_core ,then we can get caf_core_static.lib

**Comment by Neverlord** [comment]
Look, as much we'd like to help you: there's too little information to work with.

**Comment by russpowers** [comment]
In case anyone else runs into this, the solution is to link to the Windows library `Iphlpapi.lib`.

**Comment by jpsrxca** [comment]
> Iphlpapi.lib

Thank you thank you thank you!!! I was running into the same problem!! and linking Iphlpapi.lib worked for me too. BTW, how did you figure out that this library was missing??
