### ISSUE TITLE
Unit Test pipeline_streaming is broken on Windows

### ISSUE THREAD

**Issue by Hamdor** [actor-framework/actor-framework#675]
The pipeline steaming test (and maybe others) are currently broken on windows.

The test system is a Windows 10 with Visual Studio 2017.

```
** c:\users\marian\gitrepos\actor-framework\libcaf_test\caf\test\dsl.hpp:324  ::caf::test::equal_to(ptr->sender, src_)
  -> allow(timeout_msg).from(snk).to(snk) [line 373]
  -> allow(timeout_msg).from(stg).to(stg) [line 374]
  -> allow(timeout_msg).from(src).to(src) [line 375]
  -> the stage shuts down and the sink produces its final result [line 395]
  -> expect(upstream_msg::ack_batch).from(snk).to(stg) [line 396]
!! c:\users\marian\gitrepos\actor-framework\libcaf_test\caf\test\dsl.hpp:319  sched_.prioritize(whom)
     REQUIRED: sched_.prioritize(whom)
     c:\users\marian\gitrepos\actor-framework\libcaf_test\caf\test\dsl.hpp:324  had last successful check
```

I attached the complete output of the test to a gist:
https://gist.github.com/Hamdor/52d32ba2731edd9bda75e01e45fe16df

**Comment by Neverlord** [comment]
They also fail on Linux with GCC.

**Comment by Neverlord** [comment]
In fact, always fails with GCC. Even on macOS (Clang version works fine for me).

**Comment by Neverlord** [comment]
@Hamdor GCC builds are working for me now. However, this isn't compiling [in our Windows VM](https://jenkins.inet.haw-hamburg.de/job/CAF/job/msvc/label_exp=msbuild/652/console) at the moment. I'll look into this next week and see if I can reproduce this after fixing the build with our MSVC version.

**Comment by Neverlord** [comment]
Fixed in `master`. Tested via Jenkins and on a local Win 10 box. Please re-open if you still run into issues.
