### ISSUE TITLE
Hundreds of warnings for a particular line

### ISSUE THREAD

**Issue by grahamreeds** [actor-framework/actor-framework#681]
Almost every file in CAF has one or more of these warnings:

> /home/master/splint_caf/ext/caf/libcaf_core/caf/stream_slot.hpp: In member function ‘int_fast32_t caf::stream_slots::compare(caf::stream_slots) const’:
> /home/master/splint_caf/ext/caf/libcaf_core/caf/stream_slot.hpp:65:46: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>             - reinterpret_cast<int32_t&>(other);

gcc 4.8.4.

https://github.com/actor-framework/actor-framework/blob/ee79735ba0d2988e906c1873033c2d749be5b480/libcaf_core/caf/stream_slot.hpp#L65

**Comment by Neverlord** [comment]
Hm, the `static_assert` above makes sure the cast is safe. I'll see if I can maybe suppress that warning or move the code to a .cpp file.

**Comment by Neverlord** [comment]
Fixed in `master`.
