### ISSUE TITLE
ambiguous overload for 'operator!=' (operand types are 'const caf::actor_addr' and 'int')

### ISSUE THREAD

**Issue by sourcedelica** [actor-framework/actor-framework#682]
In certain situations with GCC 6 and 7 I get this when compiling:
```
C:/Users/epederson/.conan/data/caf/0.15.5/bincrafters/stable/package/1ae06f929d27249254a70969af31f053d50c10c5/include/caf/stream_id.hpp:56:19: error: ambiguous overload for 'operator!=' (operand types are 'const caf::actor_addr' and 'int')

     return origin != nullptr;
```
Changing it to this fixes the problem:
```
  inline bool valid() const {
     return origin != static_cast<std::nullptr_t>(nullptr);
  }
```
I'm not sure if that is the fix that you would like.  I can submit a PR for whatever fix you would prefer.

**Comment by Neverlord** [comment]
> In certain situations with GCC 6 and 7

That's very odd. Your change shouldn't do anything, since you cast a type to itself. Is this on current `master`?

**Comment by sourcedelica** [comment]
It happens with 0.15.5, and only with MinGW on Windows.
