### ISSUE TITLE
Error Compiling CAF

### ISSUE THREAD

**Issue by mvbaffa** [actor-framework/actor-framework#683]
A few weeks ago I have compile CAF and it worked perfectly. I am using GCC 5.4. This was version 0.15.6

Today I have cloned the last version (0.15.7) and a lot of compilation error occurred. I could not find the caf_openssl and caf_io in the resulting directory.

Am I doing something wrong or there is really an issue with this version ?

Thanks

**Comment by Neverlord** [comment]
The delta between 0.15.7 and 0.15.6 is [very small](https://github.com/actor-framework/actor-framework/compare/3344b5c9324558210b975c24819573bd12127331...ec0bc837013b940101c6dbfc717fa9872bdf62f7) and there weren't any changes to the I/O or OpenSSL module that could explain your troubles. Maybe a fresh clone can help?
