### ISSUE TITLE
typed_calculator.cpp example: errors in compilation

### ISSUE THREAD

**Issue by marcoippolito** [actor-framework/actor-framework#693]
After installing in my Ubuntu 16.04 Server Edition the actor-framework, I'm now trying to understand its functioning in order to use it in my project.
The compilation of the typed_calculator.cpp example give this error messages::

`/message_passing$ g++ -std=c++17 typed_calculator.cpp -lcaf_core -lcaf_io -L/usr/local/lib -otyped_calculator
typed_calculator.cpp: In function ‘void {anonymous}::tester(caf::event_based_actor*, const calculator_type&)’:
typed_calculator.cpp:55:47: error: no matching function for call to ‘caf::event_based_actor::request(const calculator_type&, const caf::atom_constant<(caf::atom_value)265756344>&, int, int)’
   self->request(testee, plus_atom::value, 2, 1).then(
                                               ^
In file included from /usr/local/include/caf/mixin/behavior_changer.hpp:32:0,
                 from /usr/local/include/caf/scheduled_actor.hpp:81,
                 from /usr/local/include/caf/event_based_actor.hpp:28,
                 from /usr/local/include/caf/detail/split_join.hpp:26,
                 from /usr/local/include/caf/actor_pool.hpp:30,
                 from /usr/local/include/caf/all.hpp:48,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/mixin/requester.hpp:71:3: note: candidate: template<caf::message_priority P, class Handle, class ... Ts> caf::response_handle<Subtype, typename caf::response_type<typename Handle::signatures, typename caf::detail::implicit_conversions<typename std::decay<Ts>::type>::type ...>::type, caf::mixin::is_blocking_requester<Subtype>::value> caf::mixin::requester<Base, Subtype>::request(const Handle&, const caf::duration&, Ts&& ...) [with caf::message_priority P = P; Handle = Handle; Ts = {Ts ...}; Base = caf::mixin::sender<caf::scheduled_actor, caf::event_based_actor>; Subtype = caf::event_based_actor]
   request(const Handle& dest, const duration& timeout, Ts&&... xs) {
   ^~~~~~~
/usr/local/include/caf/mixin/requester.hpp:71:3: note:   template argument deduction/substitution failed:
typed_calculator.cpp:55:47: note:   cannot convert ‘caf::atom_constant<(caf::atom_value)265756344>::value’ (type ‘const caf::atom_constant<(caf::atom_value)265756344>’) to type ‘const caf::duration&’
   self->request(testee, plus_atom::value, 2, 1).then(
                                               ^
In file included from /usr/local/include/caf/mixin/behavior_changer.hpp:32:0,
                 from /usr/local/include/caf/scheduled_actor.hpp:81,
                 from /usr/local/include/caf/event_based_actor.hpp:28,
                 from /usr/local/include/caf/detail/split_join.hpp:26,
                 from /usr/local/include/caf/actor_pool.hpp:30,
                 from /usr/local/include/caf/all.hpp:48,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/mixin/requester.hpp:107:3: note: candidate: template<caf::message_priority P, class Rep, class Period, class Handle, class ... Ts> caf::response_handle<Subtype, typename caf::response_type<typename Handle::signatures, typename caf::detail::implicit_conversions<typename std::decay<Ts>::type>::type ...>::type, caf::mixin::is_blocking_requester<Subtype>::value> caf::mixin::requester<Base, Subtype>::request(const Handle&, std::chrono::duration<Rep, Period>, Ts&& ...) [with caf::message_priority P = P; Rep = Rep; Period = Period; Handle = Handle; Ts = {Ts ...}; Base = caf::mixin::sender<caf::scheduled_actor, caf::event_based_actor>; Subtype = caf::event_based_actor]
   request(const Handle& dest, std::chrono::duration<Rep, Period> timeout,
   ^~~~~~~
/usr/local/include/caf/mixin/requester.hpp:107:3: note:   template argument deduction/substitution failed:
typed_calculator.cpp:55:47: note:   ‘caf::atom_constant<(caf::atom_value)265756344>’ is not derived from ‘std::chrono::duration<_Rep, _Period>’
   self->request(testee, plus_atom::value, 2, 1).then(
                                               ^
typed_calculator.cpp: In lambda function:
typed_calculator.cpp:58:52: error: no matching function for call to ‘caf::event_based_actor::request(const calculator_type&, const caf::atom_constant<(caf::atom_value)16957259448>&, int, int)’
       self->request(testee, minus_atom::value, 2, 1).then(
                                                    ^
In file included from /usr/local/include/caf/mixin/behavior_changer.hpp:32:0,
                 from /usr/local/include/caf/scheduled_actor.hpp:81,
                 from /usr/local/include/caf/event_based_actor.hpp:28,
                 from /usr/local/include/caf/detail/split_join.hpp:26,
                 from /usr/local/include/caf/actor_pool.hpp:30,
                 from /usr/local/include/caf/all.hpp:48,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/mixin/requester.hpp:71:3: note: candidate: template<caf::message_priority P, class Handle, class ... Ts> caf::response_handle<Subtype, typename caf::response_type<typename Handle::signatures, typename caf::detail::implicit_conversions<typename std::decay<Ts>::type>::type ...>::type, caf::mixin::is_blocking_requester<Subtype>::value> caf::mixin::requester<Base, Subtype>::request(const Handle&, const caf::duration&, Ts&& ...) [with caf::message_priority P = P; Handle = Handle; Ts = {Ts ...}; Base = caf::mixin::sender<caf::scheduled_actor, caf::event_based_actor>; Subtype = caf::event_based_actor]
   request(const Handle& dest, const duration& timeout, Ts&&... xs) {
   ^~~~~~~
/usr/local/include/caf/mixin/requester.hpp:71:3: note:   template argument deduction/substitution failed:
typed_calculator.cpp:58:52: note:   cannot convert ‘caf::atom_constant<(caf::atom_value)16957259448>::value’ (type ‘const caf::atom_constant<(caf::atom_value)16957259448>’) to type ‘const caf::duration&’
       self->request(testee, minus_atom::value, 2, 1).then(
                                                    ^
In file included from /usr/local/include/caf/mixin/behavior_changer.hpp:32:0,
                 from /usr/local/include/caf/scheduled_actor.hpp:81,
                 from /usr/local/include/caf/event_based_actor.hpp:28,
                 from /usr/local/include/caf/detail/split_join.hpp:26,
                 from /usr/local/include/caf/actor_pool.hpp:30,
                 from /usr/local/include/caf/all.hpp:48,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/mixin/requester.hpp:107:3: note: candidate: template<caf::message_priority P, class Rep, class Period, class Handle, class ... Ts> caf::response_handle<Subtype, typename caf::response_type<typename Handle::signatures, typename caf::detail::implicit_conversions<typename std::decay<Ts>::type>::type ...>::type, caf::mixin::is_blocking_requester<Subtype>::value> caf::mixin::requester<Base, Subtype>::request(const Handle&, std::chrono::duration<Rep, Period>, Ts&& ...) [with caf::message_priority P = P; Rep = Rep; Period = Period; Handle = Handle; Ts = {Ts ...}; Base = caf::mixin::sender<caf::scheduled_actor, caf::event_based_actor>; Subtype = caf::event_based_actor]
   request(const Handle& dest, std::chrono::duration<Rep, Period> timeout,
   ^~~~~~~
/usr/local/include/caf/mixin/requester.hpp:107:3: note:   template argument deduction/substitution failed:
typed_calculator.cpp:58:52: note:   ‘caf::atom_constant<(caf::atom_value)16957259448>’ is not derived from ‘std::chrono::duration<_Rep, _Period>’
       self->request(testee, minus_atom::value, 2, 1).then(
                                                    ^
typed_calculator.cpp: In function ‘int main()’:
typed_calculator.cpp:80:16: error: use of deleted function ‘caf::actor_system::actor_system()’
   actor_system system;
                ^~~~~~
In file included from /usr/local/include/caf/typed_actor.hpp:27:0,
                 from /usr/local/include/caf/send.hpp:26,
                 from /usr/local/include/caf/all.hpp:25,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/actor_system.hpp:150:3: note: declared here
   actor_system() = delete;
   ^~~~~~~~~~~~
In file included from /usr/local/include/caf/make_actor.hpp:28:0,
                 from /usr/local/include/caf/typed_actor.hpp:24,
                 from /usr/local/include/caf/send.hpp:26,
                 from /usr/local/include/caf/all.hpp:25,
                 from typed_calculator.cpp:8:
/usr/local/include/caf/actor_storage.hpp: In instantiation of ‘caf::actor_storage<T>::actor_storage(caf::actor_id, caf::node_id, caf::actor_system*, Us&& ...) [with Us = {caf::actor_config&}; T = {anonymous}::typed_calculator_class; caf::actor_id = long unsigned int]’:
/usr/local/include/caf/make_actor.hpp:49:14:   required from ‘R caf::make_actor(caf::actor_id, caf::node_id, caf::actor_system*, Ts&& ...) [with T = {anonymous}::typed_calculator_class; R = caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)265756344>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16957259448>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> > >; Ts = {caf::actor_config&}; caf::actor_id = long unsigned int]’
/usr/local/include/caf/actor_system.hpp:517:29:   required from ‘caf::infer_handle_from_class_t<T> caf::actor_system::spawn_impl(caf::actor_config&, Ts&& ...) [with C = {anonymous}::typed_calculator_class; caf::spawn_options Os = (caf::spawn_options)0; Ts = {}; caf::infer_handle_from_class_t<T> = caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)265756344>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16957259448>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> > >]’
/usr/local/include/caf/actor_system.hpp:319:29:   required from ‘caf::infer_handle_from_class_t<T> caf::actor_system::spawn(Ts&& ...) [with C = {anonymous}::typed_calculator_class; caf::spawn_options Os = (caf::spawn_options)0; Ts = {}; caf::infer_handle_from_class_t<T> = caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)265756344>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16957259448>, int, int>, caf::output_tuple<caf::atom_constant<(caf::atom_value)1090567515257>, int> > >]’
typed_calculator.cpp:85:61:   required from here
/usr/local/include/caf/actor_storage.hpp:44:5: error: ‘{anonymous}::typed_calculator_class::typed_calculator_class(caf::actor_config&)’ is protected within this context
     new (&data) T(std::forward<Us>(zs)...);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
typed_calculator.cpp:36:3: note: declared protected here
   typed_calculator_class(actor_config& cfg) : calculator_type::base(cfg) {
   ^~~~~~~~~~~~~~~~~~~~~~
`
What am I missing?
Looking forward to any hints.
Marco

**Comment by Neverlord** [comment]
> What am I missing?

You didn't miss a thing. The test was excluded in CMake for some reason and simply was broken. Sorry about that! Fixed in 2e704f7ea250731ebb6b2759887b086ddace3bef.
