### ISSUE TITLE
performance overhead of unused actor_system

### ISSUE THREAD

**Issue by jsiwek** [actor-framework/actor-framework#699]
On a 32-core Linux system (`std::thread::hardware_concurrency()` is 32) and default build of caf/master (cdfe2c223) using the following test benchmark:

```c++
#include "caf/actor_system.hpp"
#include "caf/actor_system_config.hpp"
#include <cstdint>
using namespace caf;

int main()
    {
    actor_system_config cfg;
    actor_system system{cfg};

    uint64_t total = 0u;
    uint64_t limit = 10000000000u;

    for ( uint64_t i = 0u; i < limit; ++i )
        total += i;

    return 0;
    }
```

I get this timing (built w/ `-O0`):

```
$ time ./a.out

real	1m6.162s
user	1m12.252s
sys	0m27.054s
```

Then recompile without creating an `actor_system`:

```c++
#include "caf/actor_system.hpp"
#include "caf/actor_system_config.hpp"
#include <cstdint>
using namespace caf;

int main()
    {
    //actor_system_config cfg;
    //actor_system system{cfg};

    uint64_t total = 0u;
    uint64_t limit = 10000000000u;

    for ( uint64_t i = 0u; i < limit; ++i )
        total += i;

    return 0;
    }
```

And I get this timing:

```
$ time ./a.out

real	0m45.918s
user	0m45.751s
sys	0m0.002s
```

I can also get closer to the better timing by artificially limiting the number of threads via `cfg.scheduler_max_threads = 4;`.  Running the benchmarks on a lower-core system with default configuration would also not see as much of a problem.

Does this generally indicate some scaling issues on high-core-count systems?  Or is there any room to improve CAF so that the default configuration of an actor system on a high-core-count machine doesn't have as much overhead?

**Comment by Neverlord** [comment]
This could be an artifact of various multicore optimizations for low-concurrency setups. For example, Intel's "Turbo Boost" will shutdown unused cores to be able to increase the clock speed for single-threaded applications.

You could test for this by spawning one thread per core  that does nothing but sleeps a few milliseconds in a loop (e.g. until a global shutdown flag is set). That should reproduce the performance decrease you see without CAF if something like Intel's Turbo Boost is to blame here.

Mitigating this in CAF would require tweaks to the work stealing scheduler. The scheduler is designed without any central component, so "no work is available in the entire system" is hard to detect. Shutting down workers once they agree nothing is happening might cause additional latencies once work does become available again and needs to spread to all workers. We currently do a poll strategy with increasing wait intervals to get a compromise between not wasting too much power while being able to quickly get up to speed again.

Just my thoughts so far. Can you try a simple run with periodically waking threads to see if that triggers the same behavior on your 32-core machine?

**Comment by Neverlord** [comment]
> This behaviour could possibly be fixed also by the topic/latency-integration  branch

I've actually merged the branch into master two weeks ago after finishing some final testing and benchmarking: https://github.com/actor-framework/actor-framework/commit/04c1164882dcbfa9f59c9e4d8f270a1415e219bc 🙂

**Comment by Neverlord** [comment]
Btw, the `topic/latency-integration` is actually an unsuccessful experiment of mine. I'm sure you meant `topic/latency`.

**Comment by lovemycatt** [comment]
Yep, sorry for misleading information 😊 anyways, the way to trigger the wait behavior instead of poll is to set moderate-poll-attempts to 0 and fall back asap to the relaxed policy.
T

**Comment by Neverlord** [comment]
@jsiwek IIRC, you have a working setup in Broker for now that allows to processor to shutdown most cores reliably. I think the default use case for CAF should remain focused on maximum multi-core throughput, though. I'm not sure if there's a strategy that gives us the best of both extremes, so I close this for now. Please feel free to reopen if something comes up.
