### ISSUE TITLE
class based actor with initialize() method dies [undocumented]

### ISSUE THREAD

**Issue by marcoben73** [actor-framework/actor-framework#701]
In a class-based actor, if you define a method void initialize(), the actor dies without any error note!

The output of the program below is:
before send
after send
should not run !!!
after await

```
#include <caf/all.hpp>
#include <caf/io/all.hpp>

class TestStrange : public caf::event_based_actor {
public:
	TestStrange(caf::actor_config& cfg);
	virtual ~TestStrange();
	virtual caf::behavior make_behavior();
	void initialize();
};

TestStrange::TestStrange(caf::actor_config& cfg) :
	event_based_actor(cfg) {
}

TestStrange::~TestStrange() {
}

caf::behavior TestStrange::make_behavior() {
	return {
		[&] (int) {
			caf::aout(this) << "message received" << std::endl;
			this->quit();
		}
	};
}

void TestStrange::initialize() {
	caf::aout(this) << "should not run !!!" << std::endl;
}

void caf_main(caf::actor_system& system, const caf::actor_system_config& cfg) {
	auto test = system.spawn<TestStrange>();
	caf::scoped_actor self{system};
	std::cout << "before send" << std::endl;
	self->send(test, 0);
	std::cout << "after send" << std::endl;
	self->await_all_other_actors_done();
	std::cout << "after await" << std::endl;
}

CAF_MAIN(caf::io::middleman)
```

**Comment by josephnoir** [comment]
If you call the function `initialize` of the [super class](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/src/event_based_actor.cpp#L34), the message is processed as expected.
```cpp
void TestStrange::initialize() {
    event_based_actor::initialize();
    // caf::aout(this) << "should not run !!!" << std::endl;
}
```

I didn't find anything in documentation regarding this. Should probably be added to the [class-based actor section](https://actor-framework.readthedocs.io/en/stable/Actors.html?highlight=initialize#class-based-actors) or is there any reason not to allow this, @Neverlord?

**Comment by marcoben73** [comment]
I reported this problem only because I spent one day to figure out why my application stopped working after some changes.
In the documentation there's nothing about initialize() (not even in the [class diagram](http://actor-framework.readthedocs.io/en/latest/_images/actor_types.png))

**Comment by Neverlord** [comment]
> I reported this problem only because I spent one day to figure out why my application stopped working after some changes.

Sorry for your troubles.

The `initialize` function is not meant as customization point and really exists primarily as a means to an end for supporting function-based actors (where we need to construct an actor first and delay the call to the init function). That's not an excuse for omitting it entirely from the documentation of course. If you are going to override this function than you have to call `initialize` of your base type to mimic the behavior of constructors, i.e., initialize an actor from the base type to the most derived type.

**Comment by Neverlord** [comment]
The `initialize` function got added to the manual as customization point: https://actor-framework.readthedocs.io/en/0.17.5/Actors.html#class-local-actor.
