### ISSUE TITLE
Unknown definitions for MSVC 2017 compilier

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#706]
Windows10,  MSVC 2017
1. caf/config.h  does not contain definition for CAF_PUSH_DEPRECATED_WARNING for MSVC
2. same for __attribute__ which is used in caf\detail\parser\read_ini.hpp
3.  transition macro does not contain trailing ;

**Comment by josephnoir** [comment]
Are these nitpicks, warnings, or does this lead to compile errors?

**Comment by Neverlord** [comment]
> Are these nitpicks, warnings, or does this lead to compile errors?

@josephnoir https://jenkins.inet.haw-hamburg.de/job/CAF/job/msvc/715/

@skorokhod our CI already complained about this as well. I'll look into it.

**Comment by josephnoir** [comment]
Oh, I missed that. Sorry.
