### ISSUE TITLE
Actorize event_handler

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#711]
The `io::event_handler` becomes the new foundation for our lightweight broker replacement. To fit that role it needs to be an actor.

**Comment by josephnoir** [comment]
OK, so ... first of all: why should an `event_handler` be an actor? IIRC, we want it to integrate it into streaming, make timer usage easy, and fulfill the role that brokers held before by providing an actor-like interface to sockets. And I'm not entirely sure about the last item.

With these goals in mind, There are two reasons the multiplexer loop should execute an event handler: 1) a network event such as read or write happens and 2) a message is enqueue in the handlers mailbox. Network events are straight forward and can keep their implementation on the multiplexer side. I'm not sure about messages though. The current event handler cannot receive messages ... so this is rather new. However, the multiplexer does execute brokers which have a messaging interface and event handlers might work similarly.

Looking at the broker implementation, going forward an event handler needs to implement `enqueue` , `launch`, `cleanup`, and  `resume` (see `abstract_broker`). A key difference is that the broker is not streaming aware (?) and I'm not sure how much of a difference this makes. Is there simply another actor base class to extend, a new mixin, or how does this manifest itself?

There is probably a lot more I overlooked, but I'm trying to get a sense of what's to do while #716 is pending.

**Comment by Neverlord** [comment]
We settled on a different design for `caf_net`.

**Comment by Neverlord** [comment]
We settled on a different design for `caf_net`.
