### ISSUE TITLE
Please add Windows output directories to the .gitignore

### ISSUE THREAD

**Issue by zhulika** [actor-framework/actor-framework#741]
Would you please add the x86 and x64 folders to your .gitignore for Windows builds? It'd save me having to stash it every time I pull.

Many thanks

**Comment by josephnoir** [comment]
Have you considered adding the folders to your local global gitignore?

**Comment by zhulika** [comment]
I’d completely forgotten about that, thanks for the reminder! I’m so used to fixing up every project to be “clean”.

I still think they should be in the .gitignore for this project, though. If all the Unix output folders have been added, I think that the Windows ones should be there, too.

**Comment by zhulika** [comment]
please ignore this. I misunderstood the way that CMake works. Creating another subfolder under "build" is what I should be doing.

Sorry for the noob question :)
