### ISSUE TITLE
In ./configure phase: Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by marcoippolito** [actor-framework/actor-framework#742]
In ./configure phase: 
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable   
    OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)

But 
    marco@ubuntu:~/actor-framework$ openssl version
    OpenSSL 1.0.2o  27 Mar 2018

So... what do I have to do to solve the problem?
Looking forward to your kind help.
Marco

**Comment by josephnoir** [comment]
It seems that on Ubuntu the openssl utility is packaged separately from the dev libraries. Try installing `libssl-dev`. 

(And if that doesn't help confirm that you have the headers installed, e.g., `find /usr -name ssl.h` and set the the `OPENSSL_ROOT_DIR` accordingly.)
