### ISSUE TITLE
Cannot seem to disable logging to file

### ISSUE THREAD

**Issue by zhulika** [actor-framework/actor-framework#743]
I have set the ```CAF_LOG_LEVEL``` to -1 on my build but it still produces a log file with entries for "log_first_line" and "log_last_line". As the thread and process ids are both part of the defaults for the log file, this means that my folder very quickly fills up with small files that I don't want.

I'm running in an add-in environment that cannot control the command-line (so no ```argc```/```argv```); there is no ```cout``` or ```cerr``` either. So, with that in mind, is there a way to stop CAF from producing this almost-empty log file? I have tried clearing the ```logger_file_name``` field on my actor_config but that just means CAF writes a log file with the default name.

What should I do to stop it writing any log file at all?

Many thanks,

Dan

**Comment by Neverlord** [comment]
@zhulika should be fixed now via eabbc57, if not please re-open.

**Comment by zhulika** [comment]
Thank you
