### ISSUE TITLE
cannot convert ‘caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<

### ISSUE THREAD

**Issue by marcoippolito** [actor-framework/actor-framework#746]
Using the code found here [https://actor-framework.readthedocs.io/en/latest/MessagePassing.html?highlight=adder%3A%3Apointer](url)  

    `#include <iostream>
    #include <vector>
    #include "caf/all.hpp"

    using namespace caf;

    using cell = typed_actor<reacts_to<put_atom, int>, replies_to<get_atom>::with<int>>;
    struct cell_state {
      int value = 0;
    };

    cell::behavior_type cell_impl(cell::stateful_pointer<cell_state> self, int x0) {
      self->state.value = x0;
      return {
        [=](put_atom, int val) {
          self->state.value = val;
        },
        [=](get_atom) {
          return self->state.value;
        }
      };
    }

    void waiting_testee(event_based_actor* self, std::vector<cell> cells) {
      for (auto& x : cells) {
        self->request(x, std::chrono::seconds(1), get_atom::value).await([=](int y) {
          aout(self) << "cell #" << x.id() << " -> " << y << std::endl;
        });
      }
    }

    void multiplexed_testee(event_based_actor* self, std::vector<cell> cells) {
      for (auto& x : cells) {
        self->request(x, std::chrono::seconds(1), get_atom::value).then([=](int y) {
          aout(self) << "cell #" << x.id() << " -> " << y << std::endl;
        });
      }
    }

    void blocking_testee(blocking_actor* self, std::vector<cell> cells) {
      for (auto& x : cells)
        self->request(x, std::chrono::seconds(1), get_atom::value).receive(
          [&](int y) {
            aout(self) << "cell #" << x.id() << " -> " << y << std::endl;
          },
          [&](error& err) {
            aout(self) << "cell #" << x.id()
                       << " -> " << self->system().render(err) << std::endl;
          }
        );
    }

    int main() {
      // our CAF environment
      actor_system_config cfg;
      actor_system system{cfg};

      // We spawn five cells and assign the values 0, 1, 4, 9, and 16.
      std::vector<cell> cells;
      for (auto i = 0; i < 5; ++i) {
        cells.emplace_back(system.spawn(cell_impl, i * i));
      }

      // When passing the cells vector to our three different implementations, we observe three outputs
      //waiting_testee(event_based_actor* self, std::vector<cell> cells);
      waiting_testee(cell_impl, cells);

      return 0;
    }

`

When compiling give these errors:

    `g++ -std=c++17 messageHandling.cpp -lcaf_core -lcaf_io -L /usr/local/lib -omessageHandling
    messageHandling.cpp: In function ‘int main()’:
    messageHandling.cpp:93:18: error: cannot convert    
    ‘caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4153017>,  
    int>, caf::output_tuple<void> >,   
    caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4115129> >,  
    caf::output_tuple<int> > >::behavior_type  
       
 

     (*)(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4153017>, 
    int>, caf::output_tuple<void> >,    
    caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4115129> >,  
    caf::output_tuple<int> > >::stateful_pointer<cell_state>, int)’ {aka   
    ‘caf::typed_behavior<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4153017>, int>, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4115129> >, caf::output_tuple<int> > > (*)(caf::stateful_actor<cell_state, caf::typed_event_based_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4153017>, int>, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4115129> >, caf::output_tuple<int> > > >*, int)’} to ‘caf::event_based_actor*’
       waiting_testee(cell_impl, cells);
                      ^~~~~~~~~
    

    messageHandling.cpp:46:40: note:   initializing argument 1 of ‘void  
    waiting_testee(caf::event_based_actor*,            std::vector<caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4153017>, int>, caf::output_tuple<void> >, 
    caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)4115129> >,  
    caf::output_tuple<int> > > >)’
     void waiting_testee(event_based_actor* self, std::vector<cell> cells) {
                         ~~~~~~~~~~~~~~~~~~~^~~~

    `

What to do to solve the problem?
Marco

**Comment by Neverlord** [comment]
Why are you calling `waiting_testee` in the first place? Did you mean to spawn an actor here?

**Comment by marcoippolito** [comment]
Quite surely I'm doing something wrong... because I would like to print this output:
cell #9 -> 16
cell #8 -> 9
cell #7 -> 4
cell #6 -> 1
cell #5 -> 0
as pointed out that waiting_testee will always print this output : [https://actor-framework.readthedocs.io/en/latest/MessagePassing.html?highlight=adder%3A%3Apointer](url)
so.. how to call waiting_testee in order to get this output?

**Comment by Neverlord** [comment]
All snippets in the manual have a fully running example program. The snippets you've pasted here are from this example: https://github.com/actor-framework/actor-framework/blob/master/examples/message_passing/request.cpp.

**Comment by marcoippolito** [comment]
Thanks a lot. I have to get deep into CAF syntax in order to understand it better
