### ISSUE TITLE
Segfault while receiving unhandled message after changing behaviour using become

### ISSUE THREAD

**Issue by segfault-magnet** [actor-framework/actor-framework#750]
Changing the behaviour of an actor results in segfault or in unhandled exception St9_bad_alloc. 
Caf version: 0.15.5
Minimal 'working' example:

```cpp
#include  <caf/all.hpp>

using namespace caf;

behavior actorTwo(event_based_actor* self) {
  return {};
}
behavior actorOne(event_based_actor* self) {
  return {[=](const std::string& msg) { self->become(actorTwo(self)); }};
}
void caf_main(actor_system& system, const actor_system_config& cfg) {
  auto one = system.spawn(actorOne);

  scoped_actor sc{system};
  sc->send(one, "Hey");
}
CAF_MAIN()
```

**Comment by riemass** [comment]
Hello,
I confirm the same behavior by me.
docker based on Ubuntu 17.10 with custom build of CAF 0.15.5.

**Comment by segfault-magnet** [comment]
Works with the following correction:
```cpp
#include <caf/all.hpp>

using namespace caf;

behavior actorTwo(event_based_actor* self) {
  return {[=](const std::string& msg) {

  }};
}
behavior actorOne(event_based_actor* self) {
  return {[=](const std::string& msg) { self->become(actorTwo(self)); }};
}
void caf_main(actor_system& system, const actor_system_config& cfg) {
  auto one = system.spawn(actorOne);

  scoped_actor sc{system};
  sc->send(one, std::string("Hey"));
}
CAF_MAIN()
```

**Comment by Hamdor** [comment]
The problem was, that you capture the self ptr by reference (in your first version). At the time your message handler is called, the captured argument (self ptr) is no longer valid. This is not a bug in CAF.

**Comment by segfault-magnet** [comment]
Please note that the problem persist even when you capture the pointer correctly. It would seem the segfault occurs should the actor change it's behavior to one with no message handlers.

**Comment by Hamdor** [comment]
Thanks for the clarification, I see the problem now.
