### ISSUE TITLE
Allow multiple app identifiers in handshake

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#756]
In VAST, we're running into a problem where one `actor_system` serves multiple applications with different app identifiers. We currently workaround this "bug" by adopting the app identifier of the target application.

The right fix would be to support multiple app identifiers in the form of a list, and send them all across the wire. The responder would then pick the subset it supports. Only if the intersection is empty, a connection should not be feasible.

**Comment by Neverlord** [comment]
Implemented via https://github.com/actor-framework/actor-framework/pull/816.
