### ISSUE TITLE
Windows build problems

### ISSUE THREAD

**Issue by uentity** [actor-framework/actor-framework#762]
I tested with two builds: one produced by MS vcpkg utility and the other one I built myself using CMake + Visual Studio 15.8.5.

What am I getting is division by zero exception on line 118 in `scheduled_actor.cpp`:
```
  max_batch_delay_ticks_ = sys_cfg.stream_max_batch_delay.count()
                           / interval.count();
```
After investigating a little I found out that all variables defined in `defaults.cpp` are equal zero. Do I understand correctly that they should be initialized in compile-time and just 'built in' into resulting binary without any runtime-initialization code?

Maybe I'm missing something, please take a look at what am I doing.
1) `libcaf_core_static.lib` and `libcaf_io_static.lib` compiled without any error.
2) I have a DLL that creates default `actor_system_config` and initializes `actor_system` instance. Initialization is executed in singleton constructor that is actually a static variable. DLL links statically with libraries from p. 1.
3) A small executable links with above DLL and when it is started, I'm getting an exception.

Can this happen because of statics from CAF's `default.cpp` isn't yet initialized when singleton constructor starts? If so, what is the best way to solve this problem?

BTW, there are no such issues on Linux with CAF build as shared libraries.

**Comment by uentity** [comment]
Forgot to mention version of CAF: 0.16.0.

**Comment by uentity** [comment]
I've modified variables in `default.hpp` and turned most of them into `constexp` values (besides `scheduler::max_threads` which is `static const` now) and excluded `defaults.cpp` from build. BTW why isn't that done upstream?

After that exception in the issue disappeared and I was able to move further. Now execution stuck on line 56 of `worker.hpp`:
```
    this_thread_ = std::thread{[this_worker] {
      this_worker->system().thread_started();
      this_worker->run();
      this_worker->system().thread_terminates();
    }};
``` 
This line never returns.

Are there any Windows CAF exists publicly available?

**Comment by Neverlord** [comment]
Not finding variables in the DLL looks like linking/loading issues. CAF does not export symbols by default. Did you build with `WINDOWS_EXPORT_ALL_SYMBOLS`?

**Comment by Neverlord** [comment]
> Do I have to put any extra defines for Windows?

Disclaimer: we only ever test the static library builds, mainly because we have no Windows developer in our team (and most users also seem to use UNIX derivatives).

However, if you set `WINDOWS_EXPORT_ALL_SYMBOLS` in CMake then it *should* make sure to export everything to the `.dll`. That's probably going to increase the file size a lot.

**Comment by uentity** [comment]
> Disclaimer: we only ever test the static library builds, mainly because we have no Windows developer in our team (and most users also seem to use UNIX derivatives).

That makes sense...

I don't think the issue is caused by symbols visibility, because in that case linker will complain for sure. Symbols are visible even in runtime, but they aren't correctly initialized. After all I was able to resolve it by `constexpr` modification.

Now I can't figure out why execution hangs on line where new worker or timer `std::thread` is created...

OK, two more questions.
1) Are you open to accept modifications that I will need to make to proceed with Windows build?
2) Is there some theoretical stopper from making shared (DLL) Windows build other than the fact that nobody tested it?

**Comment by Neverlord** [comment]
Once you put constants into a header with `constexpr`, the compiler will simply inline most of the constants (for example, by replacing `defaults::foo` in source code with `42` in assembly) or duplicate them in multiple translation units (and tell the linker to drop duplicates). In any case, you bypass the `.lib/.dll` alltogether.

> 1) Are you open to accept modifications that I will need to make to proceed with Windows build?

Absolutely.

> 2) Is there some theoretical stopper from making shared (DLL) Windows build other than the fact that nobody tested it?

I don't think so. In the long run, we probably need to care about explicit symbol export. However, any solution that makes `.dll` files on Windows available for CAF will be welcome.

**Comment by uentity** [comment]
Update of progress on this issue.

1) Thanks to your hint about `WINDOWS_EXPORT_ALL_SYMBOLS` I was able to build a workind CAF core and io DLL!
That required me to change default values to `constexpr` ones and I converted one value, `max_threads` to a function. This way nothing to be done in addition to CMake define. Leaving 
But this solution is a little bit ugly and probably not suitable for making into upstream.
From one point of view this is a quick way to produce a DLL that works.
From another, if we assume that explicit visibility tag is going to be added everywhere, then we can do a lot of things, for ex. convert all nested namespaces in `defaults` into structs with static members. But adding explicit visibility is a lot of work and should be done carefully. Once it's done CAF can include `-fvisibility=hidden` switch in UNIX builds.

2) Hanging on `std::thread` creation was caused by deadlock that occurs if any thread is created until DllMain() finishes. I initialized `actor_system` in static variable and that lead to hangup.

PS. I really appreciate a very clean and clever codebase in CAF.

**Comment by uentity** [comment]
OK, next issue is that program hangs on exit in -- `io::middleman` cannot die. It waits infinite in `cv.wait(guard)`:
```
  template <class Mutex, class CondVar>
  void synchronized_await(Mutex& mtx, CondVar& cv) {
    CAF_ASSERT(!closed());
    if (try_block()) {
      std::unique_lock<Mutex> guard(mtx);
      while (blocked())
        cv.wait(guard);
    }
  }
```

**Comment by Neverlord** [comment]
Thanks for sharing progress on this. Could you get past this issue?

**Comment by uentity** [comment]
@Neverlord Nope. I was busy with setting up the build environment for my project with modified CAF, etc.
The only thing I checked is that infinite wait is reproduced on both static and shared (DLL) CAF builds. 
I will continue investigation on this topic.

BTW, solution with `constexpr` defaults is no-go also because strings cannot be `constexpr`. So I'm going to add explicit symbol visibility tag finally.

**Comment by uentity** [comment]
Well, it seems that problem with infinite wait on exit is also related to `actor_system` instance being stored as static variable.
If I manually destruct `actor_system` everything works as expected.

Conclusion: DO NOT store `actor_system` as static variable. It works on Linux, but lead to deadlocks on Windows.

**Comment by uentity** [comment]
Finally I come up with solution in PR #767 
Please, take a look.

**Comment by Neverlord** [comment]
Thanks for your input! 👍

Closed via https://github.com/actor-framework/actor-framework/pull/992.
