### ISSUE TITLE
Add free function to set value in config_value_map

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#769]
It's quite cumbersome to set a value in a `config_value_map`:
```cpp
config_value_map opts;
opts.emplace("global", config_value::dictionary{{"key", config_value{"value}}});
```

What I would prefer:
```cpp
config_value_map opts;
set("global", "key", "value");
```

**Comment by Neverlord** [comment]
I'd like to avoid the name `set` to avoid ambiguities (mainly with `std::set`). What about `assign` or `put`? Also, I'd use the same notation that we use for the `get` functions:

```c++
put(opts, "global.key", "value");
assign(opts, "global.key", "value");
```

**Comment by mavam** [comment]
I have no strong preference regarding the name. If there's a free `get` function to access values, `put` has a nice symmetry.
