### ISSUE TITLE
Manual doesn't build in non-standard environment

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#773]
The manual build harness assumes a standard configuration with a default `build` directory. Otherwise it fails.

Per our discussion, we decided that a separate opt-in flag `--with-manual` makes more sense, because the LaTeX beast is difficult to tame.

**Comment by Neverlord** [comment]
Fixed in ddda3d9e0b64d2d4111a97caa76bf3f894a2d884.
