### ISSUE TITLE
caf-python: AttributeError on start

### ISSUE THREAD

**Issue by mroethke** [actor-framework/actor-framework#775]
caf-python immediately errors out on start with the following error.

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
    AttributeError: module 'IPython' has no attribute 'Config'
    Unable to launch interactive Python shell!
    Please install it using: pip install ipython

ipython is most certainly installed.

Relevant software versions:
caf: current master and 0.16.0
python: 3.7
ipython: 6.5
gcc: 8.2.1

**Comment by Neverlord** [comment]
The python shell didn't get much attention lately. @lovemycatt do I remember correctly that you work on improving the Python bindings?

**Comment by lovemycatt** [comment]
Sorry for answering so late…
Yes we’ve been working on that, I must check with a colleague if what we did is suitable for a PR
I’ll be back to you with some details in a couple of weeks, he is currently on a marriage leave :)
Tullio

**Comment by Neverlord** [comment]
The Python shell for CAF was originally meant as part of the Nexus/Probe debugging architecture. We've abandoned the plans for an introspection shell a while back, so consequently we currently have no use the Python shell.

To cut a long story short, 0.18 is going to remove the `caf_python` module. I think full fledged Python bindings would be a nice thing to have, though. So we're definitely open for contributions that allow integrating CAF and Python.
