### ISSUE TITLE
Installation: make and make install phases fail . What am I missing?

### ISSUE THREAD

**Issue by marcoippolito** [actor-framework/actor-framework#788]
Hi,
I tried twice to install the just git-cloned CAF in Ubuntu 18.04.01 Server Edition, but the make and make install phases fail:

    [ 82%] Building CXX object CMakeFiles/caf-test.dir/libcaf_io/test/triggering.cpp.o
    [ 83%] Building CXX object CMakeFiles/caf-test.dir/libcaf_io/test/typed_broker.cpp.o
    [ 83%] Building CXX object CMakeFiles/caf-test.dir/libcaf_io/test/typed_remote_actor.cpp.o
    [ 83%] Building CXX object CMakeFiles/caf-test.dir/libcaf_io/test/unpublish.cpp.o
    [ 84%] Building CXX object CMakeFiles/caf-test.dir/libcaf_openssl/test/authentication.cpp.o
    /home/marco/actor-framework/libcaf_io/test/typed_broker.cpp: In member function   
    ‘caf::match_case::result caf::trivial_match_case< <template-parameter-1-1>  
    >::invoke(caf::detail::invoke_result_visitor&, caf::type_erased_tuple&) [with F =  
    {anonymous}::peer_fun(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<caf::io::new_data_msg>,  
    caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::io::connection_closed_msg>,  
    caf::output_tuple<void> >,  
    caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)265743596>, int>, 
    caf::output_tuple<void> >,  
    caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)265768172>, int>,  
    caf::output_tuple<void> > >::broker_pointer, caf::io::connection_handle, const caf::actor&):: 
    <lambda(const caf::io::new_data_msg&)>]’:
    /home/marco/actor-framework/libcaf_io/test/typed_broker.cpp:128:7: warning: ‘x’ may be used  
    uninitialized in this function [-Wmaybe-uninitialized]
           if (x == pong_atom::value)
           ^~
    /home/marco/actor-framework/libcaf_io/test/typed_broker.cpp:123:18: note: ‘x’ was declared here
           atom_value x;
                      ^
    In file included from /usr/include/string.h:494:0,
                     from /usr/include/c++/7/cstring:42,
                     from /home/marco/actor-framework/libcaf_core/caf/string_view.hpp:22,
                     from /home/marco/actor-framework/libcaf_core/caf/detail/stringification_inspector.hpp:29,
                     from /home/marco/actor-framework/libcaf_core/caf/deep_to_string.hpp:31,
                     from /home/marco/actor-framework/libcaf_core/caf/optional.hpp:28,
                     from /home/marco/actor-framework/libcaf_core/caf/message.hpp:31,
                     from /home/marco/actor-framework/libcaf_core/caf/make_message.hpp:25,
                     from /home/marco/actor-framework/libcaf_core/caf/sec.hpp:26,
                     from /home/marco/actor-framework/libcaf_core/caf/all.hpp:23,
                     from /home/marco/actor-framework/libcaf_test/caf/test/dsl.hpp:21,
                     from /home/marco/actor-framework/libcaf_io/test/typed_broker.cpp:22:
    In function ‘void* memcpy(void*, const void*, size_t)’,
        inlined from ‘std::streamsize caf::arraybuf<CharT, Traits>::xsgetn(caf::arraybuf<CharT,  
    Traits>::char_type*, std::streamsize) [with CharT = char; Traits = std::char_traits<char>]’ at /home/marco 
    /actor-framework/libcaf_core/caf/streambuf.hpp:233:16,
        inlined from ‘std::streamsize std::basic_streambuf<_CharT, 
    _Traits>::sgetn(std::basic_streambuf<_CharT, _Traits>::char_type*, std::streamsize) [with _CharT = char;
    _Traits = std::char_traits<char>]’ at /usr/include/c++/7/streambuf:358:37,
        inlined from ‘caf::error caf::stream_deserializer<Streambuf>::apply_raw(size_t, void*) [with Streambuf 
    = caf::arraybuf<char>]’ at /home/marco/actor-framework/libcaf_core  
    /caf/stream_deserializer.hpp:107:33,
        inlined from ‘caf::error   
    caf::stream_deserializer<Streambuf>::apply_builtin(caf::data_processor<caf::deserializer>::builtin, void*) 
    [with Streambuf = caf::arraybuf<char>]’ at /home/marco/actor-framework/libcaf_core 
    /caf/stream_deserializer.hpp:135:46:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:71: warning: ‘void* __builtin_memcpy(void*, 
    const void*, long unsigned int)’: specified size between 9223372036854775808 and 
    18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
       return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
                                                                       ^
    [ 84%] Building CXX object CMakeFiles/caf-test.dir/libcaf_openssl/test/remote_actor.cpp.o
    [84%] Linking CXX executable bin/caf-test
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [ 84%] Built target caf-test
    make[2]: Leaving directory '/home/marco/actor-framework/build' 
    Makefile:140: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/home/marco/actor-framework/build'
    Makefile:4: recipe for target 'all' failed
    make: *** [all] Error 2
    marco@pc01:~/actor-framework$ sudo make check
    make: *** No rule to make target 'check'.  Stop.
    
    marco@pc01:~/actor-framework$ sudo make install
    make[1]: Entering directory '/home/marco/actor-framework/build'
    make[2]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [0%] Built target libcaf_openssl
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [0%] Built target libcaf_core
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [ 37%] Built target libcaf_core_shared
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [ 37%] Built target libcaf_io
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [48%] Built target libcaf_io_shared
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [50%] Built target libcaf_openssl_shared
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [ 50%] Built target all_unit_tests
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [83%] Built target caf-test
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [83%] Built target all_examples
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    [84%] Built target group_server
    make[3]: Entering directory '/home/marco/actor-framework/build'
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    make[3]: Entering directory '/home/marco/actor-framework/build'
    [84%] Linking CXX executable ../bin/custom_types_3
    ../lib/libcaf_core.so.0.16.2: undefined reference to `caf::detail::socket_guard::~socket_guard()'
    ../lib/libcaf_core.so.0.16.2: undefined reference to `caf::detail::socket_guard::socket_guard(int)'
    collect2: error: ld returned 1 exit status
    examples/CMakeFiles/custom_types_3.dir/build.make:99: recipe for target 'bin/custom_types_3' failed
    make[3]: *** [bin/custom_types_3] Error 1
    make[3]: Leaving directory '/home/marco/actor-framework/build'
    CMakeFiles/Makefile2:662: recipe for target 'examples/CMakeFiles/custom_types_3.dir/all' failed
    make[2]: *** [examples/CMakeFiles/custom_types_3.dir/all] Error 2
    make[2]: Leaving directory '/home/marco/actor-framework/build'
    Makefile:140: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/home/marco/actor-framework/build'
    Makefile:10: recipe for target 'install' failed
    make: *** [install] Error 2
    marco@pc01:~/actor-framework$

What am I missing?
Marco

**Comment by Neverlord** [comment]
That's not a problem on your end. The core has an unintentional dependency to a class from the I/O module.

**Comment by Neverlord** [comment]
@marcoippolito should be fixed in `master`, please re-open if the error persists.
