### ISSUE TITLE
Is is unclear if an address is created from host or network byte order.

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#796]
An CAF (IPv4) address can be created [from bits](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/ipv4_address.hpp#L49). It is unclear if the functions expects host or network byte order. This might be of interest to get the correct output when converting the address to a string.

**Comment by Neverlord** [comment]
Fixed via https://github.com/actor-framework/actor-framework/pull/815.
