### ISSUE TITLE
Find better name for config_value_map

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#802]
The alias `config_value_map` has a *very* misleading name. One would expect `std::map<config_value>` or something similar. However, it's defined as `dictionary<dictionary<config_value>>`. CAF's `dictionary<T>` is similar to `std::map<string, T>` but with a `string_view`-based interface for more efficient access.

The reason `config_value_map` is defined in this way is that this type is supposed to store the content of an `.ini` file. In other words, this type associates categories to a map of settings.

Here are my current ideas for new aliases:

```
using settings_map = dictionary<config_value>;
using configuration_map = dictionary<settings_map>;
```

This allows for intuitively named variables:

```
void fill_settings(settings_map& settings, ...);
void parse_config(configuration_map& configuration, ...);
```

I'm not sure if `configuration_map` signals "this is a map over settings" clearly enough. Thoughts?

**Comment by Neverlord** [comment]
I like the idea. I only would make it independent of the INI-format. We support it mostly for historic reasons at this point and it's straightforward to add a new format.

Here's a generalized version:

```c++
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Maps identifiers (keys) to their user-defined value.
using properties = dictionary<value>;

/// Groups properties into named sections.
using sections = dictionary<properties>;

} // namespace config
```

> I think putting the `_map` suffix into the typename does not do much good, especially since it is not really a full map type

FWIW, `dictionary<T>` is a fully fleshed out type with identical interface as `map<string, T>`. Including all the type aliases like `mapped_type`, `key_type`, `value_type`, etc.

**Comment by tobim** [comment]
> > I think putting the _map suffix into the typename does not do much good, especially since it is not really a full map type
> 
> FWIW, dictionary<T> is a fully fleshed out type with identical interface as map<string, T>. Including all the type aliases like mapped_type, key_type, value_type, etc.

Yes, now that I think about it again my line of reasoning makes no sense actually. A more concrete version of `map` is still a map after all.

I think the name changes from `section` to `properties` and `configuration` to `sections` is good, as this don't contain their own identifier.

>I like the idea. I only would make it independent of the INI-format. We support it mostly for historic reasons at this point and it's straightforward to add a new format.

But the way it you defined it above maps exactly to the INI-format.
When a new format is added you need to extend the definition, and you can rename the module at that point, client code will need to adapt to the change anyway. There is also another option: To introduce a new format independently, that way the API would stay stable.

**Comment by Neverlord** [comment]
I agree, the terminology should be format-agnostic. What would be more general names? Regardless of the format, the structure of our configuration is always component-oriented. For example, `logger.file-verbosity=trace` sets the parameter `file-verbosity` for the component `logger`.

What about `settings` and `components`?

```c++
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Maps parameter names (keys) to their user-defined value.
using settings = dictionary<value>;

/// Groups settings by component.
using components = dictionary<settings>;

} // namespace config
```

**Comment by Neverlord** [comment]
Or maybe a bit more descriptive:

```c++
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Maps parameter names (keys) to their user-defined value.
using settings = dictionary<value>;

/// Groups settings by component name.
using grouped_settings = dictionary<settings>;

} // namespace config
```

**Comment by tobim** [comment]
The most logical way of extending the expressive power of `config` I can think of is:
INI -> INI with recursively nested sections -> JSON.
YAML is not more expressive than JSON, except for the references feature, and I don't think CAF should have a YAML parser in the first place. I guess the situation with TOML is similar, but I don't know anything about it.

Now if we consider the above sequence as the logical evolution of `config`, we can already anticipate that for the next step, the definition of `value` is insufficient. Extending that in a way that is compatible is going to add additional burden on the maintainer and probably also on the user. I think it would make more sense to turn `config` into something that captures JSON, then we can parse at least INI and JSON into that, and support YAML/TOML or even some non turing complete language such as dhall with some post processing.

**Comment by Neverlord** [comment]
OK, I think we talk past each other. Please let me step back and add a bit more context.

The class `config_value` already is recursive. It can contain lists, dictionary, etc. Recursively nested sections are already implemented and you can do something like this in your `caf-application.ini`:

```ini
[abc]
def = {
  ghi = {
    some-value = 42,
    jkl = [
      mno = {
        ; ... ad infinitum ...
      },
      pqr = {
      },
      ; ...
    ]
  }
}
```

And in C++ land you can access whatever level of nesting:

```c++
auto some_value = get_or(cfg, "abc.def.ghi.some-value", 0);
```

However, the configuration framework on top of `config_value` expects a component-oriented structure (e.g. `logger.file-name` etc.). The C++ alias `settings` from my previous post simply means that we are expecting a key-value map of configuration parameters here, and nothing else. The alias `grouped_settings` means that we are expecting settings group by component, and nothing else.

Technically, the `actor_system_config` could have a `config_value` member for storing the configuration. But that would lose a lot of context about what the application actually expects. The config file is not supposed to contain a single integer or some list of values. Maybe I'm overthinking this and we should simply use the recursive `config_value` everywhere, but I think using the most restricted type possible adds a lot of value and clarity.

**Comment by mavam** [comment]
To me, it seems that we need one abstraction (e.g., `config::value`) that can represent the formats to a reasonable extent (INI, JSON, YAML, TOML). Everything on top may be use-case specific, e.g., grouping via sections.

> Maybe I'm overthinking this and we should simply use the recursive `config_value` everywhere, but I think using the most restricted type possible adds a lot of value and clarity.

On the flip site, having several restricted types adds complexity. A single `config_value` would make it easy to work with. In my opinion, the additional constraints can be expressed as preconditions and enforced at the point where you parse the value.

Personally, I would advocate for having one simple-yet-powerful data type that can be tied down as needed where it's used.

**Comment by Neverlord** [comment]
> Personally, I would advocate for having one simple-yet-powerful data type that can be tied down as needed where it's used.

Isn't that exactly what I was talking about? Please read my previous post again. `config_value` can represent all your formats already.

**Comment by mavam** [comment]
I'm lost. I provided feedback on the tension of having a single `config_value` everywhere vs. having more refined types in particular use cases. So I argued why I think the former makes more sense. This has nothing to do with formats. I'll let you take it from here.

**Comment by Neverlord** [comment]
Ok, let me give you a use case. Maybe I should've started the discussion in this way.

Say you had some central actor organizing control flow of your application. Let's call it `node`. Your `main` essentially has no other job than setting up the environment, starting this actor, and parse command line arguments. After parsing the CLI args you send them to your `node`.

For example, your user invokes `my-app --input=foo.txt --num-workers=42`. Your CLI is the classical key/value dictionary. Here, with keys `input` and `num-workers`. Now, what handler would you rather have in your node?

```c++
  (1)
  [](config_value& conf) {
    // ....
  }

  (2)
  [](config::settings& conf) {
    // ...
  }
```

I argue `(2)`, because we want to use the type system to detect nonsensical messages at compile-time. For example, approach `(1)` makes `self->send(node, config_value{"whassup?")` legal and we have to deal with bogus input the message handler.

If we can agree that we want to have such types, then we need good names for them. So far I proposed:

```c++
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Maps parameter names (keys) to their user-defined value.
using settings = dictionary<value>;

/// Groups settings by component.
using grouped_settings = dictionary<settings>;

} // namespace config
```

> Personally, I would advocate for having one simple-yet-powerful data type that can be tied down as needed where it's used.

With these two type aliases I'm trying to do exactly that by giving recognizable names for two common "tied down versions".

**Comment by josephnoir** [comment]
Just chiming in here: Of the two approaches you presented the number `(2)` makes more sense to me. And I see why finding a good name for the components is worth a discussion.

Reading your last comment, I think the problem is whether the "normal" use case or the mental model is,  using your  proposal above `settings` or `grouped_settings`. If it is the former, your naming makes sense, but if the default is to use `grouped_settings`, I'd argue for a naming scheme as follows.

```cpp
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Map parameter names (keys) to their user-defined value.
using section = dictionary<value>;

/// Group settings by section.
using settings = dictionary<section>;

} // namespace config
```

(I think `grouped_settings` sounds a weird, but I have a hard time coming up with a fitting alternative.)

**Comment by mavam** [comment]
Given your example, it would make most sense to do this:
```cpp
namespace config {

// Concrete values
using integer = int64_t;
using boolean = bool;

// Recursive types
using settings = dictionary<value>;

// Variant type
class value {
  using types = variant<integer, boolean, settings, ...>;
};

} // namespace config
```

Now you don't need to have `config::value::dictionary` and `config::settings`, which are exactly the same thing.

Like @josephnoir, I find that `grouped_settings` doesn't roll off the tongue, maybe `component_map`? If `section` would be renamed to `component`, then these might go well together.

**Comment by josephnoir** [comment]
> I argue (1), because (2) gives almost no advantage actually.

`config::settings` is not `dict<dict<val>` in the example but only `dict<val>`. Sending only the value removes most of the context. Attaching a name to values makes sense. Or did I misinterpret the example?

**Comment by tobim** [comment]
> config::settings is not dict<dict<val> in the example but only dict<val>

Just dict<val> is something I can actually get behind. Anything that does not have key identifiers at the top level can't reasonably be called a configuration, so that restriction is acceptable. Then I would propose
```c++
namespace config {

/// A value of a key/value property pair.
using value = config_value;

/// Map parameter names (keys) to their user-defined value.
using settings = dictionary<value>;

} // namespace config
```
Meaning you are not forced to use `section`s any more.
That way, that annoying built-in `global` section can also be dropped, and top level key-value pairs can be accessed from c++ like they are provided in the input.

**Comment by Neverlord** [comment]
Ok, thank you all for the feedback! Much appreciated. I agree what you're saying about the `global` category. That's really  an `.ini`-specific thing that leaked into the API.

I think @tobim made a good argument. All we need is a `using settings = ...;`. In that case I would also drop the `config` namespace altogether.

The reason why I hesitated a while to drop `global` is this. Consider these two examples:

(1)
```ini
[logger]
file-verbosity = 'trace'
console-verbosity = 'debug'
```

(2)
```ini
[global]
logger = {
  file-verbosity = 'trace',
  console-verbosity = 'debug',
}
```

Dropping `global` as an actual category means that (1) and (2) are now the same. Which can cause some surprising behavior:

```ini
[logger]
file-verbosity='trace'
[global]
logger="oooops!" ; overrides [logger] section!
```

However, I think it's still better going forward. We can print a warning for unexpected overrides. With that, we can also make `[global]` implicit. Doing so makes this example a valid `caf-application.ini` file:

```ini
logger {
  file-verbosity='debug',
  console='colored',
}
some-user-defined-integer=42
some-user-defined-list=[1, 2, 3]
some-lengthy-list=[
  "this is some long string",
  "this is another long string",
]
```

Arguably a cleaner style anyway.

**Comment by josephnoir** [comment]
Does this mean that `settings["logger"]` might give you their a dict if you specify something like this:
```ini
[logger]
file-verbosity='trace'
```
... or a value if you file looks like this:
```ini
[global]
logger='oooops!'
```

**Comment by Neverlord** [comment]
Yes, `logger` is just a `config_value`. However, you would usually access it like this: `get_if<settings>(config, "logger")` in C++ (with `settings = dictionary<config_value>`).

**Comment by josephnoir** [comment]
Right, `config_value` is already a variant. Mavam's suggestion above made me think it wasn't. So what's changing is the the requirement for the global namespace which takes away the insurance that the first hierarchy returns a dict and thus simplifies the config data structure. 👍
