### ISSUE TITLE
A circular dependency between libcaf_core and libcaf_io

### ISSUE THREAD

**Issue by vitlav** [actor-framework/actor-framework#806]
libcaf_core uses socket_guard from libcaf_io, but not linking with it:
/usr/bin/ld.default: ../libcaf_core/libcaf_core.so.0.16.2: undefined reference to `caf::detail::socket_guard::~socket_guard()'
/usr/bin/ld.default: ../libcaf_core/libcaf_core.so.0.16.2: undefined reference to `caf::detail::socket_guard::socket_guard(int)'

In the same time libcaf_io requires libcaf_core.

Can we break that dependency?

**Comment by vitlav** [comment]
Was it hard add link to the first issue about it?
https://github.com/actor-framework/actor-framework/issues/788

**Comment by Neverlord** [comment]
Sorry for this build issue and thanks for reporting it.

> Can we break that dependency?

Yes, this is already fixed in `master` and is going to be included in `0.16.3`.

This issue was previously reported here: https://github.com/actor-framework/actor-framework/issues/788, albeit not under a search-friendly name.
