### ISSUE TITLE
pthread linking issue

### ISSUE THREAD

**Issue by vitlav** [actor-framework/actor-framework#807]
I got pthread linking error:
verify-elf: ERROR: ./usr/lib64/libcaf_core.so.0.16.2: undefined symbol: pthread_create
verify-elf: ERROR: ./usr/lib64/libcaf_io.so.0.16.2: undefined symbol: pthread_create

Some mistakes:

> libcaf_openssl/CMakeLists.txt:    target_link_libraries(libcaf_openssl_shared "-pthread")
direct linking without alternatives

```
$ git grep PTHREAD_LIBRARIES
CMakeLists.txt:                        ${PTHREAD_LIBRARIES})
examples/CMakeLists.txt:                        ${PTHREAD_LIBRARIES})
examples/CMakeLists.txt:    target_link_libraries(protobuf_broker ${CMAKE_DL_LIBS} ${CAF_LIBRARIES} ${PTHREAD_LIBRARIES} ${PROTOBUF_LIBRARIES})
examples/CMakeLists.txt:    target_link_libraries(curl_fuse ${CMAKE_DL_LIBS} ${CAF_LIBRARIES} ${PTHREAD_LIBRARIES} ${CURL_LIBRARY})
libcaf_opencl/examples/CMakeLists.txt:                          ${PTHREAD_LIBRARIES}
libcaf_python/CMakeLists.txt:                        ${PTHREAD_LIBRARIES}
tools/CMakeLists.txt:                        ${PTHREAD_LIBRARIES})
```
in some CMakeLists.txt used PTHREAD_LIBRARIES and linking done correctly.
Will I send PR with missed ${PTHREAD_LIBRARIES} for libcaf_core and libcaf_io ?

**Comment by Neverlord** [comment]
> Will I send PR with missed ${PTHREAD_LIBRARIES} for libcaf_core and libcaf_io ?

A PR would be very much appreciated!

**Comment by Neverlord** [comment]
We recently switched to https://cmake.org/cmake/help/v3.2/module/FindThreads.html. Please re-open if the problem still persists.
