### ISSUE TITLE
LIB_DESTINATION is not supported

### ISSUE THREAD

**Issue by vitlav** [actor-framework/actor-framework#808]
It is common case when LIB_DESTINATION cmake variable contains lib64 or lib (destination for LIBRARY).

We need to have a default value for LIB_DESTINATION and replace all
LIBRARY DESTINATION lib
with
LIBRARY DESTINATION ${LIB_DESTINATION}

**Comment by Neverlord** [comment]
Wouldn't be the canonical way to set `LIBRARY_OUTPUT_PATH` or one of the newer alternatives? See: https://cmake.org/cmake/help/latest/variable/LIBRARY_OUTPUT_PATH.html.

**Comment by Neverlord** [comment]
Seems like `LIBRARY_OUTPUT_PATH` is the *property name*. CMake initializes this property from [`CMAKE_LIBRARY_OUTPUT_DIRECTORY`](https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_OUTPUT_DIRECTORY.html). With current `master`, setting this variable on the command line did the trick for me.
