### ISSUE TITLE
openssl config options broke in master

### ISSUE THREAD

**Issue by jsiwek** [actor-framework/actor-framework#812]
This block of changes breaks uses of `actor_system_config::set("openssl.*", ...)`:

https://github.com/actor-framework/actor-framework/commit/0541cbae148ba2ceeafc3762e704dfc8ca0b2611#diff-cab6dc35ce064721163624deed50bd4fR133

the `actor_system_config::openssl_*` members were never marked deprecated, still exist, and are still used by the libcaf_openssl module directly.  I'm not sure what the plans are, but probably at least involves reverting to the original:

```diff
diff --git a/libcaf_core/src/actor_system_config.cpp b/libcaf_core/src/actor_system_config.cpp
index c9d9bf4c..1264a48f 100644
--- a/libcaf_core/src/actor_system_config.cpp
+++ b/libcaf_core/src/actor_system_config.cpp
@@ -128,13 +128,16 @@ actor_system_config::actor_system_config()
   opt_group(custom_options_, "opencl")
     .add<std::vector<size_t>>("device-ids", "whitelist for OpenCL devices");
   opt_group(custom_options_, "openssl")
-    .add<string>("certificate", "path to the PEM-formatted certificate file")
-    .add<string>("key", "path to the private key file for this node")
-    .add<string>("passphrase", "passphrase to decrypt the private key")
-    .add<string>("capath",
-                 "path to an OpenSSL-style directory of trusted certificates")
-    .add<string>("cafile",
-                 "path to a file of concatenated PEM-formatted certificates");
+    .add(openssl_certificate, "certificate",
+         "path to the PEM-formatted certificate file")
+    .add(openssl_key, "key",
+         "path to the private key file for this node")
+    .add(openssl_passphrase, "passphrase",
+         "passphrase to decrypt the private key")
+    .add(openssl_capath, "capath",
+         "path to an OpenSSL-style directory of trusted certificates")
+    .add(openssl_cafile, "cafile",
+         "path to a file of concatenated PEM-formatted certificates");
   // add renderers for default error categories
   error_renderers.emplace(atom("system"), render_sec);
   error_renderers.emplace(atom("exit"), render_exit_reason);
```

and then possibly going through an actual deprecation process of those members before changing again.

**Comment by Neverlord** [comment]
I'm very sorry about that. I thought all of the member variables were deprecated as of 0.16. Current `master` is going to be 0.17 and we'll remove all what's deprecated at the moment. However, the `openssl_` member variables in particular were never actually deprecated until now. I'm going to revert that particular change and deprecate the members in 0.17 rather than removing them outright.
