### ISSUE TITLE
Type-specific parsing of config options is broken

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#814]
CAF attempts to infer types from CLI options while also trying to respect config parameter types directly. For example:

```c++
config_option_set opts;
opts.add<std::string>("value,v", "some value");
```

With this setup, `-v "foobar"` works. CAF also tries to attempt parsing this as a string if quotes are omitted. Hence, `-v foobar` also works. However, `-v "123"` works, while `-v 123` doesn't. Here, CAF first evaluates 123 as an integer and then produces a type clash. However, we already know that we have to parse a string. So this behavior makes no sense.

**Comment by josephnoir** [comment]
Are you sure `-v "123"` works? I think I tried this with an IP address passed to an option that expects a string and got an illegal argument error.

**Comment by Neverlord** [comment]
It only worked with the double quotes. Since they got eaten by the shell, you had to do something like `./app -v "\"123\""`. That's fixed now in `master`. I leave this story open, because many other types still fall back to the INI parser.
