### ISSUE TITLE
CAF_LOG_IMPL  fails on compile-time

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#830]
Windows 10, MSVC2017, x64, caf 0.16.3

Any use of CAF_LOG_MAKE_EVENT fails on compile-time with: 
error C2398: Element '2': conversion from 'long' to 'unsigned int' requires a narrowing conversion

The reason is in substitution of __LINE__ into ::caf::logger::event as an initializer_list. 
The issue goes away if I replace initializer_list with ctor call:
::caf::logger::event{...} -> ::caf::logger::event(...)

**Comment by Neverlord** [comment]
@skorokhod seems like a trivial fix. Mind opening a PR?
