### ISSUE TITLE
Warning from static analyzer

### ISSUE THREAD

**Issue by vyivanov** [actor-framework/actor-framework#836]
[PVS-Studio](https://www.viva64.com/en/w/v1023/) issues this warning on version [0.16.3](https://github.com/actor-framework/actor-framework/blob/ec6a89271472aa7e45cfb72d483fd8cfce0210ac/libcaf_core/caf/actor_system_config.hpp#L240):

```
caf/actor_system_config.hpp:240:1: warning: V1023 A pointer without owner is added to the 'thread_hooks_' container by the 'emplace_back' method. A memory leak will occur in case of an exception.
```

**Comment by josephnoir** [comment]
Should by addressed by #843.
