### ISSUE TITLE
Can messages get lost in local groups?

### ISSUE THREAD

**Issue by uentity** [actor-framework/actor-framework#856]
Hi everyone!

I'm trying to implement some kind of signal/slot pattern based on CAF actor groups.

Idea is the following: main processing actor creates local group in constructor and immediately joins it. On certain events it sends messages to that group.

Then I add `subscribe()` method to my actor that takes event ID and a functor responsible for handling that event. In `subscribe()` I convert functor to a small actor that reacts to message corresponding to specified event and just calls captured functor with proper arguments. This actor is then added to main actor's group.

When main actor quits it sends `bye` message to self group. Event handler actors receive this message and also leaves the group.

While the above scheme seems to work I experience random messages dropouts when they're delivered to event handlers. **For example, main actor sends four event messages to self group and event handler is called from 0 to 4 times randomly at runtime**.

I tried to add significant delays (sleeps) in main thread, executed `actor_system().await_all_actors_done()` -- nothing helps. Seems like messages sent to group aren't delivered at all to some actors inside that group. BTW `bye` message (consisting from single atom) seems to be always delivered correctly as all actors shut down properly.
These results are without any distribution, everything happens in one process.

I just don't understand whats going on and is message delivery inside group reliable?

**Comment by Neverlord** [comment]
> is message delivery inside group reliable?

For local messages it is. Do you have a code snippet (ideally a minimal example) for reproducing the issue?

**Comment by uentity** [comment]
Here is an adpated code example I extracted from my project.
I'm not sure that `actor_system` lvalue ref can be passed to actor constructor (in my code I just obtain it via singleton), but otherwise must work.

```C++
#include <caf/all.hpp>

#include <chrono>
#include <thread>
#include <iostream>
using namespace std::chrono_literals;

using a_test_rename = caf::atom_constant<caf::atom("t rename")>;
using a_test_ack = caf::atom_constant<caf::atom("t ack")>;
using a_test_bye = caf::atom_constant<caf::atom("t bye")>;

struct orig_renamer : caf::event_based_actor {
	std::string name_ = "Watson";
	caf::group self_grp;

	orig_renamer(caf::actor_config& cfg, caf::actor_system& system) : caf::event_based_actor(cfg) {
		// create self local group & join it
		self_grp = system.groups().get_local("test_renamer");
		join(self_grp);
	}

	auto goodbye() -> void {
		send(self_grp, a_test_bye());
	}

	auto make_behavior() -> behavior_type override { return {
		[=](a_test_rename, std::string new_name) {
			//caf::aout(this) << "new name = " << new_name << std::endl;
			send(self_grp, a_test_rename(), a_test_ack(), new_name, name_);
			name_ = std::move(new_name);
		},
		[=](a_test_rename, a_test_ack, const std::string&) {},  // <-- wrong pattern

		[](a_test_bye) {},

		[](int x) { return x + 42; }
	}; }
};

auto ev_listener_actor(
	caf::event_based_actor* self, caf::group tgt_grp, caf::message_handler character, caf::actor_sytem& system
) -> caf::behavior {
	// silently drop all other messages not in my character
	self->set_default_handler([](caf::scheduled_actor* self, caf::message_view& mv) {
		return caf::drop(self, mv);
	});
	// come to mummy
	self->join(tgt_grp);
	auto& Reg = system.registry();
	Reg.put(self->id(), self);

	// unsubscribe when parent leaves its group
	return character.or_else(
		[self, grp = std::move(tgt_grp), &Reg](a_test_bye) {
			self->leave(grp);
			Reg.erase(self->id());
			caf::aout(self) << "ev actor quit" << std::endl;
		}
	);
};

auto make_ev_character(handle_event_cb f) {
	return caf::message_handler {
		[f = std::move(f)](a_test_rename, a_test_ack, std::string new_name, std::string old_name) {
			f(std::move(new_name), std::move(old_name));
		}
	};
}

void caf_main(actor_system& system) {
	std::cout << "---> spawn base renamer actor..." << std::endl;
	auto ren_a = system.spawn<orig_renamer>(system);
	auto* pren = caf::actor_cast<orig_renamer*>(ren_a);

	// make shiny new subscriber actor and place into parent's room
	std::atomic<int> cb_count = 0;
	auto baby = system.spawn(
		ev_listener_actor, pren->self_grp,
		make_ev_character( [&cb_count](std::string new_name, std::string old_name) {
			std::cout << "*** callback: new name = " << old_name << " -> " <<  new_name << std::endl;
			++cb_count;
		}),
		system
	);

	// send rename
	caf::scoped_actor sender{system};
	sender->send(ren_a, a_test_rename(), "Rename Actor 1");
	// check value
	sender->request(ren_a, caf::infinite, 42).receive(
		[](int res){ std::cout << "x + 42 = " << res << std::endl; },
		[](const caf::error& er) {}
	);

	// send a couple more renames
	for(int i = 0; i < 1000; ++i)
		sender->send(ren_a, a_test_rename(), "Rename Actor " + std::to_string(i));

	std::this_thread::sleep_for(1s);
	pren->goodbye();
	std::cout << "==> Renamer callback invoked " << cb_count << " times" << std::endl;
}

CAF_MAIN()
```

**Comment by uentity** [comment]
When I compile the code above and run it multiple times I get just a few random number of callback invokes, less than 50 usually.

Next you can observe the following effects.

1. If you'll comment out `sender->request(..)` block, then a lot more successful callback invokes passes. It can vary on my machine, even all 1001 calls may succeed, but still it's a random number.

2. Notice that there's a wrong signature for `rename ack` message. If you change
`[=](a_test_rename, a_test_ack, const std::string&) {}` to
`[=](a_test_rename, a_test_ack, const std::string&, const std::string&) {}`
then almost always callback is invoked 1001 times as expected.
BUT STILL some invokes can be missed, sometimes I get <1000 invokes.

**Comment by uentity** [comment]
Any feedback on this?

Also one more question. In the example above actors in group invoke some callbacks. Let's assume that callbacks are "heavy" (they can do processing, UI updates and other slow things). Also let's assume that there are other actors in group.

Will such callbacks "slow down" messages broadcasting inside group? I mean, will it make sense if I put actors for heavy callbacks in separate `actor_pool` and translate messages from group to this pool? Or such approach won't improve anything?
Thanks beforehand.

**Comment by Neverlord** [comment]
> Any feedback on this?

I reproduced the behavior using your code and played a bit around with it. I'm still investigating, so stay tuned.

> Will such callbacks "slow down" messages broadcasting inside group?

No, everything is asynchronous. The group simply puts the message into all mailboxes. If you have actors that might block, the only thing I'd suggest is to detach those actors.

**Comment by Neverlord** [comment]
The reason you've seen your handlers called less times than expected is twofold:

- Not providing a properly typed handler. As you've already mentioned, fixing the signature results in more of your handlers getting called. The reason has nothing to do with groups. Actors by default terminate when receiving unexpected messages. Rather than just dropping messages, actors fail as early as possible to make sure errors are propagated as widely as possible.
- Calling `join` in your `ev_listener_actor` results in a race on the group. The call to `join` inside `ev_listener_actor` gets executed when initializing the function-based actor. At that point in time, you might have missed some messages already. The solution is to use `spawn_in_group`, which makes sure the group is joined immediately when creating the actor rather than relying on some call to `join` that occurs at a later time.

There are also a couple of other issues in the code:
- Dereferencing an actor handle and accessing its state is a major red flag.
- Passing a pointer to the system is unnecessary.
- Giving actors references to something that lives on a stack is asking for trouble.

I did a pass over the code and here's a version that does not "lose" messages and also solves other issues outlined above:

```c++
#include "caf/all.hpp"

#include <chrono>
#include <thread>
#include <iostream>

using a_test_rename = caf::atom_constant<caf::atom("t rename")>;
using a_test_ack = caf::atom_constant<caf::atom("t ack")>;
using a_test_bye = caf::atom_constant<caf::atom("t bye")>;

class orig_renamer : public caf::event_based_actor {
public:
  orig_renamer(caf::actor_config& cfg, caf::group grp)
    : caf::event_based_actor(cfg), grp_(grp) {
    // nop
  }

  caf::behavior make_behavior() override {
    return caf::behavior(
      [=](a_test_rename, std::string& new_name) {
        send(grp_, a_test_rename(), a_test_ack(), new_name, name_);
        name_ = std::move(new_name);
      },
      [](a_test_rename, a_test_ack, const std::string&, const std::string&) {
        // nop
      },
      [](a_test_bye) {
        // nop
      },
      [](int x) { return x + 42; });
  }

private:
  std::string name_ = "Watson";
  caf::group grp_;
};

caf::behavior ev_listener_actor(caf::event_based_actor* self,
                                caf::group tgt_grp,
                                caf::message_handler character) {
  // Silently drop all other messages not in my character.
  self->set_default_handler(caf::drop);
  // Register this actor under its ID.
  auto& Reg = self->system().registry();
  Reg.put(self->id(), self);
  // Unsubscribe when parent leaves its group.
  return character.or_else([self, tgt_grp](a_test_bye) {
    std::cout << "*** leave group" << std::endl;
    self->leave(tgt_grp);
    self->system().registry().erase(self->id());
  });
}

// Utility function for wrapping a lambda into a `message_handler`.
template <class F>
caf::message_handler make_ev_character(F f) {
  return caf::message_handler{[f](a_test_rename, a_test_ack,
                                  const std::string& new_name,
                                  const std::string& old_name) {
    // Delegate to custom function.
    f(new_name, old_name);
  }};
}

void caf_main(caf::actor_system& system) {
  std::cout << "---> spawn base renamer actor..." << std::endl;
  auto grp = system.groups().get_local("test_renamer");
  auto ren_a = system.spawn_in_group<orig_renamer>(grp, grp);
  // Make shiny new subscriber actor and place into parent's room.
  auto cb_count = std::make_shared<std::atomic<int>>(0);
  auto base_bhvr = [=](const std::string&, const std::string&) {
    // Count how many times this handler gets called.
    ++*cb_count;
  };
  auto baby = system.spawn_in_group(grp, ev_listener_actor, grp,
                                    make_ev_character(base_bhvr));
  // Send rename.
  caf::scoped_actor self{system};
  self->send(ren_a, a_test_rename(), "Rename Actor 1");
  // check value
  self->request(ren_a, caf::infinite, 42)
    .receive([](int res) { std::cout << "x + 42 = " << res << std::endl; },
             [](const caf::error&) {});
  // Send a couple more renames.
  for (int i = 0; i < 1000; ++i)
    self->send(ren_a, a_test_rename(), "Rename Actor " + std::to_string(i));
  std::this_thread::sleep_for(std::chrono::seconds(2));
  anon_send(grp, a_test_bye());
  anon_send_exit(ren_a, caf::exit_reason::user_shutdown);
  anon_send_exit(baby, caf::exit_reason::user_shutdown);
  std::cout << "==> Renamer callback invoked " << cb_count << " times"
            << std::endl;
}

CAF_MAIN()
```

**Comment by uentity** [comment]
@Neverlord big thanks for code analysis.

The only question I have after reading is about accessing actor state. Why is it illegal or error-prone? Because actor lifetime is controlled by CAF and I can end up accessing deleted objects (if actor was terminated for some reason)?

Asking because I've refactored PIMPL  into 'AIMPL' for my types: moved private state of objects from PIMPL classes to actors. And object access it's state via dereferencing actor handle. Is that wrong direction?

**Comment by Neverlord** [comment]
> [can I] end up accessing deleted objects (if actor was terminated for some reason)?

Yes, you can end up accessing deleted objects. Actors also run concurrently, so you can easily introduce data races as well.

If you *really* need to share state between a "regular" object and an actor then I'd recommend to model that state explicitly and share it via a `shared_ptr` or something similar. Keep in mind that each access to that shared state needs to thread safe.

**Comment by uentity** [comment]
@Neverlord sorry for resurrecting dead issues, but I still have one little question about state sharing.

Let's consider an event-based actor with state that can be queried or mutated only via messages and message handlers (i.e. actor owns it's state). Actor contains handler that reads and returns a value of state's variable and another handler that mutates this variable. Do following statements hold true:
1. 'Reader' and 'writer' handlers can be executed at the same time in parallel.
2. I have to explicitly sync access to described variable **inside both read and write handlers** using, for example, `std::shared_mutex` (to prevent data races).
?

Considering your answer above, if I go with 'pure' actor that doesn't share it's state, then what I win if I still have to sync access to every variable via mutex in every message handler?
