### ISSUE TITLE
Conflicting 'uninstall' targets with CMake.

### ISSUE THREAD

**Issue by ChristofferGreen** [actor-framework/actor-framework#866]
If you add actor-framework together with another library via for example the CMake FetchContent_Declare functionality and they both declare an uninstall target cmake will complain with: "add_custom_target cannot create target "uninstall" because another target with the same name already exists." since CMake targets must be unique. 

Possible solution: First check if the uninstall target already exists before adding it.

Here is another library that had the same issue (I worked around this issue with the same solution): https://github.com/leethomason/tinyxml2/issues/516

**Comment by Neverlord** [comment]
> Possible solution: First check if the uninstall target already exists before adding it.

Sounds reasonable. However, looking at the patch in `tinyxml`, I wonder whether dropping the `uninstall` instructions entirely if the target already exists is the right approach. Shouldn't the `uninstall` target get expanded in this case? Would this be the correct CMake patch?

```cmake
# process cmake_uninstall.cmake.in
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake_uninstall.cmake.in"
               "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
               IMMEDIATE @ONLY)
# add uninstall target
if(NOT TARGET uninstall)
  add_custom_target(uninstall
                    COMMAND "${CMAKE_COMMAND}" -P
                    "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake")
else()
  add_custom_command(TARGET uninstall
                     PRE_BUILD
                     COMMAND "${CMAKE_COMMAND}" -P
                     "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake")
endif()
```

**Comment by tobim** [comment]
how about:
``` cmake
# process cmake_uninstall.cmake.in
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake_uninstall.cmake.in"
               "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
               IMMEDIATE @ONLY)
if(NOT TARGET uninstall)
  add_custom_target(uninstall)
endif()
add_custom_target(uninstall_caf
                  COMMAND "${CMAKE_COMMAND}" -P
                  "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake")
add_dependencies(uninstall uninstall_caf)
```
?

**Comment by Neverlord** [comment]
Isn't this overriding the previous `uninstall` target? Appending to it makes more sense to me intuitively.

**Comment by tobim** [comment]
It's not overriding, the `uninstall` target is only created if it does not exist. If we mix both our ideas together, we get
``` cmake
# process cmake_uninstall.cmake.in
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake_uninstall.cmake.in"
               "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
               IMMEDIATE @ONLY)
# add uninstall target if it does not exist yet
if(NOT TARGET uninstall)
  add_custom_target(uninstall)
endif()
add_custom_command(TARGET uninstall
                   PRE_BUILD
                   COMMAND "${CMAKE_COMMAND}" -P
                   "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake")
```
The benefit is that the command is not specified twice. The delta that my original suggestion adds is that one could use the `uninstall_caf` target for fine-grained control. Maybe it is better not to offer that, as it would normally just break the installation.

**Comment by Neverlord** [comment]
I like that version! Less repetitive than the other approaches and less target confusion. 🙂

**Comment by tobim** [comment]
I'm afraid this has to be reopened:
`add_custom_command(TARGET ...)` has a precondition that the target the command is attached to has to be defined in the same directory: https://cmake.org/cmake/help/latest/command/add_custom_command.html#build-events. We should move to the approach I suggested at first.
I just tripped over this myself.
