### ISSUE TITLE
next 0.15.x realease

### ISSUE THREAD

**Issue by elszon** [actor-framework/actor-framework#874]
Hi,

if you may please release next 0.15.x with fix 41c12703f9d520844ce7c6f39785dddbf337bdc9 and f3f72bbd1521d9512c6abc93e7a098a73977cd0c . I have to stick with CAF 0.15 branch and it will be nice to have this fixes.

Thanks,
elszon

**Comment by Neverlord** [comment]
Sure, I don't see a reason why not to. Here you go: https://github.com/actor-framework/actor-framework/releases/tag/0.15.8.
