### ISSUE TITLE
endless loop while parsing a config file if line starts with a non-alphanumeric character

### ISSUE THREAD

**Issue by andrismednis** [actor-framework/actor-framework#894]
Let's take a minimal program minapp.cpp:
`#include "caf/exec_main.hpp"`
``void caf_main(caf::actor_system& system)``
`{`
`}`
`CAF_MAIN()`

and a minimal config file caf-application.ini with 1 line and 1 character:
`#`
Running it as
`minapp --config-file=caf-application.ini`
goes into endless loop, without error diagnostics.

Looks like it is endlessly bouncing in libcaf_core/caf/detail/parser/read_ini.hpp, in read_ini() between term_state(init) and unstable_state(return_to_global).

The same effect if '#" in config file is replaced with '/', '\', '.', ',', '!', '@', '$', '%', , '^', '&', '('.

**Comment by Neverlord** [comment]
Thanks for reporting this bug! Bugfix is underway (see #895).
