### ISSUE TITLE
Breakage in stringification_inspector::consume.

### ISSUE THREAD

**Issue by tobim** [actor-framework/actor-framework#898]
df9482534c194f721de2a1727b36036c0f2ded90 broke the VAST build for me.
`consume` has no matching overload for the types `container_view_handle`, `dummy`, and `duration`.
I believe the same problem occurs in Broker.

**Comment by Neverlord** [comment]
Thanks for reporting! Should be fixed.

**Comment by tobim** [comment]
👍
