### ISSUE TITLE
How can I resolve the circular dependency in typed actor definition.

### ISSUE THREAD

**Issue by xiewei20082008** [actor-framework/actor-framework#911]
I'd like to write some code like:

```
using type_a = typed_actor<
  reacts_to<hello_atom, type_b>
>;

using type_b = typed_actor<
  reacts_to<hello_atom, type_a>
>;
```

I was trying several ways to work around it but failed... Thank you in advance.

**Comment by Neverlord** [comment]
This is not going to work, because you cannot have recursive type aliases in C++. You need to break the recursive dependency with some wrapper that you can forward declare:

```c++
struct type_b_wrapper;

using type_a = typed_actor<
  reacts_to<hello_atom, type_b_wrapper>
>;

using type_b = typed_actor<
  reacts_to<hello_atom, type_a>
>;

// Don't forget to announce this type and to implement `inspect`.
struct type_b_wrapper { type_b value; };
```

I know it's not very satisfying to introduce an extra messaging types only to work around limitations of the type system.
