### ISSUE TITLE
API Documentation down

### ISSUE THREAD

**Issue by ChristofferGreen** [actor-framework/actor-framework#922]
Hello

It appears that the API documentation is no longer being generated.

https://actor-framework.org/doc/ is empty

**Comment by Neverlord** [comment]
Thanks for reporting! Seems like Jenkins pushed an empty Doxygen. 🤔

**Comment by Neverlord** [comment]
Should be fixed via b53a25ea5b5de493fb63d43821eeb2452822d9c4. http://actor-framework.org/doc/ seems to be up-to-date again.
