### ISSUE TITLE
Returning std::tuple results in error

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#972]
I'm trying to return a std::tuple as a response to a message, but it throws an error in the receive code.

Uuid is a wrapper class for uuids, and works fine in other messages. 

Any ideas what's going wrong here ?

cheers

[&](get_media_frame_atom, const int frame) -> caf::expected<std::tuple<caf::actor, Uuid, int>> {
      return std::make_tuple(media_uuid_[uuid], uuid, frame);
}

```
     sys->request(timeline_actor_, std::chrono::seconds(10), get_media_frame_atom::value, frame - 1).receive(
        [&](std::tuple<caf::actor, Uuid, int> data) {
        },
        [&](const error& e) {
          aout(self()) <e << std::endl;
        }

```

`error(2, 'system', (27@3443808C5E97E4E8F8F8E8AC90B3FC007A953300#17160, 11fa3037-9eff-4ec1-928c-7fd4dc4dbe96, 1))
`

**Comment by Neverlord** [comment]
CAF automatically unwraps tuples. It should work if you change

```
[&](std::tuple<caf::actor, Uuid, int> data) {
```

to

```
[&](const caf::actor& hdl, const Uuid& id, int i) {
```

**Comment by alatdneg** [comment]
Cool that did it!
