### ISSUE TITLE
libcaf_python dequeue_message_with_timeout never returns

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#985]
dequeue_message_with_timeout(absolute_receive_timeout(10))

I assume this should return after 10millisecs, but it just sits there, I'm assuming I'm calling this right.

dequeue_message works as expected.

**Comment by Neverlord** [comment]
Looking at the sources, I think you're calling this correctly. This is what `receive_one()` delegates to.

**Comment by alatdneg** [comment]
I tried to track down the problem, but quickly got lost in actor-framework, but it did start to look like the function that the python code is calling expects a duration not a time point, (but I might be missing something)

**Comment by alatdneg** [comment]
This blocks if there is no message in the queue.
 self_->next_message();
I modified the python code to check. 

```
					py::tuple py_dequeue() {
						mailbox_element_ptr ptr = nullptr;

						if(self_->has_next_message())
							ptr = self_->next_message();

						while (!ptr) {
							self_->await_data();
							ptr = self_->next_message();
						}
						return tuple_from_message(std::move(ptr->content()));
					}

					py::tuple py_dequeue_with_timeout(absolute_receive_timeout timeout) {
						mailbox_element_ptr ptr = nullptr;

						if(self_->has_next_message())
							ptr = self_->next_message();

						while (!ptr) {
							if (!self_->await_data(timeout.value()))
								return py::none{};
							ptr = self_->next_message();
						}
						return tuple_from_message(std::move(ptr->content()));
					}


```
