### ISSUE TITLE
stream_source lacks functionality to yield to parent actor

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#986]
Once I run `add_outbound_path(...)`, none of my actors behaviors trigger anymore until I've generated at least one event. This includes the _exit/down handlers_ of my actor, which means I cannot properly shut down any more. 

I think what's needed here is some sort of `yield()` function for the `stream_source` that checks if there's anything else to do for the parent actor, and then calls `advance()` or returns to the _next element handler_ in some other way.

While looking at this I also noticed that the _done handler_ is not called when calling `advance()`, which might be a bug.

Relevant source code for reproduction https://github.com/tenzir/vast/blob/master/libvast/vast/system/source.hpp#L184

I'd like to add a `if (produced == 0) st.mgr.yield()` below L184 in the linked snippet to return the control flow to the parent actor in order for it to check its _exit/down handler_.

For testing: After compiling, run `echo | vast -N -v debug import zeek` and try quitting with SIGINT, which hangs indefinitely because the source actor never checks for any exit or down messages.

**Comment by dominiklohmann** [comment]
This seems to be fixed in 0.17.4, I suppose by #1019?

**Comment by Neverlord** [comment]
Good to know that this is fixed. 👍

**Comment by dominiklohmann** [comment]
For completeness sake:

I have done `git -C aux/caf bisect start 0.17.4 0.17.3` from current VAST master with reversed good/bad to find when the bug was fixed. 

The test command was `echo | vast -N import suricata`, followed by pressing <kbd>ctrl</kbd> + <kbd>c</kbd>.

The results confirm my suspicion:

```
❯ git -C aux/caf bisect log
# bad: [7ff369655076e9baf7acd9021e2e27966f9cffb4] Change version to 0.17.4
# good: [b05a4b7b2a6f59b0508db84ea68e5ada2224f904] Change version to 0.17.3
git bisect start '0.17.4' '0.17.3'
# bad: [9c4f5804266ecd5721393e01e680f83204031014] Merge pull request #1023
git bisect bad 9c4f5804266ecd5721393e01e680f83204031014
# bad: [d5f028e236250027e85813ce60c8b638b9235d25] Merge pull request #1019
git bisect bad d5f028e236250027e85813ce60c8b638b9235d25
# good: [797df940b55bd2cefb5d299e40bf708a2b1f81fa] Merge branch 'issue/1014' into topic/0.17.4
git bisect good 797df940b55bd2cefb5d299e40bf708a2b1f81fa
# good: [cff96757c7994b44122a93f1864993cb9e4a0072] Merge pull request #1017
git bisect good cff96757c7994b44122a93f1864993cb9e4a0072z
```

```
❯ git -C aux/caf bisect view
commit d5f028e236250027e85813ce60c8b638b9235d25 (refs/bisect/bad)
Merge: cff96757 31db8929
Author: Dominik Charousset <dominik.charousset@corelight.com>
Date:   Sat Jan 18 16:17:32 2020 +0100

    Merge pull request #1019

commit 31db8929a438519926ca046cb18f6564acd7dd1f (HEAD)
Author: Dominik Charousset <dominik.charousset@corelight.com>
Date:   Sat Jan 18 15:23:10 2020 +0100

    Implement workaround for stream shutdown issue
```

**Comment by Neverlord** [comment]
Wow, thanks for bisecting (and sharing)! Sometimes one patch fixes two bugs. 🙂
