### ISSUE TITLE
Bug in actor-framework/examples/broker/simple_broker.cpp?

### ISSUE THREAD

**Issue by weberdaniel** [actor-framework/actor-framework#991]
Hello to All,

i tried out the broker example located at: actor-framework/examples/broker/simple_broker.cpp.
I used the code and started developed my own broker, thus i made use of the read_int/
write_int methods. When i changed the atom from the name "ping" to the name "update", i experienced problems with both read_int/write_int.

Analysing the problem, it turned out that the bit shift operator seems to be the problem. In the file it says "<< sizeof(uint32_t)", however this would only result in a bit shift of 4, though a bit shift of 8*4 bit (32bit) is needed.

It seems to work well for the ping/pong atoms, because luckily their value is not high enough.

Have a nice day,
Daniel

**Comment by Neverlord** [comment]
Thanks for reporting!

It's a silly bug and would be rather easy to fix. However, `caf::atom` is already on its way out for CAF 0.18 (I'll file a PR for removing it soon-*ish*). We have to update the example for this reason anyway, so it wouldn't make sense to fix obsolete code in `master`.
