### ISSUE TITLE
Remove unused OpenCL module references

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#993]
The actor system still has references to the OpenCL module. Since the module was removed there is not need to keep these:

* https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/actor_system.hpp#L154
* https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/actor_system.hpp#L272
* https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/actor_system.hpp#L276

**Comment by jakobod** [comment]
- Jenkinsfile contains openCL flag too
- FindCAF tries to find openCL lib

When searching for `opencl` it turns out that there is some opencl stuff left in `actor_system` and `actor_system_config`
